In [12]:
import pandas as pd
import numpy as np

In [13]:
df1=pd.read_csv('raw_jobs_adzuna.csv')

In [14]:
df=df1.copy()

In [198]:
df.head()

,created,latitude,title,adref,location,longitude,salary_is_predicted,description,company,redirect_url,__CLASS__,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTc4NTc3MjA3MiIsI...,"Bangalore, Karnataka",77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Adzuna::API::Response::Job,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Bangalore, Karnataka",77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,Adzuna::API::Response::Job,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Hyderabad, Telangana",78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,Adzuna::API::Response::Job,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-07T05:28:33Z,12.95703,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Bangalore, Karnataka",77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5790410357?se=bi...,Adzuna::API::Response::Job,IT Jobs,5790410357,full_time,NaN,NaN,NaN
4,2026-07-09T17:58:24Z,19.00821,Software Engineer,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYmlpM0ZWSl84UkdVe...,"Mumbai, Maharashtra",72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,Adzuna::API::Response::Job,IT Jobs,5794153227,full_time,NaN,NaN,NaN

In [199]:
df.drop(columns='__CLASS__',inplace=True)

In [200]:
# created not proper date or time 
# latitude not usefull and have null value 
#title - some rows like software engineering and software engineer or software engineers or software engineers!

In [201]:
df['title']=df['title'].str.lower()

In [202]:
pd.set_option('display.max_rows',None)

In [203]:
df[df['title'] == 'software engineers']

,created,latitude,title,adref,location,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
251,2022-09-20T07:01:50Z,NaN,software engineers,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNXZSRktWSl84UkdnW...,"Bangalore, Karnataka",NaN,0,* The Job pays flat $ 25 - 30 / Hour. This is ...,Alpha Source,https://www.adzuna.in/details/3502540360?utm_m...,IT Jobs,3502540360,full_time,NaN,4000000.0,5000000.0
333,2026-05-17T06:42:21Z,19.173350,software engineers,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTczMTk1NDkwMSIsI...,"Thane, Maharashtra",73.048450,0,Reporting to : Head of the department Position...,Quantum Asset Management Company Private Limited,https://www.adzuna.in/details/5731954901?utm_m...,IT Jobs,5731954901,NaN,NaN,NaN,NaN
335,2026-06-24T07:23:00Z,28.323996,software engineers,eyJhbGciOiJIUzI1NiJ9.eyJzIjoic3JVMUwxSl84UkdVe...,"Gurgaon, Haryana",76.983738,0,The position is for Senior Analyst Programmer ...,Augusta Infotech,https://www.adzuna.in/details/5774236635?utm_m...,IT Jobs,5774236635,NaN,NaN,NaN,NaN

In [204]:
#df[df['title']=='senior software engineer ii']

In [205]:
#df.loc[df['title']=='senior software engineer ii','title']='senior software engineer 2'

In [206]:
#df.loc[df['title']=='senior software engineer i','title']='senior software engineer 1'

In [207]:
#df.loc[df['title'] == 'software engineers','title'] = 'software engineer'

In [208]:
#df.loc[df['title']=='software development engineer ii (ai/ml)','title']='software development engineer 2 (ai/ml) '

In [209]:
#df.loc[df['title']=='software engineers!','title']='software engineer'

In [210]:
#df[df['title'].str.contains('Software',case=False, na=False)]['title'].value_counts()

In [211]:
def standardize_role(title):
    title = str(title).lower().strip()

    # Software Engineer
    if "software engineer" in title:
        return "Software Engineer"

    # Data Scientist
    elif "data scientist" in title or "data science" in title:
        return "Data Scientist"

    # Data Engineer
    elif "data engineer" in title:
        return "Data Engineer"

    # Data Analyst
    elif "data analyst" in title:
        return "Data Analyst"

    # Machine Learning Engineer
    elif "machine learning" in title or "ml engineer" in title:
        return "Machine Learning Engineer"

    # AI Engineer
    elif (
        "artificial intelligence" in title
        or "ai engineer" in title
        or "gen ai" in title
        or "genai" in title
    ):
        return "AI Engineer"

    # Python Developer
    elif "python developer" in title or "python development" in title:
        return "Python Developer"

    # Java Developer
    elif "java developer" in title or "java backend developer" in title:
        return "Java Developer"

    # Backend Developer
    elif "backend developer" in title:
        return "Backend Developer"

    # Frontend Developer
    elif "frontend developer" in title:
        return "Frontend Developer"

    # Full Stack Developer
    elif "full stack" in title or "full-stack" in title:
        return "Full Stack Developer"

    # DevOps Engineer
    elif "devops" in title:
        return "DevOps Engineer"

    # Cloud Engineer
    elif "cloud" in title:
        return "Cloud Engineer"

    # Cyber Security
    elif (
        "cyber security" in title
        or "cybersecurity" in title
        or "cyber" in title
    ):
        return "Cyber Security"

    # Business Analyst
    elif "business analyst" in title or "business analytics" in title:
        return "Business Analyst"

    # Project Manager
    elif "project manager" in title:
        return "Project Manager"

    # Professor / Faculty
    elif (
        "professor" in title
        or "faculty" in title
        or "instructor" in title
    ):
        return "Academic"

    # Sales
    elif "sales" in title:
        return "Sales"
    # Software Development Engineer
    elif "software development engineer" in title:
        return "Software Development Engineer"

    # Platform Engineer
    elif "platform engineer" in title:
        return "Platform Engineer"

    # Software Architect
    elif "software architect" in title:
        return "Software Architect"

    # AI Architect
    elif "ai architect" in title:
        return "AI Architect"

    # Engineering Manager
    elif "engineering manager" in title:
        return "Engineering Manager"

    # Technical Lead
    elif "tech lead" in title or "technical lead" in title:
        return "Technical Lead"

    else:
        return "Other"

In [212]:
position=df.columns.get_loc('title')

In [213]:
df.insert(position + 1,'standard_role', df["title"].apply(standardize_role))

In [214]:
df[df["standard_role"] == "Other"]["title"].value_counts().head(50)

title
sr advanced cyb sec archt/engr                                                                           3
sr developer - frontend (aem, java, eds)                                                                 3
india tdi - apprentice hiring - 2026-2027                                                                2
senior principal al engineer                                                                             2
accounting executive                                                                                     2
principal business systems analyst                                                                       2
junior engineer                                                                                          2
business finance senior analyst                                                                          2
it&d principle ba, finance                                                                               2
senior associate, agents/chatbots ic                                                                     2
sr principal verification engineer                                                                       2
senior - mle - python, ml frameworks, mlops, containerization, terraform, gcp, vertex ai, ibm watsonx    2
jd edwards applications engineer                                                                         2
it&d manager, smart execution                                                                            2
endpoint agent lead- windows, mac and linux                                                              2
python  fullstack developer                                                                              2
senior manager - ai transformation                                                                       2
lead engineer - sw development (c++)                                                                     2
senior middleware engineer – ibm mq & automation                                                         2
associate director, commercial ai – business value delivery                                              2
software dev ops engineer                                                                                2
it&d manager, integration engineer                                                                       2
it&d manager, service management - cmdb / ham                                                            1
it&d product manager - genesis procurement                                                               1
it&d senior manager, connectivity services                                                               1
it lead, internal audit                                                                                  1
it&d manager, service management - dr                                                                    1
it&d senior analyst, core infrastructure                                                                 1
sr security engineer(iam)                                                                                1
it&d manager, service management - ai ops / automation                                                   1
senior software test engineer                                                                            1
director, data, analytics & ai - fr/erm                                                                  1
specialist, data, analytics & ai - cfcr                                                                  1
storage architect - automation, vp                                                                       1
specialist, data, analytics & ai - otcr                                                                  1
specialist, data, analytics & ai - erm/esgr                                                              1
security lead                                                                                            1
risk and compliance manager                                                                              1
sr. consulting business partner                                                                          1
it manager                                                                                               1
vehicle security architect                                                                               1
information security consultant                                                                          1
sr. executive soc                                                                                        1
specialist, data & ai monitoring ops                                                                     1
it&d senior analyst sap engineering                                                                      1
dws internal audit manager - technology & security                                                       1
it&d platform architect, servicenow                                                                      1
it&d manager, core infrastructure                                                                        1
senior manager - security operations                                                                     1
incident response_d2881                                                                                  1
Name: count, dtype: int64

In [215]:
df.drop(columns='adref',inplace=True)

In [216]:
position=df.columns.get_loc('location')

In [217]:
city=df['location'].str.split(',').str.get(0)
df.insert(position + 1,'city',city)

In [218]:
state=df['location'].str.split(',').str.get(1)
df.insert(position + 2,'state',state)

In [219]:
df["city"] = df["city"].replace("India", "Unknown")

In [220]:
temp_df=df[df['city']=='Maharashtra']['state']

In [221]:
df.loc[temp_df.index,'state']='Maharashtra'

In [222]:
#Telangana
#Maharashtra
#Mini Sectt. 
#Tamil Nadu 
#Uttar Pradesh 
#Karnataka

In [223]:
temp_df=df[df['city']=='Tamil Nadu']['state']

In [224]:
temp_df=df[df['city']=='Telangana']['state']

In [225]:
df.loc[temp_df.index,'state']='Tamil Nadu'

In [226]:
df.loc[temp_df.index,'state']='Telangana'

In [227]:
temp_df=df[df['city']=='Uttar Pradesh']['state']

In [228]:
df.loc[temp_df.index,'state']='Uttar Pradesh'

In [229]:
temp_df=df[df['city']=='Gujarat']['state']

In [230]:
df.loc[temp_df.index,'state']='Gujarat'

In [231]:
temp_df=df[df['city']=='Karnataka']['state']

In [232]:
df.loc[temp_df.index,'state']='Karnataka'

In [233]:
temp_df=df[df['city']=='Kerala']['state']

In [234]:
df.loc[temp_df.index,'state']='Kerala'

In [235]:
temp_df=df[df['city']=='Andhra Pradesh']['state']

In [236]:
df.loc[temp_df.index,'state']='Andhra Pradesh'

In [237]:
temp_df=df[df['city']=="Goa"]['state']

In [238]:
df.loc[temp_df.index,'state']="Goa"

In [239]:
temp_df=df[df['city']=='Delhi']['state']

In [240]:
df.loc[temp_df.index,'state']='Delhi'

In [241]:
temp_df=df[df['city']=='Chandigarh']['state']

In [242]:
df.loc[temp_df.index,'state']='Chandigarh'

In [243]:
temp_df=df[df['city']=='Tamil Nadu']['state']

In [244]:
df.loc[temp_df.index,'state']='Tamil Nadu'

In [245]:
df[df['state'].str.contains('India',na=False)]

Empty DataFrame
Columns: [created, latitude, title, standard_role, location, city, state, longitude, salary_is_predicted, description, company, redirect_url, category, id, contract_time, contract_type, salary_min, salary_max]
Index: []

In [246]:
df['state']=df['state'].str.strip()

In [247]:
mumbai_areas = [
    "Andheri",
    "Borivali West",
    "Null Bazar",
    "Bazargate",
    "Chembur",
    "Prabhadevi"
]

df.loc[df["city"].isin(mumbai_areas), "city"] = "Mumbai"

In [248]:
pune_areas = [
    "Yerwada",
    "Mulshi",
    "Bhosarigoan",
    "Warje",
    "Baner",
    "N I B M"
]

df.loc[df["city"].isin(pune_areas), "city"] = "Pune"

In [249]:
hyderabad_areas = [
    "Srinivasapuram",
    "Kyasaram",
    "Hussainialam",
    "Secunderabad",
    "Golconda",
    "Balanagar"
]

df.loc[df["city"].isin(hyderabad_areas), "city"] = "Hyderabad"

In [250]:
chennai_areas = [
    "Injambakkam",
    "Ekkaduthangal"
]

df.loc[df["city"].isin(chennai_areas), "city"] = "Chennai"

In [251]:
ahmedabad_areas = [
    "Navrangpura"
]
df.loc[df["city"].isin(ahmedabad_areas), "city"] = "Ahmedabad"

In [252]:
vadodara_areas = [
    "Sevasi"
]
df.loc[df["city"].isin(vadodara_areas), "city"] = "Vadodara"

In [253]:
delhi_areas = [
    "New Delhi",
    "Lajpat Nagar",
    "Maurya Enclave",
    "H.S.Sangh"
]

df.loc[df["city"].isin(delhi_areas), "city"] = "Delhi"

In [254]:
gurgaon_areas = [
    "Dlf Qe",
    "Sohna",
    "Mini Sectt."
]

df.loc[df["city"].isin(gurgaon_areas), "city"] = "Gurgaon"

In [255]:
invalid_cities = [
    "Maharashtra",
    "Telangana",
    "Tamil Nadu",
    "Karnataka",
    "Gujarat",
    "Kerala",
    "Andhra Pradesh",
    "Goa",
    "Uttar Pradesh"
]

df.loc[df["city"].isin(invalid_cities), "city"] = "Unknown"

In [256]:
df["city"] = df["city"].replace("Ernakulam", "Kochi")

In [257]:
df["city"] = df["city"].replace("Trivandrum", "Thiruvananthapuram")

In [258]:
df['city'].value_counts()

city
Bangalore                  1363
Unknown                    1232
Hyderabad                   479
Mumbai                      432
Pune                        420
Chennai                     297
Delhi                       198
Noida                       182
Ahmedabad                    81
Gurgaon                      67
Navi Mumbai                  48
Kolkata                      45
Jaipur                       42
Indore                       40
Kochi                        24
Coimbatore                   23
Mohali                       16
Thiruvananthapuram           15
Surat                        15
Dehradun                     15
Vadodara                     13
Chandigarh                   12
Thane                        12
Richmond Town                 9
Lucknow                       8
Gandhinagar                   7
Madurai                       7
Kenchanahalli                 7
Nagpur                        6
Rajkot                        5
Chauth Ka Barwara             4
Bhubaneswar                   4
Udaipur                       3
Ramakrishna Hegde Nagar       3
Nashik                        3
Faridabad                     3
Rajpura                       3
Agra                          3
Meerut                        3
Thrissur                      2
Cahmrajendrapet               2
Koyilandi                     2
Sonipat                       2
Dhanbad                       2
Nellore                       2
Kanpur                        2
Ajmer                         2
Immedihalli                   2
Jodhpur                       2
Warangal                      1
Subramanyapura                1
Indiranagar                   1
Solapur                       1
Kalsi                         1
Ambala                        1
Panchkula                     1
Amravati                      1
Sanwer                        1
Depalpur                      1
Rabale                        1
Bhopal                        1
Doddakallasandra              1
Naduvathi                     1
Guntur                        1
Patiala                       1
Khanna                        1
Rameshnagar                   1
Vasai                         1
Mangalore                     1
Kota                          1
Raipur                        1
Jammu                         1
Visakhapatnam                 1
Karur                         1
Madivala                      1
Ator Nagla                    1
Patna                         1
Mysore                        1
Bandikodigehalli              1
Jalgaon                       1
Name: count, dtype: int64

In [259]:
bangalore_areas = [
    "Richmond Town",
    "Cahmrajendrapet",
    "Kenchanahalli",
    "Rameshnagar",
    "Ramakrishna Hegde Nagar",
    "Naduvathi",
    "Immedihalli",
    "Madivala",
    "Bandikodigehalli",
    "Doddakallasandra",
    "Indiranagar",
    "Subramanyapura"
    
]

df.loc[df["city"].isin(bangalore_areas), "city"] = "Bangalore"

In [260]:
df['state'].value_counts()

state
Karnataka              1366
Maharashtra             910
Telangana               469
Tamil Nadu              325
Delhi                   194
Ghaziabad               165
Gujarat                 119
Haryana                  69
Rajasthan                50
West Bengal              45
Madhya Pradesh           41
Bangalore                30
Ernakulam                21
Gautam Buddha Nagar      18
Kerala                   17
Punjab                   17
Uttar Pradesh            16
Uttarakhand              15
Hyderabad                14
Pune                     12
Chandigarh               12
Mumbai                    8
Chennai                   6
Gurgaon                   5
Goa                       5
Andhra Pradesh            5
Khordha                   4
Sawai Madhopur            4
Thiruvananthapuram        4
Patiala                   3
North West Delhi          3
Ahmedabad                 2
Kanpur Dehat              2
Kozhikode                 2
Thane                     2
Jharkhand                 2
Indore                    2
Vadodara                  2
Dakshin Kannada           1
Jammu and Kashmir         1
South Delhi               1
Bihar                     1
Chhattisgarh              1
Ludhiana                  1
Dehradun                  1
Name: count, dtype: int64

In [261]:
district_mapping = {
    "Ghaziabad": "Uttar Pradesh",
    "Gautam Buddha Nagar": "Uttar Pradesh",
    "Khordha": "Odisha",
    "Sawai Madhopur": "Rajasthan",
    "Patiala": "Punjab",
    "North West Delhi": "Delhi",
    "South Delhi": "Delhi",
    "Kanpur Dehat": "Uttar Pradesh",
    "Kozhikode": "Kerala",
    "Dakshin Kannada": "Karnataka",
    "Ludhiana": "Punjab",
     "Bangalore": "Karnataka",
    "Hyderabad": "Telangana",
    "Pune": "Maharashtra",
    "Mumbai": "Maharashtra",
    "Chennai": "Tamil Nadu",
    "Gurgaon": "Haryana",
    "Ahmedabad": "Gujarat",
    "Vadodara": "Gujarat",
    "Indore": "Madhya Pradesh",
    "Ernakulam": "Kerala",
    "Thiruvananthapuram": "Kerala",
    "Dehradun": "Uttarakhand",
}

df["state"] = df["state"].replace(district_mapping)

In [262]:
df["state"] = df["state"].replace("Thane", "Maharashtra")

In [263]:
df['salary_is_predicted'].value_counts()

salary_is_predicted
0    5200
Name: count, dtype: int64

In [264]:
#longitude and latitude take decision at end
#salary_is_predicted drop 
#redirect_url drop

In [265]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-07T05:28:33Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5790410357?se=bi...,IT Jobs,5790410357,full_time,NaN,NaN,NaN
4,2026-07-09T17:58:24Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,NaN,NaN,NaN

In [266]:
df["description"].isnull().sum()

0

In [267]:
df["description"].duplicated().sum()

669

In [268]:
df["description"].str.contains(r"<[^>]+>", regex=True, na=False).sum()

0

In [269]:
df = df.drop_duplicates(
    subset=["title", "company", "city", "description"],
    keep="first"
).reset_index(drop=True)

In [270]:
df.duplicated(
    subset=["title", "company", "city", "description"]
).sum()

0

In [271]:
print("Leading spaces:", df["description"].str.startswith(" ", na=False).sum())
print("Trailing spaces:", df["description"].str.endswith(" ", na=False).sum())
print("Multiple spaces:", df["description"].str.contains(r" {2,}", regex=True, na=False).sum())
print("Tabs/Newlines:", df["description"].str.contains(r"\t|\n|\r", regex=True, na=False).sum())

Leading spaces: 26
Trailing spaces: 0
Multiple spaces: 186
Tabs/Newlines: 0

In [272]:
df["description"] = (
    df["description"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [273]:
url_count = df["description"].str.contains(
    r"http[s]?://\S+|www\.\S+",
    regex=True,
    na=False
).sum()

print("Descriptions containing URLs:", url_count)

Descriptions containing URLs: 64

In [274]:
df["description"] = df["description"].str.replace(
    r"http[s]?://\S+|www\.\S+",
    "",
    regex=True
)

In [275]:
df["description"].str.contains(
    r"[^a-zA-Z0-9\s.,:;()/+\-#%&]",
    regex=True,
    na=False
).sum()

4711

In [276]:
pd.set_option('display.max_columns', None)

In [277]:
import re
symbols = set()

for text in df["description"].dropna():
    symbols.update(re.findall(r"[^a-zA-Z0-9\s]", text))

print(sorted(symbols))

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '=', '>', '?', '@', '[', '\\', ']', '_', '{', '|', '}', '~', '§', '\xad', '®', '·', 'À', '×', 'Ø', 'à', 'é', 'ê', 'ü', '\u200b', '\u200d', '\u200e', '‑', '–', '—', '‘', '’', '“', '”', '•', '…', '\u2060', '₹', '™', '→', '∙', '⏱', '▪', '○', '●', '☀', '☁', '⚙', '⚡', '✅', '✔', '✨', '❌', '❣', '❤', '➢', '⦿', '⭐', '\ue081', '\ue082', '\uf020', '\uf06c', '\uf095', '\uf0a7', '\uf0b7', '\uf0d8', 'ﬀ', 'ﬁ', 'ﬃ', '️', '\ufeff']

In [278]:
df[df["description"].str.contains(
    r"[^a-zA-Z0-9\s.,:;()/+\-#%&]",
    regex=True,
    na=False
)][["title", "description"]].head(20)

,title,description
0,software engineer,"This job is with ABB, an inclusive employer an..."
1,software engineer,"This job is with Kyndryl, an inclusive employe..."
2,software engineer,"This job is with Cornerstone OnDemand, an incl..."
3,software engineer,"This job is with Morningstar, an inclusive emp..."
4,software engineer,"This job is with Morningstar, an inclusive emp..."
5,software engineer,"This job is with Cornerstone OnDemand, an incl..."
6,software engineer,"This job is with eBay, an inclusive employer a..."
7,senior software engineer,"This job is with Morningstar, an inclusive emp..."
8,senior software engineer,"This job is with ABB, an inclusive employer an..."
9,principal software engineer,"This job is with ABB, an inclusive employer an..."
10,software engineering lead,This job is with LexisNexis Legal & Profession...
11,senior software engineer,"This job is with Morningstar, an inclusive emp..."
12,software engineering qa,"This job is with Kyndryl, an inclusive employe..."
13,senior software engineer,"This job is with Kyndryl, an inclusive employe..."
14,manager of software engineering,"This job is with Morningstar, an inclusive emp..."
15,software engineering lead,"This job is with RX Global, an inclusive emplo..."
16,software engineer - development,"This job is with Kyndryl, an inclusive employe..."
17,senior software engineer,"This job is with Moody's, an inclusive employe..."
18,staff software engineer,"This job is with Moody's, an inclusive employe..."
19,senior software engineer,"This job is with ABB, an inclusive employer an..."

In [279]:
# Remove invisible Unicode characters
df["description"] = df["description"].str.replace(
    r"[\u200b\u200d\u200e\u2060\ufeff\xad]",
    "",
    regex=True
)

In [280]:
# Normalize different dash characters to a normal hyphen
df["description"] = df["description"].str.replace(
    r"[-–—]",
    "-",
    regex=True
)

In [281]:
# Replace bullet symbols with a space
df["description"] = df["description"].str.replace(
    r"[•▪○●∙➢⦿]",
    " ",
    regex=True
)

In [282]:
# Remove icons, emojis, and private-use characters
df["description"] = df["description"].str.replace(
    r"[⏱☀☁⚙⚡✅✔✨❌❣❤⭐→\ue081\ue082\uf020\uf06c\uf095\uf0a7\uf0b7\uf0d8]",
    "",
    regex=True
)

In [283]:
# Replace ligatures
df["description"] = (
    df["description"]
    .str.replace("ﬁ", "fi", regex=False)
    .str.replace("ﬀ", "ff", regex=False)
    .str.replace("ﬃ", "ffi", regex=False)
)

In [284]:
# Remove extra whitespace created during cleaning
df["description"] = (
    df["description"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [285]:
# Observation:
# Most job descriptions are exactly 500 characters long.
# This indicates that the API returns truncated descriptions.
# This is a limitation of the data source, not a data quality issue.

In [286]:
df["description"].str.len().describe()

count    4964.000000
mean      487.076753
std        52.212526
min       103.000000
25%       500.000000
50%       500.000000
75%       500.000000
max       502.000000
Name: description, dtype: float64

In [287]:
df["description"].str.len().value_counts().head(10)

description
500    4014
499     101
498      84
494      60
488      59
490      56
496      54
492      48
486      33
497      18
Name: count, dtype: int64

In [288]:
df["description"].str.len().value_counts().head(10)

description
500    4014
499     101
498      84
494      60
488      59
490      56
496      54
492      48
486      33
497      18
Name: count, dtype: int64

In [289]:
df['company'].value_counts()

company
Accenture                                                         116
Kyndryl                                                            69
Qrata                                                              66
Jobdost                                                            56
Capco                                                              50
Wissen Technology                                                  49
Warner Bros. Discovery                                             45
eBay                                                               45
Reckitt                                                            40
EXL                                                                34
Allianz Commercial                                                 33
Morningstar                                                        32
Multi Recruit                                                      31
Deqode                                                             30
Standard Chartered Bank                                            27
MM Staffing & Career Consultants                                   27
ABB                                                                25
Acura Solution                                                     25
Unnati                                                             25
NeoGenCode Technologies Pvt Ltd                                    22
Deutsche Bank                                                      22
Amgen                                                              22
Twixor                                                             20
Cornerstone OnDemand                                               20
Danaher                                                            20
Praveza Consultancy Private Limited                                18
S&P Global                                                         18
The Hub                                                            18
People First Consultants                                           17
Merito                                                             17
Honeywell                                                          16
RECEX                                                              16
Mancraft Consulting                                                15
Webkit24                                                           15
Virtusa                                                            14
GE Vernova                                                         14
zyoin                                                              14
ALIQAN Technologies                                                14
HP                                                                 14
MSD                                                                14
Mobile Programming LLC                                             13
Weekday AI                                                         13
Trigent Software Private Limited                                   12
Photon Group                                                       12
Moody's                                                            12
Barclays                                                           12
ParamInfo                                                          11
TIGI HR Solution Pvt. Ltd.                                         11
Allime Tech Solutions                                              10
Cognizant                                                          10
Mantras2Success                                                    10
Hunarstreet Technologies Pvt Ltd                                   10
Gipfel & Schnell Consultings Pvt Ltd                               10
UnitedHealth Group                                                  9
Topcoder                                                            9
Novartis                                                            9
Google                                                              9
CONTUS TECH                                                         8
BSR & Co                                                            8
LTM                                                                 8
VyTCDC                                                              8
codersbrain                                                         8
r3 Consultant                                                       8
InvokHR                                                             8
Peak Hire Solutions                                                 7
UPS                                                                 7
Uplers                                                              7
wrackle                                                             7
Vrinda International                                                7
Fragma Data Systems                                                 7
Pluginlive                                                          7
upGrad                                                              7
Jobgether                                                           7
Career Creed HR Services                                            7
Tech Smcsquared Gcc                                                 7
Vector Labs Tech                                                    7
Adobe                                                               6
Zscaler                                                             6
Onzestt Services India Private Limited                              6
Hewlett Packard Enterprise                                          6
Mobile Programming India Pvt Ltd                                    6
Success Pact                                                        6
Ion                                                                 6
Carrier                                                             6
Colan Infotech Private Limited                                      6
Bajaj Finance Limited                                               6
appscrip                                                            6
MSCI                                                                6
Aristocrat                                                          6
We Search                                                           6
Amagi Media Labs                                                    6
Etaash Consultants                                                  6
NTT America, Inc.                                                   6
Ecolab                                                              6
Fusemachines                                                        6
Neal Analytics                                                      5
Quantiphi                                                           5
Symansys Technologies India Pvt Ltd                                 5
Roku                                                                5
CIEL HR Services                                                    5
The Cigna Group                                                     5
Test                                                                5
Flexera Software                                                    5
Intuitive Technology Partners                                       5
CloudSEK                                                            5
Eurofins GSC IT DC                                                  5
CGI                                                                 5
American Technology Consulting                                      5
Intuitive Apps India Private Limited                                5
Marktine                                                            5
Tata Elxsi Limited                                                  5
Capgemini                                                           5
Career One Stop                                                     5
HyreSpree                                                           5
New Era India                                                       5
Talent Leads Consultants                                            4
Tradelab Technologies                                               4
SKS Enterpprises                                                    4
Aliqan Services                                                     4
Rajesh Kumar                                                        4
Sparix Global.                                                      4
Adani                                                               4
Emerson                                                             4
Lloyds Bank                                                         4
Getinz                                                              4
Datamatics Technologies                                             4
RHC India                                                           4
Sia                                                                 4
Recro                                                               4
Catalyst IQ                                                         4
NAVVYASA CONSULTING PRIVATE LIMITED                                 4
RX Global                                                           4
Right Advisors                                                      4
Thales                                                              4
Talent Pro                                                          4
Tech Mahindra Limited                                               4
Dotball Interactive Private Limited                                 4
Indovision Services                                                 4
Sadup Softech                                                       4
Talent Socio Bizcon LLP                                             4
Synechron                                                           4
Hirestar job Bank                                                   4
Hitachi                                                             4
Amazon                                                              4
Versatile Commerce LLP                                              4
Antworks Solutions India Private Limited                            4
MUFG Global Service                                                 4
Cohere Health                                                       4
Open Text Technologies India Private Limited                        4
SAP                                                                 4
CES Information Technologies                                        4
Wipro Limited                                                       4
Promotup HR Solutions                                               4
Smartworks                                                          4
Abbyy                                                               4
Whitefield Careers                                                  4
Bosch India                                                         4
XenonStack                                                          4
PricewaterhouseCoopers                                              4
Tessolve Semiconductor Private Limited                              4
Terralogic Software Solutions                                       4
Semperfi Solution                                                   4
Logic Planet                                                        4
02 May                                                              4
Five9                                                               4
Vmultiply solutions                                                 4
Infor                                                               4
Humancloud Technology Pvt Ltd                                       4
A3R0-GTCI                                                           4
Spector.ai                                                          4
Anzy                                                                4
Cisco                                                               4
Response Informatics                                                4
Euclid Innovations Private Limited                                  4
QAgile Services                                                     3
Innovatily                                                          3
Ganit Business Solutions                                            3
Flytbase                                                            3
Gruve                                                               3
Kaleidofin                                                          3
Aristocrat Technologies                                             3
Zyoin Web Private Limited                                           3
Arise Global Services                                               3
Blue Sky Analytics                                                  3
WEN                                                                 3
Cadence                                                             3
London Stock Exchange Group                                         3
Mithra Global                                                       3
dentsu                                                              3
Innovalus Technologies                                              3
P99soft                                                             3
AQM Technologies                                                    3
Recruit Square                                                      3
HashRoot                                                            3
Edwards Lifesciences                                                3
Agile Hire                                                          3
GRowth Gamut Pvt. Ltd                                               3
Tridat Technologies Pvt. Ltd.                                       3
ConsultBae                                                          3
Bohiyaanam Talent Solutions                                         3
Nexsys                                                              3
Particle41                                                          3
Zyvka Global Services                                               3
VUMONIC                                                             3
Siemens Energy                                                      3
Zolvit                                                              3
IAI solution                                                        3
SOT-Science of talent Acquisition consulting services Pvt Ltd       3
Wenger and Watson Inc                                               3
Indus Net Technologies Ltd                                          3
Phenom People                                                       3
Digirex Technologies                                                3
KSB                                                                 3
makeO                                                               3
HaystackAnalytics                                                   3
Genpact India                                                       3
Schbang Digital Solutions                                           3
Novel Office                                                        3
Evoke HR Solutions                                                  3
PubMatic                                                            3
Pion Global Solutions LTD                                           3
Tradelab Software Private Limited                                   3
Align Technology                                                    3
WPP                                                                 3
BitClass                                                            3
Latent Bridge Pvt Ltd                                               3
FM India                                                            3
Indium Software                                                     3
Embitel Technologies                                                3
Vy Systems                                                          3
Epsilon                                                             3
Z5                                                                  3
TAC Security                                                        3
Solventum                                                           3
Qualcomm                                                            3
Saxon Global INC                                                    3
Thinqor                                                             3
Compunnel Technology India Private Limited                          3
Zycus                                                               3
ERM                                                                 3
Ezeiatech systems                                                   3
Kapture CX                                                          3
Emproto Technologies Private Limited                                3
Level AI                                                            3
Srijan Technologies                                                 3
Sandisk                                                             3
kaldan soft                                                         3
Two95 International Inc.                                            3
Rezo.AI                                                             3
RidenRoll                                                           3
TensorIoT Software Services Private Limited, India                  3
Baker Hughes                                                        3
Aditi Tech Consulting Private Limited                               3
Intineri infosol Pvt Ltd                                            3
InTouch CX                                                          3
Fatakpay                                                            3
Jumio                                                               3
About Ferguson                                                      3
AlphaSense India                                                    3
IRIS BUSINESS SERVICES LIMITED                                      3
MTAP Technologies                                                   3
WyngCommerce                                                        3
Harman Becker Automotive Systems Manufacturing Kft                  3
Officeworks                                                         3
Dori AI                                                             3
Metron Security Private Limited                                     3
Tata Consultancy Services                                           3
Invesco                                                             3
Persistent Systems                                                  3
Wise                                                                3
Gururo                                                              3
AVE-Promagne Business Solutions LLP                                 3
SkillCircle™                                                        3
Qualitykiosk Technologies Private Limited                           3
Cornerstone onDemand                                                3
Myna Solutions                                                      3
Fort Technologies                                                   3
ADM                                                                 3
Avaloq                                                              3
Anzy Careers                                                        3
NatWest Markets                                                     3
Sparks To Ideas                                                     3
BigRio                                                              3
Trellix                                                             3
Gracira Technologies LLP                                            3

In [290]:
# In company columns is different name of same company 
#Cornerstone onDemand-Cornerstone OnDemand

In [291]:
df["company"] = df["company"].str.strip()

In [292]:
df["company"].str.lower().nunique()

2509

In [293]:
df["company"].nunique()

2521

In [294]:
company_case = (
    df.groupby(df["company"].str.lower())["company"]
    .unique()
)

company_case[company_case.str.len() > 1]

company
ascendion                                     [Ascendion, ascendion]
bcforward                                     [BCforward, BCForward]
careernet                                     [Careernet, CareerNet]
cornerstone ondemand    [Cornerstone OnDemand, Cornerstone onDemand]
easebuzz                                        [EASEBUZZ, Easebuzz]
hashroot                                        [HashRoot, Hashroot]
intouchcx                                     [intouchcx, IntouchCX]
rezo.ai                                           [Rezo.ai, Rezo.AI]
sandisk                                           [SanDisk, Sandisk]
skillenza                                     [Skillenza, skillenza]
vmultiply solutions       [Vmultiply solutions, VMultiply Solutions]
vy systems                                  [Vy Systems, Vy systems]
Name: company, dtype: object

In [295]:
company_mapping = {
    "Ascendion": "Ascendion",
    "ascendion": "Ascendion",
    
    "BCforward": "BCForward",
    "BCForward": "BCForward",
    
    "Careernet": "CareerNet",
    "CareerNet": "CareerNet",
    
    "EASEBUZZ": "Easebuzz",
    "Easebuzz": "Easebuzz",
    
    "HashRoot": "HashRoot",
    "Hashroot": "HashRoot",
    
    "intouchcx": "IntouchCX",
    "IntouchCX": "IntouchCX",
    
    "Rezo.ai": "Rezo.AI",
    "Rezo.AI": "Rezo.AI",
    
    "Skillenza": "Skillenza",
    "skillenza": "Skillenza",
    
    "Vmultiply solutions": "VMultiply Solutions",
    "VMultiply Solutions": "VMultiply Solutions",
    
    "Vy Systems": "Vy Systems",
    "Vy systems": "Vy Systems",
    
    'Cornerstone onDemand':'Cornerstone OnDemand',
    
    'Sandisk':'SanDisk',
    
    'Tech Mahindra' : 'Tech Mahindra Limited',

}

df["company"] = df["company"].replace(company_mapping)

In [296]:
company_mapping = {
    "TCS": "Tata Consultancy Services",
    "Tata Consultancy": "Tata Consultancy Services",
    "Microsoft Corporation": "Microsoft"
}

df["company"] = df["company"].replace(company_mapping)

In [297]:
url_company = df[
    df["company"].str.contains(
        r"www\.|https?://|\.com|\.in$",
        case=False,
        na=False
    )
][["company", "title", "description"]]

url_company

,company,title,description
213,Healthians.com,software engineer/sr.software engineer,Position Software Developer/Sr.Software Develo...
509,SocialPrachar.com,data scientist,Hi We are Looking foe Data Science AI Professi...
1153,Tradeindia.com - Infocom Network,machine learning engineer,Tradeindia is looking for Machine Learning Eng...
1598,www.Houseitt.in,backend developer,ABOUT HOUSEITT: HouseItt is a student-run star...
1693,MondayMorning.in,backend developer,"Responsibilities: Write well designed, testabl..."
1782,Collegedunia.com,backend developer,Responsibilities : Design of the overall archi...
1789,Mezi.com,backend developer,We are at Mezi building an AI-enabled chat-bot...
1815,www.talentdekho.in,backend developer,- 2yrs of experience in Node.js with API frame...
1981,www.Houseitt.in,frontend developer,ABOUT HOUSEITT: HouseItt is a student-run star...
3763,Olacabs.com,devops engineer,We are looking for a Site Reliability Engineer...
3799,EaseMyTrip.com,devops engineer,Key Responsibilities: ️ Manage cloud infrastru...

In [298]:
company_mapping = {
    "Healthians.com": "Healthians",
    "SocialPrachar.com": "SocialPrachar",
    "Tradeindia.com - Infocom Network": "TradeIndia",
    "www.Houseitt.in": "HouseItt",
    "MondayMorning.in": "MondayMorning",
    "Collegedunia.com": "CollegeDunia",
    "Mezi.com": "Mezi",
    "www.talentdekho.in": "TalentDekho",
    "Olacabs.com": "Ola",
    "EaseMyTrip.com": "EaseMyTrip"
}

df["company"] = df["company"].replace(company_mapping)

In [299]:
df[df["company"].isin([
    "Healthians",
    "SocialPrachar",
    "TradeIndia",
    "HouseItt",
    "MondayMorning",
    "CollegeDunia",
    "Mezi",
    "TalentDekho",
    "Ola",
    "EaseMyTrip"
])]["company"].value_counts()

company
HouseItt         2
Healthians       1
SocialPrachar    1
TradeIndia       1
MondayMorning    1
CollegeDunia     1
Mezi             1
TalentDekho      1
Ola              1
EaseMyTrip       1
Name: count, dtype: int64

In [300]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-09T17:58:24Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,NaN,NaN,NaN
4,2026-07-03T00:54:21Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5785771924?se=bi...,IT Jobs,5785771924,full_time,NaN,NaN,NaN

In [301]:
# cargill business services and cargill can not merge because not have evidence 
#InTouch system can not merge because not have evidence

In [302]:
# replace:Persisent:Persistent Systems,Ciso systems:Ciso,Comcast Corporation:Comcast,
#Kyndryl Solutions Private Limited:Kyndryl,InTouch CX:IntouchCX
#Amazon India": "Amazon",

In [303]:
df[df['company'].str.contains('Persistent',na=False)][['title','company','description']]

,title,company,description
321,software engineer,Persistent Systems,"About Persistent We are an AI-led, platform-dr..."
2549,full stack developer,Persistent Systems,"About Persistent We are an AI-led, platform-dr..."
2711,python developer,Persistent,"What You'll Do: Design, implement, and scale d..."
3487,devops engineer,Persistent,We are looking for a DevOps Engineer to help u...
4832,business analyst,Persistent Systems,"About Persistent We are an AI-led, platform-dr..."

In [304]:
df[df['company'].str.contains('Cisco',na=False)][['title','company','description']]

,title,company,description
232,software engineer,Cisco Systems,Meet the Team Our Incident Command Software En...
307,software engineer,Cisco,Looking forward to getting an exciting start t...
324,software engineer,Cisco,Responsibilities: Design and implementation of...
941,data analyst,Cisco,Meet the Team The Customer Listening & Analyti...
4107,"cloud engineer | 8 years, infra support & moni...",Cisco Systems,"As cloud engineer, utilizes knowledge of softw..."
4108,"cloud engineer | 8 years, infra support & moni...",Cisco,"As cloud engineer, utilizes knowledge of softw..."

In [305]:
df[df['company'].str.contains('Comcast',na=False)][['standard_role','company','description']]

,standard_role,company,description
1096,Data Analyst,Comcast,Job Summary Responsible for working cross-func...
1431,Machine Learning Engineer,Comcast,Comcast brings together the best in media and ...
4401,Cyber Security,Comcast Corporation,You will be responsible for contributing towar...

In [306]:
df[df['company'].str.contains('Amazon',na=False)][['standard_role','company','description']]

,standard_role,company,description
854,Data Analyst,Amazon,Data Analyst Job Description : About GlowRoad:...
1379,Machine Learning Engineer,Amazon,Description Are you obsessed with solving chal...
1797,Backend Developer,Amazon India,"Amazon Opportunity Dear Candidate, I came acro..."
1836,Backend Developer,Amazon India,Role - Software Development Engineer-2 As a So...
4816,Business Analyst,Amazon,"Description At Amazon.com, we strive to be Ear..."
4823,Business Analyst,Amazon,"Description At Amazon.com, we strive to be Ear..."

In [307]:
df[df['company'].str.contains('Cargill',na=False)][['standard_role','company','description']]

,standard_role,company,description
246,Software Engineer,Cargill,"Job Purpose and Impact The Professional, Softw..."
278,Software Engineer,Cargill,Apply innovative and advanced software enginee...
3658,DevOps Engineer,Cargill Business Services,Job Purpose and Impact The DevOps Engineer is ...
3927,Cloud Engineer,Cargill Business Services,The Cloud Engineer will design and develop the...

In [308]:
df[df['company'].str.contains('Kyndryl',na=False)][['standard_role','company','description']]

,standard_role,company,description
1,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
12,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
13,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
16,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
23,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
24,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
41,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
51,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
54,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
78,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
79,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
81,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
85,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
94,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
98,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
99,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
122,Software Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
135,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
136,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
139,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
146,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
161,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
162,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
163,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
164,Backend Developer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
167,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
169,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
180,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
186,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
202,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
204,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
218,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
342,Software Engineer,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
361,Data Scientist,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
362,Data Scientist,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
426,AI Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
675,Data Scientist,Kyndryl,"Who We Are At Kyndryl, we design, build, manag..."
684,Data Scientist,Kyndryl,"Who We Are At Kyndryl, we design, build, manag..."
700,Data Scientist,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
701,Data Scientist,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
702,Data Scientist,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
760,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
778,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
1082,Data Analyst,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
1083,Data Analyst,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
1084,Data Analyst,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
1375,AI Architect,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
1397,AI Architect,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3066,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3451,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3454,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3458,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3461,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3464,Platform Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3465,Platform Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3470,DevOps Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3680,DevOps Engineer,Kyndryl Solutions Private Limited,The Role Are you passionate about solving comp...
3750,DevOps Engineer,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
3757,DevOps Engineer,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
3837,Cloud Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3838,Cloud Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3839,Cloud Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3840,Cloud Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
3849,Cloud Engineer,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
4086,Cloud Engineer,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
4087,Cloud Engineer,Kyndryl,"Who We Are At Kyndryl, we run and reimagine th..."
4248,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
4249,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
4399,Other,Kyndryl,"This job is with Kyndryl, an inclusive employe..."
4470,Cyber Security,Kyndryl Solutions Private Limited,The Role Your responsibilities will be varied ...
4584,Business Analyst,Kyndryl,"This job is with Kyndryl, an inclusive employe..."

In [309]:
for i in [803, 2327,2390,992, 2313]:
    print(f"\n{'='*80}")
    print("ROW:", i)
    print("COMPANY:", df.loc[i, "company"])
    print("TITLE:", df.loc[i, "title"])
    print("DESCRIPTION:")
    print(df.loc[i, "description"])

================================================================================
ROW: 803
COMPANY: InTouch CX
TITLE: data analyst
DESCRIPTION:
About the Job We are revolutionizing the way people perceive customer service, and we require your assistance! We are currently seeking a Data Analyst who will be responsible for analyzing and reporting on operational data in an effort to enhance program performance visibility. This role will also contribute to various projects and perform ad-hoc analyses to provide timely information and support for strategic decision-making. As Data Analyst, You Will… Continuously monitor and evaluate data to…

================================================================================
ROW: 2327
COMPANY: InTouch CX
TITLE: full stack developer
DESCRIPTION:
About the Job We are seeking a Full Stack Developer to play a role in the design, development and special projects for the client. The selected candidate will be responsible for ensuring all software solutions and enhancements are fully tested, debugged, and meet product quality standards while being delivered on time and on budget. Additionally, the role requires to perform a continuous review of technologies, industry standards, and industry-related developments, and make recommendations rega…

================================================================================
ROW: 2390
COMPANY: InTouch Systems
TITLE: full stack developer
DESCRIPTION:
We have hiring for Full stack developer. Experience in Angular version 6 & above. Other skills- Front End Developer - Including Angular Back End Developer with ASP.Net MVC Back End Developer with Azure or MS Core Project based experience HTML CSS Bootstrap Javascript Skills:- ASP.NET, C#, Angular (2) and MVC Framework

================================================================================
ROW: 992
COMPANY: IntouchCX
TITLE: hiring- data analyst
DESCRIPTION:
About the Job Join us in transforming the perception of customer service! We are seeking a dedicated Data Analyst to analyze and report on operational data, enhancing program performance visibility. This role is vital in contributing to various projects and performing ad-hoc analyses, providing timely insights that support strategic decision-making. If you are passionate about data and eager to make a significant impact, we invite you to apply! As Data Analyst, You Will Collect and organize lar…

================================================================================
ROW: 2313
COMPANY: IntouchCX
TITLE: full stack developer
DESCRIPTION:
Job Description About the Job We are seeking a Full Stack Developer to play a role in the design, development and special projects for the client. The selected candidate will be responsible for ensuring all software solutions and enhancements are fully tested, debugged, and meet product quality standards while being delivered on time and on budget. Additionally, the role requires to perform a continuous review of technologies, industry standards, and industry-related developments, and make reco…

In [310]:
df[df['company'].str.contains('InTouch',na=False)][['standard_role','company','description']]

,standard_role,company,description
788,Data Analyst,InTouch CX,About the Job We are looking for a Data Analys...
803,Data Analyst,InTouch CX,About the Job We are revolutionizing the way p...
2327,Full Stack Developer,InTouch CX,About the Job We are seeking a Full Stack Deve...
2390,Full Stack Developer,InTouch Systems,We have hiring for Full stack developer. Exper...

In [311]:
df[df['company'].str.contains('IntouchCX',na=False)][['standard_role','company','description']]

,standard_role,company,description
992,Data Analyst,IntouchCX,About the Job Join us in transforming the perc...
2313,Full Stack Developer,IntouchCX,Job Description About the Job We are seeking a...

In [312]:
df[df['company'].str.contains('EaseMyTrip',na=False)][['standard_role','company','description']]

,standard_role,company,description
3799,DevOps Engineer,EaseMyTrip,Key Responsibilities: ️ Manage cloud infrastru...

In [313]:
#Merge them "Aristocrat Technologies": "Aristocrat"
# "Fortive Corporation":"Fortive"
# "A P Moller Maersk": "Maersk"
# "Thales India Private Limited":"Thales"

In [314]:
company_mapping = {
    "Persistent": "Persistent Systems",
    "Cisco Systems": "Cisco",
    "Comcast Corporation": "Comcast",
    "Amazon India": "Amazon",
    "Kyndryl Solutions Private Limited": "Kyndryl",
    "InTouch CX": "IntouchCX",
    'Fortive Corporation':"Fortive",
    "A P Moller Maersk":"Maersk",
    "Thales India Private Limited":"Thales",
     "Aristocrat Technologies":"Thales",
    "Quantiphi Inc.":"Quantiphi",
    "Antal International Network":"Antal International",
    "Matellio India Private Limited":"Matellio Inc",
    "Infogain Corporation":"Infogain",
    "ServiceNow, Inc.":"ServiceNow",
    "Magna International, Inc":"Magna International",
    "Simform Solutions": "Simform",
    "Vysystem pvt Ltd":"Vy Systems",
    "Easemytrip com":"EaseMyTrip",
    "Cigna Group":"The Cigna Group",
    "Mercari, Inc":"Mercari, Inc.",
    "Guidehouse India Pvt Ltd":"Guidehouse",
    "upGrad International":"upGrad"
}

df["company"] = df["company"].replace(company_mapping)

In [315]:
df[df['company'].str.contains('LTM',na=False)][['title','company','description']]

,title,company,description
166,duckcreek integration-product engineer,LTM,Duck CreekIntegration Position Product Enginee...
513,data scientist,LTM,Urgent Hiring | Senior Data Scientist - Risk A...
626,data scientist,LTM,Role description An AIML Engineer designs deve...
1930,frontend developer,LTM,The ideal candidate will be responsible for de...
2703,python developer,LTM,Greetings from LTM! We are excited to inform y...
2844,python developer,LTM,Job Summary Experience : 8 to 12 years notice ...
2907,python developer,LTM,Job Description - Python Gen AI Developer Expe...
4296,cyber security specialist,LTM,Notice period - Imm to 30 Days. Location- PAN ...

In [316]:
for i in [3566,4495,166,513,2844]:
    print(f"\n{'='*80}")
    print("ROW:", i)
    print("COMPANY:", df.loc[i, "company"])
    print("TITLE:", df.loc[i, "title"])
    print("DESCRIPTION:")
    print(df.loc[i, "description"])

================================================================================
ROW: 3566
COMPANY: LT-Larsen & Toubro Limited
TITLE: devops engineer
DESCRIPTION:
Job Purpose We are seeking a highly experienced DevOps Engineer with exceptional expertise in AI-enabled Cloud Engineering, Observability, Operational Intelligence, and AI-driven automation. The ideal candidate will bring 5 to 8 years of enterprise-level Devops experience, with a focus on building innovative AI-enabled platforms, data-driven automation frameworks, and enterprise-grade AIOps solutions to advance operational efficiency. Role Summary Key Responsibilities Design and deliver scalabl…

================================================================================
ROW: 4495
COMPANY: LT-Larsen & Toubro Limited
TITLE: domain architect & digital adviser – cyber security /oa &it system
DESCRIPTION:
The domain Architect Cyber Security and OA/IT is a special skill Roll required to support the Telecom EDRC and Business development for the opportunities in S&T projects of MRT, High Speed, LRT and Main Line. This domain architect will ensure that the design of the network and the infrastructure is implemented with Cyber security to prevent data security, cyber threats and all the security policies are implemented in the Metro and mainline projects. This role will also help in implementing the …

================================================================================
ROW: 166
COMPANY: LTM
TITLE: duckcreek integration-product engineer
DESCRIPTION:
Duck CreekIntegration Position Product Engineer The Duck CreekPolicy Position Product Engineer is a key contributor to the success of the Duck CreekPolicy product This role requires a combination of technical and business skills to develop document and maintain the product The Product Engineer must be able to work closely with the business development and support teams to ensure the product is designed and implemented to meet customer requirements Responsibilities Analyze customer requirements …

================================================================================
ROW: 513
COMPANY: LTM
TITLE: data scientist
DESCRIPTION:
Urgent Hiring | Senior Data Scientist - Risk Assessment & Data Analytics Work Location - Noida Strictly be 5 Days work from Client Office BE/B-Tech (CSE/IT/ECE), ME/M-Tech (CSE/IT/ECE), MCA Looking for experienced Data Scientists (10) with strong expertise in Machine Learning, Statistical Modeling & Risk Analytics for a high-impact Government project ( 4-5 Years ) Must Have: Hands-on Data Scientist experience (core role) Experience in Government / PSU projects Strong ML, Data Analysis & Visuali…

================================================================================
ROW: 2844
COMPANY: LTM
TITLE: python developer
DESCRIPTION:
Job Summary Experience : 8 to 12 years notice : 0 -60 days Location : Pune,Chennai, Mumbai,Kolkata, Bengaluru,Noida We are seeking a highly skilled Python Full Stack Developer to design, develop, and maintain scalable web applications. The ideal candidate should have strong experience in Python-based backend development, modern frontend frameworks, REST API development, database design, and cloud technologies. The role requires close collaboration with cross-functional teams to deliver high-qua…

In [317]:
"Quantiphi Inc.":"Quantiphi",
"Antal International Network":"Antal International",
"Matellio India Private Limited":"Matellio Inc",
"Infogain Corporation":"Infogain",
"ServiceNow, Inc.":"ServiceNow",
"Magna International, Inc":"Magna International",
"Simform Solutions": "Simform",
"Vysystem pvt Ltd":"Vy Systems",
"Easemytrip com":"EaseMyTrip",
"Cigna Group":"The Cigna Group",
"Mercari, Inc":"Mercari, Inc.",
"Guidehouse India Pvt Ltd":"Guidehouse",
"upGrad International":"upGrad"

SyntaxError: illegal target for annotation (2204661346.py, line 1)

In [318]:
df['company'].isna().sum()

56

In [319]:
(df['company'] == 'Unknown').sum()

0

In [320]:
unknown_company = df[df['company'] == 'Unknown']

unknown_company[['title', 'description']]

Empty DataFrame
Columns: [title, description]
Index: []

In [321]:
df['standard_role'].isna().sum()

0

In [322]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-09T17:58:24Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,NaN,NaN,NaN
4,2026-07-03T00:54:21Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5785771924?se=bi...,IT Jobs,5785771924,full_time,NaN,NaN,NaN

In [323]:
df.loc[
    df["company"].isna(),
    ["title", "location", "city", "state", "description"]
]

,title,location,city,state,description
201,software engineer,"Lucknow, Uttar Pradesh",Lucknow,Uttar Pradesh,APV Technologies Private Limited is a product ...
223,software engineer,"Bangalore, Karnataka",Bangalore,Karnataka,The Software Engineering team delivers next-ge...
261,software engineer,"Bangalore, Karnataka",Bangalore,Karnataka,"Experience with Pega development and support,s..."
267,software engineer,"Thiruvananthapuram, Kerala",Thiruvananthapuram,Kerala,Looking for ( Software Engineer )Job SummaryWe...
269,software engineer,"Kerala, India",Unknown,Kerala,Develops software solutions by studying inform...
276,software engineer,"Bangalore, Karnataka",Bangalore,Karnataka,Executing full lifecycle software development ...
768,data analyst,"Thiruvananthapuram, Kerala",Thiruvananthapuram,Kerala,Immediate requirement for the post of Data Ana...
822,data analyst,"Vadodara, Gujarat",Vadodara,Gujarat,We are Hiring for ( Data Analyst ) ( Desired C...
958,data analyst,"Navi Mumbai, Maharashtra",Navi Mumbai,Maharashtra,Our Client have a wealth of experience in ente...
959,data analyst,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,"HiWelcome students, ladies, to allDo u have a ..."
962,data analyst,"Mumbai, Maharashtra",Mumbai,Maharashtra,Job description Conducting the Validation & Au...
963,data analyst,"Gurgaon, Haryana",Gurgaon,Haryana,Job brief We are looking for a passionate prof...
964,data analyst,"Mumbai, Maharashtra",Mumbai,Maharashtra,1. MIS generation 2. Coordination and Administ...
965,data analyst,"Mumbai, Maharashtra",Mumbai,Maharashtra,Acquire data from primary or secondary data so...
966,data analyst,"Hyderabad, Telangana",Hyderabad,Telangana,Data gathering/ Research Assist team leaders i...
967,data analyst,"Bangalore, Karnataka",Bangalore,Karnataka,Its primary target is to create and maintain d...
1303,machine learning engineer data scientist,India,Unknown,NaN,As a skilled Machine Learning Engineer Data Sc...
1892,frontend developer,"Ernakulam, Kerala",Kochi,Kerala,Do you have the skills and experience to devel...
2307,full stack developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,We are looking for Full Stack Developer with m...
2353,full stack developer,"Delhi, India",Delhi,Delhi,Full Stack Developer with experience in Node.j...
2400,full stack developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,Full Stack Developer Requirements:Degree in Co...
2428,full stack developer,"Kolkata, West Bengal",Kolkata,West Bengal,Role: Full Stack Developer Salary - 30K - 35K ...
2462,full stack developer,"Kolkata, West Bengal",Kolkata,West Bengal,Duties and Responsibilities - We’re looking fo...
2525,full stack developer,"Hyderabad, Telangana",Hyderabad,Telangana,We are Looking for a Full Stack PHP Developer ...
2674,python developer,"Warangal, Telangana",Warangal,Telangana,Python Developer Job Description: Python Devel...
2678,python developer,"Hyderabad, Telangana",Hyderabad,Telangana,Blue Bird Solutions is a technology consulting...
2698,python developer,"Noida, Ghaziabad",Noida,Uttar Pradesh,PROFILE : Backend Python Developer SKILLS REQU...
2708,python developer,"Delhi, India",Delhi,Delhi,JD - Python Developer -For Sofitra Position: P...
2728,python developer,"Noida, Ghaziabad",Noida,Uttar Pradesh,Hi We do have an opportunity for python develo...
2773,python developer,"Dehradun, Uttarakhand",Dehradun,Uttarakhand,"Good knowledge in Python, Java, SQL. Strong Co..."
3070,java developer,"Thane, Maharashtra",Thane,Maharashtra,Greetings from 1iT Consulting Position: Java D...
3072,java developer,"Mumbai, Maharashtra",Mumbai,Maharashtra,Godrej Infotech is hiring Java Developer. In t...
3076,java developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,We are looking for Java developer for IT MNC c...
3078,java developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,LOOKING FOR JAVA DEVELOPERNAME OF THE COMPANY ...
3080,java developer,"Pune, Maharashtra",Pune,Maharashtra,Opening for Java DeveloperExperience- 1-4 year...
3195,java developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,We are Hearing For- ( Java Developer ) 1) Java...
3206,java developer,"Delhi, India",Delhi,Delhi,Work From Office Location- Noida Role- Java de...
3217,java developer,"Pune, Maharashtra",Pune,Maharashtra,We are Hearing for ( Java Developer ) Designin...
3234,java developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,Hi We have an urgent requirement for java deve...
3240,java developer,"Pune, Maharashtra",Pune,Maharashtra,We are looking for an Java Developer for our B...
3267,java developer,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,We are looking for a resource who is strong in...
3311,java developer,"Coimbatore, Tamil Nadu",Coimbatore,Tamil Nadu,Java Developer with experience in application ...
3316,java developer,"Hyderabad, Telangana",Hyderabad,Telangana,We are Hearing for -( Java Developer ) Minimum...
3342,java developer,"Pune, Maharashtra",Pune,Maharashtra,Qualifications & Responsibilities Strong hands...
3612,devops engineer,"Pune, Maharashtra",Pune,Maharashtra,We are looking for a full-time remote DevOps E...
3820,devops engineer,"New Delhi, Delhi",Delhi,Delhi,Job Description Roles and Responsibilities Ope...
4265,cyber security intern,"Hyderabad, Telangana",Hyderabad,Telangana,Cyber Security Internship Program on Forensics...
4267,sme cyber security,"Bangalore, Karnataka",Bangalore,Karnataka,Responsibilities Threat Modeling & Threat Anal...
4303,cyber security analyst,"Delhi, India",Delhi,Delhi,JOB REQUIREMENTS AND QUALIFICATIONS Bachelor's...
4656,business analyst,"Noida, Ghaziabad",Noida,Uttar Pradesh,We are hiring a Business Analyst to join our p...
4697,business analyst,"Chennai, Tamil Nadu",Chennai,Tamil Nadu,We are looking for Business Analyst Responsibi...
4714,business analyst,"Noida, Ghaziabad",Noida,Uttar Pradesh,You will be responsible for 4-5 years of Busin...
4717,business analyst,"Noida, Ghaziabad",Noida,Uttar Pradesh,Kronos is hiring a Business Analyst in Noida w...
4739,business analyst,"Gurgaon, Haryana",Gurgaon,Haryana,The successful candidate will be part of Analy...
4744,business analyst,"Thane, Maharashtra",Thane,Maharashtra,We are Hearing For _ ( Business Analyst ) Job ...
4754,business analyst,"Delhi, India",Delhi,Delhi,Job description Role Title : Technical Busines...

In [324]:
for i in [2548]:
    print(f"\n{'='*80}")
    print("ROW:", i)
    print("COMPANY:", df.loc[i, "company"])
    print("TITLE:", df.loc[i, "title"])
    print("DESCRIPTION:")
    print(df.loc[i, "description"])
    print('category')
    print(df.loc[i,'category'])

================================================================================
ROW: 2548
COMPANY: Recruit Square
TITLE: full stack developer
DESCRIPTION:
About the Role: We are looking for a skilled Full-Stack Developer with expertise in Python, JavaScript, and No-Code AI tools to join our dynamic team. The ideal candidate should be proficient in both backend and frontend development, capable of working with modern frameworks, and have experience in LLM prompt engineering, data extraction, and response formatting. Key Responsibilities: Develop and maintain scalable backend services using FastAPI / Flask / Django. Build dynamic front-end applicat…
category
Unknown

In [325]:
df.loc[201, "company"] = "APV Technologies Private Limited"
df.loc[261, "company"] = "Globex Digital Solutions Pvt. Ltd"
df.loc[2428, "company"] = "AdzGuru"
df.loc[2678, "company"] = "Blue Bird Solutions"
df.loc[2708, "company"] = "Sofitra"
df.loc[3070, "company"] = "1iT Consulting"
df.loc[3072, "company"] = "Godrej Infotech"
df.loc[3078, "company"] = "Data Prompt"
df.loc[4717, 'company'] = 'Kronos'
df.loc[4265,'company']= "CyberLoop"

In [326]:
df['company'] = df['company'].fillna('Unknown')

In [327]:
For your company-cleaning work, examples like:

Aristocrat / Aristocrat Technologies
Fortive / Fortive Corporation
Maersk / A P Moller Maersk
Bosch India / Bosch Group
Thales / Thales India Private Limited

SyntaxError: invalid syntax (1252372006.py, line 1)

In [328]:
df['category'].isna().sum()

0

In [329]:
df['category'].value_counts()

category
IT Jobs                             4679
Engineering Jobs                      81
Accounting & Finance Jobs             71
Sales Jobs                            36
Teaching Jobs                         25
Scientific & QA Jobs                  24
Consultancy Jobs                      12
PR, Advertising & Marketing Jobs       9
Energy, Oil & Gas Jobs                 6
HR & Recruitment Jobs                  6
Admin Jobs                             4
Healthcare & Nursing Jobs              3
Trade & Construction Jobs              2
Retail Jobs                            1
Legal Jobs                             1
Creative & Design Jobs                 1
Unknown                                1
Customer Services Jobs                 1
Logistics & Warehouse Jobs             1
Name: count, dtype: int64

In [330]:
df[df['category'] == 'Unknown'][['title', 'company', 'location', 'city', 'state', 'description']]

,title,company,location,city,state,description
2548,full stack developer,Recruit Square,India,Unknown,NaN,About the Role: We are looking for a skilled F...

In [331]:
print("Total rows:", len(df))
print("Category counts:", df['category'].value_counts(dropna=False).sum())

Total rows: 4964
Category counts: 4964

In [332]:
df.loc[2548, 'category'] = 'IT Jobs'

In [333]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,NaN,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,NaN,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,NaN,NaN,NaN
3,2026-07-09T17:58:24Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,NaN,NaN,NaN
4,2026-07-03T00:54:21Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5785771924?se=bi...,IT Jobs,5785771924,full_time,NaN,NaN,NaN

In [334]:
df['contract_time'].value_counts()

contract_time
full_time    3897
part_time       3
Name: count, dtype: int64

In [335]:
df[df['contract_time'].isna()][
    ['title', 'standard_role', 'company', 'category', 'contract_time']
].head(20)

,title,standard_role,company,category,contract_time
95,network software engineering leader - presales...,Software Engineer,ACL Digital,IT Jobs,NaN
137,aem content author,Other,RAPP Indian Ocean,IT Jobs,NaN
138,associate professor - computer science,Academic,Newton School of Technology,Teaching Jobs,NaN
140,agent engineer,Other,Tata Consultancy Services,IT Jobs,NaN
142,technical project manager,Project Manager,Ascendion,IT Jobs,NaN
149,assistant professor / associate professor / pr...,Academic,Woxsen University,Teaching Jobs,NaN
154,associate / assistant professor - advanced com...,Academic,DBS Global University,IT Jobs,NaN
155,cyber security consultant,Cyber Security,Tata Consultancy Services,IT Jobs,NaN
158,professor,Academic,UPES School of Computer Science,IT Jobs,NaN
166,duckcreek integration-product engineer,Other,LTM,IT Jobs,NaN
171,assistant professor,Academic,"KL University, Vaddeswaram",Teaching Jobs,NaN
179,project manager,Project Manager,SRM Technologies,Engineering Jobs,NaN
182,sales development representative,Sales,CredHive,Sales Jobs,NaN
183,assistant professor of computer science,Academic,NIMS University,Teaching Jobs,NaN
184,software engineering - custom software engineer,Software Engineer,Trigent Software Private Limited,IT Jobs,NaN
185,software engineering - custom software engineer,Software Engineer,Trigent Software Private Limited,IT Jobs,NaN
187,software engineering - custom software engineer,Software Engineer,Trigent Software Private Limited,IT Jobs,NaN
188,software engineering - custom software engineer,Software Engineer,Trigent Software Private Limited,IT Jobs,NaN
189,software engineering - custom software engineer,Software Engineer,Trigent Software Private Limited,IT Jobs,NaN
190,assistant professor,Academic,UPES School of Computer Science,Teaching Jobs,NaN

In [339]:
df['contract_type'] = df['contract_type'].fillna('Unknown')
df['contract_time'] = df['contract_time'].fillna('Unknown')

In [340]:
df[df['contract_type'].isna()][
    ['title', 'standard_role', 'company', 'category', 'contract_time','contract_type']
].head(20)

Empty DataFrame
Columns: [title, standard_role, company, category, contract_time, contract_type]
Index: []

In [341]:
pd.crosstab(
    df['contract_type'],
    df['contract_time'],
    dropna=False
)

contract_time  Unknown  full_time  part_time
contract_type
Unknown           1002       3704          2
contract            38         71          0
permanent           24        122          1

In [342]:
for i in [171,179,182,183,184]:
    print(f"\n{'='*80}")
    print("ROW:", i)
    print("COMPANY:", df.loc[i, "company"])
    print("TITLE:", df.loc[i, "title"])
    print("DESCRIPTION:")
    print(df.loc[i, "description"])
    print('category')
    print(df.loc[i,'category'])
    print('contract_time')
    print(df.loc[i,'contract_time'])

================================================================================
ROW: 171
COMPANY: KL University, Vaddeswaram
TITLE: assistant professor
DESCRIPTION:
We are happy to inform you that K L University has an immediate opening for Teaching Faculty in the Computer Science & Engineering (CSE) Department. The Koneru Lakshmaiah Charities was established as a trust in 1980, with its official address at Museum Road, Governorpet, Vijayawada, Andhra Pradesh 520002, and started K L College of Engineering in the academic year 1980-81. Position : Assistant/Associate/Professor - CSE Location: K L University Campus, Vaddeswaram, Guntur, Andhra Pradesh Key Res…
category
Teaching Jobs
contract_time
Unknown

================================================================================
ROW: 179
COMPANY: SRM Technologies
TITLE: project manager
DESCRIPTION:
ASPICE Project Manager - Automotive Systems About SRM Tech SRM Technologies is a global digital and engineering partner delivering capabilities across Data & AI, Enterprise Platforms, Embedded & Platform Engineering, Supply Chain, and Design-to-Manufacturing services. We work across high-impact industries such as Mobility, Life Sciences, Healthcare, and Logistics, supporting enterprises across North America, APAC, and Europe in building intelligent, future-ready ecosystems and driving transform…
category
Engineering Jobs
contract_time
Unknown

================================================================================
ROW: 182
COMPANY: CredHive
TITLE: sales development representative
DESCRIPTION:
Position Overview We are a seed-funded startup focused on leveraging state-of-the-art AI technologies to revolutionize the credit industry. Our team comprises experts in machine learning and software engineers from top-tier US tech companies like Apple and Amazon. With our product already in the market, first clients onboarded, and sufficient runway secured, we are passionate about using AI to enhance access to credit information for businesses. We are seeking a proactive and driven Sales Devel…
category
Sales Jobs
contract_time
Unknown

================================================================================
ROW: 183
COMPANY: NIMS University
TITLE: assistant professor of computer science
DESCRIPTION:
We are looking for smart & sharp minds for the role of Faculties in the NIMS-MARIK INSTITUTE OF COMPUTING, A.I. & ROBOTICS AND CYBERNETICS, Department of Computer Science & Engineering (CSE) at NIMS University, Jaipur . Position Overview NIMS-Marik Institute proudly introduces India’s first-ever world-class A.I. and Robotics ecosystem, featuring AWS Smart Labs, Siemens Digitalization Labs , and the exclusive Marik Digital Lab , setting unprecedented standards in innovation, research, and indust…
category
Teaching Jobs
contract_time
Unknown

================================================================================
ROW: 184
COMPANY: Trigent Software Private Limited
TITLE: software engineering - custom software engineer
DESCRIPTION:
As a Custom Software Engineer, a typical day involves designing and developing tailored software solutions that meet unique business requirements. The role includes coding and refining various components within systems or applications, ensuring they perform efficiently and scale effectively. Collaboration with cross-functional teams and adapting to agile methodologies are integral parts of the daily workflow, enabling continuous improvement and timely delivery of high-quality software products.…
category
IT Jobs
contract_time
Unknown

In [343]:
df['salary_min'].value_counts(dropna=False)

salary_min
NaN          2595
0.0           299
500000.0      290
1000000.0     249
400000.0      201
300000.0      180
600000.0      178
800000.0      139
1500000.0     112
100000.0      100
200000.0       99
700000.0       89
1200000.0      86
2000000.0      57
750000.0       38
900000.0       34
2500000.0      19
1800000.0      16
3000000.0      14
1400000.0      10
350000.0        8
180000.0        8
1700000.0       8
2400000.0       8
2200000.0       7
1300000.0       7
360000.0        6
450000.0        6
240000.0        6
3500000.0       6
1600000.0       5
150000.0        5
650000.0        5
120000.0        4
720000.0        4
250000.0        4
35000.0         4
550000.0        4
1100000.0       4
2800000.0       3
480000.0        3
20000.0         3
50000.0         3
4000000.0       3
960000.0        2
30000.0         2
1900000.0       2
2100000.0       2
420000.0        2
2300000.0       2
7.0             1
3000.0          1
70000.0         1
216000.0        1
230000.0        1
40000.0         1
1350000.0       1
19000.0         1
1650000.0       1
4500000.0       1
2900000.0       1
10000.0         1
850000.0        1
160000.0        1
2700000.0       1
8000.0          1
90000.0         1
1920000.0       1
155325.0        1
22000.0         1
60000.0         1
1320000.0       1
12.0            1
Name: count, dtype: int64

In [344]:
# Step 1: Check suspiciously low salary_min values
df[df['salary_min'] < 100000][
    ['title', 'company', 'location', 'salary_min', 'salary_max']
].sort_values('salary_min')

,title,company,location,salary_min,salary_max
2309,full stack developer,Numadic,"Goa, India",0.0,700000.0
3114,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3113,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3111,java developer,Mobile Programming India Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
3101,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3100,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1300000.0
3052,python developer,Reval Analytics,"Pune, Maharashtra",0.0,900000.0
3046,python developer,Lazybears tech pvt ltd,"Bangalore, Karnataka",0.0,900000.0
3041,python developer,Quantsapp,"Mumbai, Maharashtra",0.0,400000.0
3021,python developer,Whitesnow Software Consultancy Pune,"Pune, Maharashtra",0.0,800000.0
3017,python developer,Latent Bridge Pvt Ltd,"Pune, Maharashtra",0.0,2000000.0
3015,python developer,ExpertRec,"Bangalore, Karnataka",0.0,1100000.0
3013,python developer,httpnesosolutionscom,"Chennai, Tamil Nadu",0.0,2300000.0
3011,python developer,Response Informatics,"Mumbai, Maharashtra",0.0,1500000.0
2998,python developer,VMultiply Solutions,"Noida, Ghaziabad",0.0,400000.0
2997,python developer,Animaker Inc,"Chennai, Tamil Nadu",0.0,2600000.0
3118,java developer,CIEL HR Services,"Bangalore, Karnataka",0.0,1500000.0
2996,python developer,Angel One,India,0.0,900000.0
3130,java developer,Digixhub,"Mumbai, Maharashtra",0.0,900000.0
3159,java developer,Gracira Technologies LLP,"Mumbai, Maharashtra",0.0,1400000.0
3271,java developer,Innominds Software,"Hyderabad, Telangana",0.0,2000000.0
3266,java developer,Careator Technologies Pvt Ltd,"Hyderabad, Telangana",0.0,800000.0
3263,java developer,BCForward,"Hyderabad, Telangana",0.0,1800000.0
3256,java developer,Crewmates,"Chennai, Tamil Nadu",0.0,900000.0
3247,java developer,MindMap Consulting,"Pune, Maharashtra",0.0,1400000.0
3233,java developer,Gipfel & Schnell Consultings Pvt Ltd,"Bangalore, Karnataka",0.0,2000000.0
3227,java developer,Response Informatics,"Bangalore, Karnataka",0.0,1800000.0
3218,java developer,Mobile Programming LLC,"Bangalore, Karnataka",0.0,1200000.0
3211,java developer,Espire infolabs,"Delhi, India",0.0,1400000.0
3209,java developer,KSoft Technologies,"Chennai, Tamil Nadu",0.0,700000.0
3205,java developer,Adecco,"Hyderabad, Telangana",0.0,1600000.0
3203,java developer,Increasingly Technologies,"Bangalore, Karnataka",0.0,400000.0
3200,java developer,Applied Data Finance,"Chennai, Tamil Nadu",0.0,1200000.0
3186,java developer,global education ltd.,"Nagpur, Maharashtra",0.0,1200000.0
3164,java developer,e-Zest Solutions,"Pune, Maharashtra",0.0,2000000.0
3154,java developer,STREETMARK Info Solutions,"Hyderabad, Telangana",0.0,1200000.0
2980,python developer,Emxcel Travel Solutions,"Pune, Maharashtra",0.0,700000.0
2960,python developer,Neotas,India,0.0,1200000.0
2956,python developer,Beauto Systems Private Limited,"Pune, Maharashtra",0.0,500000.0
2766,python developer,People Konnect,"Mumbai, Maharashtra",0.0,1500000.0
2759,python developer,NetElixir,"Hyderabad, Telangana",0.0,1200000.0
2733,python developer,Financial Hospital,"Mumbai, Maharashtra",0.0,600000.0
2701,python developer,Navtech,"Hyderabad, Telangana",0.0,800000.0
2688,python developer,GrowthFalcons,"Bangalore, Karnataka",0.0,600000.0
2682,python developer,Xpertiks,"Chandigarh, India",0.0,1000000.0
2631,full stack developer,SHASHWATH SOLUTION,"Mumbai, Maharashtra",0.0,800000.0
2570,full stack developer,Unnati,"Chandigarh, India",0.0,720000.0
2552,full stack developer,Causality Biomodels,"Kochi, Ernakulam",0.0,900000.0
2530,full stack developer,SaaS Labs,"Noida, Ghaziabad",0.0,1000000.0
2466,full stack developer,Jobdost,"Bangalore, Karnataka",0.0,1000000.0
2447,full stack -developer,Skill Monks - A unit of Scuti Tech Labs Pvt Ltd,"Hyderabad, Telangana",0.0,1000000.0
4928,business analyst,Leena AI,India,0.0,2500000.0
2282,frontend developer,Ownerstown,"Bangalore, Karnataka",0.0,600000.0
2278,frontend developer,Ideamagix,"Mumbai, Maharashtra",0.0,500000.0
2768,python developer,CES Information Technologies,India,0.0,1200000.0
2781,python developer,CES Information Technologies,"Hyderabad, Telangana",0.0,1400000.0
2802,python developer,Ellicium Solutions Private Limited,"Pune, Maharashtra",0.0,400000.0
2822,python developer,Innovatily,"Bangalore, Karnataka",0.0,1000000.0
2942,python developer,Jobrisers,"Indore, Madhya Pradesh",0.0,1200000.0
2940,python developer,Multi Recruit,"Bangalore, Karnataka",0.0,900000.0
2933,python developer,Speculatio,"Jaipur, Rajasthan",0.0,400000.0
2931,python developer,Talent Socio Bizcon LLP,"Bangalore, Karnataka",0.0,1200000.0
2919,python developer,Jobdost,"Mumbai, Maharashtra",0.0,1200000.0
2892,python developer,Aviation Indeed,"Hyderabad, Telangana",0.0,1300000.0
2888,python developer,wrackle,"Bangalore, Karnataka",0.0,2000000.0
3274,java developer,Ideapoke Technologies,"Bangalore, Karnataka",0.0,1000000.0
2881,python developer,Eco transport solution Private Limited,"Gandhinagar, Gujarat",0.0,500000.0
2872,python developer,WorksDelight,"Mohali, Punjab",0.0,400000.0
2856,python developer,Legistify,"Noida, Ghaziabad",0.0,1500000.0
2850,python developer,Sygnific Services,"Mohali, Punjab",0.0,1200000.0
2846,python developer,Sequelstring Solutions and Consultancy Pvt Ltd,"Delhi, India",0.0,900000.0
2835,python developer,TBM Technologies Pvt,"Noida, Ghaziabad",0.0,300000.0
2830,python developer,Jobdost,"Mumbai, Maharashtra",0.0,600000.0
2829,python developer,Jobdost,"Mumbai, Maharashtra",0.0,660000.0
2880,python developer,Resources Valley,"Jaipur, Rajasthan",0.0,1500000.0
2253,frontend developer,Near,"Bangalore, Karnataka",0.0,3000000.0
3284,java developer,Careator Technologies Pvt Ltd,"Hyderabad, Telangana",0.0,1000000.0
3323,java developer,Evergent,India,0.0,1200000.0
4731,business analyst,Unnati,"Pune, Maharashtra",0.0,1200000.0
4719,business analyst,DIGITAL BRAIN MEDIA,"Lucknow, Uttar Pradesh",0.0,600000.0
4692,business analyst,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,600000.0
4668,business analyst,Texila American University,"Coimbatore, Tamil Nadu",0.0,700000.0
4659,business analyst,Presidency University,"Bangalore, Karnataka",0.0,500000.0
4552,web developer,People First Consultants,"Chennai, Tamil Nadu",0.0,600000.0
4524,presales engineer,ASSERTION,"Pune, Maharashtra",0.0,1000000.0
4269,cyber security analyst,HR Global Services India,"Kochi, Ernakulam",0.0,1200000.0
4197,cloud software engineer,Banyan Data Services,"Bangalore, Karnataka",0.0,1500000.0
4029,aws cloud engineer (l2),K2India,"Noida, Ghaziabad",0.0,600000.0
3883,cloud engineer,KonfHub,India,0.0,260000.0
3880,cloud engineer,Greenway Health,"Bangalore, Karnataka",0.0,2500000.0
3867,cloud engineer,AskSid,"Bangalore, Karnataka",0.0,1400000.0
3829,devops engineer,Merkle,"Pune, Maharashtra",0.0,700000.0
3811,devops engineer,Univariety,"Hyderabad, Telangana",0.0,1000000.0
4732,business analyst.,Andesoft Consulting,"Mumbai, Maharashtra",0.0,1500000.0
3810,devops engineer,Jobdost,"Delhi, India",0.0,1500000.0
4742,business analyst,Krish Technolabs,"Ahmedabad, Gujarat",0.0,700000.0
4756,business analyst,i-Lanam Technologies,"Ahmedabad, Gujarat",0.0,200000.0
4926,business analyst,BitClass,"Bangalore, Karnataka",0.0,2500000.0
4925,business analyst,Beyond Pinks,"Hyderabad, Telangana",0.0,1500000.0
4922,business analyst,upGrad,"Mumbai, Maharashtra",0.0,1600000.0
4909,business analyst,Perdect,"Jaipur, Rajasthan",0.0,200000.0
4908,business analyst,Variable Soft,"Jaipur, Rajasthan",0.0,500000.0
4890,business analyst,CRMnext,"Mumbai, Maharashtra",0.0,800000.0
4888,business analyst,Acadecraft,"Pune, Maharashtra",0.0,600000.0
4887,business analyst,Adiyogi Technosoft Pvt Ltd,"Jodhpur, Rajasthan",0.0,400000.0
4880,business analyst,education asia,"Bhubaneswar, Khordha",0.0,800000.0
4869,business analyst,RentoMojo,"Bangalore, Karnataka",0.0,700000.0
4858,business analyst,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,1000000.0
4838,business analyst,Accion Labs,"Bangalore, Karnataka",0.0,1800000.0
4834,business analyst,Duplex Technologies Services,"Lucknow, Uttar Pradesh",0.0,300000.0
4809,business analyst,Unnati,"Mohali, Punjab",0.0,1000000.0
4772,business analyst,Qrata,"Bangalore, Karnataka",0.0,1800000.0
4743,business analyst,Multi Recruit,"Bangalore, Karnataka",0.0,1500000.0
3809,devops engineer,Cross tower India Trading pvt ltd,India,0.0,1200000.0
3808,devops engineer,Cross tower India Trading pvt ltd,India,0.0,1300000.0
3804,devops engineer,Matellio Inc,India,0.0,960000.0
3607,devops engineer,Compufy Technolab,"Ahmedabad, Gujarat",0.0,1200000.0
3583,devops engineer,Sapper.ai,"Pune, Maharashtra",0.0,2000000.0
3559,devops engineer,Vernacular.ai,"Bangalore, Karnataka",0.0,1200000.0
3553,devops engineer,CometChat,India,0.0,1200000.0
3531,devops engineer,Response Informatics,"Delhi, India",0.0,1200000.0
3507,devops engineer,InvokHR,India,0.0,1000000.0
3498,devops engineer,Kalibre global konnects,"Ahmedabad, Gujarat",0.0,600000.0
3440,java developer,Dashmesh Group,India,0.0,1000000.0
3414,java developer,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,1200000.0
3348,java developer,DSS Software Solutions Sdn. Bhd.,India,0.0,1200000.0
3342,java developer,Unknown,"Pune, Maharashtra",0.0,3000000.0
3339,java developer,TotalCloud Inc.,"Bangalore, Karnataka",0.0,1000000.0
3338,java developer,Narvee Technologies India Pvt Ltd,"Hyderabad, Telangana",0.0,7200000.0
3331,java developer,JOBS HIRE,India,0.0,2000000.0
3326,java developer,Mobile Programming LLC,India,0.0,1200000.0
3614,devops engineer,BarRaiser,"Bangalore, Karnataka",0.0,1500000.0
3617,devops engineer,Planet Spark,"Delhi, India",0.0,1200000.0
3634,devops engineer,Magicflare Software Services,"Pune, Maharashtra",0.0,1500000.0
3636,devops engineer,Vamstar,India,0.0,1000000.0
3803,devops engineer,OTO,"Bangalore, Karnataka",0.0,1000000.0
3802,devops engineer,Infiniticube Services Pvt Ltd,India,0.0,1000000.0
3796,devops engineer,Marktine,"Bangalore, Karnataka",0.0,1500000.0
3787,devops engineer,VUMONIC,"Bangalore, Karnataka",0.0,600000.0
3786,devops engineer,Jobdost,India,0.0,1300000.0
3782,devops engineer,Acadecraft,"Bangalore, Karnataka",0.0,2100000.0
3778,devops engineer,Tessact,"Mumbai, Maharashtra",0.0,1500000.0
3304,java developer,Mobile Programming LLC,India,0.0,1400000.0
3743,devops engineer,Intellve Solutions Ltd,India,0.0,1400000.0
3728,devops engineer,YourHRfolks,"Jaipur, Rajasthan",0.0,1600000.0
3726,devops engineer,InvokHR,"Mumbai, Maharashtra",0.0,2500000.0
3717,devops engineer,Indus OS,"Mumbai, Maharashtra",0.0,1300000.0
3705,devops engineer,Unnati,India,0.0,1000000.0
3686,devops engineer,IndependentConsultant,"Pune, Maharashtra",0.0,1300000.0
3681,devops engineer,Dori AI,"Bangalore, Karnataka",0.0,1300000.0
3677,devops engineer,Sanguine Global,"Chennai, Tamil Nadu",0.0,1500000.0
3742,devops engineer,Fibonalabs,"Madurai, Tamil Nadu",0.0,1200000.0
2241,frontend developer,Benchkart Services,India,0.0,2400000.0
4931,business analyst,Eco transport solution Private Limited,"Gandhinagar, Gujarat",0.0,200000.0
2237,frontend developer,Quantela,"Hyderabad, Telangana",0.0,1200000.0
1693,backend developer,MondayMorning,"Noida, Ghaziabad",0.0,800000.0
1686,backend developer,Pracify,India,0.0,750000.0
1666,backend developer,Navia Life Care,"Delhi, India",0.0,1400000.0
1643,backend developer,InvokHR,India,0.0,1000000.0
1641,backend developer,HOP Financial Services,"Bangalore, Karnataka",0.0,800000.0
1640,backend developer,Envisionard,"Pune, Maharashtra",0.0,1500000.0
1639,backend developer,Meatigocom,"Delhi, India",0.0,1000000.0
1625,backend developer,Credence Analytics,"Mumbai, Maharashtra",0.0,1000000.0
1611,backend developer,Anzy,"Bangalore, Karnataka",0.0,1600000.0
1605,backend developer,Semperfi Solution,"Bangalore, Karnataka",0.0,600000.0
1602,backend developer,Iorta Technology Solutions Pvt Ltd,"Mumbai, Maharashtra",0.0,600000.0
1590,backend developer,FirstFiling,"Jaipur, Rajasthan",0.0,450000.0
1565,backend developer,Shoocal,"Bangalore, Karnataka",0.0,700000.0
1563,backend developer,Zydelo,India,0.0,1000000.0
1560,backend developer,Hirextra,"Hyderabad, Telangana",0.0,1200000.0
1702,backend developer,Jobdost,"Delhi, India",0.0,3500000.0
1715,backend developer,invoid,"Delhi, India",0.0,600000.0
1717,backend developer,InvokHR,"Bangalore, Karnataka",0.0,1100000.0
1744,backend developer,Huptech Consultancy Services,"Ahmedabad, Gujarat",0.0,1000000.0
1848,backend developer,Wenger and Watson Inc,"Bangalore, Karnataka",0.0,1600000.0
1846,backend developer,Linarc Inc,"Chennai, Tamil Nadu",0.0,600000.0
1844,backend developer,Olegacy,"Bangalore, Karnataka",0.0,1200000.0
1843,backend developer,Rift,"Goa, India",0.0,700000.0
2240,frontend developer,Oceanfrogs Software,India,0.0,800000.0
1838,backend developer,Mobile Programming LLC,India,0.0,900000.0
1810,backend developer,Qrata,"Delhi, India",0.0,2300000.0
1549,backend developer,Recruit Square,India,0.0,900000.0
1808,backend developer,TecManic,India,0.0,400000.0
1803,backend developer,Mobile Programming LLC,"Bangalore, Karnataka",0.0,700000.0
1801,backend developer,wwwemotcoin,"Bangalore, Karnataka",0.0,300000.0
1774,backend developer,Multi Recruit,"Bangalore, Karnataka",0.0,800000.0
1771,backend developer,UACTIV,India,0.0,600000.0
1770,backend developer,All Indian IT Services LLP,"Nagpur, Maharashtra",0.0,380000.0
1767,backend developer,Scalex Technology Solutions,"Pune, Maharashtra",0.0,800000.0
1766,backend developer,Skyber Enterprises,"Mumbai, Maharashtra",0.0,700000.0
1804,backend developer,The Hub,India,0.0,2000000.0
1864,backend developer,Digitrack Sports India Pvt Ltd,"Pune, Maharashtra",0.0,900000.0
1539,backend developer,Think eBikeGo Pvt Ltd,"Mumbai, Maharashtra",0.0,800000.0
1534,backend developer,Shortcastle Technologies,"Chennai, Tamil Nadu",0.0,1600000.0
837,data analyst,Jobdost,"Bangalore, Karnataka",0.0,500000.0
818,data analyst,Syrencloud,"Hyderabad, Telangana",0.0,800000.0
817,data analyst,MSMEx,"Mumbai, Maharashtra",0.0,1200000.0
804,data analyst,Reality Premedia Services Pvt Ltd,"Pune, Maharashtra",0.0,800000.0
780,data analyst,SveltetechTechnologies Pvt Ltd,"Delhi, India",0.0,300000.0
705,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,1500000.0
696,data scientist,Ezeiatech systems,India,0.0,1500000.0
678,data scientist,Angel One,"Mumbai, Maharashtra",0.0,1500000.0
671,data scientist,Accolite Software,"Bangalore, Karnataka",0.0,2400000.0
658,data scientist,Unnati,"Bangalore, Karnataka",0.0,1200000.0
652,data scientist,Unnati,"Mumbai, Maharashtra",0.0,1500000.0
639,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,2000000.0
569,data scientist,BYGRAD,"Bangalore, Karnataka",0.0,1200000.0
529,data scientist,Fragma Data Systems,"Chennai, Tamil Nadu",0.0,1200000.0
320,software engineer,Talentspro,"Bangalore, Karnataka",0.0,2000000.0
852,data analyst,BitClass,"Bangalore, Karnataka",0.0,1600000.0
854,data analyst,Amazon,"Bangalore, Karnataka",0.0,800000.0
858,data analyst,Extramarks,"Noida, Ghaziabad",0.0,1000000.0
898,data analyst,Marktine,"Bangalore, Karnataka",0.0,1500000.0
1528,backend developer,Kalibre global konnects,"Ahmedabad, Gujarat",0.0,1000000.0
1447,senior analyst – ai/ml engineer (machine learn...,Vrinda International,"Bangalore, Karnataka",0.0,1000000.0
1392,machine learning research engineer,Vernacular.ai,"Bangalore, Karnataka",0.0,1500000.0
1232,applied machine learning engineer,Gipfel & Schnell Consultings Pvt Ltd,India,0.0,2000000.0
1194,machine learning engineer,SIlverPeople Consulting,"Mumbai, Maharashtra",0.0,2700000.0
1192,machine learning engineer,Hammoq,India,0.0,900000.0
1191,machine learning engineer,CES Information Technologies,"Hyderabad, Telangana",0.0,1500000.0
1536,backend developer,Aarms Solutions on,"Bangalore, Karnataka",0.0,1400000.0
1179,machine learning engineer,Marktine,"Bangalore, Karnataka",0.0,1500000.0
1120,mis data analyst,Randstad India,"Raipur, Chhattisgarh",0.0,1400000.0
1071,financial data analyst,Nirvana Solutions,India,0.0,300000.0
1067,data analyst- marketing,Unnati,"Delhi, India",0.0,1500000.0
919,data analyst,CIEL HR Services,"Bangalore, Karnataka",0.0,1500000.0
912,data analyst,MedCords,"Kota, Rajasthan",0.0,250000.0
911,data analyst,Srijan Technologies,India,0.0,1200000.0
908,data analyst,Azent Overseas,"Mumbai, Maharashtra",0.0,700000.0
1169,machine learning engineer,Artifex HR,"Bangalore, Karnataka",0.0,800000.0
1869,backend developer,Uniphore Software Systems,"Bangalore, Karnataka",0.0,1500000.0
1841,backend developer,GLOBAL LANCERS,"Jaipur, Rajasthan",0.0,600000.0
1873,backend developer,Digirex Technologies,"Bangalore, Karnataka",0.0,420000.0
2136,frontend developer,Storeking,"Bangalore, Karnataka",0.0,1000000.0
2129,frontend developer,Talent Socio Bizcon LLP,"Bangalore, Karnataka",0.0,400000.0
2124,frontend developer,Startupwala,"Pune, Maharashtra",0.0,300000.0
2122,frontend developer,Purple Style Labs Private Limited,"Mumbai, Maharashtra",0.0,2800000.0
2116,frontend developer,Aakash Educational Services Limited,"Delhi, India",0.0,1800000.0
2103,frontend developer,BOB eProcure Solutions,"Hyderabad, Telangana",0.0,1000000.0
2137,frontend developer,AyataCommerce,India,0.0,1500000.0
2102,frontend developer,FaceX,"Bangalore, Karnataka",0.0,900000.0
2091,frontend developer,Kool Group Ltd.,"Dehradun, Uttarakhand",0.0,500000.0
1871,backend developer,Ideamagix,"Thane, Maharashtra",0.0,500000.0
2077,frontend developer,Homesfy,"Thane, Maharashtra",0.0,1000000.0
2075,frontend developer,Transportation | Warehouse Optimization,India,0.0,2000000.0
2073,frontend developer,Eunimart Multichannel Pvt Ltd,"Hyderabad, Telangana",0.0,1000000.0
2072,frontend developer,SIMBOAI,"Bangalore, Karnataka",0.0,800000.0
2094,frontend developer,plunes technologies,"Gurgaon, Haryana",0.0,120000.0
2140,frontend developer,Displaysweet,"Pune, Maharashtra",0.0,1500000.0
2157,frontend developer,Edge CRM,"Mumbai, Maharashtra",0.0,200000.0
2182,frontend developer,Zapit,India,0.0,1200000.0
2235,frontend developer,The Hub,"Bangalore, Karnataka",0.0,2000000.0
2226,frontend developer,Elixa technologies Private Limited,"Pune, Maharashtra",0.0,1400000.0
2225,frontend developer,Ifortis corporate,"Noida, Ghaziabad",0.0,750000.0
2224,frontend developer,Skyber Enterprises,"Mumbai, Maharashtra",0.0,900000.0
2208,frontend developer,Blew Minds Consulting,"Mumbai, Maharashtra",0.0,1200000.0
2206,frontend developer,StarClinch,"Delhi, India",0.0,300000.0
2205,frontend developer,SaveIN,"Delhi, India",0.0,1000000.0
2203,frontend developer,Urbanstop Studio LLP,"Bangalore, Karnataka",0.0,550000.0
2198,frontend developer,Jet Freight Logistics Limited,"Mumbai, Maharashtra",0.0,800000.0
2192,frontend developer,Mobile Programming India Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
2190,frontend developer,pagon tech,India,0.0,450000.0
2188,frontend developer,FirstFiling,"Jaipur, Rajasthan",0.0,450000.0
2187,frontend developer,Aviation Indeed,"Hyderabad, Telangana",0.0,800000.0
2184,frontend developer,Mobile Programming LLC,"Mumbai, Maharashtra",0.0,900000.0
2183,frontend developer,Genius Placement Service,"Ahmedabad, Gujarat",0.0,500000.0
2069,frontend developer,Jobdost,India,0.0,1500000.0
2058,frontend developer,sense.bio,"Mumbai, Maharashtra",0.0,450000.0
2089,frontend developer,Konnectbox,"Bangalore, Karnataka",0.0,1200000.0
2040,frontend developer,Eagle Power,India,0.0,1500000.0
1921,frontend developer,Jobdost,India,0.0,3000000.0
1922,frontend developer,Splat Studio,"Delhi, India",0.0,480000.0
1879,backend developer,Deployd Technologies Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
1933,frontend developer,Jobdost,"Mumbai, Maharashtra",0.0,1500000.0
1936,frontend developer,Placjo Technologies Pvt ltd,"Bangalore, Karnataka",0.0,900000.0
1938,frontend developer,Digirex Technologies,India,0.0,360000.0
1940,frontend developer,Jithvar Consultancy Services,"Lucknow, Uttar Pradesh",0.0,500000.0

In [345]:
df[df['salary_min'] < 1000][
    ['title', 'company', 'location', 'salary_min', 'salary_max']
].sort_values('salary_min')

,title,company,location,salary_min,salary_max
320,software engineer,Talentspro,"Bangalore, Karnataka",0.0,2000000.0
3130,java developer,Digixhub,"Mumbai, Maharashtra",0.0,900000.0
3118,java developer,CIEL HR Services,"Bangalore, Karnataka",0.0,1500000.0
3114,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3113,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3111,java developer,Mobile Programming India Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
3101,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1200000.0
3154,java developer,STREETMARK Info Solutions,"Hyderabad, Telangana",0.0,1200000.0
3100,java developer,Promotup HR Solutions,"Ahmedabad, Gujarat",0.0,1300000.0
3046,python developer,Lazybears tech pvt ltd,"Bangalore, Karnataka",0.0,900000.0
3041,python developer,Quantsapp,"Mumbai, Maharashtra",0.0,400000.0
3021,python developer,Whitesnow Software Consultancy Pune,"Pune, Maharashtra",0.0,800000.0
3017,python developer,Latent Bridge Pvt Ltd,"Pune, Maharashtra",0.0,2000000.0
3015,python developer,ExpertRec,"Bangalore, Karnataka",0.0,1100000.0
3013,python developer,httpnesosolutionscom,"Chennai, Tamil Nadu",0.0,2300000.0
3052,python developer,Reval Analytics,"Pune, Maharashtra",0.0,900000.0
3159,java developer,Gracira Technologies LLP,"Mumbai, Maharashtra",0.0,1400000.0
3164,java developer,e-Zest Solutions,"Pune, Maharashtra",0.0,2000000.0
3186,java developer,global education ltd.,"Nagpur, Maharashtra",0.0,1200000.0
3284,java developer,Careator Technologies Pvt Ltd,"Hyderabad, Telangana",0.0,1000000.0
3274,java developer,Ideapoke Technologies,"Bangalore, Karnataka",0.0,1000000.0
3271,java developer,Innominds Software,"Hyderabad, Telangana",0.0,2000000.0
3266,java developer,Careator Technologies Pvt Ltd,"Hyderabad, Telangana",0.0,800000.0
3263,java developer,BCForward,"Hyderabad, Telangana",0.0,1800000.0
3256,java developer,Crewmates,"Chennai, Tamil Nadu",0.0,900000.0
3247,java developer,MindMap Consulting,"Pune, Maharashtra",0.0,1400000.0
3233,java developer,Gipfel & Schnell Consultings Pvt Ltd,"Bangalore, Karnataka",0.0,2000000.0
3227,java developer,Response Informatics,"Bangalore, Karnataka",0.0,1800000.0
3218,java developer,Mobile Programming LLC,"Bangalore, Karnataka",0.0,1200000.0
3211,java developer,Espire infolabs,"Delhi, India",0.0,1400000.0
3209,java developer,KSoft Technologies,"Chennai, Tamil Nadu",0.0,700000.0
3205,java developer,Adecco,"Hyderabad, Telangana",0.0,1600000.0
3203,java developer,Increasingly Technologies,"Bangalore, Karnataka",0.0,400000.0
3200,java developer,Applied Data Finance,"Chennai, Tamil Nadu",0.0,1200000.0
3011,python developer,Response Informatics,"Mumbai, Maharashtra",0.0,1500000.0
2998,python developer,VMultiply Solutions,"Noida, Ghaziabad",0.0,400000.0
2997,python developer,Animaker Inc,"Chennai, Tamil Nadu",0.0,2600000.0
2996,python developer,Angel One,India,0.0,900000.0
2822,python developer,Innovatily,"Bangalore, Karnataka",0.0,1000000.0
2802,python developer,Ellicium Solutions Private Limited,"Pune, Maharashtra",0.0,400000.0
2781,python developer,CES Information Technologies,"Hyderabad, Telangana",0.0,1400000.0
2768,python developer,CES Information Technologies,India,0.0,1200000.0
2766,python developer,People Konnect,"Mumbai, Maharashtra",0.0,1500000.0
2759,python developer,NetElixir,"Hyderabad, Telangana",0.0,1200000.0
2733,python developer,Financial Hospital,"Mumbai, Maharashtra",0.0,600000.0
2701,python developer,Navtech,"Hyderabad, Telangana",0.0,800000.0
2688,python developer,GrowthFalcons,"Bangalore, Karnataka",0.0,600000.0
2682,python developer,Xpertiks,"Chandigarh, India",0.0,1000000.0
2631,full stack developer,SHASHWATH SOLUTION,"Mumbai, Maharashtra",0.0,800000.0
2570,full stack developer,Unnati,"Chandigarh, India",0.0,720000.0
2552,full stack developer,Causality Biomodels,"Kochi, Ernakulam",0.0,900000.0
2530,full stack developer,SaaS Labs,"Noida, Ghaziabad",0.0,1000000.0
2466,full stack developer,Jobdost,"Bangalore, Karnataka",0.0,1000000.0
2829,python developer,Jobdost,"Mumbai, Maharashtra",0.0,660000.0
3304,java developer,Mobile Programming LLC,India,0.0,1400000.0
2830,python developer,Jobdost,"Mumbai, Maharashtra",0.0,600000.0
2846,python developer,Sequelstring Solutions and Consultancy Pvt Ltd,"Delhi, India",0.0,900000.0
2980,python developer,Emxcel Travel Solutions,"Pune, Maharashtra",0.0,700000.0
2960,python developer,Neotas,India,0.0,1200000.0
2956,python developer,Beauto Systems Private Limited,"Pune, Maharashtra",0.0,500000.0
2942,python developer,Jobrisers,"Indore, Madhya Pradesh",0.0,1200000.0
2940,python developer,Multi Recruit,"Bangalore, Karnataka",0.0,900000.0
2933,python developer,Speculatio,"Jaipur, Rajasthan",0.0,400000.0
2931,python developer,Talent Socio Bizcon LLP,"Bangalore, Karnataka",0.0,1200000.0
2919,python developer,Jobdost,"Mumbai, Maharashtra",0.0,1200000.0
2892,python developer,Aviation Indeed,"Hyderabad, Telangana",0.0,1300000.0
2888,python developer,wrackle,"Bangalore, Karnataka",0.0,2000000.0
2881,python developer,Eco transport solution Private Limited,"Gandhinagar, Gujarat",0.0,500000.0
2880,python developer,Resources Valley,"Jaipur, Rajasthan",0.0,1500000.0
2872,python developer,WorksDelight,"Mohali, Punjab",0.0,400000.0
2856,python developer,Legistify,"Noida, Ghaziabad",0.0,1500000.0
2850,python developer,Sygnific Services,"Mohali, Punjab",0.0,1200000.0
2835,python developer,TBM Technologies Pvt,"Noida, Ghaziabad",0.0,300000.0
4928,business analyst,Leena AI,India,0.0,2500000.0
3323,java developer,Evergent,India,0.0,1200000.0
3331,java developer,JOBS HIRE,India,0.0,2000000.0
4731,business analyst,Unnati,"Pune, Maharashtra",0.0,1200000.0
4719,business analyst,DIGITAL BRAIN MEDIA,"Lucknow, Uttar Pradesh",0.0,600000.0
4692,business analyst,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,600000.0
4668,business analyst,Texila American University,"Coimbatore, Tamil Nadu",0.0,700000.0
4659,business analyst,Presidency University,"Bangalore, Karnataka",0.0,500000.0
4552,web developer,People First Consultants,"Chennai, Tamil Nadu",0.0,600000.0
4732,business analyst.,Andesoft Consulting,"Mumbai, Maharashtra",0.0,1500000.0
4524,presales engineer,ASSERTION,"Pune, Maharashtra",0.0,1000000.0
4197,cloud software engineer,Banyan Data Services,"Bangalore, Karnataka",0.0,1500000.0
4029,aws cloud engineer (l2),K2India,"Noida, Ghaziabad",0.0,600000.0
3883,cloud engineer,KonfHub,India,0.0,260000.0
3880,cloud engineer,Greenway Health,"Bangalore, Karnataka",0.0,2500000.0
3867,cloud engineer,AskSid,"Bangalore, Karnataka",0.0,1400000.0
3829,devops engineer,Merkle,"Pune, Maharashtra",0.0,700000.0
4269,cyber security analyst,HR Global Services India,"Kochi, Ernakulam",0.0,1200000.0
4742,business analyst,Krish Technolabs,"Ahmedabad, Gujarat",0.0,700000.0
4743,business analyst,Multi Recruit,"Bangalore, Karnataka",0.0,1500000.0
4756,business analyst,i-Lanam Technologies,"Ahmedabad, Gujarat",0.0,200000.0
4926,business analyst,BitClass,"Bangalore, Karnataka",0.0,2500000.0
4925,business analyst,Beyond Pinks,"Hyderabad, Telangana",0.0,1500000.0
4922,business analyst,upGrad,"Mumbai, Maharashtra",0.0,1600000.0
4909,business analyst,Perdect,"Jaipur, Rajasthan",0.0,200000.0
4908,business analyst,Variable Soft,"Jaipur, Rajasthan",0.0,500000.0
4890,business analyst,CRMnext,"Mumbai, Maharashtra",0.0,800000.0
4888,business analyst,Acadecraft,"Pune, Maharashtra",0.0,600000.0
4887,business analyst,Adiyogi Technosoft Pvt Ltd,"Jodhpur, Rajasthan",0.0,400000.0
4880,business analyst,education asia,"Bhubaneswar, Khordha",0.0,800000.0
4869,business analyst,RentoMojo,"Bangalore, Karnataka",0.0,700000.0
4858,business analyst,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,1000000.0
4838,business analyst,Accion Labs,"Bangalore, Karnataka",0.0,1800000.0
4834,business analyst,Duplex Technologies Services,"Lucknow, Uttar Pradesh",0.0,300000.0
4809,business analyst,Unnati,"Mohali, Punjab",0.0,1000000.0
4772,business analyst,Qrata,"Bangalore, Karnataka",0.0,1800000.0
3811,devops engineer,Univariety,"Hyderabad, Telangana",0.0,1000000.0
3810,devops engineer,Jobdost,"Delhi, India",0.0,1500000.0
3809,devops engineer,Cross tower India Trading pvt ltd,India,0.0,1200000.0
3808,devops engineer,Cross tower India Trading pvt ltd,India,0.0,1300000.0
3617,devops engineer,Planet Spark,"Delhi, India",0.0,1200000.0
3614,devops engineer,BarRaiser,"Bangalore, Karnataka",0.0,1500000.0
3607,devops engineer,Compufy Technolab,"Ahmedabad, Gujarat",0.0,1200000.0
3583,devops engineer,Sapper.ai,"Pune, Maharashtra",0.0,2000000.0
3559,devops engineer,Vernacular.ai,"Bangalore, Karnataka",0.0,1200000.0
3553,devops engineer,CometChat,India,0.0,1200000.0
3531,devops engineer,Response Informatics,"Delhi, India",0.0,1200000.0
3507,devops engineer,InvokHR,India,0.0,1000000.0
3498,devops engineer,Kalibre global konnects,"Ahmedabad, Gujarat",0.0,600000.0
3440,java developer,Dashmesh Group,India,0.0,1000000.0
3414,java developer,IRIS BUSINESS SERVICES LIMITED,"Navi Mumbai, Maharashtra",0.0,1200000.0
3348,java developer,DSS Software Solutions Sdn. Bhd.,India,0.0,1200000.0
3342,java developer,Unknown,"Pune, Maharashtra",0.0,3000000.0
3339,java developer,TotalCloud Inc.,"Bangalore, Karnataka",0.0,1000000.0
3338,java developer,Narvee Technologies India Pvt Ltd,"Hyderabad, Telangana",0.0,7200000.0
3634,devops engineer,Magicflare Software Services,"Pune, Maharashtra",0.0,1500000.0
3326,java developer,Mobile Programming LLC,India,0.0,1200000.0
3636,devops engineer,Vamstar,India,0.0,1000000.0
3681,devops engineer,Dori AI,"Bangalore, Karnataka",0.0,1300000.0
3804,devops engineer,Matellio Inc,India,0.0,960000.0
3803,devops engineer,OTO,"Bangalore, Karnataka",0.0,1000000.0
3802,devops engineer,Infiniticube Services Pvt Ltd,India,0.0,1000000.0
3796,devops engineer,Marktine,"Bangalore, Karnataka",0.0,1500000.0
3787,devops engineer,VUMONIC,"Bangalore, Karnataka",0.0,600000.0
3786,devops engineer,Jobdost,India,0.0,1300000.0
3782,devops engineer,Acadecraft,"Bangalore, Karnataka",0.0,2100000.0
3778,devops engineer,Tessact,"Mumbai, Maharashtra",0.0,1500000.0
3743,devops engineer,Intellve Solutions Ltd,India,0.0,1400000.0
3742,devops engineer,Fibonalabs,"Madurai, Tamil Nadu",0.0,1200000.0
3728,devops engineer,YourHRfolks,"Jaipur, Rajasthan",0.0,1600000.0
3726,devops engineer,InvokHR,"Mumbai, Maharashtra",0.0,2500000.0
3717,devops engineer,Indus OS,"Mumbai, Maharashtra",0.0,1300000.0
3705,devops engineer,Unnati,India,0.0,1000000.0
3686,devops engineer,IndependentConsultant,"Pune, Maharashtra",0.0,1300000.0
3677,devops engineer,Sanguine Global,"Chennai, Tamil Nadu",0.0,1500000.0
2309,full stack developer,Numadic,"Goa, India",0.0,700000.0
2447,full stack -developer,Skill Monks - A unit of Scuti Tech Labs Pvt Ltd,"Hyderabad, Telangana",0.0,1000000.0
2278,frontend developer,Ideamagix,"Mumbai, Maharashtra",0.0,500000.0
1686,backend developer,Pracify,India,0.0,750000.0
1666,backend developer,Navia Life Care,"Delhi, India",0.0,1400000.0
1643,backend developer,InvokHR,India,0.0,1000000.0
1641,backend developer,HOP Financial Services,"Bangalore, Karnataka",0.0,800000.0
1640,backend developer,Envisionard,"Pune, Maharashtra",0.0,1500000.0
1639,backend developer,Meatigocom,"Delhi, India",0.0,1000000.0
1693,backend developer,MondayMorning,"Noida, Ghaziabad",0.0,800000.0
1625,backend developer,Credence Analytics,"Mumbai, Maharashtra",0.0,1000000.0
1605,backend developer,Semperfi Solution,"Bangalore, Karnataka",0.0,600000.0
1602,backend developer,Iorta Technology Solutions Pvt Ltd,"Mumbai, Maharashtra",0.0,600000.0
1590,backend developer,FirstFiling,"Jaipur, Rajasthan",0.0,450000.0
1565,backend developer,Shoocal,"Bangalore, Karnataka",0.0,700000.0
1563,backend developer,Zydelo,India,0.0,1000000.0
1560,backend developer,Hirextra,"Hyderabad, Telangana",0.0,1200000.0
1611,backend developer,Anzy,"Bangalore, Karnataka",0.0,1600000.0
1702,backend developer,Jobdost,"Delhi, India",0.0,3500000.0
1715,backend developer,invoid,"Delhi, India",0.0,600000.0
1717,backend developer,InvokHR,"Bangalore, Karnataka",0.0,1100000.0
1844,backend developer,Olegacy,"Bangalore, Karnataka",0.0,1200000.0
1843,backend developer,Rift,"Goa, India",0.0,700000.0
1841,backend developer,GLOBAL LANCERS,"Jaipur, Rajasthan",0.0,600000.0
1838,backend developer,Mobile Programming LLC,India,0.0,900000.0
1810,backend developer,Qrata,"Delhi, India",0.0,2300000.0
1808,backend developer,TecManic,India,0.0,400000.0
1804,backend developer,The Hub,India,0.0,2000000.0
1803,backend developer,Mobile Programming LLC,"Bangalore, Karnataka",0.0,700000.0
1801,backend developer,wwwemotcoin,"Bangalore, Karnataka",0.0,300000.0
1774,backend developer,Multi Recruit,"Bangalore, Karnataka",0.0,800000.0
1771,backend developer,UACTIV,India,0.0,600000.0
1770,backend developer,All Indian IT Services LLP,"Nagpur, Maharashtra",0.0,380000.0
1767,backend developer,Scalex Technology Solutions,"Pune, Maharashtra",0.0,800000.0
1766,backend developer,Skyber Enterprises,"Mumbai, Maharashtra",0.0,700000.0
1744,backend developer,Huptech Consultancy Services,"Ahmedabad, Gujarat",0.0,1000000.0
1549,backend developer,Recruit Square,India,0.0,900000.0
1539,backend developer,Think eBikeGo Pvt Ltd,"Mumbai, Maharashtra",0.0,800000.0
1536,backend developer,Aarms Solutions on,"Bangalore, Karnataka",0.0,1400000.0
1534,backend developer,Shortcastle Technologies,"Chennai, Tamil Nadu",0.0,1600000.0
852,data analyst,BitClass,"Bangalore, Karnataka",0.0,1600000.0
837,data analyst,Jobdost,"Bangalore, Karnataka",0.0,500000.0
818,data analyst,Syrencloud,"Hyderabad, Telangana",0.0,800000.0
817,data analyst,MSMEx,"Mumbai, Maharashtra",0.0,1200000.0
804,data analyst,Reality Premedia Services Pvt Ltd,"Pune, Maharashtra",0.0,800000.0
780,data analyst,SveltetechTechnologies Pvt Ltd,"Delhi, India",0.0,300000.0
705,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,1500000.0
696,data scientist,Ezeiatech systems,India,0.0,1500000.0
678,data scientist,Angel One,"Mumbai, Maharashtra",0.0,1500000.0
671,data scientist,Accolite Software,"Bangalore, Karnataka",0.0,2400000.0
658,data scientist,Unnati,"Bangalore, Karnataka",0.0,1200000.0
652,data scientist,Unnati,"Mumbai, Maharashtra",0.0,1500000.0
639,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,2000000.0
569,data scientist,BYGRAD,"Bangalore, Karnataka",0.0,1200000.0
529,data scientist,Fragma Data Systems,"Chennai, Tamil Nadu",0.0,1200000.0
854,data analyst,Amazon,"Bangalore, Karnataka",0.0,800000.0
2282,frontend developer,Ownerstown,"Bangalore, Karnataka",0.0,600000.0
858,data analyst,Extramarks,"Noida, Ghaziabad",0.0,1000000.0
908,data analyst,Azent Overseas,"Mumbai, Maharashtra",0.0,700000.0
1528,backend developer,Kalibre global konnects,"Ahmedabad, Gujarat",0.0,1000000.0
1447,senior analyst – ai/ml engineer (machine learn...,Vrinda International,"Bangalore, Karnataka",0.0,1000000.0
1392,machine learning research engineer,Vernacular.ai,"Bangalore, Karnataka",0.0,1500000.0
1232,applied machine learning engineer,Gipfel & Schnell Consultings Pvt Ltd,India,0.0,2000000.0
1194,machine learning engineer,SIlverPeople Consulting,"Mumbai, Maharashtra",0.0,2700000.0
1192,machine learning engineer,Hammoq,India,0.0,900000.0
1191,machine learning engineer,CES Information Technologies,"Hyderabad, Telangana",0.0,1500000.0
1179,machine learning engineer,Marktine,"Bangalore, Karnataka",0.0,1500000.0
1169,machine learning engineer,Artifex HR,"Bangalore, Karnataka",0.0,800000.0
1120,mis data analyst,Randstad India,"Raipur, Chhattisgarh",0.0,1400000.0
1071,financial data analyst,Nirvana Solutions,India,0.0,300000.0
1067,data analyst- marketing,Unnati,"Delhi, India",0.0,1500000.0
919,data analyst,CIEL HR Services,"Bangalore, Karnataka",0.0,1500000.0
912,data analyst,MedCords,"Kota, Rajasthan",0.0,250000.0
911,data analyst,Srijan Technologies,India,0.0,1200000.0
898,data analyst,Marktine,"Bangalore, Karnataka",0.0,1500000.0
1848,backend developer,Wenger and Watson Inc,"Bangalore, Karnataka",0.0,1600000.0
1846,backend developer,Linarc Inc,"Chennai, Tamil Nadu",0.0,600000.0
1869,backend developer,Uniphore Software Systems,"Bangalore, Karnataka",0.0,1500000.0
2182,frontend developer,Zapit,India,0.0,1200000.0
2157,frontend developer,Edge CRM,"Mumbai, Maharashtra",0.0,200000.0
2140,frontend developer,Displaysweet,"Pune, Maharashtra",0.0,1500000.0
2137,frontend developer,AyataCommerce,India,0.0,1500000.0
2136,frontend developer,Storeking,"Bangalore, Karnataka",0.0,1000000.0
2129,frontend developer,Talent Socio Bizcon LLP,"Bangalore, Karnataka",0.0,400000.0
2183,frontend developer,Genius Placement Service,"Ahmedabad, Gujarat",0.0,500000.0
2124,frontend developer,Startupwala,"Pune, Maharashtra",0.0,300000.0
2116,frontend developer,Aakash Educational Services Limited,"Delhi, India",0.0,1800000.0
2103,frontend developer,BOB eProcure Solutions,"Hyderabad, Telangana",0.0,1000000.0
2102,frontend developer,FaceX,"Bangalore, Karnataka",0.0,900000.0
2094,frontend developer,plunes technologies,"Gurgaon, Haryana",0.0,120000.0
2091,frontend developer,Kool Group Ltd.,"Dehradun, Uttarakhand",0.0,500000.0
2089,frontend developer,Konnectbox,"Bangalore, Karnataka",0.0,1200000.0
2122,frontend developer,Purple Style Labs Private Limited,"Mumbai, Maharashtra",0.0,2800000.0
2184,frontend developer,Mobile Programming LLC,"Mumbai, Maharashtra",0.0,900000.0
2187,frontend developer,Aviation Indeed,"Hyderabad, Telangana",0.0,800000.0
2188,frontend developer,FirstFiling,"Jaipur, Rajasthan",0.0,450000.0
2253,frontend developer,Near,"Bangalore, Karnataka",0.0,3000000.0
2241,frontend developer,Benchkart Services,India,0.0,2400000.0
2240,frontend developer,Oceanfrogs Software,India,0.0,800000.0
2237,frontend developer,Quantela,"Hyderabad, Telangana",0.0,1200000.0
2235,frontend developer,The Hub,"Bangalore, Karnataka",0.0,2000000.0
2226,frontend developer,Elixa technologies Private Limited,"Pune, Maharashtra",0.0,1400000.0
2225,frontend developer,Ifortis corporate,"Noida, Ghaziabad",0.0,750000.0
2224,frontend developer,Skyber Enterprises,"Mumbai, Maharashtra",0.0,900000.0
2208,frontend developer,Blew Minds Consulting,"Mumbai, Maharashtra",0.0,1200000.0
2206,frontend developer,StarClinch,"Delhi, India",0.0,300000.0
2205,frontend developer,SaveIN,"Delhi, India",0.0,1000000.0
2203,frontend developer,Urbanstop Studio LLP,"Bangalore, Karnataka",0.0,550000.0
2198,frontend developer,Jet Freight Logistics Limited,"Mumbai, Maharashtra",0.0,800000.0
2192,frontend developer,Mobile Programming India Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
2190,frontend developer,pagon tech,India,0.0,450000.0
2077,frontend developer,Homesfy,"Thane, Maharashtra",0.0,1000000.0
1864,backend developer,Digitrack Sports India Pvt Ltd,"Pune, Maharashtra",0.0,900000.0
2075,frontend developer,Transportation | Warehouse Optimization,India,0.0,2000000.0
2072,frontend developer,SIMBOAI,"Bangalore, Karnataka",0.0,800000.0
1954,frontend developer,ConsultBae,"Delhi, India",0.0,1200000.0
1949,frontend developer,1BRIDGE,"Bangalore, Karnataka",0.0,1100000.0
1945,frontend developer,Ideas2IT Technologies,"Chennai, Tamil Nadu",0.0,2000000.0
1940,frontend developer,Jithvar Consultancy Services,"Lucknow, Uttar Pradesh",0.0,500000.0
1938,frontend developer,Digirex Technologies,India,0.0,360000.0
1936,frontend developer,Placjo Technologies Pvt ltd,"Bangalore, Karnataka",0.0,900000.0
1933,frontend developer,Jobdost,"Mumbai, Maharashtra",0.0,1500000.0
1958,frontend developer,ZoomRx,"Chennai, Tamil Nadu",0.0,1400000.0
1922,frontend developer,Splat Studio,"Delhi, India",0.0,480000.0
1899,frontend developer,Ftechiz Solutions,"Dehradun, Uttarakhand",0.0,400000.0
1879,backend developer,Deployd Technologies Pvt Ltd,"Bangalore, Karnataka",0.0,1000000.0
1876,backend developer,eBikeGO,"Mumbai, Maharashtra",0.0,700000.0
1875,backend developer,School of Accelerated Learning,"Mumbai, Maharashtra",0.0,1100000.0
1874,backend developer,Sureify Labs Technology,"Hyderabad, Telangana",0.0,2400000.0

In [346]:
df[df['salary_min'] == 0][
    ['title', 'company', 'location', 'salary_min', 'salary_max']
].head(30)

,title,company,location,salary_min,salary_max
320,software engineer,Talentspro,"Bangalore, Karnataka",0.0,2000000.0
529,data scientist,Fragma Data Systems,"Chennai, Tamil Nadu",0.0,1200000.0
569,data scientist,BYGRAD,"Bangalore, Karnataka",0.0,1200000.0
639,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,2000000.0
652,data scientist,Unnati,"Mumbai, Maharashtra",0.0,1500000.0
658,data scientist,Unnati,"Bangalore, Karnataka",0.0,1200000.0
671,data scientist,Accolite Software,"Bangalore, Karnataka",0.0,2400000.0
678,data scientist,Angel One,"Mumbai, Maharashtra",0.0,1500000.0
696,data scientist,Ezeiatech systems,India,0.0,1500000.0
705,data scientist,Yottaasys AI LLC,"Bangalore, Karnataka",0.0,1500000.0
780,data analyst,SveltetechTechnologies Pvt Ltd,"Delhi, India",0.0,300000.0
804,data analyst,Reality Premedia Services Pvt Ltd,"Pune, Maharashtra",0.0,800000.0
817,data analyst,MSMEx,"Mumbai, Maharashtra",0.0,1200000.0
818,data analyst,Syrencloud,"Hyderabad, Telangana",0.0,800000.0
837,data analyst,Jobdost,"Bangalore, Karnataka",0.0,500000.0
852,data analyst,BitClass,"Bangalore, Karnataka",0.0,1600000.0
854,data analyst,Amazon,"Bangalore, Karnataka",0.0,800000.0
858,data analyst,Extramarks,"Noida, Ghaziabad",0.0,1000000.0
898,data analyst,Marktine,"Bangalore, Karnataka",0.0,1500000.0
908,data analyst,Azent Overseas,"Mumbai, Maharashtra",0.0,700000.0
911,data analyst,Srijan Technologies,India,0.0,1200000.0
912,data analyst,MedCords,"Kota, Rajasthan",0.0,250000.0
919,data analyst,CIEL HR Services,"Bangalore, Karnataka",0.0,1500000.0
1067,data analyst- marketing,Unnati,"Delhi, India",0.0,1500000.0
1071,financial data analyst,Nirvana Solutions,India,0.0,300000.0
1120,mis data analyst,Randstad India,"Raipur, Chhattisgarh",0.0,1400000.0
1169,machine learning engineer,Artifex HR,"Bangalore, Karnataka",0.0,800000.0
1179,machine learning engineer,Marktine,"Bangalore, Karnataka",0.0,1500000.0
1191,machine learning engineer,CES Information Technologies,"Hyderabad, Telangana",0.0,1500000.0
1192,machine learning engineer,Hammoq,India,0.0,900000.0

In [347]:
df.loc[df['salary_min'] == 0, 'salary_min'] = np.nan

In [348]:
df['salary_min'].isna().sum()

2894

In [349]:
df[df['salary_min'].between(1, 999)][
    ['title', 'company', 'location', 'salary_min', 'salary_max']
].sort_values('salary_min')

,title,company,location,salary_min,salary_max
4280,cyber security engineer,Bhanven Cyber Tech Inc,India,7.0,85.0
4675,business analyst,Ixora Global Services,"Gurgaon, Haryana",12.0,144.0

In [350]:
mask = df['salary_max'].isin([85, 144])

df.loc[mask, ['salary_min', 'salary_max']] = np.nan

In [351]:
df['salary_max'].value_counts(dropna=False)

salary_max
NaN          2597
1500000.0     338
1200000.0     204
1000000.0     196
2000000.0     161
2500000.0     143
800000.0      136
3000000.0     120
600000.0      111
500000.0       87
700000.0       83
1800000.0      71
900000.0       66
3500000.0      59
1400000.0      57
300000.0       52
1600000.0      48
400000.0       48
4000000.0      32
1300000.0      31
2200000.0      28
2400000.0      26
1100000.0      22
4500000.0      20
1700000.0      18
200000.0       17
2800000.0      16
5000000.0      11
2100000.0      10
450000.0       10
750000.0        8
6000000.0       8
1900000.0       8
2700000.0       8
2600000.0       7
2300000.0       6
850000.0        6
100000.0        6
5500000.0       6
480000.0        5
50000.0         4
650000.0        4
3200000.0       3
3800000.0       3
40000.0         3
840000.0        3
3400000.0       3
720000.0        3
150000.0        3
7000000.0       3
250000.0        3
1350000.0       2
3300000.0       2
360000.0        2
1699992.0       2
240000.0        2
120000.0        2
1560000.0       1
7200000.0       1
20000.0         1
3600000.0       1
960000.0        1
260000.0        1
580000.0        1
350000.0        1
660000.0        1
3700000.0       1
1440000.0       1
1650000.0       1
4800000.0       1
234350.0        1
30000.0         1
540000.0        1
1920000.0       1
2900000.0       1
370000.0        1
1999992.0       1
999996.0        1
9000000.0       1
380000.0        1
36000.0         1
420000.0        1
4100000.0       1
80000.0         1
950000.0        1
550000.0        1
170000.0        1
22000.0         1
Name: count, dtype: int64

In [352]:
df[df['salary_max'] < 1000][
    ['title', 'company', 'location', 'salary_min', 'salary_max']
].sort_values('salary_max')

Empty DataFrame
Columns: [title, company, location, salary_min, salary_max]
Index: []

In [353]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03T00:54:22Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,Unknown,NaN,NaN
1,2026-07-10T03:46:23Z,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,Unknown,NaN,NaN
2,2026-07-03T00:54:32Z,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,Unknown,NaN,NaN
3,2026-07-09T17:58:24Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,Unknown,NaN,NaN
4,2026-07-03T00:54:21Z,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5785771924?se=bi...,IT Jobs,5785771924,full_time,Unknown,NaN,NaN

In [356]:
df[df['state'].isna()][
    ['location', 'city', 'state']
].head(30)

Empty DataFrame
Columns: [location, city, state]
Index: []

In [355]:
df['state'] = df['state'].fillna('Unknown')

In [358]:
df['latitude'].value_counts(dropna=False)

latitude
NaN          2337
17.402750     429
19.008210     403
18.506200     392
13.060410     287
12.957030     227
28.565790     159
28.625230      88
23.042000      77
28.323996      62
19.020000      46
22.572850      45
26.744100      40
22.662150      40
11.017171      23
9.980110       21
30.754500      15
21.189550      15
19.173350      12
8.381590       11
30.753950      11
22.289100      11
26.867700       8
12.970600       8
23.489600       7
9.910510        7
30.354100       7
19.439563       6
12.947150       6
21.186700       6
28.626230       5
22.296500       5
17.382560       5
18.543950       5
12.973750       4
26.014230       4
20.269700       4
15.354200       4
19.116450       3
17.453150       3
10.989607       3
28.459600       3
17.864111       3
19.962240       3
24.462262       3
28.960550       3
13.015430       3
28.698150       2
26.337900       2
26.464500       2
18.550340       2
10.513580       2
23.066820       2
14.439800       2
14.325172       2
22.385318       2
26.995510       2
8.492390        2
26.524950       2
17.382770       2
18.518750       2
13.015170       2
28.382210       2
23.732480       2
27.161850       2
12.967450       2
17.977650       1
29.005350       1
28.710660       1
19.256780       1
10.368486       1
17.400320       1
30.692090       1
19.017700       1
19.049790       1
12.874200       1
12.843460       1
30.313600       1
22.693650       1
17.674403       1
28.236100       1
19.138700       1
18.942060       1
17.531350       1
21.399300       1
18.471550       1
18.955200       1
30.725890       1
28.456450       1
28.677400       1
18.553350       1
17.701000       1
30.284650       1
30.424050       1
30.690380       1
12.920250       1
22.292250       1
19.720980       1
23.274950       1
12.914480       1
25.232390       1
12.983200       1
8.489250        1
16.253450       1
12.968530       1
21.036810       1
12.968800       1
30.758800       1
10.932450       1
18.628950       1
12.895050       1
12.939100       1
11.213550       1
25.419800       1
12.507150       1
10.108450       1
13.021490       1
19.053750       1
28.569600       1
13.141450       1
32.729650       1
12.824040       1
20.848300       1
Name: count, dtype: int64

In [359]:
df[(df['latitude'] < -90) | (df['latitude'] > 90)][
    ['location', 'city', 'state', 'latitude']
]

Empty DataFrame
Columns: [location, city, state, latitude]
Index: []

In [360]:
df[df['latitude'].isna()][
    ['location', 'city', 'state', 'latitude', 'longitude']
].head(30)

                      location       city          state  latitude  longitude
6         Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
12                       India    Unknown        Unknown       NaN        NaN
17        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
18  Noida, Gautam Buddha Nagar      Noida  Uttar Pradesh       NaN        NaN
20        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
22  Noida, Gautam Buddha Nagar      Noida  Uttar Pradesh       NaN        NaN
23                       India    Unknown        Unknown       NaN        NaN
24  Noida, Gautam Buddha Nagar      Noida  Uttar Pradesh       NaN        NaN
28  Noida, Gautam Buddha Nagar      Noida  Uttar Pradesh       NaN        NaN
29        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
30        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
31        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
42        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
46        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
48        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
50                       India    Unknown        Unknown       NaN        NaN
54                       India    Unknown        Unknown       NaN        NaN
55        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
62        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
63        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
71        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
72        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
73        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
74        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
76                       India    Unknown        Unknown       NaN        NaN
77        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
78                       India    Unknown        Unknown       NaN        NaN
84        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
86        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN
89        Bangalore, Karnataka  Bangalore      Karnataka       NaN        NaN

In [361]:
df[(df['longitude'] < -180) | (df['longitude'] > 180)][
    ['location', 'city', 'state', 'latitude', 'longitude']
]

Empty DataFrame
Columns: [location, city, state, latitude, longitude]
Index: []

In [362]:
df[df['latitude'].isna() & df['longitude'].isna()].shape[0]

2337

In [363]:
df['created'] = pd.to_datetime(df['created'], errors='coerce')

In [367]:
df['created'].isna().sum()

0

In [368]:
df['created'].dtype

datetime64[ns, UTC]

In [370]:
df['id'].isna().sum()

0

In [371]:
df['id'].duplicated().sum()

0

In [372]:
df['redirect_url'].head()

0    https://www.adzuna.in/land/ad/5785772072?se=bi...
1    https://www.adzuna.in/land/ad/5794768004?se=bi...
2    https://www.adzuna.in/land/ad/5785773087?se=bi...
3    https://www.adzuna.in/land/ad/5794153227?se=bi...
4    https://www.adzuna.in/land/ad/5785771924?se=bi...
Name: redirect_url, dtype: object

In [373]:
df['redirect_url'].duplicated().sum()

0

In [374]:
df.head()

,created,latitude,title,standard_role,location,city,state,longitude,salary_is_predicted,description,company,redirect_url,category,id,contract_time,contract_type,salary_min,salary_max
0,2026-07-03 00:54:22+00:00,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with ABB, an inclusive employer an...",ABB,https://www.adzuna.in/land/ad/5785772072?se=bi...,Engineering Jobs,5785772072,full_time,Unknown,NaN,NaN
1,2026-07-10 03:46:23+00:00,12.95703,software engineer,Software Engineer,"Bangalore, Karnataka",Bangalore,Karnataka,77.59837,0,"This job is with Kyndryl, an inclusive employe...",Kyndryl,https://www.adzuna.in/land/ad/5794768004?se=bi...,IT Jobs,5794768004,full_time,Unknown,NaN,NaN
2,2026-07-03 00:54:32+00:00,17.40275,software engineer,Software Engineer,"Hyderabad, Telangana",Hyderabad,Telangana,78.50806,0,"This job is with Cornerstone OnDemand, an incl...",Cornerstone OnDemand,https://www.adzuna.in/land/ad/5785773087?se=bi...,IT Jobs,5785773087,full_time,Unknown,NaN,NaN
3,2026-07-09 17:58:24+00:00,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5794153227?se=bi...,IT Jobs,5794153227,full_time,Unknown,NaN,NaN
4,2026-07-03 00:54:21+00:00,19.00821,software engineer,Software Engineer,"Mumbai, Maharashtra",Mumbai,Maharashtra,72.84415,0,"This job is with Morningstar, an inclusive emp...",Morningstar,https://www.adzuna.in/land/ad/5785771924?se=bi...,IT Jobs,5785771924,full_time,Unknown,NaN,NaN

In [375]:
df['salary_is_predicted'].value_counts()

salary_is_predicted
0    4964
Name: count, dtype: int64

In [376]:
df['description'].isna().sum()

0

In [377]:
(df['description'].str.strip() == '').sum()

0

In [378]:
df.isna().sum()

created                   0
latitude               2337
title                     0
standard_role             0
location                  0
city                      0
state                     0
longitude              2337
salary_is_predicted       0
description               0
company                   0
redirect_url              0
category                  0
id                        0
contract_time             0
contract_type             0
salary_min             2896
salary_max             2597
dtype: int64

In [379]:
df.duplicated().sum()

0

In [380]:
df.to_csv("adzuna_cleaned.csv", index=False)