In [1]:
import pandas as pd 
import numpy as np

In [2]:
df1=pd.read_csv('raw_job_greenhouse.csv')

In [3]:
df=df1.copy()

In [4]:
df.head()

,absolute_url,data_compliance,internal_job_id,location,metadata,id,updated_at,requisition_id,title,company_name,...,language,application_deadline,content,departments,offices,ai_disclaimer,include_ai_disclaimer,ai_opt_out_request_url,education,company_board
0,https://stripe.com/jobs/search?gh_jid=7954688,"[{'type': 'gdpr', 'requires_consent': False, '...",3453698.0,"{'name': 'San Francisco, CA'}",NaN,7954688,2026-07-13T14:37:36-04:00,See Opening ID,"Account Executive, AI Sales (Grower)",Stripe,...,en,NaN,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 380786, 'name': '1654 Account Executiv...","[{'id': 65234, 'name': 'US', 'location': None,...",NaN,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
1,https://stripe.com/jobs/search?gh_jid=8042978,"[{'type': 'gdpr', 'requires_consent': False, '...",3486109.0,{'name': 'Japan'},NaN,8042978,2026-07-02T21:13:43-04:00,See Opening ID,"Account Executive, Commercial Grower (Japanese...",Stripe,...,ja,NaN,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",NaN,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
2,https://stripe.com/jobs/search?gh_jid=7789539,"[{'type': 'gdpr', 'requires_consent': False, '...",3407094.0,{'name': 'Japan'},NaN,7789539,2026-07-02T21:14:52-04:00,See Opening ID,"Account Executive, Commercial Hunter (Japanese...",Stripe,...,ja,NaN,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 87012, 'name': 'Japan Locations', 'loc...",NaN,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
3,https://stripe.com/jobs/search?gh_jid=7893199,"[{'type': 'gdpr', 'requires_consent': False, '...",3431456.0,{'name': 'Singapore'},NaN,7893199,2026-06-26T17:05:39-04:00,See Opening ID,"Account Executive, Cross Border China",Stripe,...,en,NaN,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,"[{'id': 81432, 'name': '1195 Account Executive...","[{'id': 86997, 'name': 'Singapore Locations', ...",NaN,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier
4,https://stripe.com/jobs/search?gh_jid=7993151,"[{'type': 'gdpr', 'requires_consent': False, '...",3467410.0,"{'name': 'US-Remote, US-San Francisco, US-Chic...",NaN,7993151,2026-07-01T10:19:50-04:00,See Opening ID,"Account Executive - Enterprise, Grower",Stripe,...,en,NaN,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,"[{'id': 81430, 'name': '1175 Enterprise - Acco...","[{'id': 65234, 'name': 'US', 'location': None,...",NaN,False,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier

In [5]:
df.columns

Index(['absolute_url', 'data_compliance', 'internal_job_id', 'location',
       'metadata', 'id', 'updated_at', 'requisition_id', 'title',
       'company_name', 'first_published', 'language', 'application_deadline',
       'content', 'departments', 'offices', 'ai_disclaimer',
       'include_ai_disclaimer', 'ai_opt_out_request_url', 'education',
       'company_board'],
      dtype='object')

In [6]:
df.isna().sum()

absolute_url                 0
data_compliance              0
internal_job_id             13
location                     0
metadata                   798
id                           0
updated_at                   0
requisition_id              79
title                        0
company_name                 0
first_published              0
language                     0
application_deadline      2305
content                      0
departments                  0
offices                      0
ai_disclaimer             2305
include_ai_disclaimer     1322
ai_opt_out_request_url    1713
education                 2253
company_board                0
dtype: int64

In [7]:
df.dtypes

absolute_url               object
data_compliance            object
internal_job_id           float64
location                   object
metadata                   object
id                          int64
updated_at                 object
requisition_id             object
title                      object
company_name               object
first_published            object
language                   object
application_deadline      float64
content                    object
departments                object
offices                    object
ai_disclaimer             float64
include_ai_disclaimer      object
ai_opt_out_request_url     object
education                  object
company_board              object
dtype: object

In [8]:
df[df['internal_job_id'].isna()][
    ['title', 'company_name', 'id', 'requisition_id', 'updated_at']
]

,title,company_name,id,requisition_id,updated_at
1702,Future Opportunities: Channel Sales Experience,"Gusto, Inc.",7773805,NaN,2026-06-25T15:40:57-04:00
1703,Future Opportunities: Dedicated Service Adviso...,"Gusto, Inc.",7927179,NaN,2026-06-25T15:40:57-04:00
1704,Future Opportunities: Dedicated Service Adviso...,"Gusto, Inc.",7927184,NaN,2026-06-25T15:40:57-04:00
1705,Future Opportunities: Early Career Sales Talent,"Gusto, Inc.",8001931,NaN,2026-06-25T15:40:57-04:00
1706,Future Opportunities: HR Constultant,"Gusto, Inc.",7927447,NaN,2026-06-25T15:40:57-04:00
1707,Future Opportunities: Licensed Benefits Advisor,"Gusto, Inc.",7838275,NaN,2026-06-29T19:42:54-04:00
1709,Future Opportunities: Retirement Advocate,"Gusto, Inc.",7774285,NaN,2026-06-25T15:40:57-04:00
1711,Future Opportunities: Retirement Client Relati...,"Gusto, Inc.",7984008,NaN,2026-06-25T15:40:57-04:00
1712,Future Opportunities: Retirement Implementatio...,"Gusto, Inc.",7984004,NaN,2026-06-25T15:40:57-04:00
1762,Summer Opportunities - Retirement Sales AE,"Gusto, Inc.",7833882,NaN,2026-06-25T15:40:57-04:00
1859,Customs Specialist - Join Our Talent Community,Flexport,7867207,NaN,2026-07-09T19:28:21-04:00
1898,Operations Associate - Join Our Talent Community,Flexport,7904839,NaN,2026-07-09T19:28:21-04:00
1900,Operations Specialist - Join Our Talent Commun...,Flexport,7909078,NaN,2026-07-09T19:28:21-04:00

In [9]:
df['metadata'].notna().sum()

1507

In [10]:
df['requisition_id'].isna().sum()

79

In [11]:
df[df['requisition_id'].isna()][
    ['title', 'company_name', 'id', 'internal_job_id', 'requisition_id']
].head(20)

,title,company_name,id,internal_job_id,requisition_id
1309,Regional Director - Enterprise Sales (Saudi Ar...,Datadog,7338847,3274767.0,NaN
1544,"Backend Software Engineer, Reykjavik",Asana,6619439,2715536.0,NaN
1546,Business Development Representative,Asana,6806660,3123783.0,NaN
1547,"Business Development Representative, German Sp...",Asana,7477015,3319153.0,NaN
1551,Corporate Account Executive,Asana,6981655,3171006.0,NaN
1552,Corporate Account Executive,Asana,7594694,3356637.0,NaN
1560,Data Engineer,Asana,6749982,3107401.0,NaN
1566,"Engineering Manager, Builder Platform",Asana,7979918,2929570.0,NaN
1567,"Engineering Manager, Development Infrastructure",Asana,6174752,2940810.0,NaN
1581,Fullstack Engineer,Asana,7979882,3456761.0,NaN
1596,"Junior Software Engineer, Reykjavik",Asana,7766762,3401730.0,NaN
1622,"Security Engineer, Detection Engineering",Asana,7350641,3279208.0,NaN
1624,"Security Engineer, Threat Response",Asana,7964484,3457834.0,NaN
1629,Senior Data Engineer,Asana,7859222,3423004.0,NaN
1631,"Senior Engineering Manager, Consumption Based ...",Asana,7904869,1172483.0,NaN
1632,"Senior Engineering Manager, Payment Platform",Asana,7957984,1172483.0,NaN
1634,Senior Infrastructure Engineer (Software-Focused),Asana,7160487,3147679.0,NaN
1647,Senior Software Engineer,Asana,7961508,3456761.0,NaN
1648,Senior Software Engineer,Asana,7962245,3457022.0,NaN
1649,"Senior Software Engineer, Account Management",Asana,7962239,3457020.0,NaN

In [12]:
df['updated_at'].dtype

dtype('O')

In [13]:
df['updated_at'] = pd.to_datetime(df['updated_at'], errors='coerce', utc=True)

In [14]:
df['updated_at'].isna().sum()

0

In [15]:
df['updated_at'].isna().sum()

0

In [16]:
df['first_published'].dtype

dtype('O')

In [17]:
df['first_published'].isna().sum()

0

In [18]:
df['first_published'] = pd.to_datetime(
    df['first_published'],
    errors='coerce',
    utc=True
)

In [19]:
df['first_published'].dtype

datetime64[ns, UTC]

In [20]:
df['content'].isna().sum()

0

In [21]:
(df['content'].str.strip() == '').sum()

0

In [22]:
df['title'].isna().sum()

0

In [23]:
(df['title'].str.strip() == '').sum()

0

In [24]:
df['title'].duplicated().sum()

575

In [25]:
df['company_name'].isna().sum()

0

In [26]:
(df['company_name'].str.strip() == '').sum()

0

In [27]:
df['language'].isna().sum()

0

In [28]:
(df['language'].str.strip() == '').sum()

0

In [29]:
df['departments'].isna().sum()

0

In [30]:
(df['departments'].astype(str).str.strip() == '').sum()

0

In [31]:
df['offices'].isna().sum()

0

In [32]:
(df['offices'].astype(str).str.strip() == '').sum()

0

In [33]:
df['ai_disclaimer'].isna().sum()

2305

In [34]:
df['include_ai_disclaimer'].isna().sum()

1322

In [35]:
(df['include_ai_disclaimer'].astype(str).str.strip() == '').sum()

0

In [36]:
df['include_ai_disclaimer'].value_counts(dropna=False)

include_ai_disclaimer
NaN      1322
False     983
Name: count, dtype: int64

In [37]:
df['ai_opt_out_request_url'].isna().sum()

1713

In [38]:
(df['ai_opt_out_request_url'].astype(str).str.strip() == '').sum()

0

In [39]:
df['education'].isna().sum()

2253

In [40]:
(df['education'].astype(str).str.strip() == '').sum()

0

In [41]:
df['company_board'].isna().sum()

0

In [42]:
(df['company_board'].astype(str).str.strip() == '').sum()

0

In [43]:
df['metadata'].value_counts()

metadata
[{'id': 108496618002, 'name': 'Job Post Department', 'value': 'Sales', 'value_type': 'single_select'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       68
[{'id': 108496618002, 'name': 'Job Post Department', 'value': 'Engineering', 'value_type': 'single_select'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 66
[{'id': 108496618002, 'name': 'Job Post Department', 'value': 'Product', 'value_type': 'single_select'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     23
[{'id': 108496618002, 'name': 'Job Post Department', 'value': 'People', 'value_type': 'single_select'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      22
[{'id': 58381966, 'name': 'Start of Entry', 'value': None, 'value_type': 'short_text'}, {'id': 58396540, 'name': 'Midpoint', 'value': None, 'value_type': 'short_text'}, {'id': 58396622, 'name': 'Max of Mature', 'value': None, 'value_type': 'short_text'}, {'id': 58381985, 'name': 'Variable Pay Target', 'value': None, 'value_type': 'short_text'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   21
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ..
[{'id': 22194060, 'name': 'Position ID', 'value': '10014494', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D22100-Clusters & Interfaces', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10344-Server Security', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'EMEA', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'Professional - IC', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Standard', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1gTEL5a1RCQDyS3h4bBSiv3d0NOk5UoAA4ifmS04a9dQ/edit?pli=1&tab=t.b1krrsuswamf#heading=h.xywbdj93n1l3', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]                                                              1
[{'id': 22194060, 'name': 'Position ID', 'value': '10006055', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D21000-Durable TXs & Availability', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10431-Storage Layer Services', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'North America', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['1-In Office'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'Professional - IC', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Standard', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1SK766-c0xrcLVhnQMRiHxXhs9DcVzeXqu7WFZ5pCQTU/edit?usp=sharing', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': {'unit': 'USD', 'max_value': '225000.0', 'min_value': '157000.0'}, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '248000.0', 'min_value': '126000.0'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]     1
[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D11200-Solutions Consulting', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10414-Solutions Consulting EMEA, North', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'EMEA', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': None, 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]                                                                                                                                                                                     1
[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D41808-Solutions Consulting, Growth EMEA', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10416-Solutions Consulting EMEA, France', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'EMEA', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1TXguYYFbsE36lnmmEl-3oz2bJfdcOesYanAu67ZhXWM/edit?tab=t.f8fxwqhuxn8p', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': None, 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': None, 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]                                                                    1
[{'id': 33310, 'name': 'Time Type', 'value': 'Full time', 'value_type': 'single_select'}, {'id': 166208, 'name': 'Area - Engineering', 'value': 'Corporate Development', 'value_type': 'single_select'}, {'id': 498252, 'name': 'Cost Center', 'value': 'Engineering - Corporate Development', 'value_type': 'single_select'}, {'id': 516515, 'name': 'Geography', 'value': 'North America', 'value_type': 'single_select'}, {'id': 9593635, 'name': 'Early Career Time Type', 'value': None, 'value_type': 'single_select'}, {'id': 29446322, 'name': 'Pay Transparency Range', 'value': {'unit': 'USD', 'max_value': '240000.0', 'min_value': '192000.0'}, 'value_type': 'currency_range'}, {'id': 31273219, 'name': 'Does this role require access to ITAR-controlled data?', 'value': 'No', 'value_type': 'single_select'}, {'id': 58619948, 'name': 'IC or MG', 'value': 'IC', 'value_type': 'single_select'}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
Name: count, Length: 706, dtype: int64

In [44]:
df['metadata'].dropna().iloc[0]

"[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D41350-Sales Dev(SDR)', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10211-Sales Development Americas', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'North America', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1QEpFyd5GVuM4TX3yvA2gvGk_ATv700iclQKQXHYrjVo/edit?usp=sharing', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': None, 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]"

In [45]:
df['metadata'].dropna().head(3).tolist()

["[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D41350-Sales Dev(SDR)', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10211-Sales Development Americas', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'North America', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1QEpFyd5GVuM4TX3yvA2gvGk_ATv700iclQKQXHYrjVo/edit?usp=sharing', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': None, 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]",
 "[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D41350-Sales Dev(SDR)', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10211-Sales Development Americas', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'North America', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1QEpFyd5GVuM4TX3yvA2gvGk_ATv700iclQKQXHYrjVo/edit?usp=sharing', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': None, 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]",
 "[{'id': 22194060, 'name': 'Position ID', 'value': 'N/A', 'value_type': 'short_text'}, {'id': 24918, 'name': 'Department ID', 'value': 'D41350-Sales Dev(SDR)', 'value_type': 'single_select'}, {'id': 22194061, 'name': 'Team', 'value': 'T10212-Sales Development RoW', 'value_type': 'single_select'}, {'id': 4914027, 'name': 'Region', 'value': 'EMEA', 'value_type': 'single_select'}, {'id': 4137836, 'name': 'Working Model Eligibility', 'value': ['2-Flexible'], 'value_type': 'multi_select'}, {'id': 4914029, 'name': 'Job Level', 'value': 'IC - Professional', 'value_type': 'single_select'}, {'id': 24109, 'name': 'Employment Type', 'value': 'Full-time', 'value_type': 'single_select'}, {'id': 1073551, 'name': 'Job Type', 'value': 'Pipeline', 'value_type': 'single_select'}, {'id': 988684, 'name': 'JD Link', 'value': 'https://docs.google.com/document/d/1Hh6Tf1JVwHETMkO-b9GF2x9ATt4lbBrfp76ANAOMoZI/edit?tab=t.0', 'value_type': 'url'}, {'id': 5525802, 'name': 'Baseline Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 5525816, 'name': 'Other Large Market Budgeted Salary', 'value': None, 'value_type': 'currency_range'}, {'id': 13324394, 'name': 'Job Post Range (United States)', 'value': {'unit': 'USD', 'max_value': '0.01', 'min_value': '0.01'}, 'value_type': 'currency_range'}, {'id': 40497768, 'name': 'Job Post Range (Canada)', 'value': {'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}, 'value_type': 'currency_range'}, {'id': 57694516, 'name': 'Job Post Range (Poland)', 'value': None, 'value_type': 'currency_range'}, {'id': 64002488, 'name': 'Job Post Range (Italy)', 'value': None, 'value_type': 'currency_range'}]"]

In [46]:
import ast

metadata_names = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and 'name' in item:
                metadata_names.append(item['name'])

    except (ValueError, SyntaxError):
        pass

pd.Series(metadata_names).value_counts()

Cost Center                                               567
IC or MG                                                  421
Does this role require access to ITAR-controlled data?    421
Pay Transparency Range                                    421
Early Career Time Type                                    421
Geography                                                 421
Area - Engineering                                        421
Time Type                                                 421
Job Post Range (Canada)                                   381
Department ID                                             381
Job Post Range (Italy)                                    381
Job Post Range (Poland)                                   381
Position ID                                               381
Job Post Range (United States)                            381
Baseline Budgeted Salary                                  381
JD Link                                                   381
Job Type                                                  381
Employment Type                                           381
Job Level                                                 381
Working Model Eligibility                                 381
Region                                                    381
Team                                                      381
Other Large Market Budgeted Salary                        381
Job Post Department                                       266
Workday Cost Center                                       148
Position Reason (Workday)                                 148
Careers Page: Heading                                     146
Careers Page: Location                                    146
Careers Page: Team                                        146
Midpoint                                                   78
Max of Mature                                              78
Variable Pay Target                                        78
Start of Entry                                             78
Career Site Categories                                     67
Name: count, dtype: int64

In [47]:
id="x0n9v3"
target = 'Job Level'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

Professional - IC    202
IC - Professional    123
People Manager        26
Senior Manager        11
Director               9
Manager                5
Senior Director        3
Support                1
Vice President         1
Name: count, dtype: int64

In [48]:
target = 'Employment Type'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

Full-time    381
Name: count, dtype: int64

In [49]:
target = 'Job Type'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

Standard     263
Pipeline     117
Evergreen      1
Name: count, dtype: int64

In [50]:
target = 'Region'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

North America    149
EMEA             128
APAC              97
LATAM              6
South America      1
Name: count, dtype: int64

In [51]:
target = 'Team'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

387-GTM Tech                                 16
T10339-Modernization ENG                     15
43-SRE Atlas & InfraSec                      13
T10212-Sales Development RoW                 12
19-Atlas Clusters Platform and Automation    11
                                             ..
27-Finance Enablement & Operations            1
T10436-Database PM                            1
T10149-Strategic Developer Relations          1
T10278-Strategic Events                       1
T10352-Technical Services - Cloud             1
Name: count, Length: 157, dtype: int64

In [52]:
target = 'Working Model Eligibility'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

[2-Flexible]                                 294
[1-In Office]                                 36
[3CF-Customer Facing Remote]                  19
[1-In Office, 2-Flexible, 3-Fully Remote]     15
[3-Fully Remote]                              12
[1-In Office, 2-Flexible]                      4
[2-Flexible, 3CF-Customer Facing Remote]       1
Name: count, dtype: int64

In [53]:
target = 'Geography'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

North America    200
APAC              98
EMEA              96
LATAM             27
Name: count, dtype: int64

In [54]:
target = 'Time Type'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

Full time    421
Name: count, dtype: int64

In [55]:
target = 'IC or MG'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

IC    346
MG     75
Name: count, dtype: int64

In [56]:
target = 'Baseline Budgeted Salary'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

None                                                                 228
{'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}               30
{'unit': 'INR', 'max_value': '0.0', 'min_value': '0.0'}               13
{'unit': 'USD', 'max_value': '225000.0', 'min_value': '157000.0'}     10
{'unit': 'USD', 'max_value': '226000.0', 'min_value': '226000.0'}      9
{'unit': 'USD', 'max_value': '190000.0', 'min_value': '133000.0'}      7
{'unit': 'USD', 'max_value': '270000.0', 'min_value': '189000.0'}      7
{'unit': 'CAD', 'max_value': '0.0', 'min_value': '0.0'}                5
{'unit': 'SGD', 'max_value': '0.0', 'min_value': '0.0'}                5
{'unit': 'USD', 'max_value': '160000.0', 'min_value': '112000.0'}      4
{'unit': 'GBP', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'BRL', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'USD', 'max_value': '245000.0', 'min_value': '171000.0'}      3
{'unit': 'USD', 'max_value': '147000.0', 'min_value': '103000.0'}      3
{'unit': 'ILS', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'MYR', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'AUD', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'USD', 'max_value': '330000.0', 'min_value': '231000.0'}      3
{'unit': 'USD', 'max_value': '180000.0', 'min_value': '126000.0'}      3
{'unit': 'KRW', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'USD', 'max_value': '242000.0', 'min_value': '169000.0'}      2
{'unit': 'USD', 'max_value': '198000.0', 'min_value': '139000.0'}      2
{'unit': 'MXN', 'max_value': '0.0', 'min_value': '0.0'}                2
{'unit': 'USD', 'max_value': '150000.0', 'min_value': '105000.0'}      2
{'unit': 'USD', 'max_value': '85000.0', 'min_value': '59000.0'}        2
{'unit': 'USD', 'max_value': '203000.0', 'min_value': '162400.0'}      1
{'unit': 'USD', 'max_value': '203000.0', 'min_value': '162000.0'}      1
{'unit': 'PLN', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'SEK', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '210000.0', 'min_value': '147000.0'}      1
{'unit': 'USD', 'max_value': '230000.0', 'min_value': '161000.0'}      1
{'unit': 'USD', 'max_value': '145000.0', 'min_value': '101000.0'}      1
{'unit': 'USD', 'max_value': '185000.0', 'min_value': '129000.0'}      1
{'unit': 'HKD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '187000.0', 'min_value': '131000.0'}      1
{'unit': 'USD', 'max_value': '130000.0', 'min_value': '91000.0'}       1
{'unit': 'USD', 'max_value': '175000.0', 'min_value': '122000.0'}      1
{'unit': 'TWD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '135000.0', 'min_value': '135000.0'}      1
{'unit': 'USD', 'max_value': '120000.0', 'min_value': '84000.0'}       1
{'unit': 'USD', 'max_value': '150000.0', 'min_value': '150000.0'}      1
{'unit': 'USD', 'max_value': '193000.0', 'min_value': '135000.0'}      1
{'unit': 'USD', 'max_value': '363000.0', 'min_value': '254000.0'}      1
{'unit': 'USD', 'max_value': '162000.0', 'min_value': '162000.0'}      1
{'unit': 'USD', 'max_value': '192000.0', 'min_value': '192000.0'}      1
{'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}        1
Name: count, dtype: int64

In [57]:
target = 'Pay Transparency Range'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

None                                                                 223
{'unit': 'USD', 'max_value': '240000.0', 'min_value': '192000.0'}     31
{'unit': 'USD', 'max_value': '305000.0', 'min_value': '244000.0'}      9
{'unit': 'USD', 'max_value': '120000.0', 'min_value': '110000.0'}      9
{'unit': 'USD', 'max_value': '165000.0', 'min_value': '113000.0'}      8
                                                                    ...
{'unit': 'USD', 'max_value': '146000.0', 'min_value': '100000.0'}      1
{'unit': 'USD', 'max_value': '116000.0', 'min_value': '79000.0'}       1
{'unit': 'USD', 'max_value': '160000.0', 'min_value': '128000.0'}      1
{'unit': 'USD', 'max_value': '110000.0', 'min_value': '75000.0'}       1
{'unit': 'USD', 'max_value': '141000.0', 'min_value': '96000.0'}       1
Name: count, Length: 91, dtype: int64

In [58]:
target = 'Job Post Range (United States)'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

{'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}              69
{'unit': 'INR', 'max_value': '0.0', 'min_value': '0.0'}              41
{'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}              39
{'unit': 'USD', 'max_value': '0.01', 'min_value': '0.01'}            24
{'unit': 'USD', 'max_value': '248000.0', 'min_value': '126000.0'}    12
                                                                     ..
{'unit': 'MYR', 'max_value': '0.01', 'min_value': '0.01'}             1
{'unit': 'USD', 'max_value': '132000.0', 'min_value': '67000.0'}      1
{'unit': 'TWD', 'max_value': '0.0', 'min_value': '0.0'}               1
{'unit': 'USD', 'max_value': '193000.0', 'min_value': '98000.0'}      1
{'unit': 'USD', 'max_value': '384000.0', 'min_value': '195000.0'}     1
Name: count, Length: 72, dtype: int64

In [59]:
target = 'Job Post Range (Canada)'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

{'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}              139
{'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}               69
{'unit': 'INR', 'max_value': '0.0', 'min_value': '0.0'}               41
{'unit': None, 'max_value': '0.0', 'min_value': '0.0'}                38
{'unit': 'AUD', 'max_value': '0.0', 'min_value': '0.0'}               10
{'unit': 'SGD', 'max_value': '0.0', 'min_value': '0.0'}                9
{'unit': 'CAD', 'max_value': '200000.0', 'min_value': '144000.0'}      9
None                                                                   8
{'unit': 'GBP', 'max_value': '0.0', 'min_value': '0.0'}                6
{'unit': 'BRL', 'max_value': '0.0', 'min_value': '0.0'}                6
{'unit': 'MXN', 'max_value': '0.0', 'min_value': '0.0'}                5
{'unit': 'MYR', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'KRW', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'ILS', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'CAD', 'max_value': '170000.0', 'min_value': '122000.0'}      3
{'unit': 'CAD', 'max_value': '149000.0', 'min_value': '108000.0'}      3
{'unit': 'CAD', 'max_value': '240000.0', 'min_value': '173000.0'}      3
{'unit': 'CAD', 'max_value': '221000.0', 'min_value': '159000.0'}      2
{'unit': 'CAD', 'max_value': '290000.0', 'min_value': '209000.0'}      2
{'unit': 'CAD', 'max_value': '170000.0', 'min_value': '170000.0'}      2
{'unit': 'CAD', 'max_value': '90300.0', 'min_value': '90300.0'}        2
{'unit': 'CAD', 'max_value': '178000.0', 'min_value': '129000.0'}      2
{'unit': 'CAD', 'max_value': '180000.0', 'min_value': '130000.0'}      2
{'unit': 'TWD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'PLN', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'SEK', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'HKD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'CAD', 'max_value': '148000.0', 'min_value': '107000.0'}      1
{'unit': 'CAD', 'max_value': '90000.0', 'min_value': '90000.0'}        1
{'unit': 'CAD', 'max_value': '167000.0', 'min_value': '121000.0'}      1
{'unit': 'CAD', 'max_value': '160000.0', 'min_value': '115000.0'}      1
Name: count, dtype: int64

In [60]:
target = 'Job Post Range (Italy)'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

None                                                                 378
{'unit': None, 'max_value': '0.0', 'min_value': '0.0'}                 2
{'unit': 'EUR', 'max_value': '115000.0', 'min_value': '115000.0'}      1
Name: count, dtype: int64

In [61]:
target = 'Job Post Range (Poland)'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

None                                                                 378
{'unit': 'PLN', 'max_value': '400000.0', 'min_value': '400000.0'}      1
{'unit': 'PLN', 'max_value': '426000.0', 'min_value': '287000.0'}      1
{'unit': 'PLN', 'max_value': '348000.0', 'min_value': '235000.0'}      1
Name: count, dtype: int64

In [62]:
target = 'Other Large Market Budgeted Salary'

values = []

for value in df['metadata'].dropna():
    try:
        items = ast.literal_eval(value)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                values.append(item.get('value'))

    except (ValueError, SyntaxError):
        pass

pd.Series(values).value_counts(dropna=False)

None                                                                 251
{'unit': 'EUR', 'max_value': '0.0', 'min_value': '0.0'}               30
{'unit': 'INR', 'max_value': '0.0', 'min_value': '0.0'}               13
{'unit': 'USD', 'max_value': '192000.0', 'min_value': '134000.0'}      8
{'unit': 'USD', 'max_value': '230000.0', 'min_value': '161000.0'}      7
{'unit': 'SGD', 'max_value': '0.0', 'min_value': '0.0'}                5
{'unit': 'CAD', 'max_value': '0.0', 'min_value': '0.0'}                5
{'unit': 'GBP', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'BRL', 'max_value': '0.0', 'min_value': '0.0'}                4
{'unit': 'USD', 'max_value': '153000.0', 'min_value': '107000.0'}      4
{'unit': 'USD', 'max_value': '136000.0', 'min_value': '95000.0'}       3
{'unit': 'USD', 'max_value': '191000.0', 'min_value': '134000.0'}      3
{'unit': 'MYR', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'AUD', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'ILS', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'KRW', 'max_value': '0.0', 'min_value': '0.0'}                3
{'unit': 'USD', 'max_value': '208000.0', 'min_value': '146000.0'}      2
{'unit': 'USD', 'max_value': '111000.0', 'min_value': '78000.0'}       2
{'unit': 'MXN', 'max_value': '0.0', 'min_value': '0.0'}                2
{'unit': 'USD', 'max_value': '162000.0', 'min_value': '113000.0'}      2
{'unit': 'USD', 'max_value': '213000.0', 'min_value': '149000.0'}      2
{'unit': 'USD', 'max_value': '66560.0', 'min_value': '66560.0'}        2
{'unit': 'PLN', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'SEK', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '123000.0', 'min_value': '86000.0'}       1
{'unit': 'USD', 'max_value': '157000.0', 'min_value': '110000.0'}      1
{'unit': 'USD', 'max_value': '160000.0', 'min_value': '160000.0'}      1
{'unit': 'HKD', 'max_value': '0.0', 'min_value': '0.0'}                1
{'unit': 'USD', 'max_value': '196000.0', 'min_value': '137000.0'}      1
{'unit': 'USD', 'max_value': '147000.0', 'min_value': '103000.0'}      1
{'unit': 'USD', 'max_value': '128000.0', 'min_value': '90000.0'}       1
{'unit': 'USD', 'max_value': '102000.0', 'min_value': '71000.0'}       1
{'unit': 'USD', 'max_value': '159000.0', 'min_value': '111000.0'}      1
{'unit': 'USD', 'max_value': '180000.0', 'min_value': '180000.0'}      1
{'unit': 'USD', 'max_value': '309000.0', 'min_value': '216000.0'}      1
{'unit': 'USD', 'max_value': '50003.2', 'min_value': '50003.2'}        1
{'unit': 'USD', 'max_value': '148500.0', 'min_value': '148500.0'}      1
{'unit': 'USD', 'max_value': '203000.0', 'min_value': '162400.0'}      1
{'unit': 'USD', 'max_value': '135000.0', 'min_value': '135000.0'}      1
{'unit': 'USD', 'max_value': '98000.0', 'min_value': '69000.0'}        1
{'unit': 'TWD', 'max_value': '0.0', 'min_value': '0.0'}                1
Name: count, dtype: int64

In [63]:
def get_metadata_value(metadata, target):
    try:
        items = ast.literal_eval(metadata)

        for item in items:
            if isinstance(item, dict) and item.get('name') == target:
                return item.get('value')

    except (ValueError, SyntaxError, TypeError):
        return None

    return None

In [64]:
df['job_level'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Job Level')
)

In [65]:
df['job_type'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Job Type')
)

In [66]:
df['region'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Region')
)

In [67]:
df['working_model'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Working Model Eligibility')
)

In [68]:
df['ic_or_mg'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'IC or MG')
)

In [69]:
df['baseline_salary'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Baseline Budgeted Salary')
)

In [70]:
df['other_market_salary'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Other Large Market Budgeted Salary')
)

In [71]:
df.head()

,absolute_url,data_compliance,internal_job_id,location,metadata,id,updated_at,requisition_id,title,company_name,...,ai_opt_out_request_url,education,company_board,job_level,job_type,region,working_model,ic_or_mg,baseline_salary,other_market_salary
0,https://stripe.com/jobs/search?gh_jid=7954688,"[{'type': 'gdpr', 'requires_consent': False, '...",3453698.0,"{'name': 'San Francisco, CA'}",NaN,7954688,2026-07-13 18:37:36+00:00,See Opening ID,"Account Executive, AI Sales (Grower)",Stripe,...,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier,None,None,None,None,None,None,None
1,https://stripe.com/jobs/search?gh_jid=8042978,"[{'type': 'gdpr', 'requires_consent': False, '...",3486109.0,{'name': 'Japan'},NaN,8042978,2026-07-03 01:13:43+00:00,See Opening ID,"Account Executive, Commercial Grower (Japanese...",Stripe,...,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier,None,None,None,None,None,None,None
2,https://stripe.com/jobs/search?gh_jid=7789539,"[{'type': 'gdpr', 'requires_consent': False, '...",3407094.0,{'name': 'Japan'},NaN,7789539,2026-07-03 01:14:52+00:00,See Opening ID,"Account Executive, Commercial Hunter (Japanese...",Stripe,...,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier,None,None,None,None,None,None,None
3,https://stripe.com/jobs/search?gh_jid=7893199,"[{'type': 'gdpr', 'requires_consent': False, '...",3431456.0,{'name': 'Singapore'},NaN,7893199,2026-06-26 21:05:39+00:00,See Opening ID,"Account Executive, Cross Border China",Stripe,...,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier,None,None,None,None,None,None,None
4,https://stripe.com/jobs/search?gh_jid=7993151,"[{'type': 'gdpr', 'requires_consent': False, '...",3467410.0,"{'name': 'US-Remote, US-San Francisco, US-Chic...",NaN,7993151,2026-07-01 14:19:50+00:00,See Opening ID,"Account Executive - Enterprise, Grower",Stripe,...,http://app.greenhouse.io/ai_opt_out_request/jo...,NaN,zapier,None,None,None,None,None,None,None

In [72]:
df[['job_level', 'job_type', 'region', 'working_model', 'ic_or_mg']].head()

  job_level job_type region working_model ic_or_mg
0      None     None   None          None     None
1      None     None   None          None     None
2      None     None   None          None     None
3      None     None   None          None     None
4      None     None   None          None     None

In [73]:
df[['job_level', 'job_type', 'region', 'working_model', 'ic_or_mg']].notna().sum()

job_level        381
job_type         381
region           381
working_model    381
ic_or_mg         421
dtype: int64

In [74]:
df[df['job_level'].notna()][
    ['title', 'company_name', 'job_level', 'job_type', 'region', 'working_model', 'ic_or_mg']
].head(10)

,title,company_name,job_level,job_type,region,working_model,ic_or_mg
693,Account Development Representative,MongoDB,IC - Professional,Pipeline,North America,[2-Flexible],None
694,Account Development Representative,MongoDB,IC - Professional,Pipeline,North America,[2-Flexible],None
695,"Account Development Representative, Arabic Spe...",MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
696,Account Development Representative - English S...,MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
697,"Account Development Representative, French Spe...",MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
698,"Account Development Representative, German Spe...",MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
699,"Account Development Representative, Hebrew Spe...",MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
700,"Account Development Representative, Spanish Sp...",MongoDB,IC - Professional,Pipeline,EMEA,[2-Flexible],None
701,"Account Executive, Acquisition",MongoDB,IC - Professional,Pipeline,APAC,"[1-In Office, 2-Flexible]",None
702,"Account Executive, Acquisition/Growth",MongoDB,IC - Professional,Pipeline,APAC,[2-Flexible],None

In [75]:
df['baseline_salary'].notna().sum()

153

In [76]:
df['baseline_salary'].head()

0    None
1    None
2    None
3    None
4    None
Name: baseline_salary, dtype: object

In [77]:
df[df['baseline_salary'].notna()][
    ['title', 'company_name', 'baseline_salary']
].head(10)

,title,company_name,baseline_salary
693,Account Development Representative,MongoDB,"{'unit': 'USD', 'max_value': '50003.2', 'min_v..."
707,Advisory Solutions Architect,MongoDB,"{'unit': 'MXN', 'max_value': '0.0', 'min_value..."
709,"Associate, HR Shared Services",MongoDB,"{'unit': 'INR', 'max_value': '0.0', 'min_value..."
710,"Associate Recruiter, Early Talent",MongoDB,"{'unit': 'USD', 'max_value': '85000.0', 'min_v..."
711,"Associate Recruiter, Early Talent",MongoDB,"{'unit': 'USD', 'max_value': '85000.0', 'min_v..."
715,Chief of Staff - Marketing,MongoDB,"{'unit': 'USD', 'max_value': '230000.0', 'min_..."
717,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
718,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
719,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
723,Customer Success Manager,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."

In [78]:
df['baseline_salary_currency'] = df['baseline_salary'].apply(
    lambda x: x.get('unit') if isinstance(x, dict) else None
)

In [79]:
df['baseline_salary_min'] = df['baseline_salary'].apply(
    lambda x: x.get('min_value') if isinstance(x, dict) else None
)

In [80]:
df['baseline_salary_max'] = df['baseline_salary'].apply(
    lambda x: x.get('max_value') if isinstance(x, dict) else None
)

In [81]:
df[df['baseline_salary'].notna()][
    ['title', 'company_name',
     'baseline_salary_currency',
     'baseline_salary_min',
     'baseline_salary_max']
].head(10)

,title,company_name,baseline_salary_currency,baseline_salary_min,baseline_salary_max
693,Account Development Representative,MongoDB,USD,50003.2,50003.2
707,Advisory Solutions Architect,MongoDB,MXN,0.0,0.0
709,"Associate, HR Shared Services",MongoDB,INR,0.0,0.0
710,"Associate Recruiter, Early Talent",MongoDB,USD,59000.0,85000.0
711,"Associate Recruiter, Early Talent",MongoDB,USD,59000.0,85000.0
715,Chief of Staff - Marketing,MongoDB,USD,161000.0,230000.0
717,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
718,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
719,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
723,Customer Success Manager,MongoDB,EUR,0.0,0.0

In [82]:
df[['baseline_salary_currency',
    'baseline_salary_min',
    'baseline_salary_max']].dtypes

baseline_salary_currency    object
baseline_salary_min         object
baseline_salary_max         object
dtype: object

In [83]:
df['baseline_salary_min'] = pd.to_numeric(df['baseline_salary_min'], errors='coerce')

In [84]:
df['baseline_salary_max'] = pd.to_numeric(df['baseline_salary_max'], errors='coerce')

In [85]:
df[['baseline_salary_min', 'baseline_salary_max']].dtypes

baseline_salary_min    float64
baseline_salary_max    float64
dtype: object

In [86]:
df['baseline_salary_min'].eq(0).sum()

79

In [87]:
df['baseline_salary_max'].eq(0).sum()

79

In [88]:
df.loc[
    df['baseline_salary_min'].eq(0),
    ['title', 'company_name',
     'baseline_salary_currency',
     'baseline_salary_min',
     'baseline_salary_max']
].head(20)

,title,company_name,baseline_salary_currency,baseline_salary_min,baseline_salary_max
707,Advisory Solutions Architect,MongoDB,MXN,0.0,0.0
709,"Associate, HR Shared Services",MongoDB,INR,0.0,0.0
717,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
718,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
719,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
723,Customer Success Manager,MongoDB,EUR,0.0,0.0
725,Customer Success Manager,MongoDB,ILS,0.0,0.0
727,"Director, Credit & Accounts Receivable",MongoDB,EUR,0.0,0.0
729,"Director, Global Quote-to-Cash Operations (Ind...",MongoDB,INR,0.0,0.0
734,"Director, Web Platform & Technology",MongoDB,EUR,0.0,0.0
735,Enablement Delivery Specialist,MongoDB,SGD,0.0,0.0
737,Engagement Manager,MongoDB,KRW,0.0,0.0
740,Engagement Manager (Services Sales),MongoDB,EUR,0.0,0.0
743,"Engineering Manager, Atlas Clusters Fleet Sign...",MongoDB,EUR,0.0,0.0
781,"Enterprise Account Executive, Growth",MongoDB,KRW,0.0,0.0
785,"Enterprise Account Executive, Growth (Defence ...",MongoDB,INR,0.0,0.0
790,Equity and Executive Compensation Director,MongoDB,CAD,0.0,0.0
805,"Lead Engineer, Internal Engineering",MongoDB,INR,0.0,0.0
806,"Lead, Revenue",MongoDB,INR,0.0,0.0
810,"Manager, Customer Success",MongoDB,KRW,0.0,0.0

In [89]:
df.loc[df['baseline_salary_min'].eq(0), 'baseline_salary_currency'].value_counts(dropna=False)

baseline_salary_currency
EUR    30
INR    13
SGD     5
CAD     5
BRL     4
GBP     4
ILS     3
KRW     3
AUD     3
MYR     3
MXN     2
TWD     1
HKD     1
SEK     1
PLN     1
Name: count, dtype: int64

In [90]:
df.loc[df['baseline_salary_min'] == 0, 'baseline_salary_min'] = pd.NA
df.loc[df['baseline_salary_max'] == 0, 'baseline_salary_max'] = pd.NA

In [91]:
df['baseline_salary_min'].isna().sum()

2231

In [92]:
df['baseline_salary_max'].isna().sum()

2231

In [93]:
df[['baseline_salary_currency',
    'baseline_salary_min',
    'baseline_salary_max']].notna().sum()

baseline_salary_currency    153
baseline_salary_min          74
baseline_salary_max          74
dtype: int64

In [94]:
df['other_market_salary'].notna().sum()

130

In [95]:
df['other_market_salary'].dropna().apply(type).value_counts()

other_market_salary
<class 'dict'>    130
Name: count, dtype: int64

In [96]:
df[df['other_market_salary'].notna()][
    ['title', 'company_name', 'other_market_salary']
].head(10)

,title,company_name,other_market_salary
694,Account Development Representative,MongoDB,"{'unit': 'USD', 'max_value': '50003.2', 'min_v..."
707,Advisory Solutions Architect,MongoDB,"{'unit': 'MXN', 'max_value': '0.0', 'min_value..."
709,"Associate, HR Shared Services",MongoDB,"{'unit': 'INR', 'max_value': '0.0', 'min_value..."
717,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
718,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
719,Cloud Operations Engineer,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
723,Customer Success Manager,MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
725,Customer Success Manager,MongoDB,"{'unit': 'ILS', 'max_value': '0.0', 'min_value..."
727,"Director, Credit & Accounts Receivable",MongoDB,"{'unit': 'EUR', 'max_value': '0.0', 'min_value..."
729,"Director, Global Quote-to-Cash Operations (Ind...",MongoDB,"{'unit': 'INR', 'max_value': '0.0', 'min_value..."

In [97]:
df['other_market_salary_currency']=df['other_market_salary'].apply(
    lambda x: x.get('unit') if isinstance(x,dict) else None
)

In [98]:
df['other_market_salary_max']=df['other_market_salary'].apply(
    lambda x: x.get('max_value') if isinstance(x,dict) else None
)

In [99]:
df['other_market_salary_min']=df['other_market_salary'].apply(
    lambda x: x.get('min_value') if isinstance(x,dict) else None
)

In [100]:
df[['other_market_salary_currency',
    'other_market_salary_min',
    'other_market_salary_max']].head(10)

  other_market_salary_currency other_market_salary_min other_market_salary_max
0                         None                    None                    None
1                         None                    None                    None
2                         None                    None                    None
3                         None                    None                    None
4                         None                    None                    None
5                         None                    None                    None
6                         None                    None                    None
7                         None                    None                    None
8                         None                    None                    None
9                         None                    None                    None

In [101]:
df[df['other_market_salary'].notna()][
    ['title', 'company_name',
     'other_market_salary_currency',
     'other_market_salary_min',
     'other_market_salary_max']
].head(10)

,title,company_name,other_market_salary_currency,other_market_salary_min,other_market_salary_max
694,Account Development Representative,MongoDB,USD,50003.2,50003.2
707,Advisory Solutions Architect,MongoDB,MXN,0.0,0.0
709,"Associate, HR Shared Services",MongoDB,INR,0.0,0.0
717,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
718,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
719,Cloud Operations Engineer,MongoDB,EUR,0.0,0.0
723,Customer Success Manager,MongoDB,EUR,0.0,0.0
725,Customer Success Manager,MongoDB,ILS,0.0,0.0
727,"Director, Credit & Accounts Receivable",MongoDB,EUR,0.0,0.0
729,"Director, Global Quote-to-Cash Operations (Ind...",MongoDB,INR,0.0,0.0

In [102]:
df[['other_market_salary_currency',
    'other_market_salary_min',
    'other_market_salary_max']].dtypes

other_market_salary_currency    object
other_market_salary_min         object
other_market_salary_max         object
dtype: object

In [103]:
df['other_market_salary_min']=pd.to_numeric(df['other_market_salary_min'],errors='coerce')

In [104]:
df['other_market_salary_max']=pd.to_numeric(df['other_market_salary_min'],errors='coerce')

In [105]:
df[['other_market_salary_currency',
    'other_market_salary_min',
    'other_market_salary_max']].dtypes

other_market_salary_currency     object
other_market_salary_min         float64
other_market_salary_max         float64
dtype: object

In [106]:
(df['other_market_salary_min']==0).sum()

80

In [107]:
(df['other_market_salary_max']==0).sum()

80

In [108]:
df.loc[
    df['other_market_salary_min'] == 0,
    'other_market_salary_currency'
].value_counts()

other_market_salary_currency
EUR    30
INR    13
SGD     5
CAD     5
BRL     4
GBP     4
ILS     3
KRW     3
AUD     3
MYR     3
MXN     2
TWD     1
HKD     1
USD     1
SEK     1
PLN     1
Name: count, dtype: int64

In [109]:
df.loc[df['other_market_salary_min']== 0,'other_market_salary_min']=pd.NA

In [110]:
df.loc[df['other_market_salary_max']==0,'other_market_salary_max']=pd.NA

In [111]:
df[['other_market_salary_min',
    'other_market_salary_max']].isna().sum()

other_market_salary_min    2255
other_market_salary_max    2255
dtype: int64

In [112]:
df.loc[
    df['other_market_salary_min'].notna(),
    ['title',
     'company_name',
     'other_market_salary_currency',
     'other_market_salary_min',
     'other_market_salary_max']
].head(20)

,title,company_name,other_market_salary_currency,other_market_salary_min,other_market_salary_max
694,Account Development Representative,MongoDB,USD,50003.2,50003.2
739,Engagement Manager (Services Sales),MongoDB,USD,111000.0,111000.0
762,"Enterprise Account Executive, Federal",MongoDB,USD,148500.0,148500.0
770,"Enterprise Account Executive, Growth",MongoDB,USD,135000.0,135000.0
792,Global Payroll Transformation Senior Manager,MongoDB,USD,107000.0,107000.0
793,Growth Marketing Manager,MongoDB,USD,90000.0,90000.0
798,International Tax Director,MongoDB,USD,137000.0,137000.0
799,International Tax Manager,MongoDB,USD,95000.0,95000.0
807,"Lead, Startup & Ventures Marketing",MongoDB,USD,107000.0,107000.0
808,"Manager, Candidate Experience",MongoDB,USD,78000.0,78000.0
809,"Manager, Candidate Experience",MongoDB,USD,78000.0,78000.0
821,Payroll Tax Analyst,MongoDB,USD,69000.0,69000.0
824,"Principal Business Development Manager, Fronti...",MongoDB,USD,162400.0,162400.0
832,"Principal Research Scientist, Database Systems",MongoDB,USD,216000.0,216000.0
842,"Regional Director, Enterprise, Growth",MongoDB,USD,180000.0,180000.0
846,Renewals Specialist,MongoDB,USD,66560.0,66560.0
847,Renewals Specialist,MongoDB,USD,66560.0,66560.0
857,"Security Software Engineer, Infrastructure Sec...",MongoDB,USD,134000.0,134000.0
858,"Security Software Engineer, Infrastructure Sec...",MongoDB,USD,134000.0,134000.0
859,"Senior Accountant, Technical Revenue",MongoDB,USD,71000.0,71000.0

In [113]:
df.loc[
    df['other_market_salary_min'].notna(),
    'other_market_salary_currency'
].value_counts()

other_market_salary_currency
USD    50
Name: count, dtype: int64

In [114]:
df.columns

Index(['absolute_url', 'data_compliance', 'internal_job_id', 'location',
       'metadata', 'id', 'updated_at', 'requisition_id', 'title',
       'company_name', 'first_published', 'language', 'application_deadline',
       'content', 'departments', 'offices', 'ai_disclaimer',
       'include_ai_disclaimer', 'ai_opt_out_request_url', 'education',
       'company_board', 'job_level', 'job_type', 'region', 'working_model',
       'ic_or_mg', 'baseline_salary', 'other_market_salary',
       'baseline_salary_currency', 'baseline_salary_min',
       'baseline_salary_max', 'other_market_salary_currency',
       'other_market_salary_max', 'other_market_salary_min'],
      dtype='object')

In [115]:
df['pay_transparency'] = df['metadata'].apply(
    lambda x: get_metadata_value(x, 'Pay Transparency Range')
)

In [116]:
df['pay_transparency'].notna().sum()

198

In [117]:
df['pay_transparency'].dropna().apply(type).value_counts()

pay_transparency
<class 'dict'>    198
Name: count, dtype: int64

In [118]:
df[df['pay_transparency'].notna()].head()

,absolute_url,data_compliance,internal_job_id,location,metadata,id,updated_at,requisition_id,title,company_name,...,ic_or_mg,baseline_salary,other_market_salary,baseline_salary_currency,baseline_salary_min,baseline_salary_max,other_market_salary_currency,other_market_salary_max,other_market_salary_min,pay_transparency
1075,https://careers.datadoghq.com/detail/6572669/?...,"[{'type': 'gdpr', 'requires_consent': False, '...",3056731.0,"{'name': 'New York, New York, USA'}","[{'id': 33310, 'name': 'Time Type', 'value': '...",6572669,2026-07-07 17:56:06+00:00,R12181,AI Research Scientist - Datadog AI Research (D...,Datadog,...,IC,None,None,None,NaN,NaN,None,NaN,NaN,"{'unit': 'USD', 'max_value': '400000.0', 'min_..."
1077,https://careers.datadoghq.com/detail/8003021/?...,"[{'type': 'gdpr', 'requires_consent': False, '...",3470058.0,"{'name': 'New York, New York, USA; San Francis...","[{'id': 33310, 'name': 'Time Type', 'value': '...",8003021,2026-07-10 16:33:52+00:00,R19500,Analyst Relations Manager,Datadog,...,IC,None,None,None,NaN,NaN,None,NaN,NaN,"{'unit': 'USD', 'max_value': '125000.0', 'min_..."
1078,https://careers.datadoghq.com/detail/7508990/?...,"[{'type': 'gdpr', 'requires_consent': False, '...",3328438.0,"{'name': 'New York, New York, USA; San Francis...","[{'id': 33310, 'name': 'Time Type', 'value': '...",7508990,2026-05-15 12:44:57+00:00,R17209,"Area Vice President, Enterprise Security Sales",Datadog,...,MG,None,None,None,NaN,NaN,None,NaN,NaN,"{'unit': 'USD', 'max_value': '275000.0', 'min_..."
1079,https://careers.datadoghq.com/detail/7762722/?...,"[{'type': 'gdpr', 'requires_consent': False, '...",3400647.0,"{'name': 'Boston, Massachusetts, USA; New York...","[{'id': 33310, 'name': 'Time Type', 'value': '...",7762722,2026-07-07 19:57:12+00:00,R18533,"Area Vice President, Sales Engineering",Datadog,...,MG,None,None,None,NaN,NaN,None,NaN,NaN,"{'unit': 'USD', 'max_value': '349000.0', 'min_..."
1081,https://careers.datadoghq.com/detail/7899542/?...,"[{'type': 'gdpr', 'requires_consent': False, '...",3434343.0,"{'name': 'Denver, Colorado, USA'}","[{'id': 33310, 'name': 'Time Type', 'value': '...",7899542,2026-07-07 20:01:36+00:00,R19030,Billing Operations Analyst,Datadog,...,IC,None,None,None,NaN,NaN,None,NaN,NaN,"{'unit': 'USD', 'max_value': '94000.0', 'min_v..."

In [119]:
df['pay_transparency_unit']=df['pay_transparency'].apply(
    lambda x: x.get('unit') if isinstance(x,dict) else None
)

In [120]:
df['pay_transparency_max']=df['pay_transparency'].apply(
    lambda x: x.get('max_value') if isinstance(x,dict) else None
)

In [121]:
df['pay_transparency_min']=df['pay_transparency'].apply(
    lambda x: x.get('min_value') if isinstance(x,dict) else None
)

In [122]:
(df['pay_transparency_unit'].notna()).sum()

198

In [123]:
(df['pay_transparency_min'].notna()).sum()

198

In [124]:
(df['pay_transparency_max'].notna()).sum()

198

In [125]:
df.loc[df['pay_transparency_min'].notna(),
                ['title','company_name','pay_transparency_min']].head(20)

,title,company_name,pay_transparency_min
1075,AI Research Scientist - Datadog AI Research (D...,Datadog,320000.0
1077,Analyst Relations Manager,Datadog,94000.0
1078,"Area Vice President, Enterprise Security Sales",Datadog,210000.0
1079,"Area Vice President, Sales Engineering",Datadog,238000.0
1081,Billing Operations Analyst,Datadog,64000.0
1085,Commercial Account Executive,Datadog,51000.0
1089,Commercial Account Executive - Boston,Datadog,51000.0
1094,Commercial Account Executive - LATAM (Portugue...,Datadog,51000.0
1095,Commercial Account Executive - LATAM (Spanish ...,Datadog,51000.0
1101,Commercial Sales Engineer (AMER - West),Datadog,92000.0
1102,Commercial Sales Engineer - Boston,Datadog,80000.0
1104,"Coordinator, Business Recruiting - Contract",Datadog,49000.0
1106,Customer Marketing Manager,Datadog,94000.0
1110,Customer Success Associate - Boston,Datadog,54000.0
1112,Customer Success Associate - Denver,Datadog,68000.0
1116,Customer Success Manager - Boston,Datadog,89000.0
1117,Customer Success Manager - Denver,Datadog,89000.0
1121,Datadog for Startups - Forward Deployed Engine...,Datadog,192000.0
1122,Datadog for Startups Founding Engineering Lead,Datadog,192000.0
1125,Deal Desk Analyst - Boston (Portuguese or Span...,Datadog,68000.0

In [126]:
df.loc[df['pay_transparency_max'].notna(),
                ['title','company_name','pay_transparency_max']].head(20)

,title,company_name,pay_transparency_max
1075,AI Research Scientist - Datadog AI Research (D...,Datadog,400000.0
1077,Analyst Relations Manager,Datadog,125000.0
1078,"Area Vice President, Enterprise Security Sales",Datadog,275000.0
1079,"Area Vice President, Sales Engineering",Datadog,349000.0
1081,Billing Operations Analyst,Datadog,94000.0
1085,Commercial Account Executive,Datadog,70000.0
1089,Commercial Account Executive - Boston,Datadog,70000.0
1094,Commercial Account Executive - LATAM (Portugue...,Datadog,70000.0
1095,Commercial Account Executive - LATAM (Spanish ...,Datadog,70000.0
1101,Commercial Sales Engineer (AMER - West),Datadog,134000.0
1102,Commercial Sales Engineer - Boston,Datadog,117000.0
1104,"Coordinator, Business Recruiting - Contract",Datadog,72000.0
1106,Customer Marketing Manager,Datadog,125000.0
1110,Customer Success Associate - Boston,Datadog,79000.0
1112,Customer Success Associate - Denver,Datadog,99000.0
1116,Customer Success Manager - Boston,Datadog,130000.0
1117,Customer Success Manager - Denver,Datadog,130000.0
1121,Datadog for Startups - Forward Deployed Engine...,Datadog,240000.0
1122,Datadog for Startups Founding Engineering Lead,Datadog,240000.0
1125,Deal Desk Analyst - Boston (Portuguese or Span...,Datadog,95000.0

In [127]:
df['pay_transparency_min'].value_counts(dropna=True)

pay_transparency_min
192000.0    31
110000.0    11
244000.0     9
113000.0     8
90000.0      6
            ..
82000.0      1
201000.0     1
142500.0     1
170000.0     1
96000.0      1
Name: count, Length: 73, dtype: int64

In [128]:
df[['pay_transparency_min','pay_transparency_max']].dtypes

pay_transparency_min    object
pay_transparency_max    object
dtype: object

In [129]:
df['pay_transparency_min']=pd.to_numeric(df['pay_transparency_min'],errors='coerce')

In [130]:
df['pay_transparency_max']=pd.to_numeric(df['pay_transparency_max'],errors='coerce')

In [131]:
df[['pay_transparency_min',
    'pay_transparency_max']].isna().sum()

pay_transparency_min    2107
pay_transparency_max    2107
dtype: int64

In [132]:
(df['pay_transparency_min']==0).sum()

2

In [133]:
(df['pay_transparency_max']==0).sum()

2

In [134]:
df.loc[
    df['pay_transparency_min'] == 0,
    ['title',
     'company_name',
     'pay_transparency_unit',
     'pay_transparency_min',
     'pay_transparency_max']
]

,title,company_name,pay_transparency_unit,pay_transparency_min,pay_transparency_max
1203,HRIS Manager,Datadog,USD,0.0,0.0
1429,Staff Software Engineer - ML Observability,Datadog,CAD,0.0,0.0

In [135]:
df.loc[
    df['pay_transparency_max'] == 0,
    ['title',
     'company_name',
     'pay_transparency_unit',
     'pay_transparency_min',
     'pay_transparency_max']
]

,title,company_name,pay_transparency_unit,pay_transparency_min,pay_transparency_max
1203,HRIS Manager,Datadog,USD,0.0,0.0
1429,Staff Software Engineer - ML Observability,Datadog,CAD,0.0,0.0

In [136]:
df.loc[
    df['pay_transparency_min'] == 0,
    'pay_transparency_min'
] = pd.NA

In [137]:
df.loc[
    df['pay_transparency_max'] == 0,
    'pay_transparency_max'
] = pd.NA

In [138]:
df['working_model'].value_counts(dropna=False)

working_model
None                                         1924
[2-Flexible]                                  294
[1-In Office]                                  36
[3CF-Customer Facing Remote]                   19
[1-In Office, 2-Flexible, 3-Fully Remote]      15
[3-Fully Remote]                               12
[1-In Office, 2-Flexible]                       4
[2-Flexible, 3CF-Customer Facing Remote]        1
Name: count, dtype: int64

In [139]:
df['working_model'].dropna().apply(type).value_counts()

working_model
<class 'list'>    381
Name: count, dtype: int64

In [140]:
df['working_model'].dropna().map(str).value_counts()

working_model
['2-Flexible']                                     294
['1-In Office']                                     36
['3CF-Customer Facing Remote']                      19
['1-In Office', '2-Flexible', '3-Fully Remote']     15
['3-Fully Remote']                                  12
['1-In Office', '2-Flexible']                        4
['2-Flexible', '3CF-Customer Facing Remote']         1
Name: count, dtype: int64

In [141]:
from itertools import chain
working_model_values=list(chain.from_iterable(df['working_model'].dropna()))
pd.Series(working_model_values).value_counts()

2-Flexible                    314
1-In Office                    55
3-Fully Remote                 27
3CF-Customer Facing Remote     20
Name: count, dtype: int64

In [142]:
df.loc[df['working_model'].notna(), 'working_model'].iloc[300]

['2-Flexible']

In [143]:
df.loc[df['working_model'].apply(lambda x: isinstance(x,list) and len(x)>1),'working_model']

701                     [1-In Office, 2-Flexible]
703                     [1-In Office, 2-Flexible]
838     [1-In Office, 2-Flexible, 3-Fully Remote]
857     [1-In Office, 2-Flexible, 3-Fully Remote]
858     [1-In Office, 2-Flexible, 3-Fully Remote]
937     [1-In Office, 2-Flexible, 3-Fully Remote]
951                     [1-In Office, 2-Flexible]
961                     [1-In Office, 2-Flexible]
967      [2-Flexible, 3CF-Customer Facing Remote]
986     [1-In Office, 2-Flexible, 3-Fully Remote]
987     [1-In Office, 2-Flexible, 3-Fully Remote]
988     [1-In Office, 2-Flexible, 3-Fully Remote]
989     [1-In Office, 2-Flexible, 3-Fully Remote]
1015    [1-In Office, 2-Flexible, 3-Fully Remote]
1016    [1-In Office, 2-Flexible, 3-Fully Remote]
1040    [1-In Office, 2-Flexible, 3-Fully Remote]
1041    [1-In Office, 2-Flexible, 3-Fully Remote]
1047    [1-In Office, 2-Flexible, 3-Fully Remote]
1048    [1-In Office, 2-Flexible, 3-Fully Remote]
1073    [1-In Office, 2-Flexible, 3-Fully Remote]
Name: working_model, dtype: object

In [144]:
def clean_working_model(x):
    if not isinstance(x, list):
        return None

    mapping = {
        '1-In Office': 'In Office',
        '2-Flexible': 'Flexible',
        '3-Fully Remote': 'Fully Remote',
        '3CF-Customer Facing Remote': 'Customer Facing Remote'
    }

    return ', '.join(mapping.get(item, item) for item in x)

In [145]:
df['working_model_clean'] = df['working_model'].apply(
    clean_working_model
)

In [146]:
df[['working_model', 'working_model_clean']].dropna().head(20)

                 working_model  working_model_clean
693               [2-Flexible]             Flexible
694               [2-Flexible]             Flexible
695               [2-Flexible]             Flexible
696               [2-Flexible]             Flexible
697               [2-Flexible]             Flexible
698               [2-Flexible]             Flexible
699               [2-Flexible]             Flexible
700               [2-Flexible]             Flexible
701  [1-In Office, 2-Flexible]  In Office, Flexible
702               [2-Flexible]             Flexible
703  [1-In Office, 2-Flexible]  In Office, Flexible
704               [2-Flexible]             Flexible
705               [2-Flexible]             Flexible
706               [2-Flexible]             Flexible
707               [2-Flexible]             Flexible
708               [2-Flexible]             Flexible
709              [1-In Office]            In Office
710               [2-Flexible]             Flexible
711               [2-Flexible]             Flexible
712              [1-In Office]            In Office

In [147]:
df['working_model_clean'].value_counts(dropna=False)

working_model_clean
None                                 1924
Flexible                              294
In Office                              36
Customer Facing Remote                 19
In Office, Flexible, Fully Remote      15
Fully Remote                           12
In Office, Flexible                     4
Flexible, Customer Facing Remote        1
Name: count, dtype: int64

In [148]:
df['ic_or_mg'].value_counts(dropna=False )

ic_or_mg
None    1884
IC       346
MG        75
Name: count, dtype: int64

In [149]:
df[['job_level', 'job_type', 'region', 
    'working_model_clean', 'ic_or_mg']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2305 entries, 0 to 2304
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_level            381 non-null    object
 1   job_type             381 non-null    object
 2   region               381 non-null    object
 3   working_model_clean  381 non-null    object
 4   ic_or_mg             421 non-null    object
dtypes: object(5)
memory usage: 90.2+ KB

In [150]:
df[['job_level', 'job_type', 'region',
    'working_model_clean', 'ic_or_mg']].isna().sum()

job_level              1924
job_type               1924
region                 1924
working_model_clean    1924
ic_or_mg               1884
dtype: int64

In [151]:
df.columns

Index(['absolute_url', 'data_compliance', 'internal_job_id', 'location',
       'metadata', 'id', 'updated_at', 'requisition_id', 'title',
       'company_name', 'first_published', 'language', 'application_deadline',
       'content', 'departments', 'offices', 'ai_disclaimer',
       'include_ai_disclaimer', 'ai_opt_out_request_url', 'education',
       'company_board', 'job_level', 'job_type', 'region', 'working_model',
       'ic_or_mg', 'baseline_salary', 'other_market_salary',
       'baseline_salary_currency', 'baseline_salary_min',
       'baseline_salary_max', 'other_market_salary_currency',
       'other_market_salary_max', 'other_market_salary_min',
       'pay_transparency', 'pay_transparency_unit', 'pay_transparency_max',
       'pay_transparency_min', 'working_model_clean'],
      dtype='object')

In [152]:
df['location'].value_counts(dropna=False)

location
{'name': 'San Francisco, California, United States'}               115
{'name': 'San Francisco, CA • New York, NY • United States'}        93
{'name': 'Dublin'}                                                  89
{'name': 'New York, New York, USA'}                                 84
{'name': 'New York, New York, United States'}                       62
                                                                  ...
{'name': 'British Columbia; Ontario'}                                1
{'name': 'Alberta; British Columbia; Ontario; Quebec; Toronto'}      1
{'name': 'Atlanta; Austin; Dallas; Florida; Miami'}                  1
{'name': 'Raleigh'}                                                  1
{'name': 'Remote - United Kingdom, Germany'}                         1
Name: count, Length: 573, dtype: int64

In [153]:
df['location'].apply(type).value_counts()

location
<class 'str'>    2305
Name: count, dtype: int64

In [154]:
df['location'].iloc[0]

"{'name': 'San Francisco, CA'}"

In [155]:
import ast 
x=ast.literal_eval(df['location'].iloc[0])
x['name']

'San Francisco, CA'

In [156]:
type(ast.literal_eval(df['location'].iloc[0]))

dict

In [157]:
df['location_clean']=df['location'].apply( lambda x:ast.literal_eval(x)['name'])

In [158]:
df[['location', 'location_clean']].head(10)

,location,location_clean
0,"{'name': 'San Francisco, CA'}","San Francisco, CA"
1,{'name': 'Japan'},Japan
2,{'name': 'Japan'},Japan
3,{'name': 'Singapore'},Singapore
4,"{'name': 'US-Remote, US-San Francisco, US-Chic...","US-Remote, US-San Francisco, US-Chicago, US-Ne..."
5,{'name': 'US-New York'},US-New York
6,"{'name': 'US-New York, US-Chicago, US-Atlanta,...","US-New York, US-Chicago, US-Atlanta, US-San Fr..."
7,"{'name': 'Sydney, Australia'}","Sydney, Australia"
8,"{'name': 'US-San Francisco, US-California'}","US-San Francisco, US-California"
9,"{'name': 'US-San Francisco, US-Chicago, US-New...","US-San Francisco, US-Chicago, US-New York"

In [159]:
df['location_clean'].apply(type).value_counts()

location_clean
<class 'str'>    2305
Name: count, dtype: int64

In [160]:
df['location_clean'].isna().sum()

0

In [161]:
df['location_clean'].nunique()

573

In [162]:
df['departments'].value_counts()

departments
[{'id': 4030323002, 'name': 'Sales', 'child_ids': [], 'parent_id': None}]                  75
[{'id': 4030316002, 'name': 'Engineering', 'child_ids': [], 'parent_id': None}]            66
[{'id': 4016255004, 'name': 'Sales', 'child_ids': [], 'parent_id': None}]                  58
[{'id': 72277, 'name': 'Enterprise Sales', 'child_ids': [], 'parent_id': 9021}]            57
[{'id': 72253, 'name': 'Dev Eng', 'child_ids': [], 'parent_id': 9022}]                     44
                                                                                           ..
[{'id': 289354, 'name': 'HR Tech', 'child_ids': [], 'parent_id': 298006}]                   1
[{'id': 267361, 'name': 'Cloud OEM', 'child_ids': [], 'parent_id': 268135}]                 1
[{'id': 304721, 'name': 'Inside Sales NAMER', 'child_ids': [], 'parent_id': 336792}]        1
[{'id': 336762, 'name': 'Customer Success APAC', 'child_ids': [], 'parent_id': 268135}]     1
[{'id': 4075598004, 'name': 'Finance', 'child_ids': [], 'parent_id': None}]                 1
Name: count, Length: 452, dtype: int64

In [163]:
df['departments'].apply(type).value_counts()

departments
<class 'str'>    2305
Name: count, dtype: int64

In [164]:
df['departments'].isnull().sum()

0

In [165]:
x=ast.literal_eval(df['departments'].iloc[0])
print(type(x))
type(x[0])

<class 'list'>

dict

In [166]:
df['departments'].apply(lambda x: len(ast.literal_eval(x))).value_counts()

departments
1    2305
Name: count, dtype: int64

In [167]:
df['departments_clean']=df['departments'].apply(lambda x:ast.literal_eval(x)[0]['name'])

In [168]:
df[['departments', 'departments_clean']].head(10)

,departments,departments_clean
0,"[{'id': 380786, 'name': '1654 Account Executiv...",1654 Account Executives (AI)
1,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
2,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
3,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
4,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)
5,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)
6,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)
7,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
8,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)
9,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)

In [169]:
df['departments_clean'].isna().sum()

0

In [170]:
df['departments_clean'].nunique()

381

In [171]:
df['offices'].value_counts(dropna=False)

offices
[{'id': 65234, 'name': 'US', 'location': None, 'child_ids': [89623, 249942, 249943, 230657, 61413, 80440, 344486, 83778, 61414, 83767, 83768, 83776, 83769, 83770, 83771, 83772, 83773, 83774, 89624, 83789, 83775, 83777, 83779, 83780, 83820, 83781, 83782, 83783, 83784, 83785, 83786, 83787, 83821, 83788, 83790, 83791, 83792, 83793, 83794, 83854, 83861, 83795, 83796, 83797, 83831, 83798, 83799, 83856, 83800, 83801, 83819, 83802, 83850, 83803, 83804, 83805, 83806, 83807, 83808, 83809, 83810, 83811, 83812, 83813, 83815, 83817, 83822, 83824, 83846, 83825, 83829, 83830, 65238, 83834, 83849, 83859, 83835, 83836, 83837, 83839, 83840, 83841, 83842, 83843, 83844, 83847, 83848, 83851, 83852, 83853, 83855, 83857, 83858, 83860, 83862, 83814, 83818, 83823, 83826, 83827, 83828, 83832, 83833, 83816, 85342, 83838, 83845, 223073, 265365, 16654], 'parent_id': 673}]    249
[{'id': 5664, 'name': 'New York', 'location': 'New York, NY, United States', 'child_ids': [81327, 76746], 'parent_id': 73429}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               75
[{'id': 3962, 'name': 'Dublin', 'location': 'Dublin, Ireland', 'child_ids': [], 'parent_id': 23658}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         71
[{'id': 87011, 'name': 'Ireland Locations', 'location': None, 'child_ids': [80459, 80460], 'parent_id': 17446}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              59
[{'id': 4031430004, 'name': 'Canada', 'location': None, 'child_ids': [4031432004, 4031431004], 'parent_id': 4033142004}, {'id': 4024285004, 'name': 'US', 'location': None, 'child_ids': [], 'parent_id': 4033142004}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       57
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
[{'id': 5455, 'name': 'Boston', 'location': 'Boston, MA, United States', 'child_ids': [], 'parent_id': 78117}, {'id': 61865, 'name': 'Denver', 'location': 'Denver, Colorado, United States', 'child_ids': [], 'parent_id': 78231}, {'id': 5664, 'name': 'New York', 'location': 'New York, NY, United States', 'child_ids': [81327, 76746], 'parent_id': 73429}, {'id': 158448, 'name': 'Remote', 'location': None, 'child_ids': [], 'parent_id': None}, {'id': 76746, 'name': 'Remote - New York', 'location': 'New York, United States', 'child_ids': [], 'parent_id': 5664}]                                                                                                                                                                                                                                                                                                              1
[{'id': 25185, 'name': 'Dublin', 'location': 'Dublin, Ireland', 'child_ids': [], 'parent_id': 78095}, {'id': 85005, 'name': 'Lisbon', 'location': None, 'child_ids': [], 'parent_id': 78106}, {'id': 74767, 'name': 'Madrid', 'location': 'Madrid, Madrid, Spain', 'child_ids': [], 'parent_id': 74766}, {'id': 8604, 'name': 'Paris', 'location': 'Paris, Paris, France', 'child_ids': [], 'parent_id': 78094}, {'id': 82342, 'name': 'Tel Aviv', 'location': 'Tel Aviv District, Israel', 'child_ids': [], 'parent_id': 78555}]                                                                                                                                                                                                                                                                                                                                                             1
[{'id': 5455, 'name': 'Boston', 'location': 'Boston, MA, United States', 'child_ids': [], 'parent_id': 78117}, {'id': 5664, 'name': 'New York', 'location': 'New York, NY, United States', 'child_ids': [81327, 76746], 'parent_id': 73429}, {'id': 158448, 'name': 'Remote', 'location': None, 'child_ids': [], 'parent_id': None}, {'id': 76794, 'name': 'Remote - British Columbia', 'location': None, 'child_ids': [], 'parent_id': 73430}, {'id': 76729, 'name': 'Remote - California', 'location': 'California, United States', 'child_ids': [], 'parent_id': 78108}]                                                                                                                                                                                                                                                                                                                   1
[{'id': 76748, 'name': 'Remote - Ontario', 'location': None, 'child_ids': [], 'parent_id': 73430}, {'id': 67512, 'name': 'Toronto', 'location': 'Toronto, Ontario, Canada', 'child_ids': [], 'parent_id': 73430}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
[{'id': 4091068004, 'name': 'Office - Berlin', 'location': 'Berlin, Berlin, Germany', 'child_ids': [], 'parent_id': 4014161004}, {'id': 4091069004, 'name': 'Office - London', 'location': 'London, England, United Kingdom', 'child_ids': [], 'parent_id': 4014161004}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
Name: count, Length: 388, dtype: int64

In [172]:
df['offices'].apply(type).value_counts()

offices
<class 'str'>    2305
Name: count, dtype: int64

In [173]:
df['offices'].apply(lambda x: len(ast.literal_eval(x))).value_counts()

offices
1     1792
2      201
3      118
4       67
5       61
6       18
10      14
0       13
9        5
8        4
7        4
11       3
12       3
15       2
Name: count, dtype: int64

In [174]:
df.loc[df['offices'].apply(lambda x: len(ast.literal_eval(x))) == 0,['title', 'offices']]

                                                  title offices
1702     Future Opportunities: Channel Sales Experience      []
1703  Future Opportunities: Dedicated Service Adviso...      []
1704  Future Opportunities: Dedicated Service Adviso...      []
1705    Future Opportunities: Early Career Sales Talent      []
1706               Future Opportunities: HR Constultant      []
1707   Future Opportunities: Licensed Benefits Advisor       []
1709          Future Opportunities: Retirement Advocate      []
1711  Future Opportunities: Retirement Client Relati...      []
1712  Future Opportunities: Retirement Implementatio...      []
1762         Summer Opportunities - Retirement Sales AE      []
1859     Customs Specialist - Join Our Talent Community      []
1898   Operations Associate - Join Our Talent Community      []
1900  Operations Specialist - Join Our Talent Commun...      []

In [175]:
x = ast.literal_eval(df['offices'].iloc[1702])
print(x)

[]

In [176]:
df.loc[df['offices'].apply(lambda x:len(ast.literal_eval(x)))==2,'offices'].iloc[0]

"[{'id': 80465, 'name': 'GB-London', 'location': 'London, England, United Kingdom', 'child_ids': [], 'parent_id': 87009}, {'id': 87011, 'name': 'Ireland Locations', 'location': None, 'child_ids': [80459, 80460], 'parent_id': 17446}]"

In [177]:
def clean_offices(x):
    offices=ast.literal_eval(x)
    if len(offices)==0:
        return None
    return ', '.join(office['name'] for office in offices)

In [178]:
df['offices_clean'] = df['offices'].apply(clean_offices)

In [179]:
df[['offices','offices_clean']].head(10)

                                             offices        offices_clean
0  [{'id': 65234, 'name': 'US', 'location': None,...                   US
1  [{'id': 87012, 'name': 'Japan Locations', 'loc...      Japan Locations
2  [{'id': 87012, 'name': 'Japan Locations', 'loc...      Japan Locations
3  [{'id': 86997, 'name': 'Singapore Locations', ...  Singapore Locations
4  [{'id': 65234, 'name': 'US', 'location': None,...                   US
5  [{'id': 65234, 'name': 'US', 'location': None,...                   US
6  [{'id': 65234, 'name': 'US', 'location': None,...                   US
7  [{'id': 87005, 'name': 'Australia Locations', ...  Australia Locations
8  [{'id': 65234, 'name': 'US', 'location': None,...                   US
9  [{'id': 65234, 'name': 'US', 'location': None,...                   US

In [180]:
df['offices_clean'].isnull().sum()

13

In [181]:
df['offices_clean'].nunique()

333

In [182]:
df['offices_clean'].apply(type).value_counts()

offices_clean
<class 'str'>         2292
<class 'NoneType'>      13
Name: count, dtype: int64

In [183]:
df['education'].value_counts(dropna=False)

education
NaN                   2253
education_optional      43
education_required       9
Name: count, dtype: int64

In [184]:
df['education'].apply(type).value_counts()

education
<class 'float'>    2253
<class 'str'>        52
Name: count, dtype: int64

In [185]:
df.loc[df['education'].notna(),
                ['title','company_name','education']].head(20)

,title,company_name,education
36,"Account Executive, SMB (Hunter)",Stripe,education_required
156,Finance and Strategy Analyst,Stripe,education_optional
273,"Operations Associate, New Grad (Mexico)",Stripe,education_required
306,Privacy Fellow,Stripe,education_required
428,"Software Engineer, Intern",Stripe,education_required
431,"Software Engineer, New Grad, Developer & End U...",Stripe,education_required
516,"Tech Operations Associate, New Grad (Mexico)",Stripe,education_required
563,"Data Scientist, Core Data - PhD (2026)",Figma,education_optional
598,"Manager, Enterprise Support (Singapore)",Figma,education_optional
651,Senior Sales Enablement Manager (Singapore),Figma,education_optional
1281,People Operations Apprentice,Datadog,education_required
1505,"Account Executive, Central US",Cockroach Labs,education_optional
1506,"Account Executive, Singapore",Cockroach Labs,education_optional
1507,"Director, Product Management",Cockroach Labs,education_optional
1508,Field Marketing Manager,Cockroach Labs,education_optional
1509,"GTM Recruiter, Austin (Contract to Hire)",Cockroach Labs,education_optional
1510,Incident Manager,Cockroach Labs,education_optional
1512,"Manager, Corporate Sales (UK)",Cockroach Labs,education_optional
1513,"Manager, Customer Success - West AMER",Cockroach Labs,education_optional
1514,"Manager, Engineering (Production Orchestration)",Cockroach Labs,education_optional

In [186]:
df['company_board'].value_counts()

company_board
zapier    2305
Name: count, dtype: int64

In [187]:
df['ai_disclaimer'].value_counts(dropna=False)

ai_disclaimer
NaN    2305
Name: count, dtype: int64

In [188]:
df.drop(columns=['ai_disclaimer'], inplace=True)

In [189]:
df['include_ai_disclaimer'].value_counts(dropna=False)

include_ai_disclaimer
NaN      1322
False     983
Name: count, dtype: int64

In [190]:
df['ai_opt_out_request_url'].value_counts(dropna=False)

ai_opt_out_request_url
NaN                                                                        1713
http://app.greenhouse.io/ai_opt_out_request/job_post/7954688/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/7359215/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/8023124/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/8023120/ai_opt_out       1
                                                                           ...
http://app.greenhouse.io/ai_opt_out_request/job_post/7553098/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/7993682/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/7461966/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/8008880/ai_opt_out       1
http://app.greenhouse.io/ai_opt_out_request/job_post/7991685/ai_opt_out       1
Name: count, Length: 593, dtype: int64

In [191]:
df['ai_opt_out_request_url'].apply(type).value_counts()

ai_opt_out_request_url
<class 'float'>    1713
<class 'str'>       592
Name: count, dtype: int64

In [192]:
df['data_compliance'].value_counts(dropna=False)

data_compliance
[{'type': 'gdpr', 'requires_consent': False, 'requires_processing_consent': False, 'requires_retention_consent': False, 'retention_period': None, 'demographic_data_consent_applies': False}]    1561
[{'type': 'gdpr', 'requires_consent': False, 'requires_processing_consent': False, 'requires_retention_consent': False, 'retention_period': None, 'demographic_data_consent_applies': True}]      744
Name: count, dtype: int64

In [193]:
df['data_compliance'].apply(type).value_counts()

data_compliance
<class 'str'>    2305
Name: count, dtype: int64

In [194]:
x=ast.literal_eval(df['data_compliance'].iloc[0])

In [195]:
print(type(x))
print(x)

<class 'list'>
[{'type': 'gdpr', 'requires_consent': False, 'requires_processing_consent': False, 'requires_retention_consent': False, 'retention_period': None, 'demographic_data_consent_applies': False}]

In [196]:
df['data_compliance'].apply(lambda x:len(ast.literal_eval(x))).value_counts()

data_compliance
1    2305
Name: count, dtype: int64

In [197]:
df['data_compliance'].apply(lambda x:ast.literal_eval(x)[0].get('type')).value_counts()

data_compliance
gdpr    2305
Name: count, dtype: int64

In [198]:
df['data_compliance'].apply(lambda x:ast.literal_eval(x)[0].get('requires_consent')).value_counts()

data_compliance
False    2305
Name: count, dtype: int64

In [199]:
df['data_compliance'].apply(lambda x:ast.literal_eval(x)[0].get('demographic_data_consent_applies')).value_counts()

data_compliance
False    1561
True      744
Name: count, dtype: int64

In [200]:
df['data_compliance'].apply(lambda x: ast.literal_eval(x)[0].get('requires_processing_consent')).value_counts()

data_compliance
False    2305
Name: count, dtype: int64

In [201]:
df['data_compliance'].apply(lambda x: ast.literal_eval(x)[0].get('requires_retention_consent')).value_counts()

data_compliance
False    2305
Name: count, dtype: int64

In [202]:
df['data_compliance'].apply(lambda x: ast.literal_eval(x)[0].get('retention_period')).value_counts(dropna=False)

data_compliance
None    2305
Name: count, dtype: int64

In [203]:
df['demographic_data_consent_applies'] = df['data_compliance'].apply(
    lambda x: ast.literal_eval(x)[0].get('demographic_data_consent_applies')
)

In [204]:
df['demographic_data_consent_applies'].value_counts()

demographic_data_consent_applies
False    1561
True      744
Name: count, dtype: int64

In [205]:
df['internal_job_id'].value_counts(dropna=False)

internal_job_id
NaN             13
6.368422e+09     8
6.368424e+09     8
6.342783e+09     6
6.415032e+09     6
                ..
4.936173e+09     1
5.031294e+09     1
4.936613e+09     1
4.936179e+09     1
5.057777e+09     1
Name: count, Length: 1937, dtype: int64

In [206]:
id_values = df['internal_job_id'].dropna()

(id_values % 1 == 0).value_counts()

internal_job_id
True    2292
Name: count, dtype: int64

In [207]:
 df['internal_job_id'].dtype

dtype('float64')

In [208]:
df['internal_job_id'].isna().sum()

13

In [209]:
df['internal_job_id'].nunique()

1936

In [210]:
df['internal_job_id'].head()

0    3453698.0
1    3486109.0
2    3407094.0
3    3431456.0
4    3467410.0
Name: internal_job_id, dtype: float64

In [211]:
df['internal_job_id']=df['internal_job_id'].astype('Int64')

In [212]:
 df['internal_job_id'].dtype

Int64Dtype()

In [213]:
df['internal_job_id'].isna().sum()

13

In [214]:
df['requisition_id'].value_counts(dropna=False)

requisition_id
See Opening ID    524
NaN                79
JR101333            8
JR101332            8
JR101309            6
                 ...
R17084              1
R18898              1
R18045              1
R14712              1
462                 1
Name: count, Length: 1378, dtype: int64

In [215]:
df['requisition_id'].dtype

dtype('O')

In [216]:
df['requisition_id'].isna().sum()

79

In [217]:
df['requisition_id'].nunique()

1377

In [218]:
df[df['requisition_id']=='See Opening ID'][['requisition_id', 'title', 'company_name', 'location_clean']].head(20)

,requisition_id,title,company_name,location_clean
0,See Opening ID,"Account Executive, AI Sales (Grower)",Stripe,"San Francisco, CA"
1,See Opening ID,"Account Executive, Commercial Grower (Japanese...",Stripe,Japan
2,See Opening ID,"Account Executive, Commercial Hunter (Japanese...",Stripe,Japan
3,See Opening ID,"Account Executive, Cross Border China",Stripe,Singapore
4,See Opening ID,"Account Executive - Enterprise, Grower",Stripe,"US-Remote, US-San Francisco, US-Chicago, US-Ne..."
5,See Opening ID,"Account Executive, Enterprise - Grower",Stripe,US-New York
6,See Opening ID,"Account Executive, Enterprise - Grower",Stripe,"US-New York, US-Chicago, US-Atlanta, US-San Fr..."
7,See Opening ID,"Account Executive, Enterprise Grower (Australia)",Stripe,"Sydney, Australia"
8,See Opening ID,"Account Executive - Enterprise, Growth",Stripe,"US-San Francisco, US-California"
9,See Opening ID,"Account Executive, Enterprise - Hunter",Stripe,"US-San Francisco, US-Chicago, US-New York"
10,See Opening ID,"Account Executive, Enterprise Hunter (French f...",Stripe,Paris
11,See Opening ID,"Account Executive, Enterprise Hunter (Japanese...",Stripe,Tokyo
12,See Opening ID,"Account Executive, Enterprise Platforms (Grower)",Stripe,"San Francisco, CA; Chicago, IL & New York, NY"
13,See Opening ID,"Account Executive, Enterprise Platforms, Hunter",Stripe,"New York, NY; San Francisco, CA; Seattle, WA; ..."
14,See Opening ID,"Account Executive, Enterprise Platforms, Tier ...",Stripe,"New York, NY; San Francisco, CA"
15,See Opening ID,"Account Executive, Existing Business, Platforms",Stripe,"New York, NY"
16,See Opening ID,"Account Executive, Financial Services, Grower",Stripe,London
17,See Opening ID,"Account Executive, Funded Startups - Expansion",Stripe,Chicago
18,See Opening ID,"Account Executive, Funded Startups - Expansion",Stripe,San Francisco
19,See Opening ID,"Account Executive, Funded Startups, Hunter",Stripe,"San Francisco, New York City"

In [219]:
df['requisition_id'] = df['requisition_id'].replace('See Opening ID', pd.NA)

In [220]:
df['requisition_id'].isna().sum()

603

In [221]:
df['title'].value_counts(dropna=False)

title
Enterprise Account Executive, Growth           21
Strategic Account Executive                    14
Sales Development Representative               14
Enterprise Account Executive                   13
Commercial Account Executive                   12
                                               ..
People Partner, Product & Design                1
People Partner, Japan & APAC (Singapore)        1
People Partner, Engineering                     1
Open Source Developer                           1
Vercel Development Representative, Startups     1
Name: count, Length: 1730, dtype: int64

In [222]:
df['title'].isna().sum()

0

In [223]:
print("Leading/trailing spaces:",
      (df['title'] != df['title'].str.strip()).sum())

Leading/trailing spaces: 138

In [224]:
print("Empty after stripping:",
      (df['title'].str.strip() == '').sum())

Empty after stripping: 0

In [225]:
df.columns

Index(['absolute_url', 'data_compliance', 'internal_job_id', 'location',
       'metadata', 'id', 'updated_at', 'requisition_id', 'title',
       'company_name', 'first_published', 'language', 'application_deadline',
       'content', 'departments', 'offices', 'include_ai_disclaimer',
       'ai_opt_out_request_url', 'education', 'company_board', 'job_level',
       'job_type', 'region', 'working_model', 'ic_or_mg', 'baseline_salary',
       'other_market_salary', 'baseline_salary_currency',
       'baseline_salary_min', 'baseline_salary_max',
       'other_market_salary_currency', 'other_market_salary_max',
       'other_market_salary_min', 'pay_transparency', 'pay_transparency_unit',
       'pay_transparency_max', 'pay_transparency_min', 'working_model_clean',
       'location_clean', 'departments_clean', 'offices_clean',
       'demographic_data_consent_applies'],
      dtype='object')

In [226]:
df['company_name'].value_counts(dropna=False)

company_name
Stripe            524
Datadog           421
MongoDB           381
Brex              266
Figma             169
Flexport          148
Asana             146
Gusto, Inc.        78
Vercel             67
Checkr             60
Cockroach Labs     35
CircleCI           10
Name: count, dtype: int64

In [227]:
print("Leading/trailing spaces:",
      (df['company_name'] != df['company_name'].str.strip()).sum())

Leading/trailing spaces: 0

In [228]:
print("Empty after stripping:",
      (df['company_name'].str.strip() == '').sum())

Empty after stripping: 0

In [229]:
df['first_published'].value_counts(dropna=False)

first_published
2026-06-24 20:02:41+00:00    2
2026-04-04 01:17:10+00:00    2
2025-04-14 00:15:47+00:00    2
2026-05-27 10:42:01+00:00    2
2026-03-24 16:43:04+00:00    2
                            ..
2025-08-12 14:54:09+00:00    1
2026-01-30 15:56:59+00:00    1
2026-05-14 08:04:31+00:00    1
2026-06-03 15:18:57+00:00    1
2026-02-27 21:34:28+00:00    1
Name: count, Length: 2287, dtype: int64

In [230]:
df['first_published'].isna().sum()

0

In [231]:
df['first_published'].nunique()

2287

In [232]:
df['first_published'].dtype

datetime64[ns, UTC]

In [233]:
df['first_published_date']=df['first_published'].dt.date

In [234]:
df['first_published_time']=df['first_published'].dt.time

In [235]:
cols=df.columns.tolist()
i=cols.index('first_published')
cols.insert(i + 1, cols.pop(cols.index('first_published_date')))
cols.insert(i + 2, cols.pop(cols.index('first_published_time')))
df = df[cols]

In [236]:
df[['first_published', 'first_published_date', 'first_published_time']].head()

            first_published first_published_date first_published_time
0 2026-06-02 12:58:57+00:00           2026-06-02             12:58:57
1 2026-07-02 07:24:50+00:00           2026-07-02             07:24:50
2 2026-04-17 04:47:42+00:00           2026-04-17             04:47:42
3 2026-05-06 08:59:55+00:00           2026-05-06             08:59:55
4 2026-06-09 17:38:22+00:00           2026-06-09             17:38:22

In [237]:
df['language'].value_counts(dropna=False)

language
en    2283
ja      18
ko       3
nl       1
Name: count, dtype: int64

In [238]:
df['language_clean'] = df['language'].replace({'en': 'English', 'ja': 'Japanese', 'ko': 'Korean', 'nl': 'Dutch'
})

In [239]:
df['language_clean'].value_counts(dropna=False)

language_clean
English     2283
Japanese      18
Korean         3
Dutch          1
Name: count, dtype: int64

In [240]:
df['application_deadline'].value_counts(dropna=False)

application_deadline
NaN    2305
Name: count, dtype: int64

In [241]:
# drop application-deadline

In [242]:
df['content'].head(5)

0    &lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...
1    &lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...
2    &lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...
3    &lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...
4    &lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...
Name: content, dtype: object

In [243]:
import html
df['content_decoded']=df['content'].apply(html.unescape)

In [244]:
df['content_decoded'].head(5)

0    <h2>Who we are</h2>\n<h3>About Stripe</h3>\n<p...
1    <h2><strong>Who we are</strong></h2>\n<h3><str...
2    <h2><strong>Who we are</strong></h2>\n<h3><str...
3    <h2>Who we are</h2>\n<h3>About Stripe</h3>\n<p...
4    <h2><strong>Who we are</strong></h2>\n<h3><str...
Name: content_decoded, dtype: object

In [245]:
import re

html_pattern = r'<[^>]+>'

print( df['content_decoded'].str.contains( html_pattern, regex=True, na=False ).sum())

2305

In [246]:
from bs4 import BeautifulSoup

In [247]:
def remove_html(text):
    return BeautifulSoup(text,'html.parser').get_text(' ')

In [248]:
df['content_clean'] = df['content_decoded'].apply(remove_html)

In [249]:
df['content_clean'].head(5)

0    Who we are \n About Stripe \n Stripe is a fina...
1    Who we are \n About Stripe \n Stripe is a fina...
2    Who we are \n About Stripe \n Stripe is a fina...
3    Who we are \n About Stripe \n Stripe is a fina...
4    Who we are \n About Stripe \n Stripe is a fina...
Name: content_clean, dtype: object

In [250]:
df['content_clean'].str.contains('\n',regex=True,na=False).sum()

2305

In [251]:
df['content_clean'] = df['content_clean'].str.replace( '\n',' ',regex=True)

In [252]:
df['content_clean'].head(5)

0    Who we are   About Stripe   Stripe is a financ...
1    Who we are   About Stripe   Stripe is a financ...
2    Who we are   About Stripe   Stripe is a financ...
3    Who we are   About Stripe   Stripe is a financ...
4    Who we are   About Stripe   Stripe is a financ...
Name: content_clean, dtype: object

In [253]:
df['content_clean'] = df['content_clean'].str.replace(r'\s+',' ',regex=True)

In [254]:
df['content_clean'].isna().sum()

0

In [255]:
(df['content_clean'].str.strip() == '').sum()

0

In [256]:
df['content_clean']=df['content_clean'].str.strip()

In [257]:
(df['content_clean']!=df['content_clean'].str.strip()).sum()

0

In [258]:
df['content_clean'].str.contains( r'<[^>]+>', regex=True,na=False).sum()

0

In [259]:
df['include_ai_disclaimer'].value_counts(dropna=False)

include_ai_disclaimer
NaN      1322
False     983
Name: count, dtype: int64

In [260]:
df['include_ai_disclaimer'].dropna().apply(type).value_counts()

include_ai_disclaimer
<class 'bool'>    983
Name: count, dtype: int64

In [261]:
df['education'].value_counts(dropna=False)

education
NaN                   2253
education_optional      43
education_required       9
Name: count, dtype: int64

In [262]:
df['education'].dropna().apply(type).value_counts()

education
<class 'str'>    52
Name: count, dtype: int64

In [263]:
df['company_board'].value_counts(dropna=False)

company_board
zapier    2305
Name: count, dtype: int64

In [264]:
df.columns.tolist()

['absolute_url',
 'data_compliance',
 'internal_job_id',
 'location',
 'metadata',
 'id',
 'updated_at',
 'requisition_id',
 'title',
 'company_name',
 'first_published',
 'first_published_date',
 'first_published_time',
 'language',
 'application_deadline',
 'content',
 'departments',
 'offices',
 'include_ai_disclaimer',
 'ai_opt_out_request_url',
 'education',
 'company_board',
 'job_level',
 'job_type',
 'region',
 'working_model',
 'ic_or_mg',
 'baseline_salary',
 'other_market_salary',
 'baseline_salary_currency',
 'baseline_salary_min',
 'baseline_salary_max',
 'other_market_salary_currency',
 'other_market_salary_max',
 'other_market_salary_min',
 'pay_transparency',
 'pay_transparency_unit',
 'pay_transparency_max',
 'pay_transparency_min',
 'working_model_clean',
 'location_clean',
 'departments_clean',
 'offices_clean',
 'demographic_data_consent_applies',
 'language_clean',
 'content_decoded',
 'content_clean']

In [265]:
missing_summary = pd.DataFrame({'missing_count': df.isna().sum(),'missing_percentage': df.isna().mean() * 100}).sort_values( 'missing_percentage',ascending=False
)

missing_summary

                                  missing_count  missing_percentage
application_deadline                       2305          100.000000
other_market_salary_max                    2255           97.830803
other_market_salary_min                    2255           97.830803
education                                  2253           97.744035
baseline_salary_min                        2231           96.789588
baseline_salary_max                        2231           96.789588
other_market_salary                        2175           94.360087
other_market_salary_currency               2175           94.360087
baseline_salary_currency                   2152           93.362256
baseline_salary                            2152           93.362256
pay_transparency_max                       2109           91.496746
pay_transparency_min                       2109           91.496746
pay_transparency                           2107           91.409978
pay_transparency_unit                      2107           91.409978
working_model_clean                        1924           83.470716
region                                     1924           83.470716
working_model                              1924           83.470716
job_level                                  1924           83.470716
job_type                                   1924           83.470716
ic_or_mg                                   1884           81.735358
ai_opt_out_request_url                     1713           74.316703
include_ai_disclaimer                      1322           57.353579
metadata                                    798           34.620390
requisition_id                              603           26.160521
offices_clean                                13            0.563991
internal_job_id                              13            0.563991
demographic_data_consent_applies              0            0.000000
location_clean                                0            0.000000
language_clean                                0            0.000000
departments_clean                             0            0.000000
content_decoded                               0            0.000000
absolute_url                                  0            0.000000
data_compliance                               0            0.000000
company_board                                 0            0.000000
offices                                       0            0.000000
departments                                   0            0.000000
content                                       0            0.000000
language                                      0            0.000000
first_published_time                          0            0.000000
first_published_date                          0            0.000000
first_published                               0            0.000000
company_name                                  0            0.000000
title                                         0            0.000000
updated_at                                    0            0.000000
id                                            0            0.000000
location                                      0            0.000000
content_clean                                 0            0.000000

In [266]:
df['id'].duplicated().sum()

0

In [267]:
df['absolute_url'].duplicated().sum()

0

In [268]:
df.dtypes

absolute_url                                     object
data_compliance                                  object
internal_job_id                                   Int64
location                                         object
metadata                                         object
id                                                int64
updated_at                          datetime64[ns, UTC]
requisition_id                                   object
title                                            object
company_name                                     object
first_published                     datetime64[ns, UTC]
first_published_date                             object
first_published_time                             object
language                                         object
application_deadline                            float64
content                                          object
departments                                      object
offices                                          object
include_ai_disclaimer                            object
ai_opt_out_request_url                           object
education                                        object
company_board                                    object
job_level                                        object
job_type                                         object
region                                           object
working_model                                    object
ic_or_mg                                         object
baseline_salary                                  object
other_market_salary                              object
baseline_salary_currency                         object
baseline_salary_min                             float64
baseline_salary_max                             float64
other_market_salary_currency                     object
other_market_salary_max                         float64
other_market_salary_min                         float64
pay_transparency                                 object
pay_transparency_unit                            object
pay_transparency_max                            float64
pay_transparency_min                            float64
working_model_clean                              object
location_clean                                   object
departments_clean                                object
offices_clean                                    object
demographic_data_consent_applies                   bool
language_clean                                   object
content_decoded                                  object
content_clean                                    object
dtype: object

In [269]:
df['first_published_date'] = pd.to_datetime(df['first_published_date'])

In [270]:
df[['first_published', 'first_published_date', 'first_published_time']].dtypes

first_published         datetime64[ns, UTC]
first_published_date         datetime64[ns]
first_published_time                 object
dtype: object

In [271]:
df['include_ai_disclaimer'] = df['include_ai_disclaimer'].astype('boolean')

In [272]:
df['include_ai_disclaimer'].dtype

BooleanDtype

In [273]:
df[['location', 'location_clean']].head(5)

,location,location_clean
0,"{'name': 'San Francisco, CA'}","San Francisco, CA"
1,{'name': 'Japan'},Japan
2,{'name': 'Japan'},Japan
3,{'name': 'Singapore'},Singapore
4,"{'name': 'US-Remote, US-San Francisco, US-Chic...","US-Remote, US-San Francisco, US-Chicago, US-Ne..."

In [274]:
df[['departments', 'departments_clean']].head(5)

,departments,departments_clean
0,"[{'id': 380786, 'name': '1654 Account Executiv...",1654 Account Executives (AI)
1,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
2,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
3,"[{'id': 81432, 'name': '1195 Account Executive...",1195 Account Executives (APAC)
4,"[{'id': 81430, 'name': '1175 Enterprise - Acco...",1175 Enterprise - Account Executives (NA)

In [275]:
df[['offices', 'offices_clean']].head(5)

                                             offices        offices_clean
0  [{'id': 65234, 'name': 'US', 'location': None,...                   US
1  [{'id': 87012, 'name': 'Japan Locations', 'loc...      Japan Locations
2  [{'id': 87012, 'name': 'Japan Locations', 'loc...      Japan Locations
3  [{'id': 86997, 'name': 'Singapore Locations', ...  Singapore Locations
4  [{'id': 65234, 'name': 'US', 'location': None,...                   US

In [276]:
df[['language', 'language_clean']].head(10)

  language language_clean
0       en        English
1       ja       Japanese
2       ja       Japanese
3       en        English
4       en        English
5       en        English
6       en        English
7       en        English
8       en        English
9       en        English

In [277]:
df[['content', 'content_decoded', 'content_clean']].head(2)

,content,content_decoded,content_clean
0,&lt;h2&gt;Who we are&lt;/h2&gt;\n&lt;h3&gt;Abo...,<h2>Who we are</h2>\n<h3>About Stripe</h3>\n<p...,Who we are About Stripe Stripe is a financial ...
1,&lt;h2&gt;&lt;strong&gt;Who we are&lt;/strong&...,<h2><strong>Who we are</strong></h2>\n<h3><str...,Who we are About Stripe Stripe is a financial ...

In [278]:
df[['data_compliance', 'demographic_data_consent_applies']].head(5)

,data_compliance,demographic_data_consent_applies
0,"[{'type': 'gdpr', 'requires_consent': False, '...",False
1,"[{'type': 'gdpr', 'requires_consent': False, '...",False
2,"[{'type': 'gdpr', 'requires_consent': False, '...",False
3,"[{'type': 'gdpr', 'requires_consent': False, '...",False
4,"[{'type': 'gdpr', 'requires_consent': False, '...",False

In [279]:
df[['metadata', 'job_level', 'job_type', 'region',
    'working_model', 'ic_or_mg']].head(3)

  metadata job_level job_type region working_model ic_or_mg
0      NaN      None     None   None          None     None
1      NaN      None     None   None          None     None
2      NaN      None     None   None          None     None

In [280]:
print("Metadata available:", df['metadata'].notna().sum())

print("Job level available:", df['job_level'].notna().sum())
print("Job type available:", df['job_type'].notna().sum())
print("Region available:", df['region'].notna().sum())
print("Working model available:", df['working_model'].notna().sum())
print("IC/MG available:", df['ic_or_mg'].notna().sum())

Metadata available: 1507
Job level available: 381
Job type available: 381
Region available: 381
Working model available: 381
IC/MG available: 421

In [281]:
df[['baseline_salary', 'baseline_salary_currency','baseline_salary_min','baseline_salary_max']].dropna(subset=['baseline_salary']).head(5)

,baseline_salary,baseline_salary_currency,baseline_salary_min,baseline_salary_max
693,"{'unit': 'USD', 'max_value': '50003.2', 'min_v...",USD,50003.2,50003.2
707,"{'unit': 'MXN', 'max_value': '0.0', 'min_value...",MXN,NaN,NaN
709,"{'unit': 'INR', 'max_value': '0.0', 'min_value...",INR,NaN,NaN
710,"{'unit': 'USD', 'max_value': '85000.0', 'min_v...",USD,59000.0,85000.0
711,"{'unit': 'USD', 'max_value': '85000.0', 'min_v...",USD,59000.0,85000.0

In [282]:
df[[ 'other_market_salary','other_market_salary_currency','other_market_salary_min', 'other_market_salary_max']
].dropna(subset=['other_market_salary']).head(5)

,other_market_salary,other_market_salary_currency,other_market_salary_min,other_market_salary_max
694,"{'unit': 'USD', 'max_value': '50003.2', 'min_v...",USD,50003.2,50003.2
707,"{'unit': 'MXN', 'max_value': '0.0', 'min_value...",MXN,NaN,NaN
709,"{'unit': 'INR', 'max_value': '0.0', 'min_value...",INR,NaN,NaN
717,"{'unit': 'EUR', 'max_value': '0.0', 'min_value...",EUR,NaN,NaN
718,"{'unit': 'EUR', 'max_value': '0.0', 'min_value...",EUR,NaN,NaN

In [283]:
df[['pay_transparency','pay_transparency_unit','pay_transparency_min','pay_transparency_max']
].dropna(subset=['pay_transparency']).head(5)

,pay_transparency,pay_transparency_unit,pay_transparency_min,pay_transparency_max
1075,"{'unit': 'USD', 'max_value': '400000.0', 'min_...",USD,320000.0,400000.0
1077,"{'unit': 'USD', 'max_value': '125000.0', 'min_...",USD,94000.0,125000.0
1078,"{'unit': 'USD', 'max_value': '275000.0', 'min_...",USD,210000.0,275000.0
1079,"{'unit': 'USD', 'max_value': '349000.0', 'min_...",USD,238000.0,349000.0
1081,"{'unit': 'USD', 'max_value': '94000.0', 'min_v...",USD,64000.0,94000.0

In [284]:
(df['pay_transparency_min'] == 0).sum()

0

In [285]:
(df['pay_transparency_max'] == 0).sum()

0

In [286]:
df[['working_model', 'working_model_clean']].dropna(subset=['working_model']).head(10)

                 working_model  working_model_clean
693               [2-Flexible]             Flexible
694               [2-Flexible]             Flexible
695               [2-Flexible]             Flexible
696               [2-Flexible]             Flexible
697               [2-Flexible]             Flexible
698               [2-Flexible]             Flexible
699               [2-Flexible]             Flexible
700               [2-Flexible]             Flexible
701  [1-In Office, 2-Flexible]  In Office, Flexible
702               [2-Flexible]             Flexible

In [287]:
df[['first_published','first_published_date','first_published_time']].head(5)

            first_published first_published_date first_published_time
0 2026-06-02 12:58:57+00:00           2026-06-02             12:58:57
1 2026-07-02 07:24:50+00:00           2026-07-02             07:24:50
2 2026-04-17 04:47:42+00:00           2026-04-17             04:47:42
3 2026-05-06 08:59:55+00:00           2026-05-06             08:59:55
4 2026-06-09 17:38:22+00:00           2026-06-09             17:38:22

In [288]:
df[['updated_at']].head(5)

                 updated_at
0 2026-07-13 18:37:36+00:00
1 2026-07-03 01:13:43+00:00
2 2026-07-03 01:14:52+00:00
3 2026-06-26 21:05:39+00:00
4 2026-07-01 14:19:50+00:00

In [289]:
df['requisition_id'].value_counts(dropna=False).head(10)

requisition_id
<NA>          524
NaN            79
JR101333        8
JR101332        8
JR101309        6
JR101409        6
1273390805      6
JR101367        5
JR101368        5
JR101450        5
Name: count, dtype: int64

In [290]:
df['requisition_id'] = df['requisition_id'].astype('string')

In [291]:
print("Missing:", df['absolute_url'].isna().sum())

print("Blank:", (df['absolute_url'].str.strip() == '').sum())

print("Duplicate URLs:", df['absolute_url'].duplicated().sum())

print("Valid HTTP/HTTPS:",
      df['absolute_url'].str.startswith(('http://', 'https://')).sum())

Missing: 0
Blank: 0
Duplicate URLs: 0
Valid HTTP/HTTPS: 2305

In [292]:
print("Missing:", df['updated_at'].isna().sum())
print("Minimum:", df['updated_at'].min())
print("Maximum:", df['updated_at'].max())
print("Dtype:", df['updated_at'].dtype)

Missing: 0
Minimum: 2026-01-05 21:24:37+00:00
Maximum: 2026-07-14 07:15:41+00:00
Dtype: datetime64[ns, UTC]

In [293]:
print("Missing:", df['internal_job_id'].isna().sum())

print("Duplicate non-missing IDs:",
      df['internal_job_id'].dropna().duplicated().sum())

print("Dtype:", df['internal_job_id'].dtype)

Missing: 13
Duplicate non-missing IDs: 356
Dtype: Int64

In [294]:
print("Blank:", (df['ai_opt_out_request_url'].fillna('').str.strip() == '').sum())
print("Unique URLs:", df['ai_opt_out_request_url'].nunique())

Blank: 1713
Unique URLs: 592

In [295]:
drop_columns = [
    'application_deadline',
    'company_board',
    'content_decoded',
    'location',
    'departments',
    'offices',
    'language',
    'content',
    'data_compliance',
    'metadata',
    'working_model',
    'baseline_salary',
    'other_market_salary',
    'pay_transparency'
]

In [296]:
greenhouse_clean = df.drop(columns=drop_columns).copy()

In [297]:
greenhouse_clean.shape

(2305, 33)

In [298]:
greenhouse_clean.columns.tolist()

['absolute_url',
 'internal_job_id',
 'id',
 'updated_at',
 'requisition_id',
 'title',
 'company_name',
 'first_published',
 'first_published_date',
 'first_published_time',
 'include_ai_disclaimer',
 'ai_opt_out_request_url',
 'education',
 'job_level',
 'job_type',
 'region',
 'ic_or_mg',
 'baseline_salary_currency',
 'baseline_salary_min',
 'baseline_salary_max',
 'other_market_salary_currency',
 'other_market_salary_max',
 'other_market_salary_min',
 'pay_transparency_unit',
 'pay_transparency_max',
 'pay_transparency_min',
 'working_model_clean',
 'location_clean',
 'departments_clean',
 'offices_clean',
 'demographic_data_consent_applies',
 'language_clean',
 'content_clean']

In [299]:
greenhouse_clean.duplicated().sum()

0

In [300]:
missing = greenhouse_clean.isna().sum()

print(missing[missing > 0].sort_values(ascending=False))

other_market_salary_min         2255
other_market_salary_max         2255
education                       2253
baseline_salary_min             2231
baseline_salary_max             2231
other_market_salary_currency    2175
baseline_salary_currency        2152
pay_transparency_max            2109
pay_transparency_min            2109
pay_transparency_unit           2107
region                          1924
working_model_clean             1924
job_type                        1924
job_level                       1924
ic_or_mg                        1884
ai_opt_out_request_url          1713
include_ai_disclaimer           1322
requisition_id                   603
internal_job_id                   13
offices_clean                     13
dtype: int64

In [301]:
greenhouse_clean.dtypes

absolute_url                                     object
internal_job_id                                   Int64
id                                                int64
updated_at                          datetime64[ns, UTC]
requisition_id                           string[python]
title                                            object
company_name                                     object
first_published                     datetime64[ns, UTC]
first_published_date                     datetime64[ns]
first_published_time                             object
include_ai_disclaimer                           boolean
ai_opt_out_request_url                           object
education                                        object
job_level                                        object
job_type                                         object
region                                           object
ic_or_mg                                         object
baseline_salary_currency                         object
baseline_salary_min                             float64
baseline_salary_max                             float64
other_market_salary_currency                     object
other_market_salary_max                         float64
other_market_salary_min                         float64
pay_transparency_unit                            object
pay_transparency_max                            float64
pay_transparency_min                            float64
working_model_clean                              object
location_clean                                   object
departments_clean                                object
offices_clean                                    object
demographic_data_consent_applies                   bool
language_clean                                   object
content_clean                                    object
dtype: object

In [302]:
(greenhouse_clean['baseline_salary_min'] > greenhouse_clean['baseline_salary_max']).sum()

0

In [303]:
(greenhouse_clean['pay_transparency_min']>greenhouse_clean['pay_transparency_max']).sum()

0

In [304]:
(greenhouse_clean['other_market_salary_min']>greenhouse_clean['other_market_salary_max']).sum()

0

In [305]:
adzuna_cleaned=pd.read_csv('adzuna_cleaned.csv')

In [306]:
adzuna_cleaned.columns.to_list()

['created',
 'latitude',
 'title',
 'standard_role',
 'location',
 'city',
 'state',
 'longitude',
 'salary_is_predicted',
 'description',
 'company',
 'redirect_url',
 'category',
 'id',
 'contract_time',
 'contract_type',
 'salary_min',
 'salary_max']

In [307]:
greenhouse_clean.columns.tolist()

['absolute_url',
 'internal_job_id',
 'id',
 'updated_at',
 'requisition_id',
 'title',
 'company_name',
 'first_published',
 'first_published_date',
 'first_published_time',
 'include_ai_disclaimer',
 'ai_opt_out_request_url',
 'education',
 'job_level',
 'job_type',
 'region',
 'ic_or_mg',
 'baseline_salary_currency',
 'baseline_salary_min',
 'baseline_salary_max',
 'other_market_salary_currency',
 'other_market_salary_max',
 'other_market_salary_min',
 'pay_transparency_unit',
 'pay_transparency_max',
 'pay_transparency_min',
 'working_model_clean',
 'location_clean',
 'departments_clean',
 'offices_clean',
 'demographic_data_consent_applies',
 'language_clean',
 'content_clean']

In [345]:
adzuna_cleaned[['id', 'title', 'company', 'location', 'description',
     'created', 'salary_min', 'salary_max']].dtypes

KeyError: "['company', 'location', 'description'] not in index"

In [346]:
greenhouse_clean[['id', 'title', 'company_name', 'location_clean', 'content_clean',
     'first_published', 'baseline_salary_min', 'baseline_salary_max']].dtypes

KeyError: "['first_published', 'baseline_salary_min', 'baseline_salary_max'] not in index"

In [310]:
adzuna_cleaned['created']

0       2026-07-03 00:54:22+00:00
1       2026-07-10 03:46:23+00:00
2       2026-07-03 00:54:32+00:00
3       2026-07-09 17:58:24+00:00
4       2026-07-03 00:54:21+00:00
                  ...
4959    2026-06-11 06:57:27+00:00
4960    2026-06-11 06:54:56+00:00
4961    2026-06-11 06:54:56+00:00
4962    2026-06-11 06:56:16+00:00
4963    2026-05-07 02:01:46+00:00
Name: created, Length: 4964, dtype: object

In [311]:
adzuna_cleaned['created'] = pd.to_datetime(adzuna_cleaned['created'],errors='coerce', utc=True)

In [312]:
adzuna_cleaned['created'].dtype

datetime64[ns, UTC]

In [313]:
adzuna_cleaned = adzuna_cleaned.rename(columns={
    'company': 'company_name',
    'location': 'location_clean',
    'description': 'content_clean',
    'redirect_url': 'absolute_url'
})

In [314]:
greenhouse_clean = greenhouse_clean.rename(columns={
    'first_published': 'created',
    'baseline_salary_min': 'salary_min',
    'baseline_salary_max': 'salary_max'
})

In [315]:
adzuna_cleaned.columns.to_list()

['created',
 'latitude',
 'title',
 'standard_role',
 'location_clean',
 'city',
 'state',
 'longitude',
 'salary_is_predicted',
 'content_clean',
 'company_name',
 'absolute_url',
 'category',
 'id',
 'contract_time',
 'contract_type',
 'salary_min',
 'salary_max']

In [316]:
greenhouse_clean.columns.tolist()

['absolute_url',
 'internal_job_id',
 'id',
 'updated_at',
 'requisition_id',
 'title',
 'company_name',
 'created',
 'first_published_date',
 'first_published_time',
 'include_ai_disclaimer',
 'ai_opt_out_request_url',
 'education',
 'job_level',
 'job_type',
 'region',
 'ic_or_mg',
 'baseline_salary_currency',
 'salary_min',
 'salary_max',
 'other_market_salary_currency',
 'other_market_salary_max',
 'other_market_salary_min',
 'pay_transparency_unit',
 'pay_transparency_max',
 'pay_transparency_min',
 'working_model_clean',
 'location_clean',
 'departments_clean',
 'offices_clean',
 'demographic_data_consent_applies',
 'language_clean',
 'content_clean']

In [318]:
adzuna_cleaned['salary_currency']=pd.NA

In [319]:
greenhouse_clean = greenhouse_clean.rename(columns={
    'baseline_salary_currency': 'salary_currency'
})

In [321]:
adzuna_cleaned[['salary_min', 'salary_max', 'salary_currency']].head()

   salary_min  salary_max salary_currency
0         NaN         NaN            <NA>
1         NaN         NaN            <NA>
2         NaN         NaN            <NA>
3         NaN         NaN            <NA>
4         NaN         NaN            <NA>

In [322]:
greenhouse_clean[['salary_min', 'salary_max', 'salary_currency']].head()

   salary_min  salary_max salary_currency
0         NaN         NaN            None
1         NaN         NaN            None
2         NaN         NaN            None
3         NaN         NaN            None
4         NaN         NaN            None

In [323]:
greenhouse_clean['salary_currency'].value_counts(dropna=False)

salary_currency
None    2152
USD       74
EUR       30
INR       13
SGD        5
CAD        5
BRL        4
GBP        4
ILS        3
KRW        3
AUD        3
MYR        3
MXN        2
TWD        1
HKD        1
SEK        1
PLN        1
Name: count, dtype: int64

In [324]:
adzuna_cleaned['salary_currency'].value_counts(dropna=False)

salary_currency
<NA>    4964
Name: count, dtype: int64

In [326]:
adzuna_cleaned[['latitude', 'longitude', 'city', 'state',
 'standard_role', 'category', 'contract_time', 'contract_type']
].isna().sum()

latitude         2337
longitude        2337
city                0
state               0
standard_role       0
category            0
contract_time       0
contract_type       0
dtype: int64

In [328]:
cols = ['city', 'state', 'contract_time', 'contract_type']

adzuna_cleaned[cols] = adzuna_cleaned[cols].replace('Unknown',pd.NA)

In [330]:
print("Adzuna:", len(adzuna_cleaned.columns))
print("Greenhouse:", len(greenhouse_clean.columns))

Adzuna: 19
Greenhouse: 33

In [344]:
common_columns = sorted(
    set(adzuna_cleaned.columns) &
    set(greenhouse_clean.columns)
)

print(common_columns)
print("Common columns:", len(common_columns))

['absolute_url', 'company_name', 'content_clean', 'created', 'created_date', 'created_time', 'id', 'location_clean', 'salary_currency', 'salary_max', 'salary_min', 'title']
Common columns: 12

In [332]:
all_columns = sorted(
    set(adzuna_cleaned.columns) |
    set(greenhouse_clean.columns)
)

print(all_columns)
print("Total columns:", len(all_columns))

['absolute_url', 'ai_opt_out_request_url', 'category', 'city', 'company_name', 'content_clean', 'contract_time', 'contract_type', 'created', 'demographic_data_consent_applies', 'departments_clean', 'education', 'first_published_date', 'first_published_time', 'ic_or_mg', 'id', 'include_ai_disclaimer', 'internal_job_id', 'job_level', 'job_type', 'language_clean', 'latitude', 'location_clean', 'longitude', 'offices_clean', 'other_market_salary_currency', 'other_market_salary_max', 'other_market_salary_min', 'pay_transparency_max', 'pay_transparency_min', 'pay_transparency_unit', 'region', 'requisition_id', 'salary_currency', 'salary_is_predicted', 'salary_max', 'salary_min', 'standard_role', 'state', 'title', 'updated_at', 'working_model_clean']
Total columns: 42

In [333]:
adzuna_cleaned['created_date'] = adzuna_cleaned['created'].dt.date
adzuna_cleaned['created_time'] = adzuna_cleaned['created'].dt.time

In [335]:
adzuna_cleaned[['created', 'created_date', 'created_time']].head()

                    created created_date created_time
0 2026-07-03 00:54:22+00:00   2026-07-03     00:54:22
1 2026-07-10 03:46:23+00:00   2026-07-10     03:46:23
2 2026-07-03 00:54:32+00:00   2026-07-03     00:54:32
3 2026-07-09 17:58:24+00:00   2026-07-09     17:58:24
4 2026-07-03 00:54:21+00:00   2026-07-03     00:54:21

In [336]:
adzuna_cleaned[['created_date', 'created_time']].dtypes

created_date    object
created_time    object
dtype: object

In [337]:
adzuna_cleaned['created_date'] = pd.to_datetime(
    adzuna_cleaned['created_date']
)

In [338]:
adzuna_cleaned[['created_date', 'created_time']].dtypes

created_date    datetime64[ns]
created_time            object
dtype: object

In [339]:
adzuna_only = sorted(
    set(adzuna_cleaned.columns) - set(greenhouse_clean.columns)
)

print("Adzuna-only columns:")
print(adzuna_only)

Adzuna-only columns:
['category', 'city', 'contract_time', 'contract_type', 'created_date', 'created_time', 'latitude', 'longitude', 'salary_is_predicted', 'standard_role', 'state']

In [340]:
adzuna_cleaned = adzuna_cleaned.drop(
    columns=['salary_is_predicted'],
    errors='ignore'
)

In [341]:
greenhouse_only = sorted(
    set(greenhouse_clean.columns) - set(adzuna_cleaned.columns)
)

print("Greenhouse-only columns:")
print(greenhouse_only)

Greenhouse-only columns:
['ai_opt_out_request_url', 'demographic_data_consent_applies', 'departments_clean', 'education', 'first_published_date', 'first_published_time', 'ic_or_mg', 'include_ai_disclaimer', 'internal_job_id', 'job_level', 'job_type', 'language_clean', 'offices_clean', 'other_market_salary_currency', 'other_market_salary_max', 'other_market_salary_min', 'pay_transparency_max', 'pay_transparency_min', 'pay_transparency_unit', 'region', 'requisition_id', 'updated_at', 'working_model_clean']

In [342]:
greenhouse_clean = greenhouse_clean.rename(columns={
    'first_published_date': 'created_date',
    'first_published_time': 'created_time'
})

In [353]:
df.to_csv("greenhouse_clean.csv", index=False)

In [347]:
print("Adzuna dtypes:")
print(adzuna_cleaned[common_columns].dtypes)

print("\nGreenhouse dtypes:")
print(greenhouse_clean[common_columns].dtypes)

Adzuna dtypes:
absolute_url                    object
company_name                    object
content_clean                   object
created            datetime64[ns, UTC]
created_date            datetime64[ns]
created_time                    object
id                               int64
location_clean                  object
salary_currency                 object
salary_max                     float64
salary_min                     float64
title                           object
dtype: object

Greenhouse dtypes:
absolute_url                    object
company_name                    object
content_clean                   object
created            datetime64[ns, UTC]
created_date            datetime64[ns]
created_time                    object
id                               int64
location_clean                  object
salary_currency                 object
salary_max                     float64
salary_min                     float64
title                           object
dtype: object

In [348]:
all_columns = sorted(
    set(adzuna_cleaned.columns) |
    set(greenhouse_clean.columns)
)

print("Total columns:", len(all_columns))

Total columns: 41

In [349]:
adzuna_final = adzuna_cleaned.reindex(columns=all_columns)
greenhouse_final = greenhouse_clean.reindex(columns=all_columns)

In [350]:
print(adzuna_final.shape)
print(greenhouse_final.shape)

print(adzuna_final.columns.equals(greenhouse_final.columns))

(4964, 41)
(2305, 41)
True

In [351]:
jobs_cleaned = pd.concat([adzuna_final, greenhouse_final],ignore_index=True)

C:\Users\amrit\AppData\Local\Temp\ipykernel_17336\1677239209.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  jobs_cleaned = pd.concat([adzuna_final, greenhouse_final],ignore_index=True)

In [352]:
jobs_cleaned.shape

(7269, 41)

In [354]:
jobs_cleaned.to_csv("jobs_cleaned.csv", index=False)

In [355]:
print(jobs_cleaned.shape)

print("\nDuplicate rows:", jobs_cleaned.duplicated().sum())

print("\nSource row counts:")
print("Expected Adzuna:", len(adzuna_cleaned))
print("Expected Greenhouse:", len(greenhouse_clean))
print("Merged:", len(jobs_cleaned))

(7269, 41)

Duplicate rows: 0

Source row counts:
Expected Adzuna: 4964
Expected Greenhouse: 2305
Merged: 7269