In [1]:
import pandas as pd

In [56]:
df1=pd.read_csv('jobs_cleaned_enriched.csv')

In [57]:
df=df1.copy()

In [59]:
df.head()

,absolute_url,ai_opt_out_request_url,category,city,company_name,content_clean,contract_time,contract_type,created,created_date,...,region,requisition_id,salary_currency,salary_max,salary_min,standard_role,state,title,updated_at,working_model_clean
0,https://www.adzuna.in/land/ad/5785772072?se=bi...,NaN,Engineering Jobs,Bangalore,ABB,"This job is with ABB, an inclusive employer an...",full_time,NaN,2026-07-03 00:54:22+00:00,2026-07-03,...,NaN,NaN,NaN,NaN,NaN,Software Engineer,Karnataka,software engineer,NaN,NaN
1,https://www.adzuna.in/land/ad/5794768004?se=bi...,NaN,IT Jobs,Bangalore,Kyndryl,"This job is with Kyndryl, an inclusive employe...",full_time,NaN,2026-07-10 03:46:23+00:00,2026-07-10,...,NaN,NaN,NaN,NaN,NaN,Software Engineer,Karnataka,software engineer,NaN,NaN
2,https://www.adzuna.in/land/ad/5785773087?se=bi...,NaN,IT Jobs,Hyderabad,Cornerstone OnDemand,"This job is with Cornerstone OnDemand, an incl...",full_time,NaN,2026-07-03 00:54:32+00:00,2026-07-03,...,NaN,NaN,NaN,NaN,NaN,Software Engineer,Telangana,software engineer,NaN,NaN
3,https://www.adzuna.in/land/ad/5794153227?se=bi...,NaN,IT Jobs,Mumbai,Morningstar,"This job is with Morningstar, an inclusive emp...",full_time,NaN,2026-07-09 17:58:24+00:00,2026-07-09,...,NaN,NaN,NaN,NaN,NaN,Software Engineer,Maharashtra,software engineer,NaN,NaN
4,https://www.adzuna.in/land/ad/5785771924?se=bi...,NaN,IT Jobs,Mumbai,Morningstar,"This job is with Morningstar, an inclusive emp...",full_time,NaN,2026-07-03 00:54:21+00:00,2026-07-03,...,NaN,NaN,NaN,NaN,NaN,Software Engineer,Maharashtra,software engineer,NaN,NaN

In [60]:
df.shape

(7269, 41)

In [61]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
absolute_url,7269,7269,https://www.adzuna.in/land/ad/5785772072?se=bi...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ai_opt_out_request_url,592,592,http://app.greenhouse.io/ai_opt_out_request/jo...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,4964,18,IT Jobs,4680,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,3816,70,Bangalore,1335,NaN,NaN,NaN,NaN,NaN,NaN,NaN
company_name,7269,2505,Stripe,524,NaN,NaN,NaN,NaN,NaN,NaN,NaN
content_clean,7269,6692,"This job is with Kyndryl, an inclusive employe...",51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contract_time,3900,2,full_time,3897,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contract_type,256,2,permanent,147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created,7269,6193,2026-07-03 00:54:23+00:00,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_date,7269,1339,2026-07-03,329,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_time,7269,5906,00:54:11,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
demographic_data_consent_applies,2305.0,NaN,NaN,NaN,0.322777,0.46764,0.0,0.0,0.0,1.0,1.0
departments_clean,2305,381,Sales,190,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education,79,27,education_optional,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ic_or_mg,421,2,IC,346,NaN,NaN,NaN,NaN,NaN,NaN,NaN
id,7269.0,NaN,NaN,NaN,3653887628.600358,2545939360.177222,1497543.0,1155089713.0,4686706935.0,5761955780.0,8632000002.0
include_ai_disclaimer,983,1,False,983,NaN,NaN,NaN,NaN,NaN,NaN,NaN
internal_job_id,2292.0,NaN,NaN,NaN,1290226406.47993,2419457278.206994,951280.0,3365374.75,3452168.5,3487015.75,6447479002.0
job_level,381,9,Professional - IC,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN
job_type,381,3,Standard,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
language_clean,2305,4,English,2283,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,2627.0,NaN,NaN,NaN,19.012119,5.147701,8.38159,17.40275,18.5062,20.2697,32.72965
location_clean,7261,691,"Bangalore, Karnataka",1305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
longitude,2627.0,NaN,NaN,NaN,76.465634,3.075401,70.77785,73.84735,77.224601,78.50806,88.34373
offices_clean,2292,333,US,305,NaN,NaN,NaN,NaN,NaN,NaN,NaN
other_market_salary_currency,130,16,USD,51,NaN,NaN,NaN,NaN,NaN,NaN,NaN
other_market_salary_max,50.0,NaN,NaN,NaN,124960.464,34280.630294,50003.2,104000.0,134000.0,148875.0,216000.0
other_market_salary_min,50.0,NaN,NaN,NaN,124960.464,34280.630294,50003.2,104000.0,134000.0,148875.0,216000.0
pay_transparency_max,196.0,NaN,NaN,NaN,199045.918367,75934.80965,50000.0,133750.0,195000.0,240000.0,484000.0
pay_transparency_min,196.0,NaN,NaN,NaN,151227.040816,59780.931128,49000.0,110000.0,146000.0,192000.0,330000.0
pay_transparency_unit,198,2,USD,197,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,381,5,North America,149,NaN,NaN,NaN,NaN,NaN,NaN,NaN
requisition_id,1702,1376,JR101333,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary_currency,302,16,USD,178,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary_max,2590.0,NaN,NaN,NaN,1450841.438301,1043518.862373,20000.0,700000.0,1200000.0,2000000.0,9000000.0
salary_min,2291.0,NaN,NaN,NaN,706441.155914,578620.233353,3000.0,300000.0,500000.0,1000000.0,4500000.0
standard_role,4964,25,Frontend Developer,393,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,3840,25,Karnataka,1339,NaN,NaN,NaN,NaN,NaN,NaN,NaN
title,7269,2913,frontend developer,391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
updated_at,2305,1064,2026-07-06 16:17:28+00:00,296,NaN,NaN,NaN,NaN,NaN,NaN,NaN
working_model_clean,381,7,Flexible,294,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.nunique().sort_values(ascending=False)

absolute_url                        7269
id                                  7269
content_clean                       6692
created                             6193
created_time                        5906
title                               2913
company_name                        2505
internal_job_id                     1936
requisition_id                      1376
created_date                        1339
updated_at                          1064
location_clean                       691
ai_opt_out_request_url               592
departments_clean                    381
offices_clean                        333
salary_max                           213
salary_min                           193
longitude                            125
latitude                             122
pay_transparency_max                  78
pay_transparency_min                  72
city                                  70
education                             27
standard_role                         25
state                                 25
other_market_salary_min               24
other_market_salary_max               24
category                              18
other_market_salary_currency          16
salary_currency                       16
job_level                              9
working_model_clean                    7
region                                 5
language_clean                         4
job_type                               3
pay_transparency_unit                  2
ic_or_mg                               2
demographic_data_consent_applies       2
contract_type                          2
contract_time                          2
include_ai_disclaimer                  1
dtype: int64

In [63]:
df.duplicated().sum()

0

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7269 entries, 0 to 7268
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   absolute_url                      7269 non-null   object
 1   ai_opt_out_request_url            592 non-null    object
 2   category                          4964 non-null   object
 3   city                              3816 non-null   object
 4   company_name                      7269 non-null   object
 5   content_clean                     7269 non-null   object
 6   contract_time                     3900 non-null   object
 7   contract_type                     256 non-null    object
 8   created                           7269 non-null   object
 9   created_date                      7269 non-null   object
 10  created_time                      7269 non-null   object
 11  demographic_data_consent_applies  2305 non-null   float64
 12  departments_clean                 2305 non-null   object
 13  education                         79 non-null     object
 14  ic_or_mg                          421 non-null    object
 15  id                                7269 non-null   int64
 16  include_ai_disclaimer             983 non-null    object
 17  internal_job_id                   2292 non-null   float64
 18  job_level                         381 non-null    object
 19  job_type                          381 non-null    object
 20  language_clean                    2305 non-null   object
 21  latitude                          2627 non-null   float64
 22  location_clean                    7261 non-null   object
 23  longitude                         2627 non-null   float64
 24  offices_clean                     2292 non-null   object
 25  other_market_salary_currency      130 non-null    object
 26  other_market_salary_max           50 non-null     float64
 27  other_market_salary_min           50 non-null     float64
 28  pay_transparency_max              196 non-null    float64
 29  pay_transparency_min              196 non-null    float64
 30  pay_transparency_unit             198 non-null    object
 31  region                            381 non-null    object
 32  requisition_id                    1702 non-null   object
 33  salary_currency                   302 non-null    object
 34  salary_max                        2590 non-null   float64
 35  salary_min                        2291 non-null   float64
 36  standard_role                     4964 non-null   object
 37  state                             3840 non-null   object
 38  title                             7269 non-null   object
 39  updated_at                        2305 non-null   object
 40  working_model_clean               381 non-null    object
dtypes: float64(10), int64(1), object(30)
memory usage: 2.3+ MB

In [65]:
missing_value=df.isnull().sum()
print(missing_value[missing_value>0].sort_values(ascending=False))

other_market_salary_min             7219
other_market_salary_max             7219
education                           7190
other_market_salary_currency        7139
pay_transparency_min                7073
pay_transparency_max                7073
pay_transparency_unit               7071
contract_type                       7013
salary_currency                     6967
working_model_clean                 6888
region                              6888
job_level                           6888
job_type                            6888
ic_or_mg                            6848
ai_opt_out_request_url              6677
include_ai_disclaimer               6286
requisition_id                      5567
salary_min                          4978
offices_clean                       4977
internal_job_id                     4977
language_clean                      4964
departments_clean                   4964
demographic_data_consent_applies    4964
updated_at                          4964
salary_max                          4679
longitude                           4642
latitude                            4642
city                                3453
state                               3429
contract_time                       3369
standard_role                       2305
category                            2305
location_clean                         8
dtype: int64

In [66]:
missing_precentage=(df.isnull().sum()/len(df)*100).sort_values(ascending=False)
print(missing_precentage[missing_precentage>0])

other_market_salary_min             99.312147
other_market_salary_max             99.312147
education                           98.913193
other_market_salary_currency        98.211583
pay_transparency_max                97.303618
pay_transparency_min                97.303618
pay_transparency_unit               97.276104
contract_type                       96.478195
salary_currency                     95.845371
job_type                            94.758564
job_level                           94.758564
working_model_clean                 94.758564
region                              94.758564
ic_or_mg                            94.208282
ai_opt_out_request_url              91.855826
include_ai_disclaimer               86.476819
requisition_id                      76.585500
salary_min                          68.482597
offices_clean                       68.468840
internal_job_id                     68.468840
updated_at                          68.289999
language_clean                      68.289999
departments_clean                   68.289999
demographic_data_consent_applies    68.289999
salary_max                          64.369239
latitude                            63.860228
longitude                           63.860228
city                                47.503095
state                               47.172926
contract_time                       46.347503
category                            31.710001
standard_role                       31.710001
location_clean                       0.110056
dtype: float64

In [67]:
df['created'] = pd.to_datetime( df['created'],errors='coerce',utc=True)

In [68]:
df['created_date'] = pd.to_datetime(df['created_date'],errors='coerce')

In [69]:
df[['created', 'created_date', 'created_time']].dtypes

created         datetime64[ns, UTC]
created_date         datetime64[ns]
created_time                 object
dtype: object

In [70]:
df['company_name'].value_counts().head(10)

company_name
Stripe         524
Datadog        421
MongoDB        381
Brex           266
Figma          169
Flexport       148
Asana          146
Accenture      116
Gusto, Inc.     78
Kyndryl         71
Name: count, dtype: int64

In [71]:
df['category'].notna().value_counts()

category
True     4964
False    2305
Name: count, dtype: int64

In [72]:
df['source'] = df['category'].notna().map({True: 'Adzuna', False: 'Greenhouse'})

In [73]:
df['source'].value_counts()

source
Adzuna        4964
Greenhouse    2305
Name: count, dtype: int64

In [74]:

df.groupby('source').apply(lambda x: x.isnull().sum())

C:\Users\amrit\AppData\Local\Temp\ipykernel_6512\1080145891.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('source').apply(lambda x: x.isnull().sum())

,absolute_url,ai_opt_out_request_url,category,city,company_name,content_clean,contract_time,contract_type,created,created_date,...,requisition_id,salary_currency,salary_max,salary_min,standard_role,state,title,updated_at,working_model_clean,source
source,,,,,,,,,,,,,,,,,,,,,
Adzuna,0,4964,0,1155,0,0,1064,4708,0,0,...,4964,4964,2597,2896,0,1131,0,4964,4964,0
Greenhouse,0,1713,2305,2298,0,0,2305,2305,0,0,...,603,2003,2082,2082,2305,2298,0,0,1924,0

In [75]:
missing_by_source = (  df.groupby('source').apply(lambda x: x.isnull().mean() * 100).T.sort_values('Adzuna', ascending=False))
missing_by_source

C:\Users\amrit\AppData\Local\Temp\ipykernel_6512\1884889551.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_by_source = (  df.groupby('source').apply(lambda x: x.isnull().mean() * 100).T.sort_values('Adzuna', ascending=False))

source                                Adzuna  Greenhouse
include_ai_disclaimer             100.000000   57.353579
requisition_id                    100.000000   26.160521
pay_transparency_unit             100.000000   91.409978
pay_transparency_min              100.000000   91.496746
pay_transparency_max              100.000000   91.496746
other_market_salary_min           100.000000   97.830803
other_market_salary_max           100.000000   97.830803
other_market_salary_currency      100.000000   94.360087
offices_clean                     100.000000    0.563991
salary_currency                   100.000000   86.898048
ai_opt_out_request_url            100.000000   74.316703
language_clean                    100.000000    0.000000
job_type                          100.000000   83.470716
job_level                         100.000000   83.470716
internal_job_id                   100.000000    0.563991
region                            100.000000   83.470716
ic_or_mg                          100.000000   81.735358
education                         100.000000   96.572668
departments_clean                 100.000000    0.000000
demographic_data_consent_applies  100.000000    0.000000
updated_at                        100.000000    0.000000
working_model_clean               100.000000   83.470716
contract_type                      94.842869  100.000000
salary_min                         58.340048   90.325380
salary_max                         52.316680   90.325380
longitude                          47.078969  100.000000
latitude                           47.078969  100.000000
city                               23.267526   99.696312
state                              22.784045   99.696312
contract_time                      21.434327  100.000000
standard_role                       0.000000  100.000000
title                               0.000000    0.000000
absolute_url                        0.000000    0.000000
location_clean                      0.000000    0.347072
id                                  0.000000    0.000000
created_time                        0.000000    0.000000
created_date                        0.000000    0.000000
created                             0.000000    0.000000
content_clean                       0.000000    0.000000
company_name                        0.000000    0.000000
category                            0.000000  100.000000
source                              0.000000    0.000000

In [76]:
df.dtypes

absolute_url                                     object
ai_opt_out_request_url                           object
category                                         object
city                                             object
company_name                                     object
content_clean                                    object
contract_time                                    object
contract_type                                    object
created                             datetime64[ns, UTC]
created_date                             datetime64[ns]
created_time                                     object
demographic_data_consent_applies                float64
departments_clean                                object
education                                        object
ic_or_mg                                         object
id                                                int64
include_ai_disclaimer                            object
internal_job_id                                 float64
job_level                                        object
job_type                                         object
language_clean                                   object
latitude                                        float64
location_clean                                   object
longitude                                       float64
offices_clean                                    object
other_market_salary_currency                     object
other_market_salary_max                         float64
other_market_salary_min                         float64
pay_transparency_max                            float64
pay_transparency_min                            float64
pay_transparency_unit                            object
region                                           object
requisition_id                                   object
salary_currency                                  object
salary_max                                      float64
salary_min                                      float64
standard_role                                    object
state                                            object
title                                            object
updated_at                                       object
working_model_clean                              object
source                                           object
dtype: object

In [77]:
df['updated_at'] = pd.to_datetime( df['updated_at'],errors='coerce',utc=True)

In [78]:
df['updated_at'].dtype

datetime64[ns, UTC]

In [79]:
greenhouse_df = df[df['source'] == 'Greenhouse'].copy()

print("Greenhouse rows:", len(greenhouse_df))

Greenhouse rows: 2305

In [5]:
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Edge(options=options)

print("Driver started successfully")

Driver started successfully

In [85]:
driver.get("https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583")
time.sleep(3)

print("URL:", driver.current_url)
print("TITLE:", driver.title)

page_text = driver.find_element(By.TAG_NAME, "body").text

print("\nPAGE TEXT:")
print(page_text[:2000])

URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583
TITLE: Careers | Cockroach Labs

PAGE TEXT:
Products
Solutions
Resources
Pricing
Company
Sign In
Contact Us
Try For Free
Careers
Open Interview Process
Product and Engineering
Open Positions
Don't see a position and want to join our mission? Apply through Applications (General) at the top of the page and the team will keep you in mind for future openings.
Cockroach Labs has an office-first approach, with Roachers coming into one of our offices on Monday, Tuesday and Thursday and working flexibly the rest of the week. While we’ve learned valuable lessons working remotely, nothing can replace the connection, creativity, and fun that occurs when Roachers get together and we are committed to fostering a workplace that encourages collaboration and allows us all to do our best work.
Please note: Remote-based designations are exclusively reserved for in-region required roles in Field Sales, Sales Engineering, and Enterprise Architecture. Exceptions may be made on a case-by-case basis on rare occasions for niche and/or expert roles at the executive team’s discretion.
If you are a resident of California, the United Kingdom or the European Economic Area, the Cockroach Labs Employee Privacy Policy, available here, may apply to you.
PRODUCT
Platform/Architecture
Aegis
Cockroach Continuum
Migrations
Integrations
Pricing
Sign in
SOLUTIONS
Customers
Database Modernization
High availability and disaster recovery
BY INDUSTRY
AI Innovators
Banking & Fintech
Cybersecurity
Gambling
Gaming
Healthcare
Manufacturing & Logistics
Media & Streaming
Quant/Trading & Research
Retail & eCommerce
SaaS
BY USE CASE
Vector Search
Banking & Wallet
Gaming
Identity Access Management
IoT & Device Mgmt
Orders & Inventory Management
Payments
Routing & Logistics
User Metadata
BY INITIATIVE
Database Modernization
Architectural Simplification
RESOURCES
Documentation
CONNECT
Events
Podcast
Professional Services
Support
Webinars
LEARN
Blog
Cockroach University
Competitive Comparisons
Guides
Product Demos
COMPANY
About
Careers
Contact Us
Legal Notices
Ne

In [88]:
url = "https://www.brex.com/careers/8432702002?gh_jid=8432702002"

driver.get(url)
time.sleep(3)

print("URL:", driver.current_url)
print("TITLE:", driver.title)

page_text = driver.find_element(By.TAG_NAME, "body").text

print("\nPAGE TEXT:")
print(page_text[:2000])

URL: https://www.brex.com/careers/8432702002?gh_jid=8432702002
TITLE: Staff Product Manager | Career Opportunities

PAGE TEXT:
Products
Solutions
Resources
Customers
Pricing
Sign in
See a demo
Get started
Careers
Staff Product Manager
Staff Product Manager
New York, New York, United States
Why join us
Brex is the intelligent finance platform that enables companies to spend smarter and move faster in more than 200 markets. By combining global corporate cards and banking with intuitive spend management, bill pay, and travel software, Brex enables founders and finance teams to accelerate operations, gain real-time visibility, and control spend effortlessly. Brex’s AI-native automation and world-class service eliminate manual expense and accounting tasks for customers so they can focus on what matters most. Tens of thousands of the world's best companies run on Brex, including DoorDash, Coinbase, Robinhood, Zoom, Plaid, Reddit, and SeatGeek.
Working at Brex allows you to push your limits, challenge the status quo, and collaborate with some of the brightest minds in the industry. We’re committed to building a diverse team and inclusive culture and believe your potential should only be limited by how big you can dream. We make this a reality by empowering you with the tools, resources, and support you need to grow your career.
Product at Brex
The Product team is at the forefront of Brex's mission to empower employees anywhere to make better financial decisions. With a deep understanding of the business, we identify and scope out the most impactful opportunities for Brex to tackle. We are responsible for aligning cross-functional teams — such as Engineering, Legal, Compliance, and Design — on key decisions. We set strategy and drive products from inception to launch, enabling Brex to grow rapidly and help our customers reach their full potential.
What you’ll do
As a Staff Product Manager at Brex, you will operate at the intersection of product strategy, technical depth, and business impact. You will define and drive multi-quarter strategy within one of Brex’s most critical product domains, leading

In [89]:
url = "https://job-boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004"

driver.get(url)
time.sleep(3)

print("URL:", driver.current_url)
print("TITLE:", driver.title)

page_text = driver.find_element(By.TAG_NAME, "body").text

print("\nPAGE TEXT:")
print(page_text[:1500])

URL: https://job-boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004
TITLE: Job Application for Account Executive, Strategic at Figma

PAGE TEXT:
Back to jobs
Account Executive, Strategic
San Francisco, CA • New York, NY • United States
Apply
Figma is growing our team of passionate creatives and builders on a mission to make design accessible to all. Figma’s platform helps teams bring ideas to life—whether you're brainstorming, creating a prototype, translating designs into code, or iterating with AI. From idea to product, Figma empowers teams to streamline workflows, move faster, and work together in real time from anywhere in the world. If you're excited to shape the future of design and collaboration, join us!
We are looking for a Strategic Account Executive who will play a critical role driving sales and maximizing expansion opportunities with a defined list of top-tier Enterprise customers. You will be responsible for targeting, building and nurturing positive relationships with key C-level decision-makers, understanding complex business needs, and delivering innovative solutions across our product suite. This is an opportunity to accelerate your career, learn from leading sellers in the industry and build an incredible network of cross functional partners throughout Figma.
This is a full time role that can be held from one of our US hubs or remotely in the United States.
What you'll do at Figma:
Manage a defined list of named strategic accounts to consistently meet or exceed quarterly and annual sales targets
Apply effective discovery and value-selling techniques to build and strengthen C-level relationships for

In [91]:
greenhouse_df[greenhouse_df['absolute_url'].str.contains('gh_jid', case=False, na=False )][['id', 'title', 'absolute_url']].head(10)

,id,title,absolute_url
4964,7954688,"Account Executive, AI Sales (Grower)",https://stripe.com/jobs/search?gh_jid=7954688
4965,8042978,"Account Executive, Commercial Grower (Japanese...",https://stripe.com/jobs/search?gh_jid=8042978
4966,7789539,"Account Executive, Commercial Hunter (Japanese...",https://stripe.com/jobs/search?gh_jid=7789539
4967,7893199,"Account Executive, Cross Border China",https://stripe.com/jobs/search?gh_jid=7893199
4968,7993151,"Account Executive - Enterprise, Grower",https://stripe.com/jobs/search?gh_jid=7993151
4969,8054695,"Account Executive, Enterprise - Grower",https://stripe.com/jobs/search?gh_jid=8054695
4970,7997555,"Account Executive, Enterprise - Grower",https://stripe.com/jobs/search?gh_jid=7997555
4971,7717676,"Account Executive, Enterprise Grower (Australia)",https://stripe.com/jobs/search?gh_jid=7717676
4972,7997146,"Account Executive - Enterprise, Growth",https://stripe.com/jobs/search?gh_jid=7997146
4973,7994330,"Account Executive, Enterprise - Hunter",https://stripe.com/jobs/search?gh_jid=7994330

In [92]:
url = "https://job-boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004"

In [93]:
driver.get(url)
time.sleep(3)

page_text = driver.find_element(By.TAG_NAME, "body").text

print(page_text[:5000])

Back to jobs
Account Executive, Strategic
San Francisco, CA • New York, NY • United States
Apply
Figma is growing our team of passionate creatives and builders on a mission to make design accessible to all. Figma’s platform helps teams bring ideas to life—whether you're brainstorming, creating a prototype, translating designs into code, or iterating with AI. From idea to product, Figma empowers teams to streamline workflows, move faster, and work together in real time from anywhere in the world. If you're excited to shape the future of design and collaboration, join us!
We are looking for a Strategic Account Executive who will play a critical role driving sales and maximizing expansion opportunities with a defined list of top-tier Enterprise customers. You will be responsible for targeting, building and nurturing positive relationships with key C-level decision-makers, understanding complex business needs, and delivering innovative solutions across our product suite. This is an opportunity to accelerate your career, learn from leading sellers in the industry and build an incredible network of cross functional partners throughout Figma.
This is a full time role that can be held from one of our US hubs or remotely in the United States.
What you'll do at Figma:
Manage a defined list of named strategic accounts to consistently meet or exceed quarterly and annual sales targets
Apply effective discovery and value-selling techniques to build and strengthen C-level relationships for every account in your book
Align with executives on business challenges and gain sponsorship for enterprise wide deployments for a suite of products, identifying where Figma’s roadmap and innovations fit in the long term
Conduct thorough analysis to create strategic account plans that outline company priorities and initiatives, multi-threading at at senior level to build on expansion opportunities
Co-create with cross-functional partners to expertly position Figma, drive deals forward and ensure customer success
Leverage opportunities to advance executive level relationships through in-person meetings and networking opportunities
We'd love to hear from you if you have:
Experience closing sales, over multiple years, for a software or SaaS business with the highest tier of Enterprise customers (5000+ FTEs), selling to executives
Consistent performance meeting pipeline generation targets for net new business
Demonstrated experience successfully managing complex sales cycles (9 months+)
Proficiency in a sales methodology and process that creates value for customers
While it’s not required, it’s an added plus if you also have:
Experience selling solutions to technical audiences at the highest level in Engineering, Product and Design teams
Demonstrated ability to succeed in a changing environment
Certified in deal qualification and prospect discovery
At Figma, one of our values is Grow as you go. We believe in hiring smart, curious people who are excited to learn and develop their skills. If you’re excited about this role but your past experience doesn’t align perfectly with the points outlined in the job description, we encourage you to apply anyways. You may be just the right candidate for this or other roles.
Pay Transparency Disclosure
Job level and actual compensation will be decided based on factors including, but not limited to, individual qualifications objectively assessed during the interview process (including skills and prior relevant experience, potential impact, and scope of role), market demands, and specific work location.
Figma offers equity to employees, as well as a competitive package of additional benefits, including health, dental, and vision coverage; retirement benefits with company contributions; parental leave and reproductive or family planning support; mental health and wellness benefits; and paid time off. Figma provides paid sick leave, holidays, and other leave benefits in compliance with applicable federal, state, and local laws, including the requirements of the Washington Minimum Wage Act and related regulations. Exempt employees are eligible for employer‑provided paid flexible PTO in addition to flexible paid sick leave. PTO is subject to manager approval. Additional benefits may include company recharge days, cell phone and home internet reimbursements, and a number of lifestyle spending accounts. Figma also offers sales incentive compensation for most sales roles and an annual bonus plan for eligible non-sales roles. All compensation and benefits are subject to applicable plan terms and may be modified by Figma at any time, consistent with applicable law.
Annual Base Salary Range:
$200,000 - $200,000 USD
At Figma we celebrate and support our differences. We know employing a team rich in diverse thoughts, experiences, and opinions allows our employees, our product and our community to flourish. Figma is an equal opportunity workplace - we are dedicated to equal employment opportunities regardless of race,

In [95]:
figma_url = "https://job-boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004"

figma_result = extract_figma_job(figma_url)

figma_result

{'location_clean': 'San Francisco, CA • New York, NY • United States',
 'salary_currency': 'USD',
 'salary_min': 200000.0,
 'salary_max': 200000.0,
 'education': None,
 'content_clean': 'Back to jobs\nAccount Executive, Strategic\nSan Francisco, CA • New York, NY • United States\nApply\nFigma is growing our team of passionate creatives and builders on a mission to make design accessible to all. Figma’s platform helps teams bring ideas to life—whether you\'re brainstorming, creating a prototype, translating designs into code, or iterating with AI. From idea to product, Figma empowers teams to streamline workflows, move faster, and work together in real time from anywhere in the world. If you\'re excited to shape the future of design and collaboration, join us!\nWe are looking for a Strategic Account Executive who will play a critical role driving sales and maximizing expansion opportunities with a defined list of top-tier Enterprise customers. You will be responsible for targeting, building and nurturing positive relationships with key C-level decision-makers, understanding complex business needs, and delivering innovative solutions across our product suite. This is an opportunity to accelerate your career, learn from leading sellers in the industry and build an incredible network of cross functional partners throughout Figma.\nThis is a full time role that can be held from one of our US hubs or remotely in the United States.\nWhat you\'ll do at Figma:\nManage a defined list of named strategic accounts to consistently meet or exceed quarterly and annual sales targets\nApply effective discovery and value-selling techniques to build and strengthen C-level relationships for every account in your book\nAlign with executives on business challenges and gain sponsorship for enterprise wide deployments for a suite of products, identifying where Figma’s roadmap and innovations fit in the long term\nConduct thorough analysis to create strategic account plans that outline company priorities and initiatives, multi-threading at at senior level to build on expansion opportunities\nCo-create with cross-functional partners to expertly position Figma, drive deals forward and ensure customer success\nLeverage opportunities to advance executive level relationships through in-person meetings and networking opportunities\nWe\'d love to hear from you if you have:\nExperience closing sales, over multiple years, for a software or SaaS business with the highest tier of Enterprise customers (5000+ FTEs), selling to executives\nConsistent performance meeting pipeline generation targets for net new business\nDemonstrated experience successfully managing complex sales cycles (9 months+)\nProficiency in a sales methodology and process that creates value for customers\nWhile it’s not required, it’s an added plus if you also have:\nExperience selling solutions to technical audiences at the highest level in Engineering, Product and Design teams\nDemonstrated ability to succeed in a changing environment\nCertified in deal qualification and prospect discovery\nAt Figma, one of our values is Grow as you go. We believe in hiring smart, curious people who are excited to learn and develop their skills. If you’re excited about this role but your past experience doesn’t align perfectly with the points outlined in the job description, we encourage you to apply anyways. You may be just the right candidate for this or other roles.\nPay Transparency Disclosure\nJob level and actual compensation will be decided based on factors including, but not limited to, individual qualifications objectively assessed during the interview process (including skills and prior relevant experience, potential impact, and scope of role), market demands, and specific work location. \nFigma offers equity to employees, as well as a competitive package of additional benefits, including health, dental, and vision coverage; retirement benefits with company contributions; parental leave and reproductive or family planning support; mental health and wellness benefits; and paid time off. Figma provides paid sick leave, holidays, and other leave benefits in compliance with applicable federal, state, and local laws, including the requirements of the Washington Minimum Wage Act and related regulations. Exempt employees are eligible for employer‑provided paid flexible PTO in addition to flexible paid sick leave. PTO is subject to manager approval. Additional benefits may include company recharge days, cell phone and home internet reimbursements, and a number of lifestyle spending accounts. Figma also offers sales incentive compensation for most sales roles and an annual bonus plan for eligible non-sales roles. All compensation and benefits are subject to applicable plan terms and may be modified by Figma at any time, consistent with applicable law.\nAnnual Base Salary Range:\n$200,000 - $200,000 USD\nAt Figma we celebrate and support our differences. We know employing a team rich in diverse thoughts, experiences, and opinions allows our employees, our product and our community to flourish. Figma is an equal opportunity workplace - we are dedicated to equal employment opportunities regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity/expression, veteran status, or any other characteristic protected by law. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements.\nWe will work to ensure individuals with disabilities are provided reasonable accommodation to apply for a role, participate in the interview process, perform essential job functions, and receive other benefits and privileges of employment. If you require accommodation, please reach out to accommodations-ext@figma.com. These modifications enable an individual with a disability to have an equal opportunity not only to get a job, but successfully perform their job tasks to the same extent as people without disabilities. \nExamples of accommodations include but are not limited to: \nHolding interviews in an accessible location\nEnabling closed captioning on video conferencing\nEnsuring all written communication be compatible with screen readers\nChanging the mode or format of interviews \nTo ensure the integrity of our hiring process and facilitate a more personal connection, we require all candidates keep their cameras on during video interviews. Additionally, if hired you will be required to attend in person onboarding.\nBy applying for this job, the candidate acknowledges and agrees that any personal data contained in their application or supporting materials will be processed in accordance with Figma\'s Candidate Privacy Notice.\nCreate a Job Alert\nInterested in building your career at Figma? Get future opportunities sent straight to your email.\nCreate alert\nApply for this job\n*\nindicates a required field\nAutofill my application\nFirst Name*\nLast Name*\nEmail*\nPhone\nCountry*\nPhone*\nLocation (City)*\nLocate me\nResume/CV*\nAttach\nAttach\nDropbox\nGoogle Drive\nEnter manually\nEnter manually\nAccepted file types: pdf, doc, docx, txt, rtf\nLinkedIn Profile\nOther Website\nWhy do you want to join Figma?*\nPlease share 3-4 sentences on why you want to join Figma\nPronouns\nSelect...\nIf you\'d like to, please let us know your pronouns.\nAdditional Information\nAdd a cover letter or anything else you\'d like to share\nFrom where do you intend to work? *\nPlease list city and state. (ie: San Francisco, CA) \nPreferred First Name\nAre you authorized to work in the country for which you applied? *\nSelect...\nHave you ever worked for Figma before, as an employee or a contractor/consultant? *\nSelect...\nVoluntary Self-Identification\nFor government reporting purposes, we ask candidates to respond to the below self-identification survey. Completion of the form is entirely voluntary. Whatever your decision, it will not be considered in the hiring process or thereafter. Any information that you do provide will be recorded and maintained in a confidential file.\nAs set forth in Figma’s Equal Employment Opportunity policy, we do not discriminate on the basis of any protected group status under any applicable law.\nGender\nSelect...\nAre you Hispanic/Latino?\nSelect...\nRace & Ethnicity Definitions\nIf you believe you belong to any of the categories of protected veterans listed below, please indicate by making the appropriate selection. As a government contractor subject to the Vietnam Era Veterans Readjustment Assistance Act (VEVRAA), we request this information in order to measure the effectiveness of the outreach and positive recruitment efforts we undertake pursuant to VEVRAA. Classification of protected categories is as follows:\nA "disabled veteran" is one of the following: a veteran of the U.S. military, ground, naval or air service who is entitled to compensation (or who but for the receipt of military retired pay would be entitled to compensation) under laws administered by the Secretary of Veterans Affairs; or a person who was discharged or released from active duty because of a service-connected disability.\nA "recently separated veteran" means any veteran during the three-year period beginning on the date of such veteran\'s discharge or release from active duty in the U.S. military, ground, naval, or air service.\nAn "active duty wartime or campaign badge veteran" means a veteran who served on active duty in the U.S. military, ground, naval or air service during a war, or in a campaign or expedition for which a campaign badge has been authorized under the laws administered by the Department of Defense.\nAn "Armed forces service medal veteran" means a veteran who, while serving on active duty in the U.S. military, ground, naval or air service, participated in a United States military operation for which an Armed Forces service medal was awarded pursuant to Executive Order 12985.\nVeteran Status\nSelect...\nVoluntary Self-Identification of Disability\nForm CC-305\nPage 1 of 1\nOMB Control Number 1250-0005\nExpires 07/31/2029\n\nWhy are you being asked to complete this form?\nWe are a federal contractor or subcontractor. The law requires us to provide equal employment opportunity to qualified people with disabilities. We have a goal of having at least 7% of our workers as people with disabilities. The law says we must measure our progress towards this goal. To do this, we must ask applicants and employees if they have a disability or have ever had one. People can become disabled, so we need to ask this question at least every five years.\nCompleting this form is voluntary, and we hope that you will choose to do so. Your answer is confidential. No one who makes hiring decisions will see it. Your decision to complete the form and your answer will not harm you in any way. If you want to learn more about the law or this form, visit the U.S. Department of Labor’s Office of Federal Contract Compliance Programs (OFCCP) website at www.dol.gov/ofccp.\nHow do you know if you have a disability?\nA disability is a condition that substantially limits one or more of your “major life activities.” If you have or have ever had such a condition, you are a person with a disability. Disabilities include, but are not limited to:\nAlcohol or other substance use disorder (not currently using drugs illegally)\nAutoimmune disorder, for example, lupus, fibromyalgia, rheumatoid arthritis, HIV/AIDS\nBlind or low vision\nCancer (past or present)\nCardiovascular or heart disease\nCeliac disease\nCerebral palsy\nDeaf or serious difficulty hearing\nDiabetes\nDisfigurement, for example, disfigurement caused by burns, wounds, accidents, or congenital disorders\nEpilepsy or other seizure disorder\nGastrointestinal disorders, for example, Crohn\'s Disease, irritable bowel syndrome\nIntellectual or developmental disability\nMental health conditions, for example, depression, bipolar disorder, anxiety disorder, schizophrenia, PTSD\nMissing limbs or partially missing limbs\nMobility impairment, benefiting from the use of a wheelchair, scooter, walker, leg brace(s) and/or other supports\nNervous system condition, for example, migraine headaches, Parkinson’s disease, multiple sclerosis (MS)\nNeurodivergence, for example, attention-deficit/hyperactivity disorder (ADHD), autism spectrum disorder, dyslexia, dyspraxia, other learning disabilities\nPartial or complete paralysis (any cause)\nPulmonary or respiratory conditions, for example, tuberculosis, asthma, emphysema\nShort stature (dwarfism)\nTraumatic brain injury\nDisability Status\nSelect...\nPUBLIC BURDEN STATEMENT: According to the Paperwork Reduction Act of 1995 no persons are required to respond to a collection of information unless such collection displays a valid OMB control number. This survey should take about 5 minutes to complete.\nSubmit application\nPowered by',
 'page_type': 'job_listing'}

In [96]:
figma_df = df[df['company_name'].str.contains('Figma', case=False, na=False)].copy()

print("Figma rows:", len(figma_df))

Figma rows: 169

In [97]:
figma_df[['id', 'title', 'absolute_url']].head(10)

,id,title,absolute_url
5488,5364702004,"Account Executive, Emerging Enterprise (Berlin...",https://boards.greenhouse.io/figma/jobs/536470...
5489,5426468004,"Account Executive, Enterprise",https://boards.greenhouse.io/figma/jobs/542646...
5490,5579204004,"Account Executive, Enterprise (Bengaluru, India)",https://boards.greenhouse.io/figma/jobs/557920...
5491,5783812004,"Account Executive, Enterprise (Berlin, Germany)",https://boards.greenhouse.io/figma/jobs/578381...
5492,5458801004,"Account Executive, Enterprise (London, United ...",https://boards.greenhouse.io/figma/jobs/545880...
5493,5428656004,"Account Executive, Enterprise (Paris, France)",https://boards.greenhouse.io/figma/jobs/542865...
5494,5753209004,"Account Executive, Enterprise (Singapore)",https://boards.greenhouse.io/figma/jobs/575320...
5495,5803515004,"Account Executive, Enterprise (Sydney or Melbo...",https://boards.greenhouse.io/figma/jobs/580351...
5496,5806875004,"Account Executive, Enterprise (Tokyo, Japan)",https://boards.greenhouse.io/figma/jobs/580687...
5497,5760223004,"Account Executive - Figma Weave (London, Unite...",https://boards.greenhouse.io/figma/jobs/576022...

In [98]:
figma_test_url = figma_df.iloc[0]['absolute_url']

print(figma_test_url)

https://boards.greenhouse.io/figma/jobs/5364702004?gh_jid=5364702004

In [99]:
figma_test_result = extract_figma_job(figma_test_url)

print(figma_test_result)

{'location_clean': None, 'salary_currency': None, 'salary_min': None, 'salary_max': None, 'education': None, 'content_clean': 'This website uses cookies, pixel tags, and local storage for performance, personalization, and marketing purposes. We use our own cookies and some from third parties. Only essential cookies are turned on by default. Cookies settings\nAllow all cookies\nDo not allow cookies\nProducts\nSolutions\nCommunity\nResources\nPricing\nLog in\nContact sales\nGet started for free\nCareers at Figma\nFigma is a design platform for teams who build products together. Our vision is to make design accessible to all because we know that nothing great is made alone.\nWe’re a team of makers who celebrate our differences and share a passion for our community. We’re hiring across our global hubs and remotely in the US and Canada.\nCome join us!\nSee open positions\nOur Values and Culture\nOur values and culture are the underpinning for all that we do at Figma—we believe that a great product is inextricably linked to a great internal community.\nBuild community\nWe’re multiplayer people who love the weird, wonderful magic that happens when people connect. We build bridges—with both our Figmates and our users.\nRun with it\nBuilding Figma is about taking initiative, being bold and charting a new course, not running a playbook. Figmates are building the future of design by tackling big, scary, exciting challenges like Figma’s future depends on it. Because it does.\nLove your craft\nWe build for builders and try to make complex things feel simple. We ask why until we get to the core and continually focus on solving the right problem, not just shipping work.\nGrow as you go\nWith humility and curiosity, we give and get the direct feedback we all need to become great. Everyone’s a work in progress, and we’re here to help each other grow.\nPlay\nPlaying is learning. We embrace spontaneous, unstructured exploration—because that’s where we find our best ideas.\nLife at Figma\nConnection and kindness are core to our culture (after all, we’re a group of people building a collaboration tool). We focus on lifting each other up instead of competing amongst ourselves, and we build relationships through numerous company traditions.\nFigmate Community Groups\nOur Figmate Communities are an essential part of our value of "Build Community." These groups are comprised of Figmates interested in developing community, social awareness, and education regarding groups with shared characteristics or life experiences, and are open to all Figmates regardless of whether or not they are part of that group or share those characteristics or life experiences themselves.\nMaker Week\nA time set aside once a year to pursue wild, silly, and imaginative ideas. The whole company takes part, and people can work on anything Figma-related that piques their curiosity.\nEarly career\nOur internship and early career programs let you work on meaningful Figma projects, get mentorship at every step, and grow as you go.\nLearn more\nBenefits\nCompetitive salary & equity\nHealth, Dental, & Vision\nRetirement with company contribution\nParental leave & fertility support\nMental health and wellness benefits\nGenerous PTO\nCompany recharge days\nLearning & development stipend\nWork from home stipend\nCell phone reimbursement\nLocations\nSan Francisco\nNew York City\nSeattle\nLondon\nParis\nBerlin\nTokyo\nSingapore\nBengaluru\nSydney\nSão Paulo\nTel Aviv\nJob Openings\nBusiness Development\nDistribution Partner Manager\nManager, Distribution Partnerships\nProduct Partner Manager\nStrategic Partner Manager\nBusiness Operations\nBusiness Operations\nDirector, Business Operations\nDirector, Business Systems\nDirector, Technical Revenue Accounting\nFederal Compliance Manager\nGTM Systems Architect\nIT Engineer, Internal AI Infrastructure\nManager, Security Operations\nSenior Accountant\nSenior Analyst, Revenue Transformation\nSenior Technical Revenue Analyst\nStrategic Finance\nStrategic Program Manager, Information Security\nTechnical Program Manager\nCustomer Operations and Support\nEnterprise Support Specialist, Korean Speaking (London, United Kingdom)\nManager, Technical Support (London, United Kingdom)\nSupport Engineer, AI Infrastructure & Tooling\nTechnical Quality Specialist\nVoice of the Customer Program Manager\nDesign\nBrand Designer, Product Launches\nDirector, Research - AI Evals\nExecutive Assistant, Design\nManager, Design - Systems & Infrastructure\nProduct Designer, AI Models\nProduct Designer, CMS\nProduct Designer, Design, Dev, & AI Tools\nProduct Designer, Design Systems\nProduct Designer, Growth & Monetization\nProduct Designer, Roundtripping (London, United Kingdom)\nResearcher, Figma Agentic Experiences\nEarly Career\nBrand Design Intern (Summer 2027)\nData Science Intern (2027)\nData Scientist, Core Data - PhD (2026)\nProduct Design Intern (2027)\nSoftware Engineer Intern (London, United Kingdom) (Summer 2027)\nSoftware Engineer Intern (Summer 2027)\nSoftware Engineer Intern (Winter 2027)\nEngineering\nAI Applied Scientist\nData Scientist, Finance\nDirector, Data Science\nForward Deployed Engineer\nManager, Software Engineering - AI Observability\nManager, Software Engineering - Billing\nManager, Software Engineering - Data Platform\nManager, Software Engineering - DevEx AI Tools\nManager, Software Engineering - Growth Platform\nManager, Software Engineering - Interaction Design\nSecurity Engineer\nSecurity Scientist\nSoftware Engineer - AI Platforms\nSoftware Engineer - AI Product\nSoftware Engineer - AI Product (London, United Kingdom)\nSoftware Engineer - Application Platform\nSoftware Engineer - C++\nSoftware Engineer - Data Infrastructure\nSoftware Engineer - Developer Experience\nSoftware Engineer - Distributed Systems\nSoftware Engineer - Full Stack\nSoftware Engineer - Graphics & Media\nSoftware Engineer - Growth & Monetization\nSoftware Engineer - Machine Learning\nSoftware Engineer - Mobile Web\nSoftware Engineer - Traffic\nTechnical Program Manager - Infrastructure\nLegal\nSenior Product Counsel\nMarketing\nBrand Events Manager\nDesigner Advocate\nDesigner Advocate (London, United Kingdom)\nDesigner Advocate, Partnerships\nEvents Manager\nExecutive Communications Manager\nField Marketing Manager, Third Party & Partner Events\nMarketing Engineer\nPeople\nDirector, People Partners - Product, Design & Engineering\nExecutive Assistant, Chief People Officer\nExecutive Assistant, People\nImmigration Program Manager\nManager, HRIS\nProduct\nManager, Product Management - Figma Platform Experience\nManager, Product Management - Roundtripping\nManager, Product Management - Roundtripping (London, United Kingdom)\nProduct Manager, Acquisition\nProduct Manager, AI Growth\nProduct Manager, Developer Platform\nSales\nAccount Executive, Enterprise\nAccount Executive, Enterprise (Bengaluru, India)\nAccount Executive, Enterprise (Berlin, Germany)\nAccount Executive, Enterprise, Mandarin Speaking (Singapore)\nAccount Executive, Enterprise (Paris, France)\nAccount Executive, Enterprise (Sydney or Melbourne, Australia)\nAccount Executive, Enterprise (Tokyo, Japan)\nAccount Executive, Federal - Civilian\nAccount Executive, Mid-Market\nAccount Executive, Mid-Market (London, United Kingdom)\nAccount Executive, Mid-Market, Mandarin Speaking (Singapore)\nAccount Executive, Mid-Market (Paris, France)\nAccount Executive, Mid-Market (Sydney, Australia)\nAccount Executive, SMB\nAccount Executive, SMB (Berlin, Germany)\nAccount Executive, SMB (London, United Kingdom)\nAccount Executive, SMB (Paris, France)\nAccount Executive, SMB (Tokyo, Japan)\nAccount Executive, Strategic\nAccount Executive, Strategic (Paris, France)\nAccount Executive, Strategic (Sydney or Melbourne, Australia)\nAccount Executive, Strategic (Tokyo, Japan)\nCustomer Enablement Manager (Berlin, Germany)\nCustomer Enablement Manager (London, United Kingdom)\nCustomer Enablement Manager (Paris, France)\nCustomer Enablement Manager (São Paulo, Brazil)\nDirector, Enterprise Sales (London, United Kingdom)\nDirector, SMB Sales (London, United Kingdom)\nDirector, Solutions Consulting\nDirector, Strategic Sales (Berlin, Germany)\nExecutive Assistant, Sales (São Paulo, Brazil)\nInside Sales Representative (Berlin, Germany)\nInside Sales Representative (Paris, France)\nManager, Customer Enablement (Tokyo, Japan)\nManager, Enterprise Sales\nManager, Inside Sales (London, United Kingdom)\nManager, Mid-Market Sales (Berlin, Germany)\nManager, Mid-Market Sales (London, United Kingdom)\nManager, SMB Sales\nManager, Solutions Consulting (London, United Kingdom)\nManager, Solutions Consulting (Tokyo, Japan)\nManager, Strategic Sales\nOnboarding Manager, Customer Experience (Tokyo, Japan)\nProgram Manager, Scale Onboarding (London, United Kingdom)\nSenior Account Executive, SMB\nSenior Account Executive, UK Government (London, United Kingdom)\nSenior Field Enablement Manager (Tokyo, Japan)\nSenior Manager, Enterprise Sales (London, United Kingdom)\nSolutions Consultant\nSolutions Consultant (Berlin, Germany)\nSolutions Consultant (London, United Kingdom)\nSolutions Consultant, Payload\nSolutions Consultant (Sydney, Australia)\nTechnical Account Manager\nTechnical Account Manager, Mandarin Speaking (Singapore)\nTechnical Account Manager (Tokyo, Japan)\nTalent\nBusiness Recruiter (São Paulo, Brazil)\nExecutive Recruiter\nManager, Recruiting - Corporate\nManager, Recruiting - Sales\nRecruiter (Singapore)\nWeavy - Figma Weave\nDirector, Marketing - Figma Weave (New York, United States)\nEvents Manager - Figma Weave (New York, United States)\nSoftware Engineer - Figma Weave (Tel Aviv, Israel)\nAt Figma we celebrate and support our differences. We know employing a team rich in diverse thoughts, experiences, and opinions allows our employees, our product and our community to flourish. Figma is an equal opportunity workplace. We are dedicated to equal employment opportunities regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity/expression, or veteran status.\nFrom the blog\nVersion control: How a UX writer weighs one word against another\nIn UX design, a single misplaced verb can lead users astray, frustrating their expectations and creating confusion. That’s why UX Writer Henry Freedland chose his words very carefully when he was brought in to help polish a new prototyping feature.\nRead article\nWhy are we so afraid of code as a commodity?\nInstead of asking how AI will automate our jobs, we should be focusing on what we, as engineers, uniquely do well. What problems can AI currently solve, and where is the whitespace to go beyond that?\nRead article\nBreaking in: A guide to landing your first product design role\nCurious about early career opportunities at Figma? Here are some tips on how to get your first product design job, along with insights on what we look for.\nRead article\nSee all articles\nAbout Figma\nFigma is the design platform for teams who build products together. Born on the Web, Figma helps teams brainstorm, design and build better products — from start to finish. Whether it’s consolidating tools, simplifying workflows, or collaborating across teams and time zones, Figma makes the design process faster, more efficient, and fun while keeping everyone on the same page.\nTry Figma for free\nFigma Socials\nPRODUCT\nFigma Design\nFigma Make\nFigma WeaveNEW\nDev Mode\nFigma MotionNEW\nFigJam\nFigma Slides\nFigma Draw\nFigma SitesBETA\nFigma BuzzBETA\nDesign and explore\nBuild and ship products\nAI workflows\nRelease notes\nDownloads\nPLANS\nPricing\nEnterprise\nOrganization\nProfessional\nUSE CASES\nUI design\nUX design\nWireframing\nDiagramming\nPrototyping\nBrainstorming\nPresentation Maker\nOnline whiteboard\nStrategic planning\nMind mapping\nAI website generator\nAI design generator\nAI app builder\nAI UI generator\nWeave AI tool\nAI design agent\nRESOURCES\nBlog\nBest practices\nGradient Library\nGradient Generator\nGIF maker\nColor wheel\nColors\nColor picker\nFont Library\nTemplates\nDevelopers\nIntegrations\nAffiliate program\nResource library\nReports and insights\nSupport\nStatus\nLegal and privacy\nModern slavery statement\nClimate disclosure statement\nImpressum\nCOMPANY\nEvents\nCustomers\nCareers\nNewsroom\nBrand assets\nCookie settings\nEnglish', 'page_type': 'general_page'}

In [3]:
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By

import pandas as pd
import re
import time

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Edge(options=options)

print("Driver started")

Driver started

In [101]:
def extract_figma_job(url):
    
    result = {'location_clean': None,'salary_currency': None, 'salary_min': None,
        'salary_max': None, 'education': None,'content_clean': None, 'page_type': None }
    
    try:
        driver.get(url)
        time.sleep(3)
        
        # Get page information
        page_title = driver.title
        page_text = driver.find_element(By.TAG_NAME, "body").text
        
        result['content_clean'] = page_text
        
        title_lower = page_title.lower()
        text_lower = page_text.lower()
        

        # 1. CHECK 404 / UNAVAILABLE PAGE

        unavailable_patterns = ['404','page not found', 'job not found',
            'this job is no longer available','position is no longer available']
        
        if any(pattern in text_lower for pattern in unavailable_patterns):
            result['page_type'] = '404'
            result['content_clean'] = None
            return result
        

        # 2. DETECT GENERAL FIGMA CAREERS PAGE

        general_page_indicators = [ 'careers at figma','see open positions',
            'job openings','our values and culture']
        
        general_score = sum(
            indicator in text_lower
            for indicator in general_page_indicators
        )
        

        # 3. DETECT INDIVIDUAL JOB PAGE

        job_page_indicators = ['apply for this job','apply', "what you'll do",
            'annual base salary range:','qualifications', 'requirements' ]
        
        job_score = sum(indicator in text_lower for indicator in job_page_indicators)
        
        # If strong evidence of general page and
        # insufficient evidence of individual job
        if general_score >= 2 and job_score < 2:
            result['page_type'] = 'general_page'
            result['content_clean'] = None
            return result
        
        # If enough evidence of an individual job
        if job_score >= 2:
            result['page_type'] = 'job_listing'
        else:
            result['page_type'] = 'general_page'
            result['content_clean'] = None
            return result
        

        # 4. EXTRACT LOCATION

        lines = [ line.strip()for line in page_text.split('\n') if line.strip()]
        
        # Find "Back to jobs"
        back_to_jobs_index = None
        
        for i, line in enumerate(lines):
            if line.lower() == 'back to jobs':
                back_to_jobs_index = i
                break
        
        if back_to_jobs_index is not None:
            
            # Usually:
            # Back to jobs
            # Job title
            # Location
            
            if back_to_jobs_index + 2 < len(lines):
                possible_location = lines[back_to_jobs_index + 2]
                
                # Don't accidentally take "Apply"
                if possible_location.lower() != 'apply':
                    result['location_clean'] = possible_location
        

        # 5. EXTRACT SALARY

        salary_patterns = [
            r'Annual Base Salary Range:\s*'
            r'\$([\d,]+)\s*-\s*\$([\d,]+)\s*'
            r'(USD|CAD|EUR|GBP)',
            
            r'Base Salary Range:\s*'
            r'\$([\d,]+)\s*-\s*\$([\d,]+)\s*'
            r'(USD|CAD|EUR|GBP)'
        ]
        
        for pattern in salary_patterns:
            
            salary_match = re.search(pattern, page_text, re.IGNORECASE )
            
            if salary_match:
                
                result['salary_min'] = float(salary_match.group(1).replace(',', ''))
                
                result['salary_max'] = float( salary_match.group(2).replace(',', ''))
                
                result['salary_currency'] = (salary_match.group(3).upper())
                
                break
        

        # 6. EXTRACT EDUCATION

        education_patterns = [ r"((?:Bachelor['’]?s|Master['’]?s|Ph\.?D\.?)[^\n]*)"]
        
        for pattern in education_patterns:
            
            education_match = re.search(pattern,page_text, re.IGNORECASE )
            
            if education_match:
                
                education_text = education_match.group(1).strip()
                
                result['education'] = education_text
                
                break
        
        return result
        
    except Exception as e:
        
        print(
            f"ERROR: {type(e).__name__}: {e}"
        )
        
        result['page_type'] = 'error'
        result['content_clean'] = None
        
        return result

In [102]:
test_url = figma_df.iloc[0]['absolute_url']

print("URL:")
print(test_url)

result = extract_figma_job(test_url)

print("\nRESULT:")
print(result)

URL:
https://boards.greenhouse.io/figma/jobs/5364702004?gh_jid=5364702004

RESULT:
{'location_clean': None, 'salary_currency': None, 'salary_min': None, 'salary_max': None, 'education': None, 'content_clean': None, 'page_type': 'general_page'}

In [103]:
test_url = "https://job-boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004"

result = extract_figma_job(test_url)

print(result)

{'location_clean': 'San Francisco, CA • New York, NY • United States', 'salary_currency': 'USD', 'salary_min': 200000.0, 'salary_max': 200000.0, 'education': None, 'content_clean': 'Back to jobs\nAccount Executive, Strategic\nSan Francisco, CA • New York, NY • United States\nApply\nFigma is growing our team of passionate creatives and builders on a mission to make design accessible to all. Figma’s platform helps teams bring ideas to life—whether you\'re brainstorming, creating a prototype, translating designs into code, or iterating with AI. From idea to product, Figma empowers teams to streamline workflows, move faster, and work together in real time from anywhere in the world. If you\'re excited to shape the future of design and collaboration, join us!\nWe are looking for a Strategic Account Executive who will play a critical role driving sales and maximizing expansion opportunities with a defined list of top-tier Enterprise customers. You will be responsible for targeting, building and nurturing positive relationships with key C-level decision-makers, understanding complex business needs, and delivering innovative solutions across our product suite. This is an opportunity to accelerate your career, learn from leading sellers in the industry and build an incredible network of cross functional partners throughout Figma.\nThis is a full time role that can be held from one of our US hubs or remotely in the United States.\nWhat you\'ll do at Figma:\nManage a defined list of named strategic accounts to consistently meet or exceed quarterly and annual sales targets\nApply effective discovery and value-selling techniques to build and strengthen C-level relationships for every account in your book\nAlign with executives on business challenges and gain sponsorship for enterprise wide deployments for a suite of products, identifying where Figma’s roadmap and innovations fit in the long term\nConduct thorough analysis to create strategic account plans that outline company priorities and initiatives, multi-threading at at senior level to build on expansion opportunities\nCo-create with cross-functional partners to expertly position Figma, drive deals forward and ensure customer success\nLeverage opportunities to advance executive level relationships through in-person meetings and networking opportunities\nWe\'d love to hear from you if you have:\nExperience closing sales, over multiple years, for a software or SaaS business with the highest tier of Enterprise customers (5000+ FTEs), selling to executives\nConsistent performance meeting pipeline generation targets for net new business\nDemonstrated experience successfully managing complex sales cycles (9 months+)\nProficiency in a sales methodology and process that creates value for customers\nWhile it’s not required, it’s an added plus if you also have:\nExperience selling solutions to technical audiences at the highest level in Engineering, Product and Design teams\nDemonstrated ability to succeed in a changing environment\nCertified in deal qualification and prospect discovery\nAt Figma, one of our values is Grow as you go. We believe in hiring smart, curious people who are excited to learn and develop their skills. If you’re excited about this role but your past experience doesn’t align perfectly with the points outlined in the job description, we encourage you to apply anyways. You may be just the right candidate for this or other roles.\nPay Transparency Disclosure\nJob level and actual compensation will be decided based on factors including, but not limited to, individual qualifications objectively assessed during the interview process (including skills and prior relevant experience, potential impact, and scope of role), market demands, and specific work location. \nFigma offers equity to employees, as well as a competitive package of additional benefits, including health, dental, and vision coverage; retirement benefits with company contributions; parental leave and reproductive or family planning support; mental health and wellness benefits; and paid time off. Figma provides paid sick leave, holidays, and other leave benefits in compliance with applicable federal, state, and local laws, including the requirements of the Washington Minimum Wage Act and related regulations. Exempt employees are eligible for employer‑provided paid flexible PTO in addition to flexible paid sick leave. PTO is subject to manager approval. Additional benefits may include company recharge days, cell phone and home internet reimbursements, and a number of lifestyle spending accounts. Figma also offers sales incentive compensation for most sales roles and an annual bonus plan for eligible non-sales roles. All compensation and benefits are subject to applicable plan terms and may be modified by Figma at any time, consistent with applicable law.\nAnnual Base Salary Range:\n$200,000 - $200,000 USD\nAt Figma we celebrate and support our differences. We know employing a team rich in diverse thoughts, experiences, and opinions allows our employees, our product and our community to flourish. Figma is an equal opportunity workplace - we are dedicated to equal employment opportunities regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity/expression, veteran status, or any other characteristic protected by law. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements.\nWe will work to ensure individuals with disabilities are provided reasonable accommodation to apply for a role, participate in the interview process, perform essential job functions, and receive other benefits and privileges of employment. If you require accommodation, please reach out to accommodations-ext@figma.com. These modifications enable an individual with a disability to have an equal opportunity not only to get a job, but successfully perform their job tasks to the same extent as people without disabilities. \nExamples of accommodations include but are not limited to: \nHolding interviews in an accessible location\nEnabling closed captioning on video conferencing\nEnsuring all written communication be compatible with screen readers\nChanging the mode or format of interviews \nTo ensure the integrity of our hiring process and facilitate a more personal connection, we require all candidates keep their cameras on during video interviews. Additionally, if hired you will be required to attend in person onboarding.\nBy applying for this job, the candidate acknowledges and agrees that any personal data contained in their application or supporting materials will be processed in accordance with Figma\'s Candidate Privacy Notice.\nCreate a Job Alert\nInterested in building your career at Figma? Get future opportunities sent straight to your email.\nCreate alert\nApply for this job\n*\nindicates a required field\nAutofill my application\nFirst Name*\nLast Name*\nEmail*\nPhone\nCountry*\nPhone*\nLocation (City)*\nLocate me\nResume/CV*\nAttach\nAttach\nDropbox\nGoogle Drive\nEnter manually\nEnter manually\nAccepted file types: pdf, doc, docx, txt, rtf\nLinkedIn Profile\nOther Website\nWhy do you want to join Figma?*\nPlease share 3-4 sentences on why you want to join Figma\nPronouns\nSelect...\nIf you\'d like to, please let us know your pronouns.\nAdditional Information\nAdd a cover letter or anything else you\'d like to share\nFrom where do you intend to work? *\nPlease list city and state. (ie: San Francisco, CA) \nPreferred First Name\nAre you authorized to work in the country for which you applied? *\nSelect...\nHave you ever worked for Figma before, as an employee or a contractor/consultant? *\nSelect...\nVoluntary Self-Identification\nFor government reporting purposes, we ask candidates to respond to the below self-identification survey. Completion of the form is entirely voluntary. Whatever your decision, it will not be considered in the hiring process or thereafter. Any information that you do provide will be recorded and maintained in a confidential file.\nAs set forth in Figma’s Equal Employment Opportunity policy, we do not discriminate on the basis of any protected group status under any applicable law.\nGender\nSelect...\nAre you Hispanic/Latino?\nSelect...\nRace & Ethnicity Definitions\nIf you believe you belong to any of the categories of protected veterans listed below, please indicate by making the appropriate selection. As a government contractor subject to the Vietnam Era Veterans Readjustment Assistance Act (VEVRAA), we request this information in order to measure the effectiveness of the outreach and positive recruitment efforts we undertake pursuant to VEVRAA. Classification of protected categories is as follows:\nA "disabled veteran" is one of the following: a veteran of the U.S. military, ground, naval or air service who is entitled to compensation (or who but for the receipt of military retired pay would be entitled to compensation) under laws administered by the Secretary of Veterans Affairs; or a person who was discharged or released from active duty because of a service-connected disability.\nA "recently separated veteran" means any veteran during the three-year period beginning on the date of such veteran\'s discharge or release from active duty in the U.S. military, ground, naval, or air service.\nAn "active duty wartime or campaign badge veteran" means a veteran who served on active duty in the U.S. military, ground, naval or air service during a war, or in a campaign or expedition for which a campaign badge has been authorized under the laws administered by the Department of Defense.\nAn "Armed forces service medal veteran" means a veteran who, while serving on active duty in the U.S. military, ground, naval or air service, participated in a United States military operation for which an Armed Forces service medal was awarded pursuant to Executive Order 12985.\nVeteran Status\nSelect...\nVoluntary Self-Identification of Disability\nForm CC-305\nPage 1 of 1\nOMB Control Number 1250-0005\nExpires 07/31/2029\n\nWhy are you being asked to complete this form?\nWe are a federal contractor or subcontractor. The law requires us to provide equal employment opportunity to qualified people with disabilities. We have a goal of having at least 7% of our workers as people with disabilities. The law says we must measure our progress towards this goal. To do this, we must ask applicants and employees if they have a disability or have ever had one. People can become disabled, so we need to ask this question at least every five years.\nCompleting this form is voluntary, and we hope that you will choose to do so. Your answer is confidential. No one who makes hiring decisions will see it. Your decision to complete the form and your answer will not harm you in any way. If you want to learn more about the law or this form, visit the U.S. Department of Labor’s Office of Federal Contract Compliance Programs (OFCCP) website at www.dol.gov/ofccp.\nHow do you know if you have a disability?\nA disability is a condition that substantially limits one or more of your “major life activities.” If you have or have ever had such a condition, you are a person with a disability. Disabilities include, but are not limited to:\nAlcohol or other substance use disorder (not currently using drugs illegally)\nAutoimmune disorder, for example, lupus, fibromyalgia, rheumatoid arthritis, HIV/AIDS\nBlind or low vision\nCancer (past or present)\nCardiovascular or heart disease\nCeliac disease\nCerebral palsy\nDeaf or serious difficulty hearing\nDiabetes\nDisfigurement, for example, disfigurement caused by burns, wounds, accidents, or congenital disorders\nEpilepsy or other seizure disorder\nGastrointestinal disorders, for example, Crohn\'s Disease, irritable bowel syndrome\nIntellectual or developmental disability\nMental health conditions, for example, depression, bipolar disorder, anxiety disorder, schizophrenia, PTSD\nMissing limbs or partially missing limbs\nMobility impairment, benefiting from the use of a wheelchair, scooter, walker, leg brace(s) and/or other supports\nNervous system condition, for example, migraine headaches, Parkinson’s disease, multiple sclerosis (MS)\nNeurodivergence, for example, attention-deficit/hyperactivity disorder (ADHD), autism spectrum disorder, dyslexia, dyspraxia, other learning disabilities\nPartial or complete paralysis (any cause)\nPulmonary or respiratory conditions, for example, tuberculosis, asthma, emphysema\nShort stature (dwarfism)\nTraumatic brain injury\nDisability Status\nSelect...\nPUBLIC BURDEN STATEMENT: According to the Paperwork Reduction Act of 1995 no persons are required to respond to a collection of information unless such collection displays a valid OMB control number. This survey should take about 5 minutes to complete.\nSubmit application\nPowered by', 'page_type': 'job_listing'}

In [104]:
test_urls = [
    "https://boards.greenhouse.io/figma/jobs/5426468004?gh_jid=5426468004",
    "https://boards.greenhouse.io/figma/jobs/5579204004?gh_jid=5579204004",
    "https://boards.greenhouse.io/figma/jobs/5783812004?gh_jid=5783812004"
]

for url in test_urls:
    result = extract_figma_job(url)
    print("\nURL:", url)
    print(result)

URL: https://boards.greenhouse.io/figma/jobs/5426468004?gh_jid=5426468004
{'location_clean': 'San Francisco, CA • New York, NY • United States', 'salary_currency': 'USD', 'salary_min': 165000.0, 'salary_max': 190000.0, 'education': None, 'content_clean': 'Back to jobs\nAccount Executive, Enterprise\nSan Francisco, CA • New York, NY • United States\nApply\nFigma is growing our team of passionate creatives and builders on a mission to make design accessible to all. Figma’s platform helps teams bring ideas to life—whether you\'re brainstorming, creating a prototype, translating designs into code, or iterating with AI. From idea to product, Figma empowers teams to streamline workflows, move faster, and work together in real time from anywhere in the world. If you\'re excited to shape the future of design and collaboration, join us!\nWe are looking for an Enterprise Account Executive who will play a critical role driving sales and maximizing revenue with our Enterprise customers. You will be responsible for targeting, building and nurturing positive relationships with key executive level decision-makers, understanding complex business needs, and delivering innovative solutions across our product suite. This is an opportunity to accelerate your career, learn from leading sellers in the industry and build an incredible network of cross functional partners at Figma.\nThis is a full time role that can be held from one of our US hubs or remotely in the United States.\nWhat you\'ll do at Figma:\nCreate and manage a pipeline of Enterprise accounts to consistently meet or exceed quarterly and annual sales targets\nApply effective discovery and value-selling techniques to build and strengthen relationships with key decision-makers in both new and existing customers (5000+ FTEs)\nAlign with executives on business challenges and gain sponsorship for enterprise wide deployments for a suite of products, identifying where Figma’s roadmap and innovations fit in the long term\nConduct thorough analysis to create strategic account plans that outline company priorities and initiatives, multi-threading at an executive level to build on expansion opportunities\nManage a book of business by tiering accounts and initiating techniques to save contractions\nCo-create with cross-functional partners to expertly position Figma, drive deals forward and ensure customer success\nLeverage opportunities to advance executive level relationships through in-person meetings and networking opportunities\nWe\'d love to hear from you if you have:\nExperience closing sales, over multiple years, for a software or SaaS business with an Enterprise book of customers (5000+ FTEs), selling to executives\nConsistent performance meeting pipeline generation targets for net new business\nDemonstrated experience successfully managing complex sales cycles (6 months+)\nA sales methodology and process that creates value for customers\nWhile it’s not required, it’s an added plus if you also have:\nExperience selling solutions to technical audiences at a strategic level (i.e. Engineering, Product, Design teams)\nDemonstrated ability to succeed in a changing environment\nCertified in deal qualification and prospect discovery\nAt Figma, one of our values is Grow as you go. We believe in hiring smart, curious people who are excited to learn and develop their skills. If you’re excited about this role but your past experience doesn’t align perfectly with the points outlined in the job description, we encourage you to apply anyways. You may be just the right candidate for this or other roles.\nPay Transparency Disclosure\nJob level and actual compensation will be decided based on factors including, but not limited to, individual qualifications objectively assessed during the interview process (including skills and prior relevant experience, potential impact, and scope of role), market demands, and specific work location. \nFigma offers equity to employees, as well as a competitive package of additional benefits, including health, dental, and vision coverage; retirement benefits with company contributions; parental leave and reproductive or family planning support; mental health and wellness benefits; and paid time off. Figma provides paid sick leave, holidays, and other leave benefits in compliance with applicable federal, state, and local laws, including the requirements of the Washington Minimum Wage Act and related regulations. Exempt employees are eligible for employer‑provided paid flexible PTO in addition to flexible paid sick leave. PTO is subject to manager approval. Additional benefits may include company recharge days, cell phone and home internet reimbursements, and a number of lifestyle spending accounts. Figma also offers sales incentive compensation for most sales roles and an annual bonus plan for eligible non-sales roles. All compensation and benefits are subject to applicable plan terms and may be modified by Figma at any time, consistent with applicable law.\nAnnual Base Salary Range:\n$165,000 - $190,000 USD\nAt Figma we celebrate and support our differences. We know employing a team rich in diverse thoughts, experiences, and opinions allows our employees, our product and our community to flourish. Figma is an equal opportunity workplace - we are dedicated to equal employment opportunities regardless of race, color, ancestry, religion, sex, national origin, sexual orientation, age, citizenship, marital status, disability, gender identity/expression, veteran status, or any other characteristic protected by law. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements.\nWe will work to ensure individuals with disabilities are provided reasonable accommodation to apply for a role, participate in the interview process, perform essential job functions, and receive other benefits and privileges of employment. If you require accommodation, please reach out to accommodations-ext@figma.com. These modifications enable an individual with a disability to have an equal opportunity not only to get a job, but successfully perform their job tasks to the same extent as people without disabilities. \nExamples of accommodations include but are not limited to: \nHolding interviews in an accessible location\nEnabling closed captioning on video conferencing\nEnsuring all written communication be compatible with screen readers\nChanging the mode or format of interviews \nTo ensure the integrity of our hiring process and facilitate a more personal connection, we require all candidates keep their cameras on during video interviews. Additionally, if hired you will be required to attend in person onboarding.\nBy applying for this job, the candidate acknowledges and agrees that any personal data contained in their application or supporting materials will be processed in accordance with Figma\'s Candidate Privacy Notice.\nCreate a Job Alert\nInterested in building your career at Figma? Get future opportunities sent straight to your email.\nCreate alert\nApply for this job\n*\nindicates a required field\nAutofill my application\nFirst Name*\nLast Name*\nEmail*\nPhone\nCountry*\nPhone*\nLocation (City)*\nLocate me\nResume/CV*\nAttach\nAttach\nDropbox\nGoogle Drive\nEnter manually\nEnter manually\nAccepted file types: pdf, doc, docx, txt, rtf\nLinkedIn Profile\nOther Website\nWhy do you want to join Figma?*\nPlease share 3-4 sentences on why you want to join Figma\nPronouns\nSelect...\nIf you\'d like to, please let us know your pronouns.\nAdditional Information\nAdd a cover letter or anything else you\'d like to share\nFrom where do you intend to work? *\nPlease list city and state. (ie: San Francisco, CA) \nPreferred First Name\nAre you authorized to work in the country for which you applied? *\nSelect...\nHave you ever worked for Figma before, as an employee or a contractor/consultant? *\nSelect...\nVoluntary Self-Identification\nFor government reporting purposes, we ask candidates to respond to the below self-identification survey. Completion of the form is entirely voluntary. Whatever your decision, it will not be considered in the hiring process or thereafter. Any information that you do provide will be recorded and maintained in a confidential file.\nAs set forth in Figma’s Equal Employment Opportunity policy, we do not discriminate on the basis of any protected group status under any applicable law.\nGender\nSelect...\nAre you Hispanic/Latino?\nSelect...\nRace & Ethnicity Definitions\nIf you believe you belong to any of the categories of protected veterans listed below, please indicate by making the appropriate selection. As a government contractor subject to the Vietnam Era Veterans Readjustment Assistance Act (VEVRAA), we request this information in order to measure the effectiveness of the outreach and positive recruitment efforts we undertake pursuant to VEVRAA. Classification of protected categories is as follows:\nA "disabled veteran" is one of the following: a veteran of the U.S. military, ground, naval or air service who is entitled to compensation (or who but for the receipt of military retired pay would be entitled to compensation) under laws administered by the Secretary of Veterans Affairs; or a person who was discharged or released from active duty because of a service-connected disability.\nA "recently separated veteran" means any veteran during the three-year period beginning on the date of such veteran\'s discharge or release from active duty in the U.S. military, ground, naval, or air service.\nAn "active duty wartime or campaign badge veteran" means a veteran who served on active duty in the U.S. military, ground, naval or air service during a war, or in a campaign or expedition for which a campaign badge has been authorized under the laws administered by the Department of Defense.\nAn "Armed forces service medal veteran" means a veteran who, while serving on active duty in the U.S. military, ground, naval or air service, participated in a United States military operation for which an Armed Forces service medal was awarded pursuant to Executive Order 12985.\nVeteran Status\nSelect...\nVoluntary Self-Identification of Disability\nForm CC-305\nPage 1 of 1\nOMB Control Number 1250-0005\nExpires 07/31/2029\n\nWhy are you being asked to complete this form?\nWe are a federal contractor or subcontractor. The law requires us to provide equal employment opportunity to qualified people with disabilities. We have a goal of having at least 7% of our workers as people with disabilities. The law says we must measure our progress towards this goal. To do this, we must ask applicants and employees if they have a disability or have ever had one. People can become disabled, so we need to ask this question at least every five years.\nCompleting this form is voluntary, and we hope that you will choose to do so. Your answer is confidential. No one who makes hiring decisions will see it. Your decision to complete the form and your answer will not harm you in any way. If you want to learn more about the law or this form, visit the U.S. Department of Labor’s Office of Federal Contract Compliance Programs (OFCCP) website at www.dol.gov/ofccp.\nHow do you know if you have a disability?\nA disability is a condition that substantially limits one or more of your “major life activities.” If you have or have ever had such a condition, you are a person with a disability. Disabilities include, but are not limited to:\nAlcohol or other substance use disorder (not currently using drugs illegally)\nAutoimmune disorder, for example, lupus, fibromyalgia, rheumatoid arthritis, HIV/AIDS\nBlind or low vision\nCancer (past or present)\nCardiovascular or heart disease\nCeliac disease\nCerebral palsy\nDeaf or serious difficulty hearing\nDiabetes\nDisfigurement, for example, disfigurement caused by burns, wounds, accidents, or congenital disorders\nEpilepsy or other seizure disorder\nGastrointestinal disorders, for example, Crohn\'s Disease, irritable bowel syndrome\nIntellectual or developmental disability\nMental health conditions, for example, depression, bipolar disorder, anxiety disorder, schizophrenia, PTSD\nMissing limbs or partially missing limbs\nMobility impairment, benefiting from the use of a wheelchair, scooter, walker, leg brace(s) and/or other supports\nNervous system condition, for example, migraine headaches, Parkinson’s disease, multiple sclerosis (MS)\nNeurodivergence, for example, attention-deficit/hyperactivity disorder (ADHD), autism spectrum disorder, dyslexia, dyspraxia, other learning disabilities\nPartial or complete paralysis (any cause)\nPulmonary or respiratory conditions, for example, tuberculosis, asthma, emphysema\nShort stature (dwarfism)\nTraumatic brain injury\nDisability Status\nSelect...\nPUBLIC BURDEN STATEMENT: According to the Paperwork Reduction Act of 1995 no persons are required to respond to a collection of information unless such collection displays a valid OMB control number. This survey should take about 5 minutes to complete.\nSubmit application\nPowered by', 'page_type': 'job_listing'}

URL: https://boards.greenhouse.io/figma/jobs/5579204004?gh_jid=5579204004

In [105]:
# Get all Figma jobs
figma_df = df[
    df['company_name'].str.contains('Figma', case=False, na=False)
].copy()

print("Figma rows:", len(figma_df))


# Store scraper results
figma_results = []

for count, idx in enumerate(figma_df.index, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_figma_job(url)

    result['df_index'] = idx
    result['source_url'] = url

    figma_results.append(result)

    if count % 10 == 0:
        print(f"Processed {count}/{len(figma_df)}")


# Convert results to DataFrame
figma_results_df = pd.DataFrame(figma_results)

print("\nDone!")
print(figma_results_df.shape)

Figma rows: 169
Processed 10/169
Processed 20/169
Processed 30/169
Processed 40/169
Processed 50/169
Processed 60/169
Processed 70/169
Processed 80/169
Processed 90/169
Processed 100/169
Processed 110/169
Processed 120/169
Processed 130/169
Processed 140/169
Processed 150/169
Processed 160/169

Done!
(169, 9)

In [106]:
figma_results_df['page_type'].value_counts(dropna=False)

page_type
general_page    89
job_listing     80
Name: count, dtype: int64

In [107]:
figma_results_df[['df_index','page_type','location_clean','salary_currency',  'salary_min',
     'salary_max', 'education']].head(20)

,df_index,page_type,location_clean,salary_currency,salary_min,salary_max,education
0,5488,general_page,None,None,NaN,NaN,None
1,5489,job_listing,"San Francisco, CA • New York, NY • United States",USD,165000.0,190000.0,None
2,5490,job_listing,"Bengaluru, India",None,NaN,NaN,None
3,5491,job_listing,"Berlin, Germany",None,NaN,NaN,None
4,5492,general_page,None,None,NaN,NaN,None
5,5493,job_listing,"Paris, France",None,NaN,NaN,None
6,5494,job_listing,Singapore,None,NaN,NaN,None
7,5495,job_listing,"Sydney, Australia • Melbourne, Australia",None,NaN,NaN,None
8,5496,job_listing,"Tokyo, Japan",None,NaN,NaN,None
9,5497,general_page,None,None,NaN,NaN,None
10,5498,general_page,None,None,NaN,NaN,None
11,5499,job_listing,"San Francisco, CA • New York, NY • United States",USD,110000.0,110000.0,None
12,5500,job_listing,"London, England",None,NaN,NaN,None
13,5501,job_listing,"Paris, France",None,NaN,NaN,None
14,5502,job_listing,"San Francisco, CA • New York, NY",USD,70500.0,70500.0,None
15,5503,job_listing,"Berlin, Germany",None,NaN,NaN,None
16,5504,job_listing,"London, England",None,NaN,NaN,None
17,5505,job_listing,"Paris, France",None,NaN,NaN,None
18,5506,general_page,None,None,NaN,NaN,None
19,5507,job_listing,"Tokyo, Japan",None,NaN,NaN,None

In [108]:
figma_results_df['page_type'].value_counts(dropna=False)

page_type
general_page    89
job_listing     80
Name: count, dtype: int64

In [109]:
figma_job_pages = figma_results_df[
    figma_results_df['page_type'] == 'job_listing'
].copy()

print("Figma individual job pages:", len(figma_job_pages))

print("\nLocation available:")
print(figma_job_pages['location_clean'].notna().sum())

print("\nSalary currency available:")
print(figma_job_pages['salary_currency'].notna().sum())

print("\nSalary min available:")
print(figma_job_pages['salary_min'].notna().sum())

print("\nSalary max available:")
print(figma_job_pages['salary_max'].notna().sum())

print("\nEducation available:")
print(figma_job_pages['education'].notna().sum())

Figma individual job pages: 80

Location available:
80

Salary currency available:
52

Salary min available:
52

Salary max available:
52

Education available:
2

In [110]:
fill_columns = ['location_clean', 'salary_currency', 'salary_min', 'salary_max','education']

updated_count = {col: 0 for col in fill_columns}

for _, row in figma_job_pages.iterrows():

    idx = row['df_index']

    for col in fill_columns:

        # Fill only if original value is missing
        # and scraper found a value
        if pd.isna(df.loc[idx, col]) and pd.notna(row[col]):

            df.loc[idx, col] = row[col]
            updated_count[col] += 1


print("Figma enrichment completed.\n")

for col, count in updated_count.items():
    print(f"{col}: {count} values filled")

Figma enrichment completed.

location_clean: 0 values filled
salary_currency: 52 values filled
salary_min: 52 values filled
salary_max: 52 values filled
education: 1 values filled

In [111]:
figma_results_df[ (figma_results_df['page_type'] == 'job_listing') &
    (figma_results_df['education'].notna())][
    ['df_index', 'education']]

     df_index                                          education
39       5527                                         PhD (2026)
132      5620  Masters or PhD) in Machine Learning, Artificia...

In [112]:
df.to_csv("jobs_cleaned_enriched_figma.csv", index=False)

print("Saved successfully!")
print(df.shape)

Saved successfully!
(7269, 42)

In [113]:
cockroach_df = df[
    df['company_name'].str.contains('Cockroach Labs', case=False, na=False)].copy()

print("Cockroach Labs rows:", len(cockroach_df))

cockroach_df[['id', 'title', 'absolute_url']].head(10)

Cockroach Labs rows: 35

,id,title,absolute_url
6469,7552671,"Account Executive, Central US",https://www.cockroachlabs.com/careers/job/?gh_...
6470,7939409,"Account Executive, Singapore",https://www.cockroachlabs.com/careers/job/?gh_...
6471,7918100,"Director, Product Management",https://www.cockroachlabs.com/careers/job/?gh_...
6472,7973917,Field Marketing Manager,https://www.cockroachlabs.com/careers/job/?gh_...
6473,8054229,"GTM Recruiter, Austin (Contract to Hire)",https://www.cockroachlabs.com/careers/job/?gh_...
6474,7939483,Incident Manager,https://www.cockroachlabs.com/careers/job/?gh_...
6475,2578081,Join our Talent Community!,https://www.cockroachlabs.com/careers/job/?gh_...
6476,7762734,"Manager, Corporate Sales (UK)",https://www.cockroachlabs.com/careers/job/?gh_...
6477,8030965,"Manager, Customer Success - West AMER",https://www.cockroachlabs.com/careers/job/?gh_...
6478,7950598,"Manager, Engineering (Production Orchestration)",https://www.cockroachlabs.com/careers/job/?gh_...

In [116]:
test_urls = [
    "https://www.cockroachlabs.com/careers/job/?gh_jid=7552671",
    "https://www.cockroachlabs.com/careers/job/?gh_jid=7939409",
    "https://www.cockroachlabs.com/careers/job/?gh_jid=7918100"
]

for url in test_urls:
    print("\nURL:", url)
    driver.get(url)
    time.sleep(3)

    print("Actual URL:", driver.current_url)
    print("Page title:", driver.title)

    page_text = driver.find_element(By.TAG_NAME, "body").text

    print("\nFirst 1000 characters:")
    print(page_text[:1000])

URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7552671
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7552671
Page title: Careers | Cockroach Labs

First 1000 characters:
Products
Solutions
Resources
Pricing
Company
Sign In
Contact Us
Try For Free
Careers
Open Interview Process
Product and Engineering
Open Positions
Don't see a position and want to join our mission? Apply through Applications (General) at the top of the page and the team will keep you in mind for future openings.
Cockroach Labs has an office-first approach, with Roachers coming into one of our offices on Monday, Tuesday and Thursday and working flexibly the rest of the week. While we’ve learned valuable lessons working remotely, nothing can replace the connection, creativity, and fun that occurs when Roachers get together and we are committed to fostering a workplace that encourages collaboration and allows us all to do our best work.
Please note: Remote-based designations are exclusively reserved for in-region required roles in Field Sales, Sales Engineering, and Enterprise Architecture. Exceptions may be made on a case-by-case basis on rare occasions for niche and/or expert roles at t

URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7939409
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939409
Page title: Careers | Cockroach Labs

First 1000 characters:
Products
Solutions
Resources
Pricing
Company
Sign In
Contact Us
Try For Free
Careers
Open Interview Process
Product and Engineering
Open Positions
Don't see a position and want to join our mission? Apply through Applications (General) at the top of the page and the team will keep you in mind for future openings.
Cockroach Labs has an office-first approach, with Roachers coming into one of our offices on Monday, Tuesday and Thursday and working flexibly the rest of the week. While we’ve learned valuable lessons working remotely, nothing can replace the connection, creativity, and fun that occurs when Roachers get together and we are committed to fostering a workplace that encourages collaboration and allows us all to do our best work.
Please note: Remote-based designations are exclusively reserved for in-region required roles in Field Sales, Sales Engineering, and Enterprise Architecture. Exceptions may be made on a case-by-case basis on rare occasions for niche and/or expert roles at t

URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7918100
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7918100
Page title: Careers | Cockroach Labs

First 1000 characters:
Products
Solutions
Resources
Pricing
Company
Sign In
Contact Us
Try For Free
Careers
Open Interview Process
Product and Engineering
Open Positions
Don't see a position and want to join our mission? Apply through Applications (General) at the top of the page and the team will keep you in mind for future openings.
Cockroach Labs has an office-first approach, with Roachers coming into one of our offices on Monday, Tuesday and Thursday and working flexibly the rest of the week. While we’ve learned valuable lessons working remotely, nothing can replace the connection, creativity, and fun that occurs when Roachers get together and we are committed to fostering a workplace that encourages collaboration and allows us all to do our best work.
Please note: Remote-based designations are exclusively reserved for in-region required roles in Field Sales, Sales Engineering, and Enterprise Architecture. Exceptions may be made on a case-by-case basis on rare occasions for niche and/or expert roles at t

In [117]:
cockroach_results = []

for count, idx in enumerate(cockroach_df.index, start=1):

    url = df.loc[idx, 'absolute_url']

    driver.get(url)
    time.sleep(3)

    actual_url = driver.current_url
    page_title = driver.title
    page_text = driver.find_element(By.TAG_NAME, "body").text

    cockroach_results.append({
        'df_index': idx,
        'job_id': df.loc[idx, 'id'],
        'source_url': url,
        'actual_url': actual_url,
        'page_title': page_title,
        'page_text_start': page_text[:300]
    })

    if count % 5 == 0:
        print(f"Processed {count}/{len(cockroach_df)}")

cockroach_results_df = pd.DataFrame(cockroach_results)

print("\nDone!")
print(cockroach_results_df.shape)

Processed 5/35
Processed 10/35
Processed 15/35
Processed 20/35
Processed 25/35
Processed 30/35
Processed 35/35

Done!
(35, 6)

In [118]:
cockroach_results_df['actual_url'].value_counts()

actual_url
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7552671    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7578404    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7758561    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7874104    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7967509    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7846573    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7578362    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7571182    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7950551    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=6741614    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7951392    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7963247    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7932110    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7852365    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7852398    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982696    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7774966    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939409    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=8030965    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7918100    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7973917    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=8054229    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939483    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=2578081    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7762734    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7950598    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7663160    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7926298    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=8029020    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7775008    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7950669    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7950651    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7422578    1
https://www.cockroachlabs.com/careers/jobs/?gh_jid=7963224    1
Name: count, dtype: int64

In [119]:
test_urls = [
    "https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583",
    "https://www.cockroachlabs.com/careers/jobs/?gh_jid=7552671",
    "https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939409"
]

for url in test_urls:

    driver.get(url)
    time.sleep(3)

    page_text = driver.find_element(By.TAG_NAME, "body").text

    print("\n" + "=" * 80)
    print("URL:", url)
    print("Actual URL:", driver.current_url)
    print("Title:", driver.title)
    print("\nContains 'The Role':", "the role" in page_text.lower())
    print("Contains 'You Have':", "you have" in page_text.lower())
    print("Contains 'Annual Anticipated Base Salary Range':",
          "annual anticipated base salary range" in page_text.lower())

================================================================================
URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583
Title: Careers | Cockroach Labs

Contains 'The Role': False
Contains 'You Have': False
Contains 'Annual Anticipated Base Salary Range': False

================================================================================
URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7552671
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7552671
Title: Careers | Cockroach Labs

Contains 'The Role': False
Contains 'You Have': False
Contains 'Annual Anticipated Base Salary Range': False

================================================================================
URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939409
Actual URL: https://www.cockroachlabs.com/careers/jobs/?gh_jid=7939409
Title: Careers | Cockroach Labs

Contains 'The Role': False
Contains 'You Have': False
Contains 'Annual Anticipated Base Salary Range': False

In [123]:
url = "https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583"

driver.get(url)
time.sleep(10)

iframes = driver.find_elements(By.TAG_NAME, "iframe")

print("Number of iframes:", len(iframes))

for i, iframe in enumerate(iframes):
    print("\nIframe", i)
    print("src:", iframe.get_attribute("src"))

Number of iframes: 6

Iframe 0
src: https://job-boards.greenhouse.io/embed/job_app?for=cockroachlabs&validityToken=YGsaU6lC64zsDak7F_ceqw3JFSyMwfxyn5lPJJ_SJgsz9dNA1pjLvrFbvNdbhX3OrMBSV84wrgMa688-RqZZuSKdK5gT85TOxDuuf4nwls2CIO69vBfZVJGSzPaFTxZ2PbPSlL7I1QhKaffbC8P1I9_xciiNcMCJUzMPclGU3hJcZHZ3ju1DcxI8bvYZ0WT55Va5WzNG0pftdoXd2iafxoHAD9jzWeCJhIzEjz9sqDik-Rv15PrwAHysY3f19fGmkrAH3VdVHcF8dITDaLKFVnv8yZ12WR1tf7xhBVAECV0Ve4gsBENbuDxntWUYocQjKxAeuDPONZiaCr5koPJVYA%3D%3D&token=7982583

Iframe 1
src: https://js.stripe.com/v3/controller-with-preconnect-e08badfdd6cb81e68707e82ee478c280.html#__shared_params__[version]=dahlia&__shared_params__[light_experiment_assignments]=%7B%22token%22%3A%22200b5641-16d7-4801-8c11-d6aac831ae9b%22%2C%22assignments%22%3A%7B%7D%7D&apiKey=pk_live_51KlaT7GQx5YgqMPf4JEqmSICBfB8k8qI6F27bW3qMa1XvMyrCrpLCWuIVf9EJyaYo39CJ7s44rAGvEKGSuIOcXEz00SOaTcpSJ&apiVersion=2026-03-25.dahlia&stripeJsId=200b5641-16d7-4801-8c11-d6aac831ae9b&stripeObjId=sobj-463767e1-fd80-4d07-ba52-caaafb07a8d0&firstStripeInstanceCreatedLatency=20&controllerCount=1&isCheckout=false&stripeJsLoadTime=1789809561692.7002&manualBrowserDeprecationRollout=false&mids[guid]=NA&mids[muid]=8e96f801-93ab-4938-86be-e0a697eee4dc283a73&mids[sid]=335da937-6c01-427e-b9ed-c6de570f00f0530a81&referrer=https%3A%2F%2Fwww.cockroachlabs.com%2Fcareers%2Fjobs%2F%3Fgh_jid%3D7982583&controllerId=__privateStripeController0961

Iframe 2
src:

Iframe 3
src: https://www.google.com/recaptcha/enterprise/anchor?ar=1&k=6Lck4YwlAAAAAEIE1hR--varWp0qu9F-8-emQn2v&co=aHR0cHM6Ly93d3cuY29ja3JvYWNobGFicy5jb206NDQz&hl=en&v=zqB-6Xpbd3lCIvi7Tr2D0pob&size=invisible&anchor-ms=20000&execute-ms=30000&cb=o3zmd0np6tdz

Iframe 4
src:

Iframe 5
src: https://js.stripe.com/v3/m-outer-3437aaddcdf6922d623e172c2d6f9278.html#url=https%3A%2F%2Fwww.cockroachlabs.com%2Fcareers%2Fjobs%2F%3Fgh_jid%3D7982583&title=Careers%20%7C%20Cockroach%20Labs&referrer=&muid=8e96f801-93ab-4938-86be-e0a697eee4dc283a73&sid=335da937-6c01-427e-b9ed-c6de570f00f0530a81&version=6&preview=false&__shared_params__[version]=dahlia

In [124]:
print("\n--- BODY TEXT LENGTH ---")
print(len(driver.find_element(By.TAG_NAME, "body").text))

print("\n--- PAGE SOURCE LENGTH ---")
print(len(driver.page_source))

--- BODY TEXT LENGTH ---
2352

--- PAGE SOURCE LENGTH ---
263773

In [125]:
from selenium.webdriver.common.by import By
import time

url = "https://www.cockroachlabs.com/careers/jobs/?gh_jid=7982583"

driver.get(url)
time.sleep(5)

# Find the Greenhouse iframe
iframe = driver.find_element(
    By.CSS_SELECTOR,
    'iframe[src*="job-boards.greenhouse.io/embed/job_app"]'
)

print("Greenhouse iframe found:", iframe is not None)

# Enter the iframe
driver.switch_to.frame(iframe)

time.sleep(3)

# Read iframe content
iframe_text = driver.find_element(By.TAG_NAME, "body").text

print("Iframe text length:", len(iframe_text))

print("\nFirst 3000 characters:")
print(iframe_text[:3000])

print("\n--- CHECKS ---")
print("Value Engineer:", "value engineer" in iframe_text.lower())
print("London:", "london" in iframe_text.lower())
print("New York:", "new york" in iframe_text.lower())
print("145,000:", "145,000" in iframe_text)
print("190,000:", "190,000" in iframe_text)

# Return to main page
driver.switch_to.default_content()

Greenhouse iframe found: True
Iframe text length: 11387

First 3000 characters:
Back to jobs
Value Engineer, Solutions Engineering
London, UK; New York, NY
Apply Here!
  Category-defining tech. Career-defining work.
For more than a decade, Cockroach Labs has built database technology trusted to power some of the world's most mission-critical applications. Now, as AI transforms how software is created and operated, the infrastructure behind it has to keep pace. Cockroach Continuum is built to meet this moment, bringing individual databases together into one fleet designed for agentic applications, where AI agents help teams provision, scale, and optimize workloads at machine speed.
The customers you’ll work with are some of the most innovative businesses in the world, and the problems they’re trying to solve are real and urgent. You’ll bring a genuinely differentiated product to a market moving fast, at a company positioned to lead it. The people who thrive here are the ones who want to own that opportunity.
The Role
The Value Engineer at Cockroach Labs is a strategic advisor embedded within our Solution Engineering organization, working directly with Account Executives, Sales Engineers, and Customer Success Managers to quantify and communicate the financial impact of adopting CockroachDB. You'll engage directly with customer IT Directors, CTOs, CFOs, and other senior executives, designing and delivering custom Return on Investment (ROI) and Total Cost of Ownership (TCO) models that translate complex technical advantages into compelling financial narratives.
This is a high-visibility, high-impact role that sits at the intersection of finance, technology, and consultative sales. You'll help customers across banking, payments, gaming, retail, and high technology make confident, data-driven decisions about their infrastructure investment, and you'll help build the Value Engineering practice at Cockroach Labs from the ground up.
You Will
ROI and TCO Modeling: Design and deliver custom, bottoms-up financial models that quantify the business value of migrating to or standardizing on CockroachDB. Models will account for infrastructure spend, operational overhead, licensing, developer productivity, and risk mitigation, calibrated to each customer's actual environment.
Executive-Level Storytelling: Lead whiteboard sessions, executive presentations, and boardroom discussions that translate CockroachDB's technical advantages into financial narratives tied to P&L impact, capital efficiency, and long-term competitive advantage. Your audience is both the CFO and the CTO; you have to be credible with both.
Customer Discovery: Conduct meaningful discovery with senior customer stakeholders to understand how their current database landscape (legacy RDBMS, NoSQL, or managed cloud) is creating cost drag, operational fragility, or scalability constraints, and how CockroachDB addresses those challenges.
Field Enablement: Build and maintain the Value Engineering practice: customer discovery guides, technical-to-business pain taxonomy, ROI/TCO templ

--- CHECKS ---
Value Engineer: True
London: True
New York: True
145,000: True
190,000: True

In [126]:
import re
import time
from selenium.webdriver.common.by import By


def extract_cockroach_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        driver.get(url)
        time.sleep(5)

        # Find Greenhouse iframe
        iframe = driver.find_element(
            By.CSS_SELECTOR,
            'iframe[src*="job-boards.greenhouse.io/embed/job_app"]'
        )

        # Switch into Greenhouse iframe
        driver.switch_to.frame(iframe)
        time.sleep(2)

        page_text = driver.find_element(By.TAG_NAME, "body").text


        # Check whether this is a job
        text_lower = page_text.lower()

        job_indicators = ['back to jobs','apply here','the role', 'you will','you have' ]

        job_score = sum(indicator in text_lower for indicator in job_indicators)

        if job_score >= 2:
            result['page_type'] = 'job_listing'
        else:
            result['page_type'] = 'general_page'
            driver.switch_to.default_content()
            return result


        # Extract location

        lines = [line.strip()
            for line in page_text.split('\n')
            if line.strip()]

        back_to_jobs_index = None

        for i, line in enumerate(lines):
            if line.lower() == 'back to jobs':
                back_to_jobs_index = i
                break

        if back_to_jobs_index is not None:

            if back_to_jobs_index + 1 < len(lines):

                possible_location = lines[back_to_jobs_index + 2]

                if (
                    possible_location.lower() not in
                    ['apply here!', 'apply here']
                ):
                    result['location_clean'] = possible_location


        # Extract salary

        salary_patterns = [

            # $145,000 - $190,000 USD
            r'\$([\d,]+)\s*-\s*\$([\d,]+)\s*(USD|CAD|EUR|GBP)',

            # $145,000–$190,000 USD
            r'\$([\d,]+)\s*[–-]\s*\$([\d,]+)\s*(USD|CAD|EUR|GBP)',

            # 145,000 - 190,000 USD
            r'([\d,]+)\s*-\s*([\d,]+)\s*(USD|CAD|EUR|GBP)'
        ]

        for pattern in salary_patterns:

            salary_match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if salary_match:

                result['salary_min'] = float(
                    salary_match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    salary_match.group(2).replace(',', '')
                )

                result['salary_currency'] = (
                    salary_match.group(3).upper()
                )

                break


        # Extract education

        education_patterns = [

            r"((?:Bachelor['’]?s|Master['’]?s|Ph\.?D\.?)[^\n.]*)",

            r"((?:Bachelor['’]?s|Master['’]?s|Ph\.?D\.?)[^.\n]*degree[^.\n]*)"
        ]

        for pattern in education_patterns:

            education_match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if education_match:

                education = education_match.group(1).strip()

                # Avoid extremely long accidental matches
                if len(education) <= 300:
                    result['education'] = education

                break

        driver.switch_to.default_content()

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        try:
            driver.switch_to.default_content()
        except:
            pass

        return result

In [127]:
cockroach_df = df[
    df['company_name'].str.contains(
        'Cockroach Labs',
        case=False,
        na=False
    )
].copy()

print("Cockroach Labs rows:", len(cockroach_df))

test_indices = cockroach_df.index[:3]

cockroach_test_results = []

for idx in test_indices:

    url = df.loc[idx, 'absolute_url']

    print("\n" + "=" * 80)
    print("INDEX:", idx)
    print("URL:", url)

    result = extract_cockroach_job(url)

    result['df_index'] = idx
    result['source_url'] = url

    cockroach_test_results.append(result)

    print(result)

Cockroach Labs rows: 35

================================================================================
INDEX: 6469
URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7552671
{'location_clean': None, 'salary_currency': None, 'salary_min': None, 'salary_max': None, 'education': None, 'page_type': 'general_page', 'df_index': 6469, 'source_url': 'https://www.cockroachlabs.com/careers/job/?gh_jid=7552671'}

================================================================================
INDEX: 6470
URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7939409
{'location_clean': None, 'salary_currency': None, 'salary_min': None, 'salary_max': None, 'education': None, 'page_type': 'general_page', 'df_index': 6470, 'source_url': 'https://www.cockroachlabs.com/careers/job/?gh_jid=7939409'}

================================================================================
INDEX: 6471
URL: https://www.cockroachlabs.com/careers/job/?gh_jid=7918100
{'location_clean': None, 'salary_currency': None, 'salary_min': None, 'salary_max': None, 'education': None, 'page_type': 'general_page', 'df_index': 6471, 'source_url': 'https://www.cockroachlabs.com/careers/job/?gh_jid=7918100'}

In [130]:
print("7552671 present in iframe:", "7552671" in iframe_text)
print("Account Executive present:", "account executive" in iframe_text.lower())

7552671 present in iframe: False
Account Executive present: False

In [6]:
import pandas as pd
df1=pd.read_csv("jobs_cleaned_enriched_figma.csv")
df=df1.copy()

In [7]:
import re
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


def extract_cockroach_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        driver.get(url)

        wait = WebDriverWait(driver, 15)

        # Wait for the Greenhouse iframe
        iframe = wait.until(
            EC.presence_of_element_located(
                (
                    By.CSS_SELECTOR,
                    'iframe[src*="job-boards.greenhouse.io/embed/job_app"]'
                )
            )
        )

        # Switch into iframe
        driver.switch_to.frame(iframe)

        # Wait until body exists inside iframe
        wait.until(
            EC.presence_of_element_located(
                (By.TAG_NAME, "body")
            )
        )

        # Give Greenhouse a little extra time to render content
        time.sleep(2)

        page_text = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        text_lower = page_text.lower()


        # Detect individual job vs listing page


        job_indicators = ['back to jobs','apply here','the role','you will','you have']

        job_score = sum(
            indicator in text_lower
            for indicator in job_indicators
        )

        listing_indicators = ['create a job alert','applications (general)',
            'search','jobs']

        listing_score = sum(
            indicator in text_lower
            for indicator in listing_indicators
        )

        if job_score >= 2:
            result['page_type'] = 'individual_job'

        elif listing_score >= 2:
            result['page_type'] = 'job_listing_page'

            driver.switch_to.default_content()
            return result

        else:
            result['page_type'] = 'unknown_page'

            driver.switch_to.default_content()
            return result

 
        # Extract location


        lines = [
            line.strip()
            for line in page_text.split('\n')
            if line.strip()
        ]

        back_to_jobs_index = None

        for i, line in enumerate(lines):

            if line.lower() == 'back to jobs':
                back_to_jobs_index = i
                break

        if back_to_jobs_index is not None:

            location_index = back_to_jobs_index + 2

            if location_index < len(lines):

                possible_location = lines[location_index]

                if possible_location.lower() not in [
                    'apply here',
                    'apply here!'
                ]:
                    result['location_clean'] = possible_location


        # Extract salary


        salary_patterns = [
            r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)\s*(USD|CAD|EUR|GBP)',
            r'([\d,]+)\s*[-–]\s*([\d,]+)\s*(USD|CAD|EUR|GBP)'
        ]

        for pattern in salary_patterns:

            match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if match:

                result['salary_min'] = float(
                    match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    match.group(2).replace(',', '')
                )

                result['salary_currency'] = (
                    match.group(3).upper()
                )

                break


        # Extract explicit education


        education_patterns = [
            r"((?:Bachelor['’]?s|Master['’]?s|Ph\.?D\.?)[^.\n]*)"
        ]

        for pattern in education_patterns:

            match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if match:

                education = match.group(1).strip()

                if len(education) <= 300:
                    result['education'] = education

                break

        driver.switch_to.default_content()

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        try:
            driver.switch_to.default_content()
        except:
            pass

        return result

In [8]:
cockroach_df = df[
    df['company_name'].str.contains(
        'Cockroach Labs',
        case=False,
        na=False
    )
].copy()

cockroach_results = []

for count, idx in enumerate(cockroach_df.index, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_cockroach_job(url)

    result['df_index'] = idx
    result['source_url'] = url

    cockroach_results.append(result)

    print(
        f"Processed {count}/{len(cockroach_df)} | "
        f"Index: {idx} | "
        f"Type: {result['page_type']}"
    )

cockroach_results_df = pd.DataFrame(cockroach_results)

Processed 1/35 | Index: 6469 | Type: job_listing_page
Processed 2/35 | Index: 6470 | Type: job_listing_page
Processed 3/35 | Index: 6471 | Type: job_listing_page
Processed 4/35 | Index: 6472 | Type: job_listing_page
Processed 5/35 | Index: 6473 | Type: job_listing_page
Processed 6/35 | Index: 6474 | Type: job_listing_page
Processed 7/35 | Index: 6475 | Type: individual_job
Processed 8/35 | Index: 6476 | Type: job_listing_page
Processed 9/35 | Index: 6477 | Type: job_listing_page
Processed 10/35 | Index: 6478 | Type: job_listing_page
Processed 11/35 | Index: 6479 | Type: job_listing_page
Processed 12/35 | Index: 6480 | Type: job_listing_page
Processed 13/35 | Index: 6481 | Type: job_listing_page
Processed 14/35 | Index: 6482 | Type: job_listing_page
Processed 15/35 | Index: 6483 | Type: job_listing_page
Processed 16/35 | Index: 6484 | Type: individual_job
Processed 17/35 | Index: 6485 | Type: individual_job
Processed 18/35 | Index: 6486 | Type: individual_job
Processed 19/35 | Index: 6487 | Type: job_listing_page
Processed 20/35 | Index: 6488 | Type: job_listing_page
Processed 21/35 | Index: 6489 | Type: job_listing_page
Processed 22/35 | Index: 6490 | Type: job_listing_page
Processed 23/35 | Index: 6491 | Type: job_listing_page
Processed 24/35 | Index: 6492 | Type: job_listing_page
Processed 25/35 | Index: 6493 | Type: job_listing_page
Processed 26/35 | Index: 6494 | Type: job_listing_page
Processed 27/35 | Index: 6495 | Type: job_listing_page
Processed 28/35 | Index: 6496 | Type: job_listing_page
Processed 29/35 | Index: 6497 | Type: job_listing_page
Processed 30/35 | Index: 6498 | Type: job_listing_page
Processed 31/35 | Index: 6499 | Type: job_listing_page
Processed 32/35 | Index: 6500 | Type: job_listing_page
Processed 33/35 | Index: 6501 | Type: job_listing_page
Processed 34/35 | Index: 6502 | Type: individual_job
Processed 35/35 | Index: 6503 | Type: job_listing_page

In [9]:
print("\n--- PAGE TYPES ---")
print(cockroach_results_df['page_type'].value_counts(dropna=False))

print("\n--- DATA FOUND ---")
print( "Location:",cockroach_results_df['location_clean'].notna().sum())

print("Salary:",cockroach_results_df['salary_min'].notna().sum())

print( "Education:",cockroach_results_df['education'].notna().sum())

--- PAGE TYPES ---
page_type
job_listing_page    30
individual_job       5
Name: count, dtype: int64

--- DATA FOUND ---
Location: 5
Salary: 2
Education: 2

In [10]:
cockroach_individual = cockroach_results_df[
    cockroach_results_df['page_type'] == 'individual_job'
].copy()

cockroach_individual[['df_index','location_clean','salary_currency','salary_min','salary_max','education' ]
].to_string(index=False)

' df_index           location_clean salary_currency  salary_min  salary_max                                                      education\n     6475                   Global            None         NaN         NaN                                                           None\n     6484         Bangalore, India            None         NaN         NaN                                                           None\n     6485             New York, NY             USD    185000.0    200000.0               PhD in Computer Science or equivalent experience\n     6486         Bangalore, India            None         NaN         NaN Ph.D. in Computer Science from Stevens Institute of Technology\n     6502 London, UK; New York, NY             USD    145000.0    190000.0                                                           None'

In [11]:
for _, row in cockroach_individual.iterrows():

    idx = row['df_index']

    print("\n" + "=" * 70)
    print("INDEX:", idx)
    print("TITLE:", df.loc[idx, 'title'])

    for col in [
        'location_clean',
        'salary_currency',
        'salary_min',
        'salary_max',
        'education'
    ]:
        print(
            f"{col}: "
            f"existing = {df.loc[idx, col]!r} | "
            f"scraped = {row[col]!r}"
        )

======================================================================
INDEX: 6475
TITLE: Join our Talent Community!
location_clean: existing = 'Global' | scraped = 'Global'
salary_currency: existing = nan | scraped = None
salary_min: existing = nan | scraped = nan
salary_max: existing = nan | scraped = nan
education: existing = nan | scraped = None

======================================================================
INDEX: 6484
TITLE: Member of Technical Staff (Senior - Specialized Indexing)
location_clean: existing = 'Bangalore, India' | scraped = 'Bangalore, India'
salary_currency: existing = nan | scraped = None
salary_min: existing = nan | scraped = nan
salary_max: existing = nan | scraped = nan
education: existing = 'education_optional' | scraped = None

======================================================================
INDEX: 6485
TITLE: Member of Technical Staff (Storage)
location_clean: existing = 'New York, NY' | scraped = 'New York, NY'
salary_currency: existing = nan | scraped = 'USD'
salary_min: existing = nan | scraped = 185000.0
salary_max: existing = nan | scraped = 200000.0
education: existing = 'education_optional' | scraped = 'PhD in Computer Science or equivalent experience'

======================================================================
INDEX: 6486
TITLE: Member of Technical Staff (Test Engineering)
location_clean: existing = 'Bangalore, India' | scraped = 'Bangalore, India'
salary_currency: existing = nan | scraped = None
salary_min: existing = nan | scraped = nan
salary_max: existing = nan | scraped = nan
education: existing = 'education_optional' | scraped = 'Ph.D. in Computer Science from Stevens Institute of Technology'

======================================================================
INDEX: 6502
TITLE: Value Engineer, Solutions Engineering
location_clean: existing = 'London, UK; New York, NY' | scraped = 'London, UK; New York, NY'
salary_currency: existing = nan | scraped = 'USD'
salary_min: existing = nan | scraped = 145000.0
salary_max: existing = nan | scraped = 190000.0
education: existing = 'education_optional' | scraped = None

In [12]:
fill_columns = ['location_clean','salary_currency','salary_min','salary_max', 'education']

updated_count = {
    col: 0
    for col in fill_columns
}

for _, row in cockroach_individual.iterrows():

    idx = row['df_index']

    for col in fill_columns:

        if (
            pd.isna(df.loc[idx, col])
            and pd.notna(row[col])
        ):
            df.loc[idx, col] = row[col]
            updated_count[col] += 1


print("Updated values:")
print(updated_count)

Updated values:
{'location_clean': 0, 'salary_currency': 2, 'salary_min': 2, 'salary_max': 2, 'education': 0}

In [13]:
df.to_csv("jobs_cleaned_enriched_cockroach.csv",index=False)

print("Saved successfully:", df.shape)

Saved successfully: (7269, 42)

In [14]:
brex_df = df[
    df['company_name'].str.contains(
        'Brex',
        case=False,
        na=False
    )
].copy()

print("Brex rows:", len(brex_df))

brex_df[
    ['id', 'title', 'absolute_url']
].head(10)

Brex rows: 266

,id,title,absolute_url
6936,8377280002,"Account Executive, Mid Market",https://www.brex.com/careers/8377280002?gh_jid...
6937,7704415002,"Account Executive, Mid Market",https://www.brex.com/careers/7704415002?gh_jid...
6938,7704444002,"Account Executive, Mid Market",https://www.brex.com/careers/7704444002?gh_jid...
6939,7704446002,"Account Executive, Mid Market",https://www.brex.com/careers/7704446002?gh_jid...
6940,8399566002,"Account Executive, Mid Market",https://www.brex.com/careers/8399566002?gh_jid...
6941,8605706002,Accounting Channel Partner Manager,https://www.brex.com/careers/8605706002?gh_jid...
6942,8608960002,Accounting Channel Partner Manager,https://www.brex.com/careers/8608960002?gh_jid...
6943,8558968002,Accounting Manager,https://www.brex.com/careers/8558968002?gh_jid...
6944,8562291002,Accounting Manager,https://www.brex.com/careers/8562291002?gh_jid...
6945,8606885002,"AI Engineer, Ecosystem",https://www.brex.com/careers/8606885002?gh_jid...

In [15]:
test_indices = brex_df.index[:3]

for idx in test_indices:

    url = df.loc[idx, 'absolute_url']

    print("\n" + "=" * 80)
    print("INDEX:", idx)
    print("TITLE:", df.loc[idx, 'title'])
    print("URL:", url)

    driver.get(url)
    time.sleep(5)

    print("\nCurrent URL:")
    print(driver.current_url)

    print("\nPage title:")
    print(driver.title)

    page_text = driver.find_element(
        By.TAG_NAME,
        "body"
    ).text

    print("\nBody text length:", len(page_text))

    print("\nFirst 3000 characters:")
    print(page_text[:3000])

================================================================================
INDEX: 6936
TITLE: Account Executive, Mid Market
URL: https://www.brex.com/careers/8377280002?gh_jid=8377280002

Current URL:
https://www.brex.com/careers/8377280002?gh_jid=8377280002

Page title:
404 Page Not Found

Body text length: 5731

First 3000 characters:
New features just dropped in September Early Access. See what’s new →
Products
Solutions
Resources
Customers
Pricing
Sign in
See a demo
Get started
404
Sorry, we can’t seem to find that page.
Head back to the homepage, or check out our most popular products below.
Get your Brex card.
Accepted worldwide and available in 20+ currencies.
Spend smarter
Reimagine business travel.
Book trips that are in-policy and on-budget.
Book travel
Simplify your spending.
Manage all global spend and reimbursements in one place.
Simplify spend
Automate bill payments.
Accelerate your AP with invoice scanning and auto-approvals.
Automate bills
Get business banking.
Modern checking, vault, and a treasury that earns up to 3.79%† yield.
Open an account
Take Brex anywhere.
Get our iOS or Android app and manage your business wherever you are.
Go mobile
<-
->
;
Product
Corporate card
Business banking
Expense management
Accounting automation
Bill pay
Travel
Startups
Release notes
Platform
Intelligence
Global ready
Native integrations
Live Budgets
Reporting
Mobile app
API
Company
About Brex
Careers
Contact
Partner portal
Press
Security
Resources
Customer Hub
Help center
Resource center & blog
Spend trends
Accounting services
Status
Implementation services
Legal
Privacy
Your Privacy Choices
†The “total treasury return” posted (between 3.44% and 3.79%) is not the DGVXX 7-day yield. It is an annualized compounded number based on the current 7-day yield for the BNY Dreyfus Government Cash Management Fund (DGVXX) (3.39%) and the additional return provided by Brex. It assumes (1) the yield remains static and (2) all dividends and distributions are reinvested for one year.
The additional-return rate is a Brex-set nominal rate based on your applicable balance tier. It is an annualized, compounded figure. If additional returns are not held for one year, the realized return will be lower than the displayed rate. Your tier is determined daily based on your total Brex balance across Checking, Treasury, and Vault. It may change as that balance changes. Brex may also change the tier schedule at any time. Actual payouts are calculated daily and may be lower or higher.
The total return shown is an annualized estimate. It assumes the current DGVXX yield and your applicable additional-return rate remain unchanged for one year. It also assumes monthly payouts are reinvested. Actual returns will vary because fund yields, your balance tier, and your Treasury balance may change. Additional return is calculated daily and paid monthly on funds invested in Treasury. More information can be found here.
DGVXX yields fluctuate daily. Past yields are not indicative of future yields. If dividends and additional returns are not held for one year, the realized return will be lower. The realized return can also decrease if rates fall.
The posted rate applies to customers eligible for the highest-tier rate on their Brex business account. Yield and additional return are variable. They are earned only on inves

================================================================================
INDEX: 6937
TITLE: Account Executive, Mid Market
URL: https://www.brex.com/careers/7704415002?gh_jid=7704415002

Current URL:
https://www.brex.com/careers/7704415002?gh_jid=7704415002

Page title:
404 Page Not Found

Body text length: 5731

First 3000 characters:
New features just dropped in September Early Access. See what’s new →
Products
Solutions
Resources
Customers
Pricing
Sign in
See a demo
Get started
404
Sorry, we can’t seem to find that page.
Head back to the homepage, or check out our most popular products below.
Get your Brex card.
Accepted worldwide and available in 20+ currencies.
Spend smarter
Reimagine business travel.
Book trips that are in-policy and on-budget.
Book travel
Simplify your spending.
Manage all global spend and reimbursements in one place.
Simplify spend
Automate bill payments.
Accelerate your AP with invoice scanning and auto-approvals.
Automate bills
Get business banking.
Modern checking, vault, and a treasury that earns up to 3.79%† yield.
Open an account
Take Brex anywhere.
Get our iOS or Android app and manage your business wherever you are.
Go mobile
<-
->
;
Product
Corporate card
Business banking
Expense management
Accounting automation
Bill pay
Travel
Startups
Release notes
Platform
Intelligence
Global ready
Native integrations
Live Budgets
Reporting
Mobile app
API
Company
About Brex
Careers
Contact
Partner portal
Press
Security
Resources
Customer Hub
Help center
Resource center & blog
Spend trends
Accounting services
Status
Implementation services
Legal
Privacy
Your Privacy Choices
†The “total treasury return” posted (between 3.44% and 3.79%) is not the DGVXX 7-day yield. It is an annualized compounded number based on the current 7-day yield for the BNY Dreyfus Government Cash Management Fund (DGVXX) (3.39%) and the additional return provided by Brex. It assumes (1) the yield remains static and (2) all dividends and distributions are reinvested for one year.
The additional-return rate is a Brex-set nominal rate based on your applicable balance tier. It is an annualized, compounded figure. If additional returns are not held for one year, the realized return will be lower than the displayed rate. Your tier is determined daily based on your total Brex balance across Checking, Treasury, and Vault. It may change as that balance changes. Brex may also change the tier schedule at any time. Actual payouts are calculated daily and may be lower or higher.
The total return shown is an annualized estimate. It assumes the current DGVXX yield and your applicable additional-return rate remain unchanged for one year. It also assumes monthly payouts are reinvested. Actual returns will vary because fund yields, your balance tier, and your Treasury balance may change. Additional return is calculated daily and paid monthly on funds invested in Treasury. More information can be found here.
DGVXX yields fluctuate daily. Past yields are not indicative of future yields. If dividends and additional returns are not held for one year, the realized return will be lower. The realized return can also decrease if rates fall.
The posted rate applies to customers eligible for the highest-tier rate on their Brex business account. Yield and additional return are variable. They are earned only on inves

================================================================================
INDEX: 6938
TITLE: Account Executive, Mid Market
URL: https://www.brex.com/careers/7704444002?gh_jid=7704444002

Current URL:
https://www.brex.com/careers/7704444002?gh_jid=7704444002

Page title:
404 Page Not Found

Body text length: 5731

First 3000 characters:
New features just dropped in September Early Access. See what’s new →
Products
Solutions
Resources
Customers
Pricing
Sign in
See a demo
Get started
404
Sorry, we can’t seem to find that page.
Head back to the homepage, or check out our most popular products below.
Get your Brex card.
Accepted worldwide and available in 20+ currencies.
Spend smarter
Reimagine business travel.
Book trips that are in-policy and on-budget.
Book travel
Simplify your spending.
Manage all global spend and reimbursements in one place.
Simplify spend
Automate bill payments.
Accelerate your AP with invoice scanning and auto-approvals.
Automate bills
Get business banking.
Modern checking, vault, and a treasury that earns up to 3.79%† yield.
Open an account
Take Brex anywhere.
Get our iOS or Android app and manage your business wherever you are.
Go mobile
<-
->
;
Product
Corporate card
Business banking
Expense management
Accounting automation
Bill pay
Travel
Startups
Release notes
Platform
Intelligence
Global ready
Native integrations
Live Budgets
Reporting
Mobile app
API
Company
About Brex
Careers
Contact
Partner portal
Press
Security
Resources
Customer Hub
Help center
Resource center & blog
Spend trends
Accounting services
Status
Implementation services
Legal
Privacy
Your Privacy Choices
†The “total treasury return” posted (between 3.44% and 3.79%) is not the DGVXX 7-day yield. It is an annualized compounded number based on the current 7-day yield for the BNY Dreyfus Government Cash Management Fund (DGVXX) (3.39%) and the additional return provided by Brex. It assumes (1) the yield remains static and (2) all dividends and distributions are reinvested for one year.
The additional-return rate is a Brex-set nominal rate based on your applicable balance tier. It is an annualized, compounded figure. If additional returns are not held for one year, the realized return will be lower than the displayed rate. Your tier is determined daily based on your total Brex balance across Checking, Treasury, and Vault. It may change as that balance changes. Brex may also change the tier schedule at any time. Actual payouts are calculated daily and may be lower or higher.
The total return shown is an annualized estimate. It assumes the current DGVXX yield and your applicable additional-return rate remain unchanged for one year. It also assumes monthly payouts are reinvested. Actual returns will vary because fund yields, your balance tier, and your Treasury balance may change. Additional return is calculated daily and paid monthly on funds invested in Treasury. More information can be found here.
DGVXX yields fluctuate daily. Past yields are not indicative of future yields. If dividends and additional returns are not held for one year, the realized return will be lower. The realized return can also decrease if rates fall.
The posted rate applies to customers eligible for the highest-tier rate on their Brex business account. Yield and additional return are variable. They are earned only on inves

In [16]:
url = "https://www.brex.com/careers/8432702002?gh_jid=8432702002"

driver.get(url)
time.sleep(5)

print("Current URL:")
print(driver.current_url)

print("\nPage title:")
print(driver.title)

page_text = driver.find_element(By.TAG_NAME, "body").text

print("\nBody text length:")
print(len(page_text))

print("\nFirst 3000 characters:")
print(page_text[:3000])

print("\n--- CHECKS ---")
print( "Staff Product Manager:",
    "staff product manager" in page_text.lower())

print("New York:","new york" in page_text.lower())

print(
    "240,000:",
    "240,000" in page_text
)

print("300,000:","300,000" in page_text)

print("Compensation:","compensation" in page_text.lower())

Current URL:
https://www.brex.com/careers/8432702002?gh_jid=8432702002

Page title:
Staff Product Manager | Career Opportunities

Body text length:
8496

First 3000 characters:
Products
Solutions
Resources
Customers
Pricing
Sign in
See a demo
Get started
Careers
Staff Product Manager
Staff Product Manager
New York, New York, United States
Why join us
Brex is the intelligent finance platform that enables companies to spend smarter and move faster in more than 200 markets. By combining global corporate cards and banking with intuitive spend management, bill pay, and travel software, Brex enables founders and finance teams to accelerate operations, gain real-time visibility, and control spend effortlessly. Brex’s AI-native automation and world-class service eliminate manual expense and accounting tasks for customers so they can focus on what matters most. Tens of thousands of the world's best companies run on Brex, including DoorDash, Coinbase, Robinhood, Zoom, Plaid, Reddit, and SeatGeek.
Working at Brex allows you to push your limits, challenge the status quo, and collaborate with some of the brightest minds in the industry. We’re committed to building a diverse team and inclusive culture and believe your potential should only be limited by how big you can dream. We make this a reality by empowering you with the tools, resources, and support you need to grow your career.
Product at Brex
The Product team is at the forefront of Brex's mission to empower employees anywhere to make better financial decisions. With a deep understanding of the business, we identify and scope out the most impactful opportunities for Brex to tackle. We are responsible for aligning cross-functional teams — such as Engineering, Legal, Compliance, and Design — on key decisions. We set strategy and drive products from inception to launch, enabling Brex to grow rapidly and help our customers reach their full potential.
What you’ll do
As a Staff Product Manager at Brex, you will operate at the intersection of product strategy, technical depth, and business impact. You will define and drive multi-quarter strategy within one of Brex’s most critical product domains, leading initiatives that materially shape the company’s trajectory. You will be expected to identify the highest-leverage problems, frame them with rigor, and mobilize cross-functional teams to deliver step-function improvements in customer value, revenue, efficiency, or distribution. You will work directly with senior leaders across Product, Engineering, Design, Data, Risk, Legal, Compliance, Finance, and GTM. You will influence decisions beyond your immediate team and elevate the standards of product thinking across the organization.
Where you’ll work
This role will be based in either our San Francisco, Seattle or New York City office. You must be willing to work in the office at least three days per week on Monday, Wednesday and Thursday. Employees will be able to work remotely for up to four weeks per year, for a minimum of one week at a time.
Responsibilities
Define and own a multi-quarter product vision and strategy aligned to Brex’s highest company priorities.
Identify high-leverage op

--- CHECKS ---
Staff Product Manager: True
New York: True
240,000: True
300,000: True
Compensation: True

In [17]:
import re
import time
from selenium.webdriver.common.by import By


def extract_brex_job(url):

    result = { 'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        driver.get(url)
        time.sleep(4)

        page_text = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        text_lower = page_text.lower()


        # Detect 404

        if (
            '404 page not found' in text_lower
            or "sorry, we can’t seem to find that page" in text_lower
            or "sorry, we can't seem to find that page" in text_lower
        ):
            result['page_type'] = '404'
            return result


        # Detect individual job page


        job_indicators = [
            'why join us',
            'what you’ll do',
            "what you'll do",
            'requirements',
            'compensation'
        ]

        job_score = sum(
            indicator in text_lower
            for indicator in job_indicators
        )

        if job_score >= 2:
            result['page_type'] = 'individual_job'
        else:
            result['page_type'] = 'unknown_page'
            return result


        # Extract location


        lines = [
            line.strip()
            for line in page_text.split('\n')
            if line.strip()
        ]

        # Brex structure:
        #
        # Careers
        # Job title
        # Job title
        # Location

        for i, line in enumerate(lines):

            if line.lower() == 'careers':

                if i + 3 < len(lines):

                    possible_location = lines[i + 3]

                    if possible_location:
                        result['location_clean'] = possible_location

                    break


        # Extract salary


        salary_patterns = [

            # $240,000 - $300,000
            r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)',

            # $240,000–$300,000
            r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)'
        ]

        for pattern in salary_patterns:

            match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if match:

                result['salary_min'] = float(
                    match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    match.group(2).replace(',', '')
                )

                # Brex salary is explicitly in dollars.
                # We'll verify USD from surrounding text.
                salary_context = page_text[
                    max(0, match.start() - 200):
                    min(len(page_text), match.end() + 200)
                ].lower()

                if 'usd' in salary_context:
                    result['salary_currency'] = 'USD'
                elif '$' in match.group(0):
                    # Brex compensation page uses $
                    # but only assign USD when context
                    # supports it.
                    result['salary_currency'] = 'USD'

                break


        # Extract explicit education


        education_patterns = [
            r"((?:Bachelor['’]?s|Master['’]?s|Ph\.?D\.?)[^.\n]*)"
        ]

        for pattern in education_patterns:

            match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if match:

                education = match.group(1).strip()

                if len(education) <= 300:
                    result['education'] = education

                break

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        return result

In [19]:
brex_df = df[df['company_name'].str.contains( 'Brex', case=False,  na=False)].copy()

brex_results = []

for count, idx in enumerate(brex_df.index, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_brex_job(url)

    result['df_index'] = idx
    result['source_url'] = url

    brex_results.append(result)

    print( f"Processed {count}/{len(brex_df)} | "
        f"Index: {idx} | "
        f"Type: {result['page_type']}")

brex_results_df = pd.DataFrame(brex_results)

Processed 1/266 | Index: 6936 | Type: 404
Processed 2/266 | Index: 6937 | Type: 404
Processed 3/266 | Index: 6938 | Type: 404
Processed 4/266 | Index: 6939 | Type: 404
Processed 5/266 | Index: 6940 | Type: 404
Processed 6/266 | Index: 6941 | Type: 404
Processed 7/266 | Index: 6942 | Type: 404
Processed 8/266 | Index: 6943 | Type: 404
Processed 9/266 | Index: 6944 | Type: 404
Processed 10/266 | Index: 6945 | Type: 404
Processed 11/266 | Index: 6946 | Type: 404
Processed 12/266 | Index: 6947 | Type: individual_job
Processed 13/266 | Index: 6948 | Type: 404
Processed 14/266 | Index: 6949 | Type: 404
Processed 15/266 | Index: 6950 | Type: 404
Processed 16/266 | Index: 6951 | Type: 404
Processed 17/266 | Index: 6952 | Type: 404
Processed 18/266 | Index: 6953 | Type: 404
Processed 19/266 | Index: 6954 | Type: 404
Processed 20/266 | Index: 6955 | Type: 404
Processed 21/266 | Index: 6956 | Type: 404
Processed 22/266 | Index: 6957 | Type: 404
Processed 23/266 | Index: 6958 | Type: 404
Processed 24/266 | Index: 6959 | Type: 404
Processed 25/266 | Index: 6960 | Type: 404
Processed 26/266 | Index: 6961 | Type: 404
Processed 27/266 | Index: 6962 | Type: 404
Processed 28/266 | Index: 6963 | Type: 404
Processed 29/266 | Index: 6964 | Type: 404
Processed 30/266 | Index: 6965 | Type: 404
Processed 31/266 | Index: 6966 | Type: 404
Processed 32/266 | Index: 6967 | Type: 404
Processed 33/266 | Index: 6968 | Type: 404
Processed 34/266 | Index: 6969 | Type: 404
Processed 35/266 | Index: 6970 | Type: 404
Processed 36/266 | Index: 6971 | Type: 404
Processed 37/266 | Index: 6972 | Type: individual_job
Processed 38/266 | Index: 6973 | Type: individual_job
Processed 39/266 | Index: 6974 | Type: individual_job
Processed 40/266 | Index: 6975 | Type: 404
Processed 41/266 | Index: 6976 | Type: 404
Processed 42/266 | Index: 6977 | Type: individual_job
Processed 43/266 | Index: 6978 | Type: individual_job
Processed 44/266 | Index: 6979 | Type: 404
Processed 45/266 | Index: 6980 | Type: 404
Processed 46/266 | Index: 6981 | Type: 404
Processed 47/266 | Index: 6982 | Type: 404
Processed 48/266 | Index: 6983 | Type: 404
Processed 49/266 | Index: 6984 | Type: 404
Processed 50/266 | Index: 6985 | Type: individual_job
Processed 51/266 | Index: 6986 | Type: individual_job
Processed 52/266 | Index: 6987 | Type: individual_job
Processed 53/266 | Index: 6988 | Type: individual_job
Processed 54/266 | Index: 6989 | Type: individual_job
Processed 55/266 | Index: 6990 | Type: individual_job
Processed 56/266 | Index: 6991 | Type: individual_job
Processed 57/266 | Index: 6992 | Type: 404
Processed 58/266 | Index: 6993 | Type: 404
Processed 59/266 | Index: 6994 | Type: 404
Processed 60/266 | Index: 6995 | Type: 404
Processed 61/266 | Index: 6996 | Type: 404
Processed 62/266 | Index: 6997 | Type: individual_job
Processed 63/266 | Index: 6998 | Type: 404
Processed 64/266 | Index: 6999 | Type: 404
Processed 65/266 | Index: 7000 | Type: 404
Processed 66/266 | Index: 7001 | Type: individual_job
Processed 67/266 | Index: 7002 | Type: individual_job
Processed 68/266 | Index: 7003 | Type: individual_job
Processed 69/266 | Index: 7004 | Type: individual_job
Processed 70/266 | Index: 7005 | Type: individual_job
Processed 71/266 | Index: 7006 | Type: individual_job
Processed 72/266 | Index: 7007 | Type: individual_job
Processed 73/266 | Index: 7008 | Type: individual_job
Processed 74/266 | Index: 7009 | Type: individual_job
Processed 75/266 | Index: 7010 | Type: individual_job
Processed 76/266 | Index: 7011 | Type: individual_job
Processed 77/266 | Index: 7012 | Type: individual_job
Processed 78/266 | Index: 7013 | Type: individual_job
Processed 79/266 | Index: 7014 | Type: 404
Processed 80/266 | Index: 7015 | Type: 404
Processed 81/266 | Index: 7016 | Type: 404
Processed 82/266 | Index: 7017 | Type: 404
Processed 83/266 | Index: 7018 | Type: 404
Processed 84/266 | Index: 7019 | Type: 404
Processed 85/266 | Index: 7020 | Type: 404
Processed 86/266 | Index: 7021 | Type: individual_job
Processed 87/266 | Index: 7022 | Type: individual_job
Processed 88/266 | Index: 7023 | Type: individual_job
Processed 89/266 | Index: 7024 | Type: individual_job
Processed 90/266 | Index: 7025 | Type: individual_job
Processed 91/266 | Index: 7026 | Type: 404
Processed 92/266 | Index: 7027 | Type: 404
Processed 93/266 | Index: 7028 | Type: 404
Processed 94/266 | Index: 7029 | Type: 404
Processed 95/266 | Index: 7030 | Type: 404
Processed 96/266 | Index: 7031 | Type: individual_job
Processed 97/266 | Index: 7032 | Type: individual_job
Processed 98/266 | Index: 7033 | Type: individual_job
Processed 99/266 | Index: 7034 | Type: 404
Processed 100/266 | Index: 7035 | Type: 404
Processed 101/266 | Index: 7036 | Type: 404
Processed 102/266 | Index: 7037 | Type: 404
Processed 103/266 | Index: 7038 | Type: 404
Processed 104/266 | Index: 7039 | Type: 404
Processed 105/266 | Index: 7040 | Type: 404
Processed 106/266 | Index: 7041 | Type: 404
Processed 107/266 | Index: 7042 | Type: individual_job
Processed 108/266 | Index: 7043 | Type: individual_job
Processed 109/266 | Index: 7044 | Type: individual_job
Processed 110/266 | Index: 7045 | Type: individual_job
Processed 111/266 | Index: 7046 | Type: 404
Processed 112/266 | Index: 7047 | Type: 404
Processed 113/266 | Index: 7048 | Type: individual_job
Processed 114/266 | Index: 7049 | Type: individual_job
Processed 115/266 | Index: 7050 | Type: individual_job
Processed 116/266 | Index: 7051 | Type: individual_job
Processed 117/266 | Index: 7052 | Type: individual_job
Processed 118/266 | Index: 7053 | Type: individual_job
Processed 119/266 | Index: 7054 | Type: individual_job
Processed 120/266 | Index: 7055 | Type: individual_job
Processed 121/266 | Index: 7056 | Type: individual_job
Processed 122/266 | Index: 7057 | Type: individual_job
Processed 123/266 | Index: 7058 | Type: 404
Processed 124/266 | Index: 7059 | Type: 404
Processed 125/266 | Index: 7060 | Type: 404
Processed 126/266 | Index: 7061 | Type: 404
Processed 127/266 | Index: 7062 | Type: individual_job
Processed 128/266 | Index: 7063 | Type: individual_job
Processed 129/266 | Index: 7064 | Type: individual_job
Processed 130/266 | Index: 7065 | Type: individual_job
Processed 131/266 | Index: 7066 | Type: individual_job
Processed 132/266 | Index: 7067 | Type: 404
Processed 133/266 | Index: 7068 | Type: 404
Processed 134/266 | Index: 7069 | Type: 404
Processed 135/266 | Index: 7070 | Type: 404
Processed 136/266 | Index: 7071 | Type: 404
Processed 137/266 | Index: 7072 | Type: 404
Processed 138/266 | Index: 7073 | Type: 404
Processed 139/266 | Index: 7074 | Type: 404
Processed 140/266 | Index: 7075 | Type: 404
Processed 141/266 | Index: 7076 | Type: 404
Processed 142/266 | Index: 7077 | Type: 404
Processed 143/266 | Index: 7078 | Type: 404
Processed 144/266 | Index: 7079 | Type: 404
Processed 145/266 | Index: 7080 | Type: 404
Processed 146/266 | Index: 7081 | Type: individual_job
Processed 147/266 | Index: 7082 | Type: individual_job
Processed 148/266 | Index: 7083 | Type: individual_job
Processed 149/266 | Index: 7084 | Type: individual_job
Processed 150/266 | Index: 7085 | Type: 404
Processed 151/266 | Index: 7086 | Type: 404
Processed 152/266 | Index: 7087 | Type: 404
Processed 153/266 | Index: 7088 | Type: 404
Processed 154/266 | Index: 7089 | Type: 404
Processed 155/266 | Index: 7090 | Type: 404
Processed 156/266 | Index: 7091 | Type: 404
Processed 157/266 | Index: 7092 | Type: 404
Processed 158/266 | Index: 7093 | Type: 404
Processed 159/266 | Index: 7094 | Type: 404
Processed 160/266 | Index: 7095 | Type: 404
Processed 161/266 | Index: 7096 | Type: 404
Processed 162/266 | Index: 7097 | Type: 404
Processed 163/266 | Index: 7098 | Type: 404
Processed 164/266 | Index: 7099 | Type: 404
Processed 165/266 | Index: 7100 | Type: 404
Processed 166/266 | Index: 7101 | Type: 404
Processed 167/266 | Index: 7102 | Type: individual_job
Processed 168/266 | Index: 7103 | Type: individual_job
Processed 169/266 | Index: 7104 | Type: 404
Processed 170/266 | Index: 7105 | Type: 404
Processed 171/266 | Index: 7106 | Type: 404
Processed 172/266 | Index: 7107 | Type: 404
Processed 173/266 | Index: 7108 | Type: 404
Processed 174/266 | Index: 7109 | Type: 404
Processed 175/266 | Index: 7110 | Type: 404
Processed 176/266 | Index: 7111 | Type: 404
Processed 177/266 | Index: 7112 | Type: 404
Processed 178/266 | Index: 7113 | Type: 404
Processed 179/266 | Index: 7114 | Type: 404
Processed 180/266 | Index: 7115 | Type: 404
Processed 181/266 | Index: 7116 | Type: 404
Processed 182/266 | Index: 7117 | Type: 404
Processed 183/266 | Index: 7118 | Type: 404
Processed 184/266 | Index: 7119 | Type: 404
Processed 185/266 | Index: 7120 | Type: individual_job
Processed 186/266 | Index: 7121 | Type: individual_job
Processed 187/266 | Index: 7122 | Type: individual_job
Processed 188/266 | Index: 7123 | Type: individual_job
Processed 189/266 | Index: 7124 | Type: individual_job
Processed 190/266 | Index: 7125 | Type: 404
Processed 191/266 | Index: 7126 | Type: 404
Processed 192/266 | Index: 7127 | Type: 404
Processed 193/266 | Index: 7128 | Type: 404
Processed 194/266 | Index: 7129 | Type: 404
Processed 195/266 | Index: 7130 | Type: 404
Processed 196/266 | Index: 7131 | Type: 404
Processed 197/266 | Index: 7132 | Type: individual_job
Processed 198/266 | Index: 7133 | Type: individual_job
Processed 199/266 | Index: 7134 | Type: individual_job
Processed 200/266 | Index: 7135 | Type: 404
Processed 201/266 | Index: 7136 | Type: 404
Processed 202/266 | Index: 7137 | Type: 404
Processed 203/266 | Index: 7138 | Type: individual_job
Processed 204/266 | Index: 7139 | Type: individual_job
Processed 205/266 | Index: 7140 | Type: individual_job
Processed 206/266 | Index: 7141 | Type: individual_job
Processed 207/266 | Index: 7142 | Type: 404
Processed 208/266 | Index: 7143 | Type: 404
Processed 209/266 | Index: 7144 | Type: 404
Processed 210/266 | Index: 7145 | Type: 404
Processed 211/266 | Index: 7146 | Type: individual_job
Processed 212/266 | Index: 7147 | Type: individual_job
Processed 213/266 | Index: 7148 | Type: individual_job
Processed 214/266 | Index: 7149 | Type: 404
Processed 215/266 | Index: 7150 | Type: individual_job
Processed 216/266 | Index: 7151 | Type: individual_job
Processed 217/266 | Index: 7152 | Type: individual_job
Processed 218/266 | Index: 7153 | Type: individual_job
Processed 219/266 | Index: 7154 | Type: individual_job
Processed 220/266 | Index: 7155 | Type: individual_job
Processed 221/266 | Index: 7156 | Type: individual_job
Processed 222/266 | Index: 7157 | Type: individual_job
Processed 223/266 | Index: 7158 | Type: individual_job
Processed 224/266 | Index: 7159 | Type: individual_job
Processed 225/266 | Index: 7160 | Type: 404
Processed 226/266 | Index: 7161 | Type: 404
Processed 227/266 | Index: 7162 | Type: 404
Processed 228/266 | Index: 7163 | Type: 404
Processed 229/266 | Index: 7164 | Type: 404
Processed 230/266 | Index: 7165 | Type: individual_job
Processed 231/266 | Index: 7166 | Type: 404
Processed 232/266 | Index: 7167 | Type: 404
Processed 233/266 | Index: 7168 | Type: individual_job
Processed 234/266 | Index: 7169 | Type: 404
Processed 235/266 | Index: 7170 | Type: 404
Processed 236/266 | Index: 7171 | Type: 404
Processed 237/266 | Index: 7172 | Type: 404
Processed 238/266 | Index: 7173 | Type: 404
Processed 239/266 | Index: 7174 | Type: 404
Processed 240/266 | Index: 7175 | Type: 404
Processed 241/266 | Index: 7176 | Type: individual_job
Processed 242/266 | Index: 7177 | Type: 404
Processed 243/266 | Index: 7178 | Type: 404
Processed 244/266 | Index: 7179 | Type: 404
Processed 245/266 | Index: 7180 | Type: 404
Processed 246/266 | Index: 7181 | Type: 404
Processed 247/266 | Index: 7182 | Type: individual_job
Processed 248/266 | Index: 7183 | Type: individual_job
Processed 249/266 | Index: 7184 | Type: individual_job
Processed 250/266 | Index: 7185 | Type: individual_job
Processed 251/266 | Index: 7186 | Type: individual_job
Processed 252/266 | Index: 7187 | Type: 404
Processed 253/266 | Index: 7188 | Type: individual_job
Processed 254/266 | Index: 7189 | Type: individual_job
Processed 255/266 | Index: 7190 | Type: individual_job
Processed 256/266 | Index: 7191 | Type: individual_job
Processed 257/266 | Index: 7192 | Type: individual_job
Processed 258/266 | Index: 7193 | Type: individual_job
Processed 259/266 | Index: 7194 | Type: individual_job
Processed 260/266 | Index: 7195 | Type: individual_job
Processed 261/266 | Index: 7196 | Type: individual_job
Processed 262/266 | Index: 7197 | Type: individual_job
Processed 263/266 | Index: 7198 | Type: individual_job
Processed 264/266 | Index: 7199 | Type: individual_job
Processed 265/266 | Index: 7200 | Type: individual_job
Processed 266/266 | Index: 7201 | Type: 404

In [20]:
print("\n--- PAGE TYPES ---")
print(brex_results_df['page_type'].value_counts(dropna=False))

print("\n--- DATA FOUND ---")

print("Location:",brex_results_df['location_clean'].notna().sum())

print("Salary:", brex_results_df['salary_min'].notna().sum())

print( "Education:", brex_results_df['education'].notna().sum())

--- PAGE TYPES ---
page_type
404               160
individual_job    106
Name: count, dtype: int64

--- DATA FOUND ---
Location: 106
Salary: 93
Education: 15

In [23]:
brex_individual = brex_results_df[
    brex_results_df['page_type'] == 'individual_job'].copy()

print("Individual Brex jobs:", len(brex_individual))

brex_individual[['df_index','location_clean','salary_currency', 'salary_min', 'salary_max', 'education']
].head(20).to_string(index=False)

Individual Brex jobs: 106

' df_index                           location_clean salary_currency  salary_min  salary_max                                                                          education\n     6947 San Francisco, California, United States             USD    171000.0    240000.0                                                                               None\n     6972             São Paulo, São Paulo, Brazil            None         NaN         NaN                                                                               None\n     6973        New York, New York, United States             USD     93600.0    117000.0                                                                               None\n     6974 San Francisco, California, United States             USD     93600.0    117000.0                                                                               None\n     6977             São Paulo, São Paulo, Brazil            None         NaN         NaN                                                                               None\n     6978 San Francisco, California, United States             USD    120800.0    151000.0                                                                               None\n     6985       Seattle, Washington, United States             USD    340000.0    425000.0                                                                               None\n     6986      Vancouver, British Columbia, Canada             USD    340000.0    425000.0                                                                               None\n     6987 San Francisco, California, United States             USD    340000.0    425000.0                                                                               None\n     6988        New York, New York, United States             USD    340000.0    425000.0                                                                               None\n     6989       Seattle, Washington, United States             USD    220000.0    276000.0                                                                               None\n     6990 San Francisco, California, United States             USD    220000.0    276000.0                                                                               None\n     6991        New York, New York, United States             USD    220000.0    276000.0                                                                               None\n     6997 San Francisco, California, United States             USD    248600.0    310750.0                                                                               None\n     7001        New York, New York, United States             USD    240000.0    300000.0 Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field\n     7002 San Francisco, California, United States             USD    240000.0    300000.0 Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field\n     7003      Vancouver, British Columbia, Canada            None         NaN         NaN Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field\n     7004       Seattle, Washington, United States             USD    240000.0    300000.0 Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field\n     7005      Vancouver, British Columbia, Canada            None         NaN         NaN Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field\n     7006 San Francisco, California, United States             USD    240000.0    300000.0 Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

In [24]:
for _, row in brex_individual.iterrows():

    idx = row['df_index']

    differences = []

    for col in [
        'location_clean',
        'salary_currency',
        'salary_min',
        'salary_max',
        'education'
    ]:

        existing = df.loc[idx, col]
        scraped = row[col]

        if pd.isna(existing) and pd.notna(scraped):
            differences.append(
                f"{col}: MISSING -> {scraped!r}"
            )

    if differences:
        print("\n" + "=" * 70)
        print("INDEX:", idx)
        print("TITLE:", df.loc[idx, 'title'])

        for item in differences:
            print(item)

======================================================================
INDEX: 6947
TITLE: AI Engineer, Product
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 171000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 6973
TITLE: Data Analyst II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 93600.0
salary_max: MISSING -> 117000.0

======================================================================
INDEX: 6974
TITLE: Data Analyst II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 93600.0
salary_max: MISSING -> 117000.0

======================================================================
INDEX: 6978
TITLE: Data Engineer
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 120800.0
salary_max: MISSING -> 151000.0

======================================================================
INDEX: 6985
TITLE: Director of Product, Growth/AI
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 340000.0
salary_max: MISSING -> 425000.0

======================================================================
INDEX: 6986
TITLE: Director of Product, Growth/AI
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 340000.0
salary_max: MISSING -> 425000.0

======================================================================
INDEX: 6987
TITLE: Director of Product, Growth/AI
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 340000.0
salary_max: MISSING -> 425000.0

======================================================================
INDEX: 6988
TITLE: Director of Product, Growth/AI
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 340000.0
salary_max: MISSING -> 425000.0

======================================================================
INDEX: 6989
TITLE: Director, Organic Growth & Discoverability
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 220000.0
salary_max: MISSING -> 276000.0

======================================================================
INDEX: 6990
TITLE: Director, Organic Growth & Discoverability
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 220000.0
salary_max: MISSING -> 276000.0

======================================================================
INDEX: 6991
TITLE: Director, Organic Growth & Discoverability
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 220000.0
salary_max: MISSING -> 276000.0

======================================================================
INDEX: 6997
TITLE: Director, Product Marketing
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 248600.0
salary_max: MISSING -> 310750.0

======================================================================
INDEX: 7001
TITLE: Engineering Manager, GTM Engineering
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7002
TITLE: Engineering Manager, GTM Engineering
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7003
TITLE: Engineering Manager, GTM Engineering
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7004
TITLE: Engineering Manager, GTM Engineering
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7005
TITLE: Engineering Manager, Onboarding
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7006
TITLE: Engineering Manager, Onboarding
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7007
TITLE: Engineering Manager, Onboarding
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7008
TITLE: Engineering Manager, Onboarding
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0
education: MISSING -> 'Bachelor’s or Master’s degree in Computer Science, Engineering, or a related field'

======================================================================
INDEX: 7009
TITLE: Enterprise Account Executive I, Embedded Finance
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 185320.0
salary_max: MISSING -> 231650.0

======================================================================
INDEX: 7010
TITLE: Enterprise Account Executive II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 294000.0
salary_max: MISSING -> 325000.0
education: MISSING -> 'Bachelor’s degree'

======================================================================
INDEX: 7011
TITLE: Enterprise Account Executive II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 208000.0
salary_max: MISSING -> 290000.0
education: MISSING -> 'Bachelor’s degree'

======================================================================
INDEX: 7012
TITLE: Enterprise Account Executive II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 294000.0
salary_max: MISSING -> 325000.0
education: MISSING -> 'Bachelor’s degree'

======================================================================
INDEX: 7013
TITLE: Enterprise Account Executive II
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 294000.0
salary_max: MISSING -> 325000.0
education: MISSING -> 'Bachelor’s degree'

======================================================================
INDEX: 7021
TITLE: Enterprise Implementation Consultant
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 145544.0
salary_max: MISSING -> 181930.0

======================================================================
INDEX: 7022
TITLE: Enterprise Implementation Consultant
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 145544.0
salary_max: MISSING -> 181930.0

======================================================================
INDEX: 7023
TITLE: Enterprise Implementation Consultant
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 128800.0
salary_max: MISSING -> 161000.0

======================================================================
INDEX: 7024
TITLE: Enterprise Implementation Consultant
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 128800.0
salary_max: MISSING -> 161000.0

======================================================================
INDEX: 7025
TITLE: Enterprise Implementation Consultant
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 145544.0
salary_max: MISSING -> 181930.0

======================================================================
INDEX: 7031
TITLE: Finance Manager
education: MISSING -> 'Bachelor’s Degree in Economics, Finance, Business, or related field'

======================================================================
INDEX: 7032
TITLE: Finance Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 104000.0
salary_max: MISSING -> 130000.0
education: MISSING -> 'Bachelor’s Degree in Economics, Finance, Business, or related field'

======================================================================
INDEX: 7033
TITLE: Finance Manager
education: MISSING -> 'Bachelor’s Degree in Economics, Finance, Business, or related field'

======================================================================
INDEX: 7042
TITLE: Group Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 280000.0
salary_max: MISSING -> 350000.0

======================================================================
INDEX: 7043
TITLE: Group Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 280000.0
salary_max: MISSING -> 350000.0

======================================================================
INDEX: 7044
TITLE: Group Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 280000.0
salary_max: MISSING -> 350000.0

======================================================================
INDEX: 7045
TITLE: Group Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 280000.0
salary_max: MISSING -> 350000.0

======================================================================
INDEX: 7048
TITLE: Lead, Social Media
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 173568.0
salary_max: MISSING -> 216960.0

======================================================================
INDEX: 7049
TITLE: Manager, Account Management
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 191648.0
salary_max: MISSING -> 239560.0

======================================================================
INDEX: 7050
TITLE: Manager, Account Management
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 169600.0
salary_max: MISSING -> 212000.0

======================================================================
INDEX: 7052
TITLE: Manager, Banking Operations
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 105600.0
salary_max: MISSING -> 132000.0

======================================================================
INDEX: 7053
TITLE: Manager, CX AI Strategy
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 141928.0
salary_max: MISSING -> 177410.0

======================================================================
INDEX: 7054
TITLE: Manager, CX AI Strategy
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 125600.0
salary_max: MISSING -> 157000.0

======================================================================
INDEX: 7055
TITLE: Manager, CX AI Strategy
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 120800.0
salary_max: MISSING -> 151000.0

======================================================================
INDEX: 7056
TITLE: Manager, CX AI Strategy
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 141928.0
salary_max: MISSING -> 177410.0

======================================================================
INDEX: 7057
TITLE: Manager, CX AI Strategy
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 141928.0
salary_max: MISSING -> 177410.0

======================================================================
INDEX: 7062
TITLE: Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 120000.0
salary_max: MISSING -> 150000.0

======================================================================
INDEX: 7063
TITLE: Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 135000.0
salary_max: MISSING -> 169500.0

======================================================================
INDEX: 7064
TITLE: Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 135000.0
salary_max: MISSING -> 169500.0

======================================================================
INDEX: 7065
TITLE: Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 135000.0
salary_max: MISSING -> 169500.0

======================================================================
INDEX: 7066
TITLE: Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 120000.0
salary_max: MISSING -> 150000.0

======================================================================
INDEX: 7081
TITLE: People Business Partner Director, Engineering
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 247470.0
salary_max: MISSING -> 309338.0

======================================================================
INDEX: 7082
TITLE: People Business Partner Director, Engineering
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 247470.0
salary_max: MISSING -> 309338.0

======================================================================
INDEX: 7083
TITLE: Product Marketing Lead
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 231365.0
salary_max: MISSING -> 257075.0

======================================================================
INDEX: 7084
TITLE: Product Marketing Lead
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 231365.0
salary_max: MISSING -> 257075.0

======================================================================
INDEX: 7102
TITLE: Senior Application Security Engineer (Remote)
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7103
TITLE: Senior Application Security Engineer (Remote)
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7120
TITLE: Senior Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 200000.0
salary_max: MISSING -> 250000.0

======================================================================
INDEX: 7121
TITLE: Senior Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 226000.0
salary_max: MISSING -> 282500.0

======================================================================
INDEX: 7122
TITLE: Senior Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 226000.0
salary_max: MISSING -> 282500.0

======================================================================
INDEX: 7123
TITLE: Senior Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 226000.0
salary_max: MISSING -> 282500.0

======================================================================
INDEX: 7124
TITLE: Senior Manager, Sales Development
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 200000.0
salary_max: MISSING -> 250000.0

======================================================================
INDEX: 7138
TITLE: Senior Security Operations Engineer
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7139
TITLE: Senior Security Operations Engineer
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7141
TITLE: Senior Security Operations Engineer
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7146
TITLE:  Senior Software Engineer, Data Enablement Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7147
TITLE: Senior Software Engineer, Data Enablement Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7148
TITLE: Senior Software Engineer, Data Enablement Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7150
TITLE: Senior Software Engineer, Full Stack
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7151
TITLE: Senior Software Engineer, Full Stack
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7153
TITLE: Senior Software Engineer, Full Stack
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7154
TITLE: Senior Software Engineer, Full Stack
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7155
TITLE: Senior Software Engineer, Product Data Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7156
TITLE: Senior Software Engineer, Product Data Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7157
TITLE: Senior Software Engineer, Product Data Platform
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7158
TITLE: Senior Software Engineer, Release Infra
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7159
TITLE: Senior Software Engineer, Release Infra
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 192000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7165
TITLE: Software Engineer, Forward Deployed Agent Builder
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 152000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7168
TITLE: Software Engineer, Forward Deployed Agent Builder
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 152000.0
salary_max: MISSING -> 240000.0

======================================================================
INDEX: 7182
TITLE: Staff Product Designer, AI
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7183
TITLE: Staff Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7184
TITLE: Staff Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7185
TITLE: Staff Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7186
TITLE: Staff Product Manager
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7188
TITLE: Staff Product Manager, Growth
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0

======================================================================
INDEX: 7189
TITLE: Staff Product Manager, Growth
salary_currency: MISSING -> 'USD'
salary_min: MISSING -> 240000.0
salary_max: MISSING -> 300000.0


In [25]:
fill_columns = ['location_clean','salary_currency','salary_min','salary_max','education']

updated_count = {col: 0
    for col in fill_columns}

for _, row in brex_individual.iterrows():

    idx = row['df_index']

    for col in fill_columns:

        if (
            pd.isna(df.loc[idx, col])
            and pd.notna(row[col])
        ):
            df.loc[idx, col] = row[col]
            updated_count[col] += 1


print("Updated values:")
print(updated_count)

Updated values:
{'location_clean': 0, 'salary_currency': 93, 'salary_min': 93, 'salary_max': 93, 'education': 15}

In [26]:
brex_added = brex_results_df[brex_results_df['page_type'] == 'individual_job'].copy()

print("Brex individual jobs:", len(brex_added))

print("\nCurrent Brex missing values:")
print( df.loc[brex_added['df_index'],
        ['location_clean','salary_currency','salary_min',
            'salary_max','education']].isna().sum())

Brex individual jobs: 106

Current Brex missing values:
location_clean      0
salary_currency    13
salary_min         13
salary_max         13
education          91
dtype: int64

In [27]:
df.to_csv("jobs_cleaned_enriched_Brex.csv", index=False)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [29]:
df[df['absolute_url'].str.contains('6100103004', na=False)][
    ['id', 'title', 'location_clean',
     'salary_currency', 'salary_min', 'salary_max', 'education']
]

,id,title,location_clean,salary_currency,salary_min,salary_max,education
7204,6100103004,"Account Executive, Majors- Install Base (APAC)",Hybrid - Sydney,NaN,NaN,NaN,NaN

In [30]:
greenhouse_companies = df[df['category'].isna()]['company_name'].dropna().value_counts()

print(greenhouse_companies.to_string())

company_name
Stripe            524
Datadog           421
MongoDB           381
Brex              266
Figma             169
Flexport          148
Asana             146
Gusto, Inc.        78
Vercel             67
Checkr             60
Cockroach Labs     35
CircleCI           10

In [31]:
vercel_jobs = df[ df['absolute_url'].str.contains('job-boards.greenhouse.io/vercel', case=False, na=False)].copy()

print("Vercel rows:", len(vercel_jobs))

print( vercel_jobs[['id', 'title', 'absolute_url']].head(10).to_string(index=False))

Vercel rows: 67
        id                                          title                                            absolute_url
5999792004                      Account Executive, Majors https://job-boards.greenhouse.io/vercel/jobs/5999792004
5841911004               Account Executive, Majors (APAC) https://job-boards.greenhouse.io/vercel/jobs/5841911004
6100103004 Account Executive, Majors- Install Base (APAC) https://job-boards.greenhouse.io/vercel/jobs/6100103004
5624231004        Account Executive- Startups, Greenfield https://job-boards.greenhouse.io/vercel/jobs/5624231004
5752956004  Account Executive-Startups, Greenfield (EMEA) https://job-boards.greenhouse.io/vercel/jobs/5752956004
5042166004      Commercial Account Executive, Greenfield  https://job-boards.greenhouse.io/vercel/jobs/5042166004
5989803004                     Developer Success Engineer https://job-boards.greenhouse.io/vercel/jobs/5989803004
5974107004               Director, Commercial Sales, EMEA https://job-boards.greenhouse.io/vercel/jobs/5974107004
6099752004                          Director, Major Sales https://job-boards.greenhouse.io/vercel/jobs/6099752004
5701765004                       Engineering Manager, CDN https://job-boards.greenhouse.io/vercel/jobs/5701765004

In [34]:
from selenium.webdriver.common.by import By
import time

test_url = "https://job-boards.greenhouse.io/vercel/jobs/6100103004"

driver.get(test_url)
time.sleep(3)

page_title = driver.title
page_text = driver.find_element(By.TAG_NAME, "body").text

print("Page title:")
print(page_title)

print("\nPage text length:", len(page_text))

print("\nFirst 3000 characters:")
print(page_text[:3000])

Page title:
Job Application for Account Executive, Majors- Install Base (APAC) at Vercel

Page text length: 8840

First 3000 characters:
Back to jobs
Account Executive, Majors- Install Base (APAC)
Hybrid - Sydney
Apply
About Vercel:
Vercel is the agentic infrastructure company. We free people and agents to ship what’s next.
For more than a decade, Vercel has shaped how the web is built. As the team behind Next.js, v0, and AI SDK, we create products that help builders move from idea to production with speed, security, and exceptional developer experience.
Now, software is entering a new era, and the next generation of products will not just be used by people. They will be built, extended, and operated by agents.
We are building the platform for that future, trusted by companies like OpenAI, PayPal, Ramp, Supreme, and millions of developers worldwide. Whether you’re building our products, supporting our customers, growing our community, or shaping our story, you’ll help define what comes next.
About Vercel:
Vercel is the agentic infrastructure company. We free people and agents to ship what's next.
For more than a decade, Vercel has shaped how the web is built. As the team behind Next.js, v0, and AI SDK, we create products that help builders move from idea to production with speed, security, and exceptional developer experience.
Now, software is entering a new era, and the next generation of products will not just be used by people. They will be built, extended, and operated by agents.
We are building the platform for that future, trusted by companies like OpenAI, PayPal, Ramp, Supreme, and millions of developers worldwide. Whether you're building our products, supporting our customers, growing our community, or shaping our story, you'll help define what comes next.
About the Role:
Vercel's Enterprise sales team is built on people who are technically fluent, commercially sharp, and deeply curious about the companies they work with. As a Majors Install Base AE covering the ANZ market, you will own a curated book of named enterprise accounts and be the primary driver of net-revenue retention, expansion, and long-term platform depth. This is not a maintenance role — you will be expected to identify whitespace, accelerate adoption of Vercel's newest products, and drive meaningful growth across a portfolio of some of the most digitally ambitious companies in the region.
  You will work alongside Solutions Engineers, Customer Success, and cross-functional Vercel stakeholders to build strategic account plans rooted in customer outcomes — and to establish Vercel as an indispensable infrastructure partner embedded in your accounts' roadmaps for web and AI transformation.
What You Will Do:
Own a book of named Major Accounts, driving renewals, upsells, and cross-sells to grow account value and ensure strong net revenue retention
Identify and execute expansion opportunities across your portfolio — mapping whitespace, uncovering new teams or use cases, and activating Vercel's newest products (including platform API, AI SDK, and observability tooling)
Build and maintain multi-threaded relationshi

In [40]:
import re
import time
from selenium.webdriver.common.by import By


def extract_vercel_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        # Open job page
        driver.get(url)
        time.sleep(3)

        page_title = driver.title
        page_text = driver.find_element(
            By.TAG_NAME, "body"
        ).text

        text_lower = page_text.lower()


        # 1. Check for 404 / unavailable page


        unavailable_patterns = [
            '404',
            'page not found',
            'job not found',
            'this job is no longer available',
            'position is no longer available'
        ]

        if any(
            pattern in text_lower
            for pattern in unavailable_patterns
        ):
            result['page_type'] = '404'
            return result


        # 2. Check whether this is an individual job page


        job_indicators = [
            'back to jobs',
            'apply',
            'about vercel:',
            'about the role:',
            'what you will do:',
            "what you'll do:",
            'requirements',
            'benefits'
        ]

        job_score = sum(
            indicator in text_lower
            for indicator in job_indicators
        )

        if job_score >= 3:
            result['page_type'] = 'individual_job'
        else:
            result['page_type'] = 'unknown_page'
            return result


        # 3. Extract location
        lines = [
            line.strip()
            for line in page_text.split('\n')
            if line.strip()
        ]

        back_to_jobs_index = None

        for i, line in enumerate(lines):
            if line.lower() == 'back to jobs':
                back_to_jobs_index = i
                break

        if back_to_jobs_index is not None:

            location_index = back_to_jobs_index + 2

            if location_index < len(lines):

                possible_location = lines[location_index]

                if (
                    possible_location.lower() != 'apply'
                    and possible_location.lower() != 'back to jobs'
                    and len(possible_location) <= 300
                ):
                    result['location_clean'] = possible_location


        # 4. Extract salary
        salary_patterns = [

            # Example:
            # 388,000 - 524,000 AUD OTE
            r'([\d,]+)\s*[-–]\s*([\d,]+)\s*'
            r'(AUD|USD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)'
            r'(?:\s+OTE)?',

            # Example:
            # $200,000 - $300,000 USD
            r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)\s*'
            r'(USD|AUD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)',

            # Example:
            # 200,000 - 300,000 USD
            r'([\d,]+)\s*[-–]\s*([\d,]+)\s*'
            r'(USD|AUD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)'
        ]

        salary_found = False

        for pattern in salary_patterns:

            match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )

            if match:

                result['salary_min'] = float(
                    match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    match.group(2).replace(',', '')
                )

                if len(match.groups()) >= 3:

                    result['salary_currency'] = (
                        match.group(3).upper()
                    )

                salary_found = True
                break

        # --------------------------------------------------
        # 5. Dollar range without explicit currency
        # --------------------------------------------------
        # Extract salary numbers but DO NOT assume USD.
        # --------------------------------------------------

        if not salary_found:

            dollar_match = re.search(
                r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)',
                page_text,
                re.IGNORECASE
            )

            if dollar_match:

                result['salary_min'] = float(
                    dollar_match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    dollar_match.group(2).replace(',', '')
                )

                # Currency intentionally remains None.


        # 6. Extract explicit education requirement

        education_patterns = [

            r"\b(Bachelor['’]s"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Master['’]s"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Ph\.?\s*D\.?"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Doctorate"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})"
        ]

        for pattern in education_patterns:

            matches = re.finditer(
                pattern,
                page_text,
                re.IGNORECASE
            )

            for match in matches:

                education = match.group(1).strip()

                education_lower = education.lower()

                # Reject false matches such as:
                # "master your craft"
                # "master the..."
                # "mastery..."
                false_positive_patterns = [
                    'master your',
                    'master the',
                    'mastering ',
                    'mastery',
                    'masterfully'
                ]

                if any(
                    bad in education_lower
                    for bad in false_positive_patterns
                ):
                    continue

                if 5 <= len(education) <= 300:

                    result['education'] = education
                    break

            if result['education'] is not None:
                break

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        return result

In [41]:
test_url = "https://job-boards.greenhouse.io/vercel/jobs/6100103004"

test_result = extract_vercel_job(test_url)

print(test_result)

{'location_clean': 'Hybrid - Sydney', 'salary_currency': 'AUD', 'salary_min': 388000.0, 'salary_max': 524000.0, 'education': None, 'page_type': 'individual_job'}

In [42]:
vercel_indices = df.index[ df['absolute_url'].str.contains('job-boards.greenhouse.io/vercel',case=False, na=False )]

vercel_results = []

for count, idx in enumerate(vercel_indices, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_vercel_job(url)

    result['df_index'] = idx
    result['source_url'] = url
    result['title'] = df.loc[idx, 'title']

    vercel_results.append(result)

    if count % 10 == 0:
        print(
            f"Processed {count}/{len(vercel_indices)} Vercel jobs"
        )

print("Finished:", len(vercel_results))

Processed 10/67 Vercel jobs
Processed 20/67 Vercel jobs
Processed 30/67 Vercel jobs
Processed 40/67 Vercel jobs
Processed 50/67 Vercel jobs
Processed 60/67 Vercel jobs
Finished: 67

In [43]:
print( vercel_results_df[
        ['df_index','title','location_clean','salary_currency','salary_min','salary_max','education','page_type']
    ].to_string(index=False))

 df_index                                              title                                        location_clean salary_currency  salary_min  salary_max                                                                                                                                                                education      page_type
     7202                          Account Executive, Majors                                       Hybrid - London             GBP    200000.0    270000.0                                                                                                                                                                     None individual_job
     7203                   Account Executive, Majors (APAC)                                       Hybrid - Sydney             AUD    388000.0    524000.0                                                                                                                                                                     None individual_job
     7204     Account Executive, Majors- Install Base (APAC)                                       Hybrid - Sydney             AUD    388000.0    524000.0                                                                                                                                                                     None individual_job
     7205            Account Executive- Startups, Greenfield                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7206      Account Executive-Startups, Greenfield (EMEA)                                       Hybrid - London            None         NaN         NaN                                                                                                                                                                     None individual_job
     7207          Commercial Account Executive, Greenfield          Hybrid - San Francisco, New York City, Austin            None         NaN         NaN                                                                                                                                                                     None individual_job
     7208                         Developer Success Engineer                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7209                   Director, Commercial Sales, EMEA                                       Hybrid - London            None         NaN         NaN                                                                                                                                                                     None individual_job
     7210                              Director, Major Sales                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7211                           Engineering Manager, CDN                                Hybrid - San Francisco            None         NaN         NaN                                                                                                                                                                     None individual_job
     7212                       Enterprise Account Executive         Hybrid - San Francisco, New York City, Austin            None    290000.0    340000.0                                                                                                                                                                     None individual_job
     7213               Enterprise Account Executive, Retail                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7214           Field Marketing Manager, Startups (EMEA)                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7215                          Forward-Deployed Engineer                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7216                         Forward-Deployed Engineer          Hybrid - San Francisco, New York City, Austin            None         NaN         NaN Mastery of React and its ecosystem, including advanced state management, performance optimization, and modern patterns like streaming, suspense, and concurrent features individual_job
     7217                                        GRC Analyst         Hybrid - San Francisco, New York City, Austin            None    134000.0    202000.0                                                                                                                                                                     None individual_job
     7218             Growth Marketing Manager, Agent Stack          Hybrid - San Francisco, New York City, Austin            None    176000.0    220000.0                                                                                                                                                                     None individual_job
     7219                        Head of Developer Community                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7220               Head of Field Engineering Operations                                Hybrid - San Francisco            None    260000.0    300000.0                                                                                                                                                                     None individual_job
     7221       Head of Southern Europe, Enterprise / Majors                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7222            Head of Workplace Strategy & Operations                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7223                   Majors Account Executive, Berlin                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7224                          Manager, Commercial Sales                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7225                    Manager, Solutions Architecture                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7226                             Media Engineer, Social                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7227                                 Partner Lead, EMEA                               Hybrid - London, Berlin            None         NaN         NaN                                                                                                                                                                     None individual_job
     7228                            Partner Operations Lead                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7229                     Performance Marketing Manager          Hybrid - San Francisco, New York City, Austin            None    150000.0    188000.0                                                                                                                                                                     None individual_job
     7230                          Product Security Engineer Hybrid - San Francisco, New York City, London, Berlin            None         NaN         NaN                                                                                                                                                                     None individual_job
     7231                      Product Strategy & Operations                                Hybrid - San Francisco            None    232000.0    348000.0                                                                                                                                                                     None individual_job
     7232 Sales Development Representative, Enterprise, UK&I                                       Hybrid - London            None         NaN         NaN                                                                                                                                                                     None individual_job
     7233                           Security Engineer, Cloud                                Remote - United States            None         NaN         NaN                                                                                                      bachelors or masters degree in Cybersecurity or similar disciplines individual_job
     7234              Security Engineer, Detection Response Hybrid - San Francisco, New York City, London, Berlin            None    208000.0    312000.0                                                                                                                                                                     None individual_job
     7235                    Security Software Engineer, IAM                                Remote - United States            None    208000.0    312000.0                                                                                                                                                                     None individual_job
     7236                                 Senior HRBP - G&A                                 Hybrid - San Francisco            None         NaN         NaN                                                                                                                                                                     None individual_job
     7237                      Senior Legal Counsel, Product                                Hybrid - San Francisco            None    270000.0    300000.0                                                                                                                                                                     None individual_job
     7238               Senior Manager, Corporate Accounting                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7239                Senior Manager, Solutions Architect                                    Remote - Australia             AUD    280000.0    350000.0                                                                                                                                                                     None individual_job
     7240                        Senior Partner Manager, AWS                                Hybrid - San Francisco            None    297000.0    362000.0                                                                                                                                                                     None individual_job
     7241                             Senior Payroll Analyst                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7242                            Senior Product Designer                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7243                   Senior Technical Account Manager         Hybrid - San Francisco, New York City, Austin            None    163000.0    204000.0                                                                                                                                                                     None individual_job
     7244                                      Site Engineer                                Remote - United States            None    196000.0    294000.0                                                                                                                                                        master your craft individual_job
     7245                           Software Engineer, Agent                                Hybrid - New York City            None    232000.0    348000.0                                                                                                                                                                     None individual_job
     7246                      Software Engineer, AI Gateway                                Hybrid - San Francisco            None    196000.0    294000.0                                                                                                                                                                     None individual_job
     7247                          Software Engineer, AI SDK                 Hybrid - San Francisco, New York City            None    196000.0    294000.0                                                                                                                                                                     None individual_job
     7248                         Software Engineer, Backend                                Remote - United States            None    196000.0    294000.0                                                                                                                                                                     None individual_job
     7249                             Software Engineer, CDN                 Hybrid - San Francisco, New York City            None    196000.0    294000.0                                                                                                                                                                     None individual_job
     7250                     Software Engineer, CDN Content                                Hybrid - San Francisco            None    172000.0    258000.0                                                                                                                                                                     None individual_job
     7251                         Software Engineer, Compute                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7252                       Software Engineer, Dashboard                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7253       Software Engineer, Deployment Infrastructure                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7254                             Software Engineer, eve                 Hybrid - San Francisco, New York City            None    208000.0    312000.0                                                                                                                                                                     None individual_job
     7255                          Software Engineer, Growth                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7256                         Software Engineer, Next.js                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page
     7257                   Software Engineer, Observability         Hybrid - San Francisco, New York City, London            None         NaN         NaN                                                                                                                                                                     None individual_job
     7258                  Software Engineer, Trust & Safety                                                  None            None         NaN         NaN                                                                                                                                                                     None   unknown_page

In [44]:
vercel_results_df.loc[vercel_results_df['education'].astype(str).str.lower().str.contains(
        'master your|master the|mastery|mastering',
        na=False),'education'] = None

In [45]:
print( vercel_results_df[vercel_results_df['education'].notna()][
        ['df_index','title','education']].to_string(index=False))

 df_index                    title                                                           education
     7233 Security Engineer, Cloud bachelors or masters degree in Cybersecurity or similar disciplines

In [46]:
fill_columns = ['location_clean','salary_currency','salary_min','salary_max','education']

comparison_rows = []

vercel_individual = vercel_results_df[vercel_results_df['page_type'] == 'individual_job'].copy()

for _, row in vercel_individual.iterrows():

    idx = row['df_index']

    changes = {}

    for col in fill_columns:

        old_value = df.loc[idx, col]
        new_value = row[col]

        if pd.isna(old_value) and pd.notna(new_value):
            changes[col] = new_value

    if changes:

        comparison_rows.append({
            'df_index': idx,
            'id': df.loc[idx, 'id'],
            'title': df.loc[idx, 'title'],
            **changes
        })

comparison_df = pd.DataFrame(comparison_rows)

print("Values that can be safely added:")

if comparison_df.empty:
    print("No new values to add.")
else:
    print(comparison_df.to_string(index=False))

Values that can be safely added:
 df_index         id                                          title salary_currency  salary_min  salary_max                                                           education
     7202 5999792004                      Account Executive, Majors             GBP    200000.0    270000.0                                                                 NaN
     7203 5841911004               Account Executive, Majors (APAC)             AUD    388000.0    524000.0                                                                 NaN
     7204 6100103004 Account Executive, Majors- Install Base (APAC)             AUD    388000.0    524000.0                                                                 NaN
     7212 5042174004                   Enterprise Account Executive             NaN    290000.0    340000.0                                                                 NaN
     7217 6102654004                                    GRC Analyst             NaN    134000.0    202000.0                                                                 NaN
     7218 6016765004         Growth Marketing Manager, Agent Stack              NaN    176000.0    220000.0                                                                 NaN
     7220 5979111004           Head of Field Engineering Operations             NaN    260000.0    300000.0                                                                 NaN
     7229 6011904004                 Performance Marketing Manager              NaN    150000.0    188000.0                                                                 NaN
     7231 6011651004                  Product Strategy & Operations             NaN    232000.0    348000.0                                                                 NaN
     7233 6102335004                       Security Engineer, Cloud             NaN         NaN         NaN bachelors or masters degree in Cybersecurity or similar disciplines
     7234 6111332004          Security Engineer, Detection Response             NaN    208000.0    312000.0                                                                 NaN
     7235 6093255004                Security Software Engineer, IAM             NaN    208000.0    312000.0                                                                 NaN
     7237 5691965004                  Senior Legal Counsel, Product             NaN    270000.0    300000.0                                                                 NaN
     7239 5995789004            Senior Manager, Solutions Architect             AUD    280000.0    350000.0                                                                 NaN
     7240 5825469004                    Senior Partner Manager, AWS             NaN    297000.0    362000.0                                                                 NaN
     7243 6112845004               Senior Technical Account Manager             NaN    163000.0    204000.0                                                                 NaN
     7244 5732855004                                  Site Engineer             NaN    196000.0    294000.0                                                                 NaN
     7245 5704320004                       Software Engineer, Agent             NaN    232000.0    348000.0                                                                 NaN
     7246 5798406004                  Software Engineer, AI Gateway             NaN    196000.0    294000.0                                                                 NaN
     7247 5474915004                      Software Engineer, AI SDK             NaN    196000.0    294000.0                                                                 NaN
     7248 5430088004                     Software Engineer, Backend             NaN    196000.0    294000.0                                                                 NaN
     7249 5179639004                         Software Engineer, CDN             NaN    196000.0    294000.0                                                                 NaN
     7250 6105394004                 Software Engineer, CDN Content             NaN    172000.0    258000.0                                                                 NaN
     7254 6098390004                         Software Engineer, eve             NaN    208000.0    312000.0                                                                 NaN
     7259 5798416004                   Software Engineer, Workflows             NaN    196000.0    294000.0                                                                 NaN
     7262 5806749004                           Solutions Architect              NaN    190000.0    340000.0                                                                 NaN
     7265 5971203004                         Startups Program Lead              NaN    148000.0    185000.0                                                                 NaN
     7266 5855000004             Strategic Finance Manager, Product             NaN    180000.0    220000.0                                                                 NaN
     7267 5039945004      Vercel Development Representative, Majors             NaN    100000.0    120000.0                                                                 NaN

In [47]:
fill_columns = ['location_clean','salary_currency','salary_min','salary_max','education']

updated_count = {
    col: 0
    for col in fill_columns
}

for _, row in vercel_individual.iterrows():

    idx = row['df_index']

    for col in fill_columns:

        # Existing value
        old_value = df.loc[idx, col]

        # Scraped value
        new_value = row[col]

        # Fill ONLY if existing value is missing
        # and scraped value is available
        if (
            pd.isna(old_value)
            and pd.notna(new_value)
        ):

            df.loc[idx, col] = new_value

            updated_count[col] += 1


print("Updated values:")
print(updated_count)

Updated values:
{'location_clean': 0, 'salary_currency': 4, 'salary_min': 28, 'salary_max': 28, 'education': 1}

In [49]:
print(df.loc[comparison_df['df_index'],
        [ 'id', 'title','location_clean','salary_currency','salary_min','salary_max', 'education']
    ].to_string(index=False))

        id                                          title                                        location_clean salary_currency  salary_min  salary_max                                                           education
5999792004                      Account Executive, Majors                                       Hybrid - London             GBP    200000.0    270000.0                                                                 NaN
5841911004               Account Executive, Majors (APAC)                                       Hybrid - Sydney             AUD    388000.0    524000.0                                                                 NaN
6100103004 Account Executive, Majors- Install Base (APAC)                                       Hybrid - Sydney             AUD    388000.0    524000.0                                                                 NaN
5042174004                   Enterprise Account Executive         Hybrid - San Francisco, New York City, Austin             NaN    290000.0    340000.0                                                                 NaN
6102654004                                    GRC Analyst                                Remote - United States             NaN    134000.0    202000.0                                                                 NaN
6016765004         Growth Marketing Manager, Agent Stack          Hybrid - San Francisco, New York City, Austin             NaN    176000.0    220000.0                                                                 NaN
5979111004           Head of Field Engineering Operations                                Hybrid - San Francisco             NaN    260000.0    300000.0                                                                 NaN
6011904004                 Performance Marketing Manager          Hybrid - San Francisco, New York City, Austin             NaN    150000.0    188000.0                                                                 NaN
6011651004                  Product Strategy & Operations                                Hybrid - San Francisco             NaN    232000.0    348000.0                                                                 NaN
6102335004                       Security Engineer, Cloud                                Remote - United States             NaN         NaN         NaN bachelors or masters degree in Cybersecurity or similar disciplines
6111332004          Security Engineer, Detection Response Hybrid - San Francisco, New York City, London, Berlin             NaN    208000.0    312000.0                                                                 NaN
6093255004                Security Software Engineer, IAM                                Remote - United States             NaN    208000.0    312000.0                                                                 NaN
5691965004                  Senior Legal Counsel, Product                                Hybrid - San Francisco             NaN    270000.0    300000.0                                                                 NaN
5995789004            Senior Manager, Solutions Architect                                    Remote - Australia             AUD    280000.0    350000.0                                                                 NaN
5825469004                    Senior Partner Manager, AWS         Hybrid - San Francisco, New York City, Austin             NaN    297000.0    362000.0                                                                 NaN
6112845004               Senior Technical Account Manager         Hybrid - San Francisco, New York City, Austin             NaN    163000.0    204000.0                                                                 NaN
5732855004                                  Site Engineer                                Remote - United States             NaN    196000.0    294000.0                                                                 NaN
5704320004                       Software Engineer, Agent                                Hybrid - San Francisco             NaN    232000.0    348000.0                                                                 NaN
5798406004                  Software Engineer, AI Gateway                 Hybrid - San Francisco, New York City             NaN    196000.0    294000.0                                                                 NaN
5474915004                      Software Engineer, AI SDK                 Hybrid - San Francisco, New York City             NaN    196000.0    294000.0                                                                 NaN
5430088004                     Software Engineer, Backend                                Remote - United States             NaN    196000.0    294000.0                                                                 NaN
5179639004                         Software Engineer, CDN                 Hybrid - San Francisco, New York City             NaN    196000.0    294000.0                                                                 NaN
6105394004                 Software Engineer, CDN Content                                Hybrid - San Francisco             NaN    172000.0    258000.0                                                                 NaN
6098390004                         Software Engineer, eve                 Hybrid - San Francisco, New York City             NaN    208000.0    312000.0                                                                 NaN
5798416004                   Software Engineer, Workflows                 Hybrid - San Francisco, New York City             NaN    196000.0    294000.0                                                                 NaN
5806749004                           Solutions Architect          Hybrid - San Francisco, New York City, Austin             NaN    190000.0    340000.0                                                                 NaN
5971203004                         Startups Program Lead                  Hybrid - San Francisco, New York City             NaN    148000.0    185000.0                                                                 NaN
5855000004             Strategic Finance Manager, Product                                Hybrid - San Francisco             NaN    180000.0    220000.0                                                                 NaN
5039945004      Vercel Development Representative, Majors         Hybrid - San Francisco, New York City, Austin             NaN    100000.0    120000.0                                                                 NaN

In [50]:
df.to_csv(
    "jobs_cleaned_enriched_vercel.csv",
    index=False
)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [51]:
checkr_jobs = df[df['absolute_url'].str.contains('job-boards.greenhouse.io/checkr',case=False,na=False)].copy()

print("Checkr rows:", len(checkr_jobs))

print( checkr_jobs[['id', 'title', 'absolute_url']].head(10).to_string(index=False))

Checkr rows: 60
     id                                                title                                         absolute_url
7962033            Account Director – Strategic Partnerships https://job-boards.greenhouse.io/checkr/jobs/7962033
7958414                             AI Conversation Designer https://job-boards.greenhouse.io/checkr/jobs/7958414
7921295                        Associate Manager, Operations https://job-boards.greenhouse.io/checkr/jobs/7921295
7913718                                       Chief of Staff https://job-boards.greenhouse.io/checkr/jobs/7913718
7909785                              Chief of Staff, Product https://job-boards.greenhouse.io/checkr/jobs/7909785
8027296                         Commercial Account Executive https://job-boards.greenhouse.io/checkr/jobs/8027296
8048820                             Customer Success Manager https://job-boards.greenhouse.io/checkr/jobs/8048820
8022521                          Customer Support Specialist https://job-boards.greenhouse.io/checkr/jobs/8022521
7964126 Demand & Integration Partnerships Manager - Mortgage https://job-boards.greenhouse.io/checkr/jobs/7964126
7985646                       Director, Assistant Controller https://job-boards.greenhouse.io/checkr/jobs/7985646

In [53]:
from selenium import webdriver
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.by import By
import time

options = Options()
options.add_argument("--start-maximized")

driver = webdriver.Edge(options=options)

print("Driver started successfully")

Driver started successfully

In [54]:
test_url = "https://job-boards.greenhouse.io/checkr/jobs/7727737"

driver.get(test_url)
time.sleep(3)

page_title = driver.title
page_text = driver.find_element(By.TAG_NAME, "body").text

print("Page title:")
print(page_title)

print("\nPage text length:", len(page_text))

print("\nFirst 3000 characters:")
print(page_text[:3000])

Page title:
Job Application for Staff Customer Success Manager at Checkr

Page text length: 7844

First 3000 characters:
Back to jobs
Staff Customer Success Manager
San Francisco, California, United States
Apply
About Checkr
Checkr is building the data platform to power safe and fair decisions. Over 140,000 companies and millions of people rely on Checkr for AI verification in the moments that matter most: getting a new job, a new place to live, a car ride, childcare, even a date. Customers include Uber, Pennymac, Airbnb, Doordash, and Anthropic.

We’re a team that thrives on solving complex problems with innovative solutions that advance our mission. Checkr is recognized on Forbes Cloud 100 2025 List and is a Y Combinator 2024 Breakthrough Company.
As a Customer Success Manager for Checkr Trust, you will join an emerging business inside Checkr, operating across multiple verticals that we interact with in our everyday lives. We have strong traction — but our post-sale motion is still in its early stages.
This role sits at the intersection of Customer Success, Technical Strategy, and Commercial Growth.
You will own a portfolio of strategic accounts and be accountable for:
Adoption
Expansion
Executive alignment
Long-term value realization
This is not a reactive CSM role.
This is not a pure TAM role.
You are the strategic operator ensuring customers deploy deeply, expand meaningfully, and become long-term partners.
If you want clear swim lanes and mature playbooks, this isn’t it.
If you want to help define how this business scales, this is the opportunity.
What You’ll Do
Own Strategic Accounts End-to-End
Serve as the primary post-sale owner for high-impact, high-visibility customers
Drive executive-level alignment on business goals and measurable outcomes
Ensure deployments move from contract to meaningful production usage quickly
Drive Adoption & Commercial Growth
Identify underutilization and remove barriers to deeper embedding
Surface expansion opportunities tied to customer workflows and risk exposure
Partner closely with Sales on renewals and strategic growth motions
Be accountable for retention and expansion revenue across your portfolio
Use advanced AI tools to build systems that help us grow
Translate Product Into Business Impact
Understand customer workflows well enough to connect product capabilities to operational and financial outcomes
Lead quarterly business reviews that demonstrate ROI and strategic value
Turn performance data into actionable insights that influence customer strategy
Leverage AI to turn data into insights
Partner cross-functionally with leadership to shape the future our product
Build the Playbook
Help define segmentation, engagement models, and risk signals.
Develop scalable frameworks for launches, renewals, and expansion.
Influence product roadmap through structured customer feedback.
Raise the bar on what “great” customer partnership looks like in a new market.
What We’re Looking For
You likely have:
6–10+ years in Customer Success, Strategic Account Management, or a hybrid post-sale role in B2B SaaS
Experience owning enterprise or h

In [55]:
import re
import time
from selenium.webdriver.common.by import By


def extract_checkr_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:


        # 1. Open page

        driver.get(url)
        time.sleep(3)

        page_text = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        text_lower = page_text.lower()


        # 2. Check for unavailable / 404 page

        unavailable_patterns = ['404', 'page not found',
            'job not found','this job is no longer available',
            'position is no longer available']

        if any(
            pattern in text_lower
            for pattern in unavailable_patterns
        ):

            result['page_type'] = '404'

            return result



        # 3. Check individual job page

        job_indicators = ['back to jobs','apply','about checkr',
            'what you’ll do',"what you'll do",'what we’re looking for',
            "what we're looking for",'pay transparency disclosure','what we offer']

        job_score = sum(indicator in text_lower for indicator in job_indicators)

        if job_score >= 3:

            result['page_type'] = 'individual_job'

        else:

            result['page_type'] = 'unknown_page'

            return result



        # 4. Extract location


        lines = [ line.strip()
            for line in page_text.split('\n')
            if line.strip()]

        back_to_jobs_index = None

        for i, line in enumerate(lines):

            if line.lower() == 'back to jobs':

                back_to_jobs_index = i
                break


        if back_to_jobs_index is not None:

            location_index = back_to_jobs_index + 2

            if location_index < len(lines):

                possible_location = lines[
                    location_index
                ]

                if (
                    possible_location.lower() != 'apply'
                    and possible_location.lower() != 'back to jobs'
                    and len(possible_location) <= 300
                ):

                    result['location_clean'] = (
                        possible_location
                    )



        # 5. Extract salary

        salary_patterns = [

            # Example:
            # $169,000 - $199,000 USD
            r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)\s*'
            r'(USD|AUD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)',

            # Example:
            # 169,000 - 199,000 USD
            r'([\d,]+)\s*[-–]\s*([\d,]+)\s*'
            r'(USD|AUD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)',

            # Example:
            # 169,000 - 199,000 USD OTE
            r'([\d,]+)\s*[-–]\s*([\d,]+)\s*'
            r'(USD|AUD|CAD|EUR|GBP|SGD|INR|JPY|CHF|NZD)'
            r'(?:\s+OTE)?'
        ]


        salary_found = False

        for pattern in salary_patterns:

            match = re.search(pattern,page_text, re.IGNORECASE)

            if match:

                result['salary_min'] = float(
                    match.group(1).replace(',', ''))

                result['salary_max'] = float(
                    match.group(2).replace(',', '')
                )

                if len(match.groups()) >= 3:

                    result['salary_currency'] = (
                        match.group(3).upper()
                    )

                salary_found = True

                break



        # 6. Dollar range without explicit currency
 

        if not salary_found:

            dollar_match = re.search(
                r'\$([\d,]+)\s*[-–]\s*\$([\d,]+)',
                page_text,
                re.IGNORECASE
            )

            if dollar_match:

                result['salary_min'] = float(
                    dollar_match.group(1).replace(',', '')
                )

                result['salary_max'] = float(
                    dollar_match.group(2).replace(',', '')
                )

                # Do NOT assume USD.



        # 7. Extract explicit education requirement


        education_patterns = [

            r"\b(Bachelor['’]s"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Master['’]s"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Ph\.?\s*D\.?"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})",

            r"\b(Doctorate"
            r"(?:\s+degree)?"
            r"[^.\n]{0,250})"
        ]


        for pattern in education_patterns:

            matches = re.finditer(
                pattern,
                page_text,
                re.IGNORECASE
            )

            for match in matches:

                education = match.group(1).strip()

                education_lower = education.lower()


                # Reject obvious false positives
                false_positive_patterns = ['master your','master the',
                    'mastering ', 'mastery', 'masterfully']

                if any(
                    bad in education_lower
                    for bad in false_positive_patterns
                ):

                    continue


                if 5 <= len(education) <= 300:

                    result['education'] = education

                    break


            if result['education'] is not None:

                break


        return result


    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        return result

In [56]:
test_url = "https://job-boards.greenhouse.io/checkr/jobs/7727737"

test_result = extract_checkr_job(test_url)

print(test_result)

{'location_clean': 'San Francisco, California, United States', 'salary_currency': 'USD', 'salary_min': 169000.0, 'salary_max': 199000.0, 'education': None, 'page_type': 'individual_job'}

In [57]:
checkr_indices = df.index[ df['absolute_url'].str.contains('job-boards.greenhouse.io/checkr', case=False,na=False)]

checkr_results = []

for count, idx in enumerate(
    checkr_indices,
    start=1
):

    url = df.loc[idx, 'absolute_url']

    result = extract_checkr_job(url)

    result['df_index'] = idx
    result['source_url'] = url
    result['title'] = df.loc[idx, 'title']

    checkr_results.append(result)

    if count % 10 == 0:
        print(
            f"Processed "
            f"{count}/{len(checkr_indices)} Checkr jobs"
        )

print(
    "Finished:",
    len(checkr_results)
)

Processed 10/60 Checkr jobs
Processed 20/60 Checkr jobs
Processed 30/60 Checkr jobs
Processed 40/60 Checkr jobs
Processed 50/60 Checkr jobs
Processed 60/60 Checkr jobs
Finished: 60

In [58]:
checkr_results_df = pd.DataFrame( checkr_results)

print("Shape:", checkr_results_df.shape)

print("\nPage types:")
print(checkr_results_df['page_type'].value_counts())

Shape: (60, 9)

Page types:
page_type
unknown_page      52
individual_job     8
Name: count, dtype: int64

In [59]:
print( checkr_results_df[checkr_results_df['page_type'] == 'individual_job' ][
        [ 'df_index','title','location_clean','salary_currency', 'salary_min', 'salary_max','education'
        ] ].to_string(index=False))

 df_index                                         title                                                            location_clean salary_currency  salary_min  salary_max                                                 education
     6731                                Chief of Staff                                  San Francisco, California, United States             USD    238000.0    280000.0                                                      None
     6733                  Commercial Account Executive Denver, Colorado, United States; San Francisco, California, United States             USD    164475.0    193500.0                                                      None
     6738                  Director of Customer Success Denver, Colorado, United States; San Francisco, California, United States             USD    233000.0    274000.0                                                      None
     6750            Product Finance & Strategy Manager                                  San Francisco, California, United States             USD    161000.0    217000.0                                                      None
     6756                          Senior Data Engineer Denver, Colorado, United States; San Francisco, California, United States             USD    185000.0    218000.0                                                      None
     6768                Senior Staff Software Engineer                                  San Francisco, California, United States             USD    257000.0    302000.0                                   Bachelor's or Master's)
     6778                Staff Customer Success Manager                                  San Francisco, California, United States             USD    169000.0    199000.0                                                      None
     6782 Staff Product Manager, Hiring Fraud Solutions Denver, Colorado, United States; San Francisco, California, United States             USD    170000.0    200000.0 Bachelor's in Computer Science or related field preferred

In [60]:
# Clean Checkr education values
checkr_results_df.loc[ checkr_results_df['education'].notna(),
    'education'] = (checkr_results_df.loc[ checkr_results_df['education'].notna(),
        'education'].str.strip() .str.rstrip(')').str.strip())

print( checkr_results_df[checkr_results_df['education'].notna()][
        ['df_index', 'title', 'education']].to_string(index=False))

 df_index                                         title                                                 education
     6768                Senior Staff Software Engineer                                    Bachelor's or Master's
     6782 Staff Product Manager, Hiring Fraud Solutions Bachelor's in Computer Science or related field preferred

In [61]:
checkr_individual = checkr_results_df[checkr_results_df['page_type'] == 'individual_job'].copy()

fill_columns = ['location_clean','salary_currency','salary_min','salary_max','education']

for _, row in checkr_individual.iterrows():
    idx = row['df_index']

    changes = {}

    for col in fill_columns:
        old_value = df.loc[idx, col]
        new_value = row[col]

        if pd.isna(old_value) and pd.notna(new_value):
            changes[col] = new_value

    if changes:
        print(f"\nIndex {idx} | {row['title']}")
        print(changes)

Index 6731 | Chief of Staff
{'salary_currency': 'USD', 'salary_min': 238000.0, 'salary_max': 280000.0}

Index 6733 | Commercial Account Executive
{'salary_currency': 'USD', 'salary_min': 164475.0, 'salary_max': 193500.0}

Index 6738 | Director of Customer Success
{'salary_currency': 'USD', 'salary_min': 233000.0, 'salary_max': 274000.0}

Index 6750 | Product Finance & Strategy Manager
{'salary_currency': 'USD', 'salary_min': 161000.0, 'salary_max': 217000.0}

Index 6756 | Senior Data Engineer
{'salary_currency': 'USD', 'salary_min': 185000.0, 'salary_max': 218000.0}

Index 6768 | Senior Staff Software Engineer
{'salary_currency': 'USD', 'salary_min': 257000.0, 'salary_max': 302000.0, 'education': "Bachelor's or Master's"}

Index 6778 | Staff Customer Success Manager
{'salary_currency': 'USD', 'salary_min': 169000.0, 'salary_max': 199000.0}

Index 6782 | Staff Product Manager, Hiring Fraud Solutions
{'salary_currency': 'USD', 'salary_min': 170000.0, 'salary_max': 200000.0, 'education': "Bachelor's in Computer Science or related field preferred"}

In [62]:
fill_columns = ['location_clean','salary_currency','salary_min','salary_max', 'education']

updated_count = {col: 0 for col in fill_columns}

for _, row in checkr_individual.iterrows():
    idx = row['df_index']

    for col in fill_columns:
        if pd.isna(df.loc[idx, col]) and pd.notna(row[col]):
            df.loc[idx, col] = row[col]
            updated_count[col] += 1

print("Updated values:")
print(updated_count)

Updated values:
{'location_clean': 0, 'salary_currency': 8, 'salary_min': 8, 'salary_max': 8, 'education': 2}

In [63]:
df.to_csv("jobs_cleaned_enriched_checkr.csv", index=False)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [64]:
# gusto_indices

In [65]:
gusto_indices = df.index[ df['absolute_url'].str.contains('job-boards.greenhouse.io/gusto',case=False, na=False )]

print("Gusto rows:", len(gusto_indices))

print(df.loc[gusto_indices, ['id', 'title', 'absolute_url']].head(10) .to_string(index=False))

Gusto rows: 78
     id                                                       title                                        absolute_url
7665279                     Application Systems Engineering Manager https://job-boards.greenhouse.io/gusto/jobs/7665279
7983701                             Benefit Customer Care Advocate  https://job-boards.greenhouse.io/gusto/jobs/7983701
8055761                            Benefits Care Advocate, Phoenix  https://job-boards.greenhouse.io/gusto/jobs/8055761
7983773                                Broker Integration Advocate  https://job-boards.greenhouse.io/gusto/jobs/7983773
8035802                                  Business Money Engineering https://job-boards.greenhouse.io/gusto/jobs/8035802
8022493 Channel Partnerships Manager, Investor Ecosystems (VC & PE) https://job-boards.greenhouse.io/gusto/jobs/8022493
8024433      Compliance Manager, Broker-Dealer & Investment Adviser https://job-boards.greenhouse.io/gusto/jobs/8024433
8036726                                  Consumer Money Team Leader https://job-boards.greenhouse.io/gusto/jobs/8036726
6348898              Corporate Development & Partnerships Deal Lead https://job-boards.greenhouse.io/gusto/jobs/6348898
7656216                                       Data Scientist, Risk  https://job-boards.greenhouse.io/gusto/jobs/7656216

In [66]:
gusto_test_url = "https://job-boards.greenhouse.io/gusto/jobs/7654934"

driver.get(gusto_test_url)
time.sleep(3)

page_title = driver.title
page_text = driver.find_element(By.TAG_NAME, "body").text

print("Title:", page_title)
print("Text length:", len(page_text))
print("\nFirst 4000 characters:\n")
print(page_text[:4000])

Title: Job Application for Senior Staff Software Engineer, Money Group at Gusto, Inc.
Text length: 14021

First 4000 characters:

Back to jobs
Senior Staff Software Engineer, Money Group
Denver, CO;San Francisco, CA;New York, NY
Apply
  About Gusto
At Gusto, we're on a mission to grow the small business economy. We handle the hard stuff — payroll, health insurance, 401(k)s, and HR — so owners can focus on their craft and their customers. With teams in Denver, San Francisco, and New York, we support more than 500,000 small businesses nationwide and are building a workplace that reflects the people we serve.

All full-time employees receive competitive base pay, benefits, and equity (RSUs) — because everyone who helps build Gusto should share in its success. Offer amounts are determined by role, level, and location. Learn more about our Total Rewards philosophy.

AI is a fundamental part of how work gets done at Gusto. We expect all team members to actively engage with AI tools relevant to their role and grow their fluency as the technology evolves. AI experience requirements vary by role and will be assessed during the interview process.
About the Role
We're hiring a Senior Staff Engineer to serve as a Technical Lead across multiple pods in the Money Group – Gusto's fastest-growing organization and a cornerstone of the company's transformation into the Small Business Finance Platform.
You'll leverage deep domain expertise to help shape the technical vision for systems that power consumer and business financial health including financial accounts, money movement, lending, expense controls, etc. – ensuring the architecture scales as we grow. This role spans strategy and execution: guiding architectural direction across a group of 15-20 engineers, vetting external partners, prototyping new product lines to unblock product decisions, extracting services from our monolith, and mentoring the engineers around you. You'll be the person who fills whatever role the group needs to hit its goals – from hands-on coding to strategic planning to unblocking other teams.
If you're excited about building financial infrastructure with real impact on the people and businesses that power the modern economy, we'd love for you to join us.
About the Team
Money is Gusto's fastest-growing group, building financial products for both sides of the employment relationship. For small businesses, we're extending the category of employer-facing financial services – bill pay, invoicing, working capital, expense cards, and cash flow insights that help SMBs get paid faster and pay others with confidence. For employees, we build tools that reduce financial stress: on-demand pay, high-yield cash accounts, automated savings, and credit-building features. This is a deeply technical domain spanning payments infrastructure, lending, multi-party integrations, and mobile-first experiences – with the complexity and scale to match.
Together, these teams are building toward a unified financial operating system for small businesses – accounting, banking, payments, lending, and tax – all connected to Gusto's payroll and people platform.
Our unique advantage is Gusto's authority over payroll data, which we leverage to build a payroll-confidence engine no standalone fintech can replicate.
Sub-Teams
Business Money: Business Money is building the financial operating system for small businesses on Gusto. We help owners manage how money flows in and out of their business – from paying bills and running payroll on time, to accessing capital and controlling employee expenses. Our tools (expense management, lending/payroll protection, cash flow insights, invoicing) give business owners more confidence and control over their cash flow so they can focus on building their business. Whether it's a Money Dashboard that flags payroll risks before they happen, or a Payroll Bridge loan that covers a cash shortfall, we're shaping solutions that make a real difference for SMBs.
Consumer Money: Consumer Money exists to help every employee achieve financial peace of mind through the connection between their employment a

In [80]:
import re
import time
from selenium.webdriver.common.by import By


def extract_gusto_job(url):

    result = {
        'location_clean': None,
        'salary_ranges': [],
        'education': None,
        'page_type': None
    }

    try:

        # OPEN PAGE

        driver.get(url)
        time.sleep(3)

        page_text = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        text_lower = page_text.lower()


        # CHECK 404 / UNAVAILABLE PAGE

        unavailable_patterns = ['404',
            'page not found',
            'job not found',
            'this job is no longer available',
            'position is no longer available' ]

        if any(
            pattern in text_lower
            for pattern in unavailable_patterns
        ):
            result['page_type'] = '404'
            return result


        # IDENTIFY INDIVIDUAL JOB PAGE

        job_indicators = ['back to jobs','apply','about gusto',
            'about the role',"here's what you'll do", "here's what we're looking for",
            'what we’re looking for','cash compensation','total rewards' ]

        job_score = sum(
            indicator in text_lower
            for indicator in job_indicators
        )

        if job_score >= 3:
            result['page_type'] = 'individual_job'
        else:
            result['page_type'] = 'unknown_page'
            return result


        # EXTRACT LOCATION
  
        lines = [ line.strip()
            for line in page_text.split('\n')
            if line.strip() ]

        back_to_jobs_index = None

        for i, line in enumerate(lines):

            if line.lower() == 'back to jobs':
                back_to_jobs_index = i
                break

        if back_to_jobs_index is not None:

            location_index = back_to_jobs_index + 2

            if location_index < len(lines):

                possible_location = lines[location_index]

                if (
                    possible_location.lower() != 'apply'
                    and possible_location.lower() != 'back to jobs'
                    and len(possible_location) <= 300
                ):
                    result['location_clean'] = possible_location


        # EXTRACT SALARY DISCLOSURE

        salary_sentences = [
            line.strip()
            for line in lines
            if (
                'cash compensation' in line.lower()
                or 'compensation amount' in line.lower()
            )
        ]

        # ---------------------------------------------------------
        # FORMAT A
        #
        # $153,000 to $195,000 USD for Denver...
        # $180,815 to $230,000 USD for San Francisco...
        # $146,940-$185,000 CAD for Toronto
        # ---------------------------------------------------------
        pattern_with_currency = re.compile(
            r'\$([\d,]+)'
            r'\s*(?:to|[-–])\s*'
            r'\$?([\d,]+)'
            r'\s*'
            r'(USD|CAD|AUD|EUR|GBP|SGD|INR|JPY|CHF|NZD)'
            r'\s*'
            r'(?:for|in)\s*'
            r'([^$]+?)'
            r'(?=\s+and\s+\$|\.\s*Final offer)',
            re.IGNORECASE
        )

        # ---------------------------------------------------------
        # FORMAT B
        #
        # $189,000–$236,000 per year in Denver...
        # $223,000–$278,000 per year in San Francisco...
        #
        # Currency is not immediately after the range.
        # Gusto's disclosure is USD in these examples.
        # ---------------------------------------------------------
        pattern_without_currency = re.compile(
            r'\$([\d,]+)'
            r'\s*[–-]\s*'
            r'\$([\d,]+)'
            r'(?:\s+per\s+year|\s*/yr)?'
            r'\s+(?:in|for)\s+'
            r'([^$]+?)'
            r'(?=,\s*and\s+\$|\s+and\s+\$|\.\s*Stock|\.\s*Final offer)',
            re.IGNORECASE
        )

        for salary_text in salary_sentences:


            # FIRST: ranges where currency is explicitly present

            matches = pattern_with_currency.findall( salary_text )

            for match in matches:

                salary_record = {
                    'salary_currency': match[2].upper(),
                    'salary_min': float(
                        match[0].replace(',', '')
                    ),
                    'salary_max': float(
                        match[1].replace(',', '')
                    ),
                    'salary_location': match[3].strip()
                }

                if salary_record not in result['salary_ranges']:
                    result['salary_ranges'].append(
                        salary_record
                    )


            # SECOND: ranges where currency isn't beside range

            matches = pattern_without_currency.findall(
                salary_text
            )

            for match in matches:

                salary_record = {
                    'salary_currency': 'USD',
                    'salary_min': float(
                        match[0].replace(',', '')
                    ),
                    'salary_max': float(
                        match[1].replace(',', '')
                    ),
                    'salary_location': match[2].strip()
                }

                if salary_record not in result['salary_ranges']:
                    result['salary_ranges'].append(
                        salary_record
                    )


        # EXTRACT EDUCATION

        education_patterns = [
            r"\b(Bachelor['’]s(?:\s+degree)?[^.\n]{0,250})",
            r"\b(Master['’]s(?:\s+degree)?[^.\n]{0,250})",
            r"\b(Ph\.?\s*D\.?(?:\s+degree)?[^.\n]{0,250})",
            r"\b(Doctorate(?:\s+degree)?[^.\n]{0,250})"
        ]

        false_positive_patterns = ['master your','master the','mastering ','mastery','masterfully' ]

        for pattern in education_patterns:

            matches = re.finditer( pattern,page_text,re.IGNORECASE)

            for match in matches:

                education = match.group(1).strip()

                education_lower = education.lower()

                if any(
                    bad in education_lower
                    for bad in false_positive_patterns
                ):
                    continue

                if 5 <= len(education) <= 300:

                    result['education'] = education
                    break

            if result['education'] is not None:
                break

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        return result

In [82]:
gusto_test_url = "https://job-boards.greenhouse.io/gusto/jobs/7654934"

gusto_test_result = extract_gusto_job(gusto_test_url)

print(gusto_test_result)

{'location_clean': 'Denver, CO;San Francisco, CA;New York, NY', 'salary_ranges': [{'salary_currency': 'USD', 'salary_min': 189000.0, 'salary_max': 236000.0, 'salary_location': 'Denver and most remote locations'}, {'salary_currency': 'USD', 'salary_min': 223000.0, 'salary_max': 278000.0, 'salary_location': 'San Francisco, Seattle, and New York'}], 'education': None, 'page_type': 'individual_job'}

In [70]:
gusto_test_url = "https://job-boards.greenhouse.io/gusto/jobs/7654934"

gusto_test_result = extract_gusto_job(gusto_test_url)

print(gusto_test_result)

{'location_clean': 'Denver, CO;San Francisco, CA;New York, NY', 'salary_ranges': [{'salary_currency': 'USD', 'salary_min': 189000.0, 'salary_max': 236000.0}, {'salary_currency': 'USD', 'salary_min': 223000.0, 'salary_max': 278000.0}], 'education': None, 'page_type': 'individual_job'}

In [83]:
gusto_results = []

for count, idx in enumerate(gusto_indices, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_gusto_job(url)

    result['df_index'] = idx
    result['source_url'] = url
    result['title'] = df.loc[idx, 'title']
    result['id'] = df.loc[idx, 'id']

    gusto_results.append(result)

    if count % 10 == 0:
        print(
            f"Processed {count}/{len(gusto_indices)} "
            f"Gusto jobs"
        )

print("Finished:", len(gusto_results))

Processed 10/78 Gusto jobs
Processed 20/78 Gusto jobs
Processed 30/78 Gusto jobs
Processed 40/78 Gusto jobs
Processed 50/78 Gusto jobs
Processed 60/78 Gusto jobs
Processed 70/78 Gusto jobs
Finished: 78

In [84]:
gusto_results_df = pd.DataFrame(gusto_results)

print("Shape:", gusto_results_df.shape)

print("\nPage types:")
print(gusto_results_df['page_type'].value_counts())

print("\nSalary range counts:")
print(gusto_results_df['salary_ranges'].apply(len) .value_counts().sort_index())

Shape: (78, 8)

Page types:
page_type
unknown_page      50
individual_job    27
404                1
Name: count, dtype: int64

Salary range counts:
salary_ranges
0    70
2     7
3     1
Name: count, dtype: int64

In [85]:
gusto_salary_jobs = gusto_results_df[gusto_results_df['salary_ranges'].apply(len) > 0].copy()

print(gusto_salary_jobs[ ['df_index','id','title','location_clean','salary_ranges','education', 'page_type' ] ].to_string(index=False))

 df_index      id                                                       title                                                                                                          location_clean                                                                                                                                                                                                                                                                                                                                                                salary_ranges education      page_type
     6655 8022493 Channel Partnerships Manager, Investor Ecosystems (VC & PE) Atlanta, GA - Remote; Denver, CO - Hybrid; New York, NY - Hybrid; San Francisco, CA - Hybrid; Toronto, Ontario - Remote [{'salary_currency': 'USD', 'salary_min': 153000.0, 'salary_max': 195000.0, 'salary_location': 'Denver, Phoenix, Atlanta metro areas'}, {'salary_currency': 'USD', 'salary_min': 180815.0, 'salary_max': 230000.0, 'salary_location': 'San Francisco & New York'}, {'salary_currency': 'CAD', 'salary_min': 146940.0, 'salary_max': 185000.0, 'salary_location': 'Toronto'}]      None individual_job
     6660 7369003                         Enterprise Application AI Architect                                                                                              San Francisco, CA - Hybrid                                                                                                        [{'salary_currency': 'USD', 'salary_min': 185000.0, 'salary_max': 205000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 225000.0, 'salary_max': 250000.0, 'salary_location': 'San Francisco, Seattle & New York'}]      None individual_job
     6707 7654934                Senior Staff Software Engineer, Money Group                                                                                Denver, CO;San Francisco, CA;New York, NY                                                                                                   [{'salary_currency': 'USD', 'salary_min': 189000.0, 'salary_max': 236000.0, 'salary_location': 'Denver and most remote locations'}, {'salary_currency': 'USD', 'salary_min': 223000.0, 'salary_max': 278000.0, 'salary_location': 'San Francisco, Seattle, and New York'}]      None individual_job
     6717 7760341                  Staff Software Engineer, Core AI Platforms                                                  San Francisco, CA - Hybrid; Denver, CO - Hybrid; New York, NY - Hybrid                                                                                                                 [{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}]      None individual_job
     6719 8008696                      Staff Software Engineer, Core Products                                                                       New York, NY - Hybrid; San Francisco, CA - Hybrid                                                                                                                 [{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}]      None individual_job
     6722 7673999        Staff Software Engineer, Growth (Revenue Enablement)                                                                                              San Francisco, CA - Hybrid                                                                                                                 [{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}]      None individual_job
     6723 7943169  Staff Software Engineer, Pricing and Packaging Engineering                                                                                                       San Francisco, CA                                                                                                                 [{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}]      None individual_job
     6725 7918214                    Staff Software Engineer, Tax Experiences                                                                                                       San Francisco, CA                                                                                                                 [{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}, {'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}]      None individual_job

In [86]:
for _, row in gusto_salary_jobs.iterrows():

    idx = row['df_index']

    print("\n" + "=" * 80)
    print(f"Index: {idx}")
    print(f"ID: {row['id']}")
    print(f"Title: {row['title']}")

    print("\nExisting df values:")
    print(df.loc[idx, ['salary_currency','salary_min','salary_max', 'location_clean','education'] ].to_dict() )

    print("\nScraped salary ranges:")
    for salary in row['salary_ranges']:
        print(salary)

================================================================================
Index: 6655
ID: 8022493
Title: Channel Partnerships Manager, Investor Ecosystems (VC & PE)

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'Phoenix, AZ; Las Vegas, NV; Denver, CO; Atlanta, GA; Chicago, IL; San Francisco, CA;New York, NY;Toronto, Ontario, CAN - Remote', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 153000.0, 'salary_max': 195000.0, 'salary_location': 'Denver, Phoenix, Atlanta metro areas'}
{'salary_currency': 'USD', 'salary_min': 180815.0, 'salary_max': 230000.0, 'salary_location': 'San Francisco & New York'}
{'salary_currency': 'CAD', 'salary_min': 146940.0, 'salary_max': 185000.0, 'salary_location': 'Toronto'}

================================================================================
Index: 6660
ID: 7369003
Title: Enterprise Application AI Architect

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'Denver, CO;San Francisco, CA;New York, NY;Los Angeles, CA;Seattle, WA;Ontario, CAN - Remote;Toronto, Ontario, CAN - Remote;United States - Remote', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 185000.0, 'salary_max': 205000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 225000.0, 'salary_max': 250000.0, 'salary_location': 'San Francisco, Seattle & New York'}

================================================================================
Index: 6707
ID: 7654934
Title: Senior Staff Software Engineer, Money Group

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'Denver, CO;San Francisco, CA;New York, NY', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 189000.0, 'salary_max': 236000.0, 'salary_location': 'Denver and most remote locations'}
{'salary_currency': 'USD', 'salary_min': 223000.0, 'salary_max': 278000.0, 'salary_location': 'San Francisco, Seattle, and New York'}

================================================================================
Index: 6717
ID: 7760341
Title: Staff Software Engineer, Core AI Platforms

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'San Francisco, CA - Hybrid; Denver, CO - Hybrid; New York, NY - Hybrid', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}

================================================================================
Index: 6719
ID: 8008696
Title: Staff Software Engineer, Core Products

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'New York, NY; San Francisco, CA', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}

================================================================================
Index: 6722
ID: 7673999
Title: Staff Software Engineer, Growth (Revenue Enablement)

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'San Francisco, CA', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}

================================================================================
Index: 6723
ID: 7943169
Title: Staff Software Engineer, Pricing and Packaging Engineering

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'San Francisco, CA', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}

================================================================================
Index: 6725
ID: 7918214
Title: Staff Software Engineer, Tax Experiences

Existing df values:
{'salary_currency': nan, 'salary_min': nan, 'salary_max': nan, 'location_clean': 'San Francisco, CA', 'education': nan}

Scraped salary ranges:
{'salary_currency': 'USD', 'salary_min': 163000.0, 'salary_max': 204000.0, 'salary_location': 'Denver & most remote locations'}
{'salary_currency': 'USD', 'salary_min': 197000.0, 'salary_max': 247000.0, 'salary_location': 'San Francisco & New York'}

In [87]:
# Save the first salary range for each Gusto job
# Only fill missing salary values — never overwrite existing data

updated_count = {
    'salary_currency': 0,
    'salary_min': 0,
    'salary_max': 0
}

for _, row in gusto_salary_jobs.iterrows():

    idx = row['df_index']

    # Take the first salary range
    first_salary = row['salary_ranges'][0]

    # Fill only if the existing value is missing
    if pd.isna(df.loc[idx, 'salary_currency']):
        df.loc[idx, 'salary_currency'] = first_salary['salary_currency']
        updated_count['salary_currency'] += 1

    if pd.isna(df.loc[idx, 'salary_min']):
        df.loc[idx, 'salary_min'] = first_salary['salary_min']
        updated_count['salary_min'] += 1

    if pd.isna(df.loc[idx, 'salary_max']):
        df.loc[idx, 'salary_max'] = first_salary['salary_max']
        updated_count['salary_max'] += 1


print("Updated values:")
print(updated_count)

Updated values:
{'salary_currency': 8, 'salary_min': 8, 'salary_max': 8}

In [88]:
gusto_ids = [ 8022493,7369003,7654934,7760341,8008696,7673999,7943169,7918214]

print(df[df['id'].isin(gusto_ids)][[ 'id','title','salary_currency','salary_min','salary_max' ] ].to_string(index=False))

     id                                                       title salary_currency  salary_min  salary_max
8022493 Channel Partnerships Manager, Investor Ecosystems (VC & PE)             USD    153000.0    195000.0
7369003                         Enterprise Application AI Architect             USD    185000.0    205000.0
7654934                Senior Staff Software Engineer, Money Group              USD    189000.0    236000.0
7760341                  Staff Software Engineer, Core AI Platforms             USD    163000.0    204000.0
8008696                      Staff Software Engineer, Core Products             USD    163000.0    204000.0
7673999        Staff Software Engineer, Growth (Revenue Enablement)             USD    163000.0    204000.0
7943169  Staff Software Engineer, Pricing and Packaging Engineering             USD    163000.0    204000.0
7918214                    Staff Software Engineer, Tax Experiences             USD    163000.0    204000.0

In [89]:
df.to_csv("jobs_cleaned_enriched_gusto.csv", index=False)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [90]:
# CircleCI verified data from the 4 job pages

circleci_updates = {
    8608742002: {
        'salary_currency': 'USD',
        'salary_min': 150000.0,
        'salary_max': 171000.0,
        'education': 'BA/BS in a related field (Business, Entrepreneurship, Sales/Marketing, or Computer Science preferred)'
    },

    8475304002: {
        'salary_currency': 'CAD',
        'salary_min': 156000.0,
        'salary_max': 196000.0,
        'education': None
    },

    8092604002: {
        'salary_currency': 'USD',
        'salary_min': 153000.0,
        'salary_max': 191000.0,
        'education': None
    },

    8420901002: {
        'salary_currency': 'CAD',
        'salary_min': 127000.0,
        'salary_max': 159000.0,
        'education': None
    }
}


# Update only missing values
updated_count = {
    'salary_currency': 0,
    'salary_min': 0,
    'salary_max': 0,
    'education': 0
}

for job_id, values in circleci_updates.items():

    matching_indices = df.index[df['id'] == job_id]

    for idx in matching_indices:

        for col in [
            'salary_currency',
            'salary_min',
            'salary_max',
            'education'
        ]:

            new_value = values[col]

            if (
                pd.isna(df.loc[idx, col])
                and pd.notna(new_value)
            ):
                df.loc[idx, col] = new_value
                updated_count[col] += 1


print("Updated values:")
print(updated_count)

Updated values:
{'salary_currency': 4, 'salary_min': 4, 'salary_max': 4, 'education': 1}

In [91]:
df.to_csv(  "jobs_cleaned_enriched_gusto_circleci.csv",index=False)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [92]:
# datadog

In [10]:
df=pd.read_csv('jobs_cleaned_enriched_gusto_circleci.csv')

In [11]:
datadog_indices = df.index[df['absolute_url'].str.contains('datadoghq.com',case=False, na=False )]

print("Datadog rows:", len(datadog_indices))

Datadog rows: 421

In [12]:
datadog_sample_indices = datadog_indices[:5]

print(df.loc[ datadog_sample_indices,['id', 'title', 'absolute_url']].to_string(index=False))

     id                                              title                                                 absolute_url
7194969  AI Research Engineer - Datadog AI Research (DAIR) https://careers.datadoghq.com/detail/7194969/?gh_jid=7194969
6572669 AI Research Scientist - Datadog AI Research (DAIR) https://careers.datadoghq.com/detail/6572669/?gh_jid=6572669
6652564 AI Research Scientist - Datadog AI Research (DAIR) https://careers.datadoghq.com/detail/6652564/?gh_jid=6652564
8003021                          Analyst Relations Manager https://careers.datadoghq.com/detail/8003021/?gh_jid=8003021
7508990     Area Vice President, Enterprise Security Sales https://careers.datadoghq.com/detail/7508990/?gh_jid=7508990

In [13]:
import re
import time
from selenium.webdriver.common.by import By


def extract_datadog_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        driver.get(url)
        time.sleep(3)

        page_text = driver.find_element(
            By.TAG_NAME, "body"
        ).text

        text_lower = page_text.lower()


        # 1. Check unavailable pages


        unavailable_patterns = [
            '404',
            'page not found',
            'job not found',
            'this job is no longer available',
            'position is no longer available'
        ]

        if any(
            pattern in text_lower
            for pattern in unavailable_patterns
        ):
            result['page_type'] = '404'
            return result


        # 2. Identify individual job page

        job_indicators = ["what you'll do","who you are", "benefits and growth",
            "about datadog","datadog offers", "requisition id", "salary" ]

        job_score = sum(
            indicator in text_lower
            for indicator in job_indicators
        )

        if job_score >= 3:
            result['page_type'] = 'individual_job'
        else:
            result['page_type'] = 'unknown_page'
            return result


        # 3. Extract location


        lines = [line.strip()
            for line in page_text.split('\n')
            if line.strip() ]

        # Datadog normally places location near the top,
        # immediately after the job title.

        location_patterns = [
            r'^.+,\s*.+,\s*USA$',
            r'^.+,\s*.+,\s*US$',
            r'^.+,\s*.+,\s*Canada$',
            r'^.+,\s*.+,\s*UK$',
            r'^.+,\s*.+,\s*United Kingdom$',
            r'^.+,\s*.+,\s*Australia$',
            r'^.+,\s*.+,\s*Germany$',
            r'^.+,\s*.+,\s*France$',
            r'^.+,\s*.+,\s*Netherlands$',
            r'^.+,\s*.+,\s*Singapore$',
            r'^.+,\s*.+,\s*Japan$'
        ]

        # Search only the beginning of the page so that
        # locations mentioned later in the job description
        # aren't incorrectly selected.

        for line in lines[:20]:

            for pattern in location_patterns:

                if re.match(
                    pattern,
                    line,
                    re.IGNORECASE
                ):
                    result['location_clean'] = line
                    break

            if result['location_clean'] is not None:
                break


        # 4. Extract salary

        # Examples:
        # $170,000—$227,000 USD
        # $150,000-$200,000 USD
        # $150,000–$200,000 USD

        salary_patterns = [r'\$([\d,]+)\s*[—–-]\s*\$([\d,]+)\s*(USD|CAD|AUD|EUR|GBP|SGD|INR|JPY|CHF|NZD)',
            r'\$([\d,]+)\s*(?:to)\s*\$([\d,]+)\s*(USD|CAD|AUD|EUR|GBP|SGD|INR|JPY|CHF|NZD)'  ]

        for pattern in salary_patterns:

            salary_match = re.search(  pattern, page_text, re.IGNORECASE )

            if salary_match:

                result['salary_min'] = float( salary_match.group(1).replace(',', '') )

                result['salary_max'] = float(salary_match.group(2).replace(',', '') )

                result['salary_currency'] = (salary_match.group(3).upper())
                break


        # 5. Extract education

        education_patterns = [

            # BA/BS
            r'\b(BA/BS[^.\n]{0,250})',

            # Bachelor's
            r"\b(Bachelor['’]s(?:\s+degree)?[^.\n]{0,250})",

            # Master's
            r"\b(Master['’]s(?:\s+degree)?[^.\n]{0,250})",

            # PhD
            r'\b(Ph\.?\s*D\.?(?:\s+degree)?[^.\n]{0,250})',

            # Doctorate
            r'\b(Doctorate(?:\s+degree)?[^.\n]{0,250})',

            # "degree in Computer Science..."
            r'\b(degree\s+in\s+[A-Za-z][^.\n]{0,250})'
        ]

        false_positive_patterns = [ 'master your','master the', 'mastering ',  'mastery','masterfully']

        for pattern in education_patterns:

            matches = re.finditer( pattern,page_text, re.IGNORECASE)

            for match in matches:

                education = match.group(1).strip()
                education_lower = education.lower()

                if any(
                    bad in education_lower
                    for bad in false_positive_patterns
                ):
                    continue

                if 5 <= len(education) <= 300:

                    result['education'] = education

                    break

            if result['education'] is not None:
                break

        return result

    except Exception as e:

        print( f"ERROR for {url}: " f"{type(e).__name__}: {e}" )

        result['page_type'] = 'error'

        return result

In [14]:
url = "https://careers.datadoghq.com/detail/8011158/?gh_jid=8011158"

result = extract_datadog_job(url)

print(result)

{'location_clean': 'New York, New York, USA', 'salary_currency': 'USD', 'salary_min': 170000.0, 'salary_max': 227000.0, 'education': 'degree in Computer Science (or equivalent)', 'page_type': 'individual_job'}

In [15]:
datadog_results = []

for count, idx in enumerate(datadog_indices, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_datadog_job(url)

    result['df_index'] = idx
    result['source_url'] = url
    result['title'] = df.loc[idx, 'title']
    result['id'] = df.loc[idx, 'id']

    datadog_results.append(result)

    if count % 10 == 0:
        print(
            f"Processed {count}/{len(datadog_indices)} "
            f"Datadog jobs"
        )

print("\nFinished:", len(datadog_results))

datadog_results_df = pd.DataFrame(datadog_results)

Processed 10/421 Datadog jobs
Processed 20/421 Datadog jobs
Processed 30/421 Datadog jobs
Processed 40/421 Datadog jobs
Processed 50/421 Datadog jobs
Processed 60/421 Datadog jobs
Processed 70/421 Datadog jobs
Processed 80/421 Datadog jobs
Processed 90/421 Datadog jobs
Processed 100/421 Datadog jobs
Processed 110/421 Datadog jobs
Processed 120/421 Datadog jobs
Processed 130/421 Datadog jobs
Processed 140/421 Datadog jobs
Processed 150/421 Datadog jobs
Processed 160/421 Datadog jobs
Processed 170/421 Datadog jobs
Processed 180/421 Datadog jobs
Processed 190/421 Datadog jobs
Processed 200/421 Datadog jobs
Processed 210/421 Datadog jobs
Processed 220/421 Datadog jobs
Processed 230/421 Datadog jobs
Processed 240/421 Datadog jobs
Processed 250/421 Datadog jobs
Processed 260/421 Datadog jobs
Processed 270/421 Datadog jobs
Processed 280/421 Datadog jobs
Processed 290/421 Datadog jobs
Processed 300/421 Datadog jobs
Processed 310/421 Datadog jobs
Processed 320/421 Datadog jobs
Processed 330/421 Datadog jobs
Processed 340/421 Datadog jobs
Processed 350/421 Datadog jobs
Processed 360/421 Datadog jobs
Processed 370/421 Datadog jobs
Processed 380/421 Datadog jobs
Processed 390/421 Datadog jobs
Processed 400/421 Datadog jobs
Processed 410/421 Datadog jobs
Processed 420/421 Datadog jobs

Finished: 421

In [16]:
print("Shape:", datadog_results_df.shape)

print("\nPage types:")
print(datadog_results_df['page_type'].value_counts())

print("\nLocation extracted:",
      datadog_results_df['location_clean'].notna().sum())

print("Salary extracted:",
      datadog_results_df['salary_min'].notna().sum())

print("Education extracted:",
      datadog_results_df['education'].notna().sum())

Shape: (421, 10)

Page types:
page_type
individual_job    211
404               209
unknown_page        1
Name: count, dtype: int64

Location extracted: 94
Salary extracted: 108
Education extracted: 34

In [17]:
print(datadog_results_df[ datadog_results_df['salary_min'].notna() ][
        ['df_index', 'id','title', 'location_clean', 'salary_currency','salary_min', 'salary_max' ] ].to_string(index=False))

 df_index      id                                                                              title                                                                                             location_clean salary_currency  salary_min  salary_max
     6039 6572669                                 AI Research Scientist - Datadog AI Research (DAIR)                                                     New York, New York, USA; Pittsburgh, Pennsylvania, USA             USD    320000.0    400000.0
     6043 7762722                                             Area Vice President, Sales Engineering Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA; San Francisco, California, USA             USD    238000.0    317000.0
     6049 1694375                                                       Commercial Account Executive                                                                                      Denver, Colorado, USA             USD     65000.0     70000.0
     6053 1497543                                              Commercial Account Executive - Boston                                                                                 Boston, Massachusetts, USA             USD     65000.0     70000.0
     6058 7858788                Commercial Account Executive - LATAM (Portuguese Speaking) - Denver                                                                                      Denver, Colorado, USA             USD     65000.0     70000.0
     6059 7329207                   Commercial Account Executive - LATAM (Spanish Speaking) - Boston                                                                                 Boston, Massachusetts, USA             USD     65000.0     70000.0
     6065 7683226                                            Commercial Sales Engineer (AMER - West)                                                                                      Denver, Colorado, USA             USD     80000.0    106000.0
     6066 7452669                                                 Commercial Sales Engineer - Boston                                                                                 Boston, Massachusetts, USA             USD     80000.0    106000.0
     6080 7128703                                                  Customer Success Manager - Boston                                                                                 Boston, Massachusetts, USA             USD     89000.0    118000.0
     6081 7232590                                                  Customer Success Manager - Denver                                                                                      Denver, Colorado, USA             USD     89000.0    118000.0
     6085 8003181                           Datadog for Startups - Forward Deployed Engineering Lead                                                                             San Francisco, California, USA             USD    200000.0    250000.0
     6086 7536402                                     Datadog for Startups Founding Engineering Lead                                                                             San Francisco, California, USA             USD    200000.0    250000.0
     6093 8003080                                                        Deal Desk Analyst - US West                                                      Denver, Colorado, USA; San Francisco, California, USA             USD     68000.0     91000.0
     6097 7583609                                      Director, Product Management - Core Platforms                                                                                    New York, New York, USA             USD    280000.0    350000.0
     6100 7984985                                        Director, Security Channels (North America)                                                                                                       None             USD    164000.0    218000.0
     6102 8010585            Director, Technical Program Management - Technical Solutions Operations                        Boston, Massachusetts, USA; New York, New York, USA; San Francisco, California, USA             USD    224000.0    280000.0
     6105 7966795                                                        Distinguished Architect, AI                                                    New York, New York, USA; San Francisco, California, USA             USD    330000.0    440000.0
     6110 7958663                                            Engineering Manager I, Threat Detection                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6132 7857714                                                Enterprise Sales Engineer - Rockies                                                                                                       None             USD    118000.0    157000.0
     6135 7405822                                                         Enterprise Sales Executive                                                                                                       None             USD    113000.0    150000.0
     6136 7465857                                                         Enterprise Sales Executive                                                                                                       None             USD    110000.0    120000.0
     6137 7405831                                                         Enterprise Sales Executive                                                                                    New York, New York, USA             USD    124000.0    165000.0
     6138 7426707                                                         Enterprise Sales Executive                                                                      Washington, District of Columbia, USA             USD    110000.0    120000.0
     6140 7410254                                                         Enterprise Sales Executive                                                                                 Boston, Massachusetts, USA             USD    110000.0    120000.0
     6141 7466155                                                         Enterprise Sales Executive                                                                                                       None             USD    110000.0    120000.0
     6142 7421284                                                   Enterprise Sales Executive (FED)                                                                                                       None             USD     90000.0    120000.0
     6143 7426680                                                   Enterprise Sales Executive (FED)                                                                      Washington, District of Columbia, USA             USD     90000.0    120000.0
     6144 7453039                                                  Enterprise Sales Executive (SLED)                                                                                                       None             USD    110000.0    120000.0
     6145 7426752                                                  Enterprise Sales Executive (SLED)                                                                             San Francisco, California, USA             USD     98000.0    130000.0
     6149 7997846                                                         Federal Support Engineer 3                                                                                      Denver, Colorado, USA             USD     92000.0    122000.0
     6154 8024863                                       Group Product Manager - Bring Your Own Cloud                                                                                    New York, New York, USA             USD    244000.0    305000.0
     6156 8023763                                              Group Product Manager - Code Security                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    244000.0    305000.0
     6159 7843331                                              GTM Strategy and Operations Associate                                                                                    New York, New York, USA             USD    100000.0    133000.0
     6160 8049521                                                  GTM Strategy/Operations Associate                                                                                    New York, New York, USA             USD    100000.0    133000.0
     6167 8024708                                                                       HRIS Manager                                                                                    New York, New York, USA             USD    131000.0    191000.0
     6170 7409236                                                             Key Accounts Executive                                 Atlanta, Georgia, USA; Boston, Massachusetts, USA; New York, New York, USA             USD    113000.0    150000.0
     6172 7409198                                                              Major Account Manager                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    165000.0    180000.0
     6184 8060821                                            Manager I, Engineering - APM Serverless                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6185 7560494 Manager I, Engineering - Applied AI - Natural Language & Conversational Interfaces                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6186 8031007                                Manager I, Engineering - Change Experience Platform                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6188 7696093                                            Manager I, Engineering - Core Analytics                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6189 7947742                           Manager I, Engineering - Data Visualization Explorations                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6190 8060788                                               Manager I, Engineering - Experiments                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6192 8041594                                         Manager I, Engineering - Onboarding Growth                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6203 7787715                           Manager I, Technical Account Management - Chicago/Denver                                                                                     Chicago, Illinois, USA             USD    154000.0    205000.0
     6212 8024670                          Manager, Strategic Sourcing, AI Infrastructure & Services                                                                                    New York, New York, USA             USD    128000.0    187000.0
     6214 6163246                                                       Mid Market Account Executive                                                                                      Denver, Colorado, USA             USD     90000.0     95000.0
     6216 6665385                                                       Mid Market Account Executive                                                                                    New York, New York, USA             USD     90000.0     95000.0
     6218 6798820                                              Mid-Market Account Executive - Boston                                                                                 Boston, Massachusetts, USA             USD     90000.0     95000.0
     6221 7082012                                       Mid-Market Account Executive - San Francisco                                                                             San Francisco, California, USA             USD     90000.0     95000.0
     6238 8003977                                      Partner Solutions Architect (GSI) - AMER East                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    149000.0    199000.0
     6243 8028508                                                      Payroll Specialist - New York                                 Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA             USD     80000.0    106000.0
     6246 7874990                                                           People Systems Developer                                 Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA             USD    156000.0    195000.0
     6248 7582679                                         Principal Partner Manager - Channels (GSI) Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA; San Francisco, California, USA             USD    138000.0    184000.0
     6249 7584250                                         Principal Partner Manager - Channels (GSI)                                                                                                       None             USD    138000.0    184000.0
     6257 7982288                                             Product Manager II, AI & Data Security                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    156000.0    195000.0
     6267 8011158                                Product Strategy and Corporate Development Lead, AI                                                                                    New York, New York, USA             USD    170000.0    227000.0
     6270 7927485                                                              Recruiter, Enterprise                                                        Boston, Massachusetts, USA; New York, New York, USA             USD     98000.0    130000.0
     6284 6685931                     Sales Development Representative (LATAM - Portuguese Speaking)                                                                                      Denver, Colorado, USA             USD     50000.0     50000.0
     6285 7003239                        Sales Development Representative (LATAM - Spanish Speaking)                                                                                 Boston, Massachusetts, USA             USD     50000.0     50000.0
     6290 7982345                                    Security Engineer 2 - Cyber Threat Intelligence                                                                                    New York, New York, USA             USD    156000.0    195000.0
     6291 7554877                                                            Security Sales Engineer                                                                                                       None             USD    149000.0    198000.0
     6299 7815616                                               Senior Cloud Security Engineer - K8s                                                                                    New York, New York, USA             USD    187000.0    240000.0
     6301 7555575                                              Senior Corporate Development Lead, AI                                                                             San Francisco, California, USA             USD    213000.0    284000.0
     6305 7985840                                 Senior Developer Advocate - Modern App Development                                                                                                       None             USD    172000.0    215000.0
     6309 8002771                                                   Senior Financial Systems Analyst                                                                                    New York, New York, USA             USD    101000.0    147000.0
     6312 7960450                                     Senior Manager, Product Solutions Architecture Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA; San Francisco, California, USA             USD    211000.0    281000.0
     6321 7984983                           Senior Partner Program Manager - Pricing & Deal Strategy                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    197000.0    246000.0
     6322 7977339                             Senior Partner Program Manager - Strategic Initiatives                                                                     Remote (US) or New York, New York, USA             USD    163000.0    204000.0
     6326 7947683                       Senior Platform Product Manager - AI SDLC Trusted Throughput                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6332 7785350                                                Senior Product Manager - Data Agent                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6335 7763117                                              Senior Product Manager - Network Path                                                                                    New York, New York, USA             USD    192000.0    240000.0
     6336 7974481                                                    Senior Product Manager - Search                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    192000.0    240000.0
     6339 7627531                             Senior Product Solutions Architect - LLM Observability Boston, Massachusetts, USA; Denver, Colorado, USA; New York, New York, USA; San Francisco, California, USA             USD    185000.0    246000.0
     6345 7516279                                               Senior Sales Engineer - Key Accounts                                                                                                       None             USD    149000.0    198000.0
     6347 7917340                                              Senior Sales Engineer - Majors (East)                                                                                                       None             USD    149000.0    198000.0
     6357 7996907                                     Senior Services Architect, Security-Cloud SIEM                                                                                    New York, New York, USA             USD    154000.0    205000.0
     6358 3851935                                                          Senior Software Engineer                                                         Boston, Massachusetts, USA; New York, New York, USA             USD    192000.0    240000.0
     6363 3851927                                     Senior Software Engineer - Distributed Systems                                                        Boston, Massachusetts, USA; New York, New York, USA             USD    192000.0    240000.0

In [18]:
update_counts = {
    'location_clean': 0,
    'salary_currency': 0,
    'salary_min': 0,
    'salary_max': 0,
    'education': 0
}

for _, row in datadog_results_df.iterrows():

    idx = row['df_index']

    for col in update_counts:

        # Update ONLY if existing value is missing
        if pd.isna(df.loc[idx, col]) and pd.notna(row[col]):
            df.loc[idx, col] = row[col]
            update_counts[col] += 1

print(update_counts)

{'location_clean': 0, 'salary_currency': 108, 'salary_min': 108, 'salary_max': 108, 'education': 34}

In [19]:
df.to_csv("jobs_cleaned_enriched_gusto_circleci_datadog.csv", index=False)

print("Saved successfully")
print("Shape:", df.shape)

Saved successfully
Shape: (7269, 42)

In [20]:
# mongodb

In [2]:
import pandas as pd
df=pd.read_csv('jobs_cleaned_enriched_gusto_circleci_datadog.csv')

In [3]:
mongodb_indices = df.index[df['absolute_url'].str.contains( 'mongodb.com',case=False, na=False )]

print("MongoDB rows:", len(mongodb_indices))

MongoDB rows: 381

In [5]:
print(df.loc[ mongodb_indices, ['id', 'title', 'absolute_url']].head(10).to_string(index=False))

     id                                                 title                                        absolute_url
7310506                    Account Development Representative https://www.mongodb.com/careers/job/?gh_jid=7310506
7311204                    Account Development Representative https://www.mongodb.com/careers/job/?gh_jid=7311204
7334950   Account Development Representative, Arabic Speaking https://www.mongodb.com/careers/job/?gh_jid=7334950
7334895 Account Development Representative - English Speaking https://www.mongodb.com/careers/job/?gh_jid=7334895
7335567   Account Development Representative, French Speaking https://www.mongodb.com/careers/job/?gh_jid=7335567
7337287   Account Development Representative, German Speaking https://www.mongodb.com/careers/job/?gh_jid=7337287
7334938   Account Development Representative, Hebrew Speaking https://www.mongodb.com/careers/job/?gh_jid=7334938
7335205  Account Development Representative, Spanish Speaking https://www.mongodb.com/careers/job/?gh_jid=7335205
7154017                        Account Executive, Acquisition https://www.mongodb.com/careers/job/?gh_jid=7154017
7870623                 Account Executive, Acquisition/Growth https://www.mongodb.com/careers/job/?gh_jid=7870623

In [21]:
import re
import time
from selenium.webdriver.common.by import By


def extract_mongodb_job(url):

    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'page_type': None
    }

    try:
        driver.get(url)
        time.sleep(3)

        page_text = driver.find_element(
            By.TAG_NAME,
            "body"
        ).text

        text_lower = page_text.lower()


        # Check unavailable pages

        unavailable_patterns = [ '404','page not found', 'job not found',
            'this job is no longer available','position is no longer available' ]

        if any(
            pattern in text_lower
            for pattern in unavailable_patterns
        ):
            result['page_type'] = '404'
            return result


        # Identify individual job page

        job_indicators = [
            "what you'll do",
            "who you are",
            "about mongodb",
            "req id",
            "salary range",
            "base salary range",
            "success measures"
        ]

        job_score = sum( indicator in text_lower for indicator in job_indicators  )

        if job_score >= 3:
            result['page_type'] = 'individual_job'
        else:
            result['page_type'] = 'unknown_page'
            return result


        # LOCATION

        lines = [line.strip() for line in page_text.split('\n') if line.strip() ]

        # Explicit remote-location statements
        remote_patterns = [
            r'this role can be based remotely in the united states',
            r'can be based remotely in the united states',
            r'remote in the united states',
            r'remotely in the united states'
        ]

        for pattern in remote_patterns:

            if re.search( pattern, page_text,
                re.IGNORECASE
            ):
                result['location_clean'] = (
                    'Remote, United States'
                )
                break

        # Normal location patterns
        if result['location_clean'] is None:

            location_patterns = [
                r'^Remote\s*[-,]?\s*.+$',
                r'^.+,\s*United States$',
                r'^.+,\s*USA$',
                r'^.+,\s*Canada$',
                r'^.+,\s*United Kingdom$',
                r'^.+,\s*UK$',
                r'^.+,\s*Australia$',
                r'^.+,\s*Germany$',
                r'^.+,\s*France$',
                r'^.+,\s*Singapore$'
            ]

            for line in lines[:40]:

                for pattern in location_patterns:

                    if re.match(
                        pattern,
                        line,
                        re.IGNORECASE
                    ):
                        result['location_clean'] = line
                        break

                if result['location_clean'] is not None:
                    break


        # SALARY

        salary_patterns = [

            # Example:
            # $192,800—$241,000 USD
            r'\$([\d,]+)\s*[—–-]\s*\$?([\d,]+)\s*'
            r'(USD|CAD|AUD|EUR|GBP|SGD|INR|JPY|CHF|NZD)',

            # Example:
            # $192,800 - $241,000
            r'\$([\d,]+)\s*[—–-]\s*\$?([\d,]+)'
        ]

        for pattern in salary_patterns:

            salary_match = re.search( pattern,page_text, re.IGNORECASE )

            if salary_match:

                result['salary_min'] = float(salary_match.group(1).replace(',', ''))

                result['salary_max'] = float(salary_match.group(2).replace(',', ''))

                # Currency only when explicitly stated
                if salary_match.lastindex >= 3:

                    result['salary_currency'] = (salary_match.group(3).upper())

                break


        # EDUCATION

        education_patterns = [
            r"\bBachelor['’]s(?:\s+degree)?[^.\n]{0,250}",
            r"\bMaster['’]s(?:\s+degree)?[^.\n]{0,250}",
            r'\bBA/BS[^.\n]{0,250}',
            r'\bB\.?Tech\.?[^.\n]{0,250}',
            r'\bM\.?Tech\.?[^.\n]{0,250}',
            r'\bMBA[^.\n]{0,250}',
            r'\bPh\.?\s*D\.?(?:\s+degree)?[^.\n]{0,250}',
            r'\bdegree in [A-Za-z][^.\n]{0,250}'
        ]

        false_positive_patterns = ['master your','master the', 'mastering', 'mastery' ]

        for pattern in education_patterns:

            matches = re.finditer( pattern, page_text, re.IGNORECASE)

            for match in matches:

                education = match.group(0).strip()

                if any(
                    bad in education.lower()
                    for bad in false_positive_patterns
                ):
                    continue

                if 5 <= len(education) <= 300:

                    result['education'] = education
                    break

            if result['education'] is not None:
                break

        return result

    except Exception as e:

        print(
            f"ERROR for {url}: "
            f"{type(e).__name__}: {e}"
        )

        result['page_type'] = 'error'

        return result

In [22]:
test_url = "https://www.mongodb.com/careers/jobs/7942142"

test_result = extract_mongodb_job(test_url)

print(test_result)

{'location_clean': 'Remote, United States', 'salary_currency': 'USD', 'salary_min': 192800.0, 'salary_max': 241000.0, 'education': None, 'page_type': 'individual_job'}

In [23]:
mongodb_results = []

for count, idx in enumerate(mongodb_indices, start=1):

    url = df.loc[idx, 'absolute_url']

    result = extract_mongodb_job(url)

    result['df_index'] = idx
    result['source_url'] = url
    result['title'] = df.loc[idx, 'title']
    result['id'] = df.loc[idx, 'id']

    mongodb_results.append(result)

    if count % 10 == 0:
        print(
            f"Processed {count}/{len(mongodb_indices)} "
            f"MongoDB jobs"
        )

print("\nFinished:", len(mongodb_results))

mongodb_results_df = pd.DataFrame(mongodb_results)

Processed 10/381 MongoDB jobs
Processed 20/381 MongoDB jobs
Processed 30/381 MongoDB jobs
Processed 40/381 MongoDB jobs
Processed 50/381 MongoDB jobs
Processed 60/381 MongoDB jobs
Processed 70/381 MongoDB jobs
Processed 80/381 MongoDB jobs
Processed 90/381 MongoDB jobs
Processed 100/381 MongoDB jobs
Processed 110/381 MongoDB jobs
Processed 120/381 MongoDB jobs
Processed 130/381 MongoDB jobs
Processed 140/381 MongoDB jobs
Processed 150/381 MongoDB jobs
Processed 160/381 MongoDB jobs
Processed 170/381 MongoDB jobs
Processed 180/381 MongoDB jobs
Processed 190/381 MongoDB jobs
Processed 200/381 MongoDB jobs
Processed 210/381 MongoDB jobs
Processed 220/381 MongoDB jobs
Processed 230/381 MongoDB jobs
Processed 240/381 MongoDB jobs
Processed 250/381 MongoDB jobs
Processed 260/381 MongoDB jobs
Processed 270/381 MongoDB jobs
Processed 280/381 MongoDB jobs
Processed 290/381 MongoDB jobs
Processed 300/381 MongoDB jobs
Processed 310/381 MongoDB jobs
Processed 320/381 MongoDB jobs
Processed 330/381 MongoDB jobs
Processed 340/381 MongoDB jobs
Processed 350/381 MongoDB jobs
Processed 360/381 MongoDB jobs
Processed 370/381 MongoDB jobs
Processed 380/381 MongoDB jobs

Finished: 381

In [24]:
print("Shape:", mongodb_results_df.shape)

print("\nPage types:")
print(mongodb_results_df['page_type'].value_counts())

print("\nLocation extracted:",  mongodb_results_df['location_clean'].notna().sum())

print("Salary extracted:",mongodb_results_df['salary_min'].notna().sum())

print( "Education extracted:",mongodb_results_df['education'].notna().sum())

Shape: (381, 10)

Page types:
page_type
404               213
unknown_page       93
individual_job     75
Name: count, dtype: int64

Location extracted: 5
Salary extracted: 54
Education extracted: 27

In [25]:
update_counts = {'location_clean': 0,
    'salary_currency': 0,
    'salary_min': 0,
    'salary_max': 0,
    'education': 0}

for _, row in mongodb_results_df.iterrows():
    idx = row['df_index']

    for col in update_counts:
        if pd.isna(df.loc[idx, col]) and pd.notna(row[col]):
            df.loc[idx, col] = row[col]
            update_counts[col] += 1

print(update_counts)

{'location_clean': 0, 'salary_currency': 21, 'salary_min': 22, 'salary_max': 22, 'education': 27}

In [26]:
df.to_csv("jobs_mongodb.csv",index=False)

print("Saved successfully")
print(df.shape)

Saved successfully
(7269, 42)

In [27]:
salary_check = df[df['salary_min'].notna() & df['salary_max'].notna()].copy()

print("Rows with both salaries:", len(salary_check))

print("\nMin = Max:")
print((salary_check['salary_min'] == salary_check['salary_max']).sum())

print("\nMin > Max:")
print((salary_check['salary_min'] > salary_check['salary_max']).sum())

Rows with both salaries: 2616

Min = Max:
60

Min > Max:
0

In [28]:
equal_salary = salary_check[ salary_check['salary_min'] == salary_check['salary_max']
][['id','title', 'company_name', 'salary_currency', 'salary_min',  'salary_max','location_clean','absolute_url']]

print(equal_salary.to_string(index=False))

        id                                                                 title                        company_name salary_currency  salary_min  salary_max                                                                                                 location_clean                                                                absolute_url
5786180968                                                          data analyst                      Proof of Skill             NaN   1200000.0   1200000.0                                                                                                Andheri, Mumbai https://www.adzuna.in/details/5786180968?utm_medium=api&utm_source=aabebcdf
5314053973                                                          data analyst                              Fisdom             NaN    100000.0    100000.0                                                                                           Bangalore, Karnataka https://www.adzuna.in/details/5314053973?utm_medium=api&utm_source=aabebcdf
5794371700                                                 data analyst(powerbi)    Trigent Software Private Limited             NaN    400000.0    400000.0                                                                                                  Yerwada, Pune https://www.adzuna.in/details/5794371700?utm_medium=api&utm_source=aabebcdf
5795880176                                                       sr data analyst    Trigent Software Private Limited             NaN    900000.0    900000.0                                                                                       Richmond Town, Bangalore https://www.adzuna.in/details/5795880176?utm_medium=api&utm_source=aabebcdf
1171507734                                             machine learning engineer                             UnFound             NaN    500000.0    500000.0                                                                                            Mumbai, Maharashtra https://www.adzuna.in/details/1171507734?utm_medium=api&utm_source=aabebcdf
5767360834                                      data engineer – machine learning                Vrinda International             NaN   1200000.0   1200000.0                                                                                           Mini Sectt., Gurgaon https://www.adzuna.in/details/5767360834?utm_medium=api&utm_source=aabebcdf
5790066219                                                                 mlops                      Sparix Global.             NaN   1920000.0   1920000.0                                                                                                          India https://www.adzuna.in/details/5790066219?utm_medium=api&utm_source=aabebcdf
5767360820                                                     backend developer                          nanokernel             NaN   1600000.0   1600000.0                                                                                       Kenchanahalli, Bangalore https://www.adzuna.in/details/5767360820?utm_medium=api&utm_source=aabebcdf
4295397020                                                     backend developer Praveza Consultancy Private Limited             NaN   1000000.0   1000000.0                                                                                            Chennai, Tamil Nadu https://www.adzuna.in/details/4295397020?utm_medium=api&utm_source=aabebcdf
2063660312                                                     backend developer         BiCSoM Technologies Pvt Ltd             NaN    100000.0    100000.0                                                                                           Bangalore, Karnataka https://www.adzuna.in/details/2063660312?utm_medium=api&utm_source=aabebcdf
1171506544                                                    frontend developer                             Mindise             NaN    200000.0    200000.0                                                                                            Mumbai, Maharashtra https://www.adzuna.in/details/1171506544?utm_medium=api&utm_source=aabebcdf
1849771151                                                    frontend developer                             Deskera             NaN    100000.0    100000.0                                                                                              Pune, Maharashtra https://www.adzuna.in/details/1849771151?utm_medium=api&utm_source=aabebcdf
1171508554                                                    frontend developer                Weekendworks Pvt Ltd             NaN    100000.0    100000.0                                                                                                   Delhi, India https://www.adzuna.in/details/1171508554?utm_medium=api&utm_source=aabebcdf
1171508381                                                    frontend developer                               Zero1             NaN    300000.0    300000.0                                                                                                   Delhi, India https://www.adzuna.in/details/1171508381?utm_medium=api&utm_source=aabebcdf
1245386188                                                    frontend developer               HappLabs Software LLP             NaN    200000.0    200000.0                                                                                           Bangalore, Karnataka https://www.adzuna.in/details/1245386188?utm_medium=api&utm_source=aabebcdf
5792256089                                                  full stack developer                      Digital Aptech             NaN     30000.0     30000.0                                                                                           Kolkata, West Bengal https://www.adzuna.in/details/5792256089?utm_medium=api&utm_source=aabebcdf
4064208657                                                  full stack developer Praveza Consultancy Private Limited             NaN    600000.0    600000.0                                                                                            Chennai, Tamil Nadu https://www.adzuna.in/details/4064208657?utm_medium=api&utm_source=aabebcdf
5798989423                                                      python developer    Trigent Software Private Limited             NaN   2500000.0   2500000.0                                                                                                          India https://www.adzuna.in/details/5798989423?utm_medium=api&utm_source=aabebcdf
4249078252                                                      python developer Praveza Consultancy Private Limited             NaN    900000.0    900000.0                                                                                            Mumbai, Maharashtra https://www.adzuna.in/details/4249078252?utm_medium=api&utm_source=aabebcdf
4034480406                                                      python developer Praveza Consultancy Private Limited             NaN   1500000.0   1500000.0                                                                                                          India https://www.adzuna.in/details/4034480406?utm_medium=api&utm_source=aabebcdf
4062011134                                                        java developer Praveza Consultancy Private Limited             NaN   1350000.0   1350000.0                                                                                                          India https://www.adzuna.in/details/4062011134?utm_medium=api&utm_source=aabebcdf
5637096407                                                       devops engineer                           We Search             NaN   1900000.0   1900000.0                                                                                           Bangalore, Karnataka https://www.adzuna.in/details/5637096407?utm_medium=api&utm_source=aabebcdf
1171508734                                                       devops engineer     RecoSense Infosolutions Pvt Ltd             NaN    100000.0    100000.0                                                                                           Bangalore, Karnataka https://www.adzuna.in/details/1171508734?utm_medium=api&utm_source=aabebcdf
5753184548                            azure cloud engineer //mumbai // 3-8 years                               2coms             NaN   2000000.0   2000000.0                                                                                              Bazargate, Mumbai https://www.adzuna.in/details/5753184548?utm_medium=api&utm_source=aabebcdf
5792949507                                      cyber security engineer (senior)    Trigent Software Private Limited             NaN   1650000.0   1650000.0                                                                                       Richmond Town, Bangalore https://www.adzuna.in/details/5792949507?utm_medium=api&utm_source=aabebcdf
4174581689                                      cyber security - risk management Praveza Consultancy Private Limited             NaN   2400000.0   2400000.0                                                                                       Navi Mumbai, Maharashtra https://www.adzuna.in/details/4174581689?utm_medium=api&utm_source=aabebcdf
5767360777                cyber security asset management (associate consultant)                Vrinda International             NaN   1200000.0   1200000.0                                                                                              Pune, Maharashtra https://www.adzuna.in/details/5767360777?utm_medium=api&utm_source=aabebcdf
5375874681        relationship manager – storage, server, cyber security & cloud                       r3 Consultant             NaN   2500000.0   2500000.0                                                                                             Ahmedabad, Gujarat https://www.adzuna.in/details/5375874681?utm_medium=api&utm_source=aabebcdf
5791199862                                                      business analyst    Trigent Software Private Limited             NaN   2300000.0   2300000.0                                                                                                          India https://www.adzuna.in/details/5791199862?utm_medium=api&utm_source=aabebcdf
4211079128                                                      business analyst Praveza Consultancy Private Limited             NaN    300000.0    300000.0                                                                                               New Delhi, Delhi https://www.adzuna.in/details/4211079128?utm_medium=api&utm_source=aabebcdf
5422236004                                         Account Executive, Mid-Market                               Figma             USD    110000.0    110000.0                                                               San Francisco, CA • New York, NY • United States        https://boards.greenhouse.io/figma/jobs/5422236004?gh_jid=5422236004
5694259004                                               Account Executive, SMB                                Figma             USD     70500.0     70500.0                                                                               San Francisco, CA • New York, NY        https://boards.greenhouse.io/figma/jobs/5694259004?gh_jid=5694259004
5558737004                                          Account Executive, Strategic                               Figma             USD    200000.0    200000.0                                                               San Francisco, CA • New York, NY • United States        https://boards.greenhouse.io/figma/jobs/5558737004?gh_jid=5558737004
5565447004                                         Senior Account Executive, SMB                               Figma             USD     82500.0     82500.0                                                               San Francisco, CA • New York, NY • United States        https://boards.greenhouse.io/figma/jobs/5565447004?gh_jid=5565447004
   7310506                                    Account Development Representative                             MongoDB             USD     50003.2     50003.2                                                                                                  New York City                         https://www.mongodb.com/careers/job/?gh_jid=7310506
   6587328                                        Enterprise Account Executive\t                             MongoDB             USD    150000.0    150000.0                                                                                                    Los Angeles                         https://www.mongodb.com/careers/job/?gh_jid=6587328
   7028355                                 Enterprise Account Executive, Federal                             MongoDB             USD    148500.0    148500.0                                                                                                         Tysons                         https://www.mongodb.com/careers/job/?gh_jid=7028355
   7269518                                  Enterprise Account Executive, Growth                             MongoDB             CAD    170000.0    170000.0                                                                                                       Montreal                         https://www.mongodb.com/careers/job/?gh_jid=7269518
   7191603                                  Enterprise Account Executive, Growth                             MongoDB             USD    150000.0    150000.0                                                                                             Chicago; St. Louis                         https://www.mongodb.com/careers/job/?gh_jid=7191603
   7141759                                  Enterprise Account Executive, Growth                             MongoDB             CAD    170000.0    170000.0                                                                                                        Toronto                         https://www.mongodb.com/careers/job/?gh_jid=7141759
   7032023                                  Enterprise Account Executive, Growth                             MongoDB             USD    135000.0    135000.0                                                                                                  New York City                         https://www.mongodb.com/careers/job/?gh_jid=7032023
   7027846                                  Enterprise Account Executive, Growth                             MongoDB             USD    150000.0    150000.0                                                                                                         Austin                         https://www.mongodb.com/careers/job/?gh_jid=7027846
   7362411                                  Enterprise Account Executive, Growth                             MongoDB             USD    150000.0    150000.0                                                                                                           Ohio                         https://www.mongodb.com/careers/job/?gh_jid=7362411
   7362626                                  Enterprise Account Executive, Growth                             MongoDB             USD    150000.0    150000.0                                                                            Boston; New York City; Pennsylvania                         https://www.mongodb.com/careers/job/?gh_jid=7362626
   7818435                                              IBM Principal Specialist                             MongoDB             USD    192000.0    192000.0                                               Atlanta; Boston; Charlotte; Chicago; New York City; Philadelphia                         https://www.mongodb.com/careers/job/?gh_jid=7818435
   8021118                                              Inside Account Executive                             MongoDB             CAD     90000.0     90000.0                                                                                                        Toronto                         https://www.mongodb.com/careers/job/?gh_jid=8021118
   7818327                            Principal Partner Specialist, Google Cloud                             MongoDB             USD    162000.0    162000.0                                                                                          Austin; New York City                         https://www.mongodb.com/careers/job/?gh_jid=7818327
   7727899 Security Software Engineer, Infrastructure Security (Staff or Senior)                             MongoDB             USD    226000.0    226000.0                                                                                                Dublin; Ireland                         https://www.mongodb.com/careers/job/?gh_jid=7727899
   7727896 Security Software Engineer, Infrastructure Security (Staff or Senior)                             MongoDB             USD    226000.0    226000.0                                                   Austin; New York City; San Francisco; Seattle; United States                         https://www.mongodb.com/careers/job/?gh_jid=7727896
   7687359                           Senior Enterprise Account Executive, Growth                             MongoDB             USD    160000.0    160000.0                                                                                                         Denver                         https://www.mongodb.com/careers/job/?gh_jid=7687359
   7727873                   Senior Site Reliability Engineer,  Fleet Management                             MongoDB             USD    226000.0    226000.0                   Austin; Boston; Chicago; Denver; Miami; New York City; San Francisco; Seattle; United States                         https://www.mongodb.com/careers/job/?gh_jid=7727873
   7727910                           Site Reliability Engineer (Senior or Staff)                             MongoDB             USD    226000.0    226000.0                                    Boston; Miami; New Jersey; New York City; Princeton; Raleigh; Washington DC                         https://www.mongodb.com/careers/job/?gh_jid=7727910
   7727913                           Site Reliability Engineer (Senior or Staff)                             MongoDB             USD    226000.0    226000.0                                                                                                        Toronto                         https://www.mongodb.com/careers/job/?gh_jid=7727913
   7727964                    Site Reliability Engineer (Senior or Staff), Atlas                             MongoDB             USD    226000.0    226000.0 Austin; Boston; Chicago; Miami; New York City; Philadelphia; Pittsburgh; Raleigh; United States; Washington DC                         https://www.mongodb.com/careers/job/?gh_jid=7727964
   7758610  Site Reliability Engineer (Senior or Staff), Infrastructure Security                             MongoDB             USD    226000.0    226000.0                                                   Austin; New York City; San Francisco; Seattle; United States                         https://www.mongodb.com/careers/job/?gh_jid=7758610
   7727920                               Staff Site Reliability Engineer, Fabric                             MongoDB             USD    226000.0    226000.0                                                                                                  United States                         https://www.mongodb.com/careers/job/?gh_jid=7727920
   7727923                               Staff Site Reliability Engineer, Fabric                             MongoDB             USD    226000.0    226000.0                                                                                             Toronto; Vancouver                         https://www.mongodb.com/careers/job/?gh_jid=7727923