In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('jobs_mongodb.csv')

In [3]:
df=df1.copy()

In [4]:
missing_summary = ( df.isnull().sum().to_frame('missing_count'))
missing_summary['missing_percent'] = (missing_summary['missing_count'] / len(df) * 100)
missing_summary = missing_summary.sort_values( 'missing_percent',ascending=False)
missing_summary

                                  missing_count  missing_percent
other_market_salary_min                    7219        99.312147
other_market_salary_max                    7219        99.312147
other_market_salary_currency               7139        98.211583
education                                  7109        97.798872
pay_transparency_min                       7073        97.303618
pay_transparency_max                       7073        97.303618
pay_transparency_unit                      7071        97.276104
contract_type                              7013        96.478195
job_level                                  6888        94.758564
job_type                                   6888        94.758564
working_model_clean                        6888        94.758564
region                                     6888        94.758564
ic_or_mg                                   6848        94.208282
ai_opt_out_request_url                     6677        91.855826
salary_currency                            6667        91.718256
include_ai_disclaimer                      6286        86.476819
requisition_id                             5567        76.585500
offices_clean                              4977        68.468840
internal_job_id                            4977        68.468840
language_clean                             4964        68.289999
departments_clean                          4964        68.289999
demographic_data_consent_applies           4964        68.289999
updated_at                                 4964        68.289999
salary_min                                 4653        64.011556
longitude                                  4642        63.860228
latitude                                   4642        63.860228
salary_max                                 4354        59.898198
city                                       3453        47.503095
state                                      3429        47.172926
contract_time                              3369        46.347503
standard_role                              2305        31.710001
category                                   2305        31.710001
location_clean                                8         0.110056
title                                         0         0.000000
absolute_url                                  0         0.000000
id                                            0         0.000000
created_time                                  0         0.000000
created_date                                  0         0.000000
created                                       0         0.000000
content_clean                                 0         0.000000
company_name                                  0         0.000000
source                                        0         0.000000

In [5]:
missing_by_source = pd.DataFrame({ 'Adzuna_missing_%': df[df['source'] == 'Adzuna'].isna().mean() * 100,
                                  'Greenhouse_missing_%': df[df['source'] == 'Greenhouse'].isna().mean() * 100})
missing_by_source = missing_by_source.sort_values( 'Adzuna_missing_%',ascending=False)
missing_by_source

                                  Adzuna_missing_%  Greenhouse_missing_%
include_ai_disclaimer                   100.000000             57.353579
requisition_id                          100.000000             26.160521
pay_transparency_unit                   100.000000             91.409978
pay_transparency_min                    100.000000             91.496746
pay_transparency_max                    100.000000             91.496746
other_market_salary_min                 100.000000             97.830803
other_market_salary_max                 100.000000             97.830803
other_market_salary_currency            100.000000             94.360087
offices_clean                           100.000000              0.563991
salary_currency                         100.000000             73.882863
ai_opt_out_request_url                  100.000000             74.316703
language_clean                          100.000000              0.000000
job_type                                100.000000             83.470716
job_level                               100.000000             83.470716
internal_job_id                         100.000000              0.563991
region                                  100.000000             83.470716
ic_or_mg                                100.000000             81.735358
education                               100.000000             93.058568
departments_clean                       100.000000              0.000000
demographic_data_consent_applies        100.000000              0.000000
updated_at                              100.000000              0.000000
working_model_clean                     100.000000             83.470716
contract_type                            94.842869            100.000000
salary_min                               58.340048             76.225597
salary_max                               52.316680             76.225597
longitude                                47.078969            100.000000
latitude                                 47.078969            100.000000
city                                     23.267526             99.696312
state                                    22.784045             99.696312
contract_time                            21.434327            100.000000
standard_role                             0.000000            100.000000
title                                     0.000000              0.000000
absolute_url                              0.000000              0.000000
location_clean                            0.000000              0.347072
id                                        0.000000              0.000000
created_time                              0.000000              0.000000
created_date                              0.000000              0.000000
created                                   0.000000              0.000000
content_clean                             0.000000              0.000000
company_name                              0.000000              0.000000
category                                  0.000000            100.000000
source                                    0.000000              0.000000

In [6]:
salary_currency_missing = pd.crosstab(df['source'],df['salary_currency'].isna(),normalize='index') * 100
salary_currency_missing

salary_currency      False       True
source
Adzuna            0.000000  100.000000
Greenhouse       26.117137   73.882863

In [7]:
salary_missing_pattern = pd.crosstab(df['salary_min'].isna(), df['salary_max'].isna())
salary_missing_pattern

salary_max  False  True
salary_min
False        2616      0
True          299   4354

In [8]:
df[ df['salary_min'].isna() &df['salary_max'].notna()][['source', 'company_name', 'title', 'salary_currency', 'salary_max']].head(20)

,source,company_name,title,salary_currency,salary_max
320,Adzuna,Talentspro,software engineer,NaN,2000000.0
529,Adzuna,Fragma Data Systems,data scientist,NaN,1200000.0
569,Adzuna,BYGRAD,data scientist,NaN,1200000.0
639,Adzuna,Yottaasys AI LLC,data scientist,NaN,2000000.0
652,Adzuna,Unnati,data scientist,NaN,1500000.0
658,Adzuna,Unnati,data scientist,NaN,1200000.0
671,Adzuna,Accolite Software,data scientist,NaN,2400000.0
678,Adzuna,Angel One,data scientist,NaN,1500000.0
696,Adzuna,Ezeiatech systems,data scientist,NaN,1500000.0
705,Adzuna,Yottaasys AI LLC,data scientist,NaN,1500000.0
780,Adzuna,SveltetechTechnologies Pvt Ltd,data analyst,NaN,300000.0
804,Adzuna,Reality Premedia Services Pvt Ltd,data analyst,NaN,800000.0
817,Adzuna,MSMEx,data analyst,NaN,1200000.0
818,Adzuna,Syrencloud,data analyst,NaN,800000.0
837,Adzuna,Jobdost,data analyst,NaN,500000.0
852,Adzuna,BitClass,data analyst,NaN,1600000.0
854,Adzuna,Amazon,data analyst,NaN,800000.0
858,Adzuna,Extramarks,data analyst,NaN,1000000.0
898,Adzuna,Marktine,data analyst,NaN,1500000.0
908,Adzuna,Azent Overseas,data analyst,NaN,700000.0

In [9]:
df[(df['source'] == 'Adzuna') &(df['salary_min'].isna()) &(df['salary_max'].notna())]['salary_max'].describe()

count    2.990000e+02
mean     1.160067e+06
std      6.762451e+05
min      1.200000e+05
25%      7.000000e+05
50%      1.000000e+06
75%      1.500000e+06
max      7.200000e+06
Name: salary_max, dtype: float64

In [10]:
pd.crosstab(df['source'],df['city'].isna(),normalize='index') * 100

city            False      True
source
Adzuna      76.732474  23.267526
Greenhouse   0.303688  99.696312

In [11]:
pd.crosstab(df['source'],df['state'].isna(), normalize='index') * 100

state           False      True
source
Adzuna      77.215955  22.784045
Greenhouse   0.303688  99.696312

In [12]:
pd.crosstab( df['source'], df['contract_time'].isna(), normalize='index') * 100

contract_time      False       True
source
Adzuna         78.565673   21.434327
Greenhouse      0.000000  100.000000

In [13]:
pd.crosstab(df['source'],df['contract_type'].isna(), normalize='index') * 100

contract_type     False       True
source
Adzuna         5.157131   94.842869
Greenhouse     0.000000  100.000000

In [14]:
pd.crosstab(df['source'],df['job_level'].isna(), normalize='index') * 100

job_level       False       True
source
Adzuna       0.000000  100.000000
Greenhouse  16.529284   83.470716

In [15]:
pd.crosstab(df['source'],df['job_type'].isna(),normalize='index') * 100

job_type        False       True
source
Adzuna       0.000000  100.000000
Greenhouse  16.529284   83.470716

In [16]:
pd.crosstab(df['source'],df['working_model_clean'].isna(),normalize='index') * 100

working_model_clean      False       True
source
Adzuna                0.000000  100.000000
Greenhouse           16.529284   83.470716

In [17]:
pd.crosstab(df['source'], df['region'].isna(), normalize='index') * 100

region          False       True
source
Adzuna       0.000000  100.000000
Greenhouse  16.529284   83.470716

In [18]:
pd.crosstab(df['source'],df['education'].isna(), normalize='index') * 100

education      False       True
source
Adzuna      0.000000  100.000000
Greenhouse  6.941432   93.058568

In [19]:
pd.crosstab(df['source'],df['ic_or_mg'].isna(),normalize='index' ) * 100

ic_or_mg        False       True
source
Adzuna       0.000000  100.000000
Greenhouse  18.264642   81.735358

In [20]:
pd.crosstab(df['source'], df['offices_clean'].isna(),normalize='index') * 100

offices_clean      False       True
source
Adzuna          0.000000  100.000000
Greenhouse     99.436009    0.563991

In [21]:
pd.crosstab( df['source'],df['departments_clean'].isna(), normalize='index') * 100

departments_clean  False  True
source
Adzuna               0.0  100.0
Greenhouse         100.0    0.0

In [22]:
pd.crosstab(df['source'],df['language_clean'].isna(),normalize='index') * 100

language_clean  False  True
source
Adzuna            0.0  100.0
Greenhouse      100.0    0.0

In [23]:
pd.crosstab(df['source'],df['demographic_data_consent_applies'].isna(),normalize='index') * 100

demographic_data_consent_applies  False  True
source
Adzuna                              0.0  100.0
Greenhouse                        100.0    0.0

In [24]:
pd.crosstab(df['source'], df['updated_at'].isna(),normalize='index') * 100

updated_at  False  True
source
Adzuna        0.0  100.0
Greenhouse  100.0    0.0

In [25]:
pd.crosstab( df['source'],df['requisition_id'].isna(), normalize='index') * 100

requisition_id      False       True
source
Adzuna           0.000000  100.000000
Greenhouse      73.839479   26.160521

In [26]:
pd.crosstab(df['source'],df['internal_job_id'].isna(), normalize='index') * 100

internal_job_id      False       True
source
Adzuna            0.000000  100.000000
Greenhouse       99.436009    0.563991

In [27]:
pd.crosstab( df['source'], df['ai_opt_out_request_url'].isna(), normalize='index') * 100

ai_opt_out_request_url      False       True
source
Adzuna                   0.000000  100.000000
Greenhouse              25.683297   74.316703

In [28]:
pd.crosstab(df['source'],df['include_ai_disclaimer'].isna(),normalize='index') * 100

include_ai_disclaimer      False       True
source
Adzuna                  0.000000  100.000000
Greenhouse             42.646421   57.353579

## Final Missing-Value Treatment Plan

| Column | Missingness Pattern | Treatment | Reason |
|---|---|---|---|
| `salary_currency` | Source-specific / not reported | Keep NaN | Currency cannot be safely assumed |
| `salary_min` | Missing salary information | Keep NaN | No reliable value to impute |
| `salary_max` | Missing salary information | Keep NaN | No reliable value to impute |
| `city` | Strongly source-specific | Keep NaN | Greenhouse primarily uses `location_clean` |
| `state` | Strongly source-specific | Keep NaN | Greenhouse primarily uses `location_clean` |
| `contract_time` | Adzuna-specific | Keep NaN | Greenhouse does not provide this field |
| `contract_type` | Mostly missing / source-specific | Keep NaN | Insufficient information for imputation |
| `job_level` | Greenhouse-specific | Keep NaN | Missing means level was not provided |
| `job_type` | Greenhouse-specific | Keep NaN | Missing means type was not provided |
| `working_model_clean` | Greenhouse-specific | Keep NaN | Missing means work model was not provided |
| `region` | Greenhouse-specific | Keep NaN | Missing means region was not provided |
| `education` | Explicitly verified only | Keep NaN | Do not assume an education requirement |
| `ic_or_mg` | Greenhouse-specific | Keep NaN | Do not infer IC/manager status |
| `offices_clean` | Greenhouse-specific | Keep NaN | No reliable value for missing records |
| `departments_clean` | Source-specific | Keep NaN | Adzuna does not provide this field |
| `language_clean` | Source-specific | Keep NaN | Adzuna does not provide this field |
| `demographic_data_consent_applies` | Source-specific | Keep NaN | Adzuna does not provide this field |
| `updated_at` | Source-specific | Keep NaN | Adzuna does not provide this field |
| `requisition_id` | Source-specific / identifier | Keep NaN | IDs cannot be meaningfully imputed |
| `internal_job_id` | Source-specific / identifier | Keep NaN | IDs cannot be meaningfully imputed |
| `ai_opt_out_request_url` | Source-specific metadata | Keep NaN | Missing URL cannot be safely inferred |
| `include_ai_disclaimer` | Source-specific metadata | Keep NaN | Do not assume True/False |

In [29]:
df[['other_market_salary_min', 'other_market_salary_max', 'other_market_salary_currency']].notna().sum()

other_market_salary_min          50
other_market_salary_max          50
other_market_salary_currency    130
dtype: int64

In [30]:
df[ df['other_market_salary_min'].notna()][[
'company_name','title','salary_currency','salary_min','salary_max', 'other_market_salary_currency',
'other_market_salary_min','other_market_salary_max'
]].head(20)

,company_name,title,salary_currency,salary_min,salary_max,other_market_salary_currency,other_market_salary_min,other_market_salary_max
5658,MongoDB,Account Development Representative,NaN,NaN,NaN,USD,50003.2,50003.2
5703,MongoDB,Engagement Manager (Services Sales),USD,131000.0,187000.0,USD,111000.0,111000.0
5726,MongoDB,"Enterprise Account Executive, Federal",USD,148500.0,148500.0,USD,148500.0,148500.0
5734,MongoDB,"Enterprise Account Executive, Growth",USD,150000.0,150000.0,USD,135000.0,135000.0
5756,MongoDB,Global Payroll Transformation Senior Manager,NaN,NaN,NaN,USD,107000.0,107000.0
5757,MongoDB,Growth Marketing Manager,USD,105000.0,150000.0,USD,90000.0,90000.0
5762,MongoDB,International Tax Director,NaN,NaN,NaN,USD,137000.0,137000.0
5763,MongoDB,International Tax Manager,USD,112000.0,160000.0,USD,95000.0,95000.0
5771,MongoDB,"Lead, Startup & Ventures Marketing",USD,126000.0,180000.0,USD,107000.0,107000.0
5772,MongoDB,"Manager, Candidate Experience",USD,91000.0,130000.0,USD,78000.0,78000.0
5773,MongoDB,"Manager, Candidate Experience",NaN,NaN,NaN,USD,78000.0,78000.0
5785,MongoDB,Payroll Tax Analyst,NaN,NaN,NaN,USD,69000.0,69000.0
5788,MongoDB,"Principal Business Development Manager, Fronti...",USD,162400.0,203000.0,USD,162400.0,162400.0
5796,MongoDB,"Principal Research Scientist, Database Systems",USD,254000.0,363000.0,USD,216000.0,216000.0
5806,MongoDB,"Regional Director, Enterprise, Growth",NaN,NaN,NaN,USD,180000.0,180000.0
5810,MongoDB,Renewals Specialist,NaN,NaN,NaN,USD,66560.0,66560.0
5811,MongoDB,Renewals Specialist,NaN,NaN,NaN,USD,66560.0,66560.0
5821,MongoDB,"Security Software Engineer, Infrastructure Sec...",USD,226000.0,226000.0,USD,134000.0,134000.0
5822,MongoDB,"Security Software Engineer, Infrastructure Sec...",USD,226000.0,226000.0,USD,134000.0,134000.0
5823,MongoDB,"Senior Accountant, Technical Revenue",USD,84000.0,120000.0,USD,71000.0,71000.0

In [31]:
df[['pay_transparency_min','pay_transparency_max', 'pay_transparency_unit']].notna().sum()

pay_transparency_min     196
pay_transparency_max     196
pay_transparency_unit    198
dtype: int64

In [32]:
df[ df['pay_transparency_min'].notna()][['company_name','title',
    'salary_currency','salary_min','salary_max','pay_transparency_unit','pay_transparency_min',
    'pay_transparency_max']].head(20)

,company_name,title,salary_currency,salary_min,salary_max,pay_transparency_unit,pay_transparency_min,pay_transparency_max
6039,Datadog,AI Research Scientist - Datadog AI Research (D...,USD,320000.0,400000.0,USD,320000.0,400000.0
6041,Datadog,Analyst Relations Manager,NaN,NaN,NaN,USD,94000.0,125000.0
6042,Datadog,"Area Vice President, Enterprise Security Sales",NaN,NaN,NaN,USD,210000.0,275000.0
6043,Datadog,"Area Vice President, Sales Engineering",USD,238000.0,317000.0,USD,238000.0,349000.0
6045,Datadog,Billing Operations Analyst,NaN,NaN,NaN,USD,64000.0,94000.0
6049,Datadog,Commercial Account Executive,USD,65000.0,70000.0,USD,51000.0,70000.0
6053,Datadog,Commercial Account Executive - Boston,USD,65000.0,70000.0,USD,51000.0,70000.0
6058,Datadog,Commercial Account Executive - LATAM (Portugue...,USD,65000.0,70000.0,USD,51000.0,70000.0
6059,Datadog,Commercial Account Executive - LATAM (Spanish ...,USD,65000.0,70000.0,USD,51000.0,70000.0
6065,Datadog,Commercial Sales Engineer (AMER - West),USD,80000.0,106000.0,USD,92000.0,134000.0
6066,Datadog,Commercial Sales Engineer - Boston,USD,80000.0,106000.0,USD,80000.0,117000.0
6068,Datadog,"Coordinator, Business Recruiting - Contract",NaN,NaN,NaN,USD,49000.0,72000.0
6070,Datadog,Customer Marketing Manager,NaN,NaN,NaN,USD,94000.0,125000.0
6074,Datadog,Customer Success Associate - Boston,NaN,NaN,NaN,USD,54000.0,79000.0
6076,Datadog,Customer Success Associate - Denver,NaN,NaN,NaN,USD,68000.0,99000.0
6080,Datadog,Customer Success Manager - Boston,USD,89000.0,118000.0,USD,89000.0,130000.0
6081,Datadog,Customer Success Manager - Denver,USD,89000.0,118000.0,USD,89000.0,130000.0
6085,Datadog,Datadog for Startups - Forward Deployed Engine...,USD,200000.0,250000.0,USD,192000.0,240000.0
6086,Datadog,Datadog for Startups Founding Engineering Lead,USD,200000.0,250000.0,USD,192000.0,240000.0
6089,Datadog,Deal Desk Analyst - Boston (Portuguese or Span...,NaN,NaN,NaN,USD,68000.0,95000.0

In [33]:
pd.crosstab(df['source'],df['pay_transparency_min'].isna(), normalize='index') * 100

pay_transparency_min     False       True
source
Adzuna                0.000000  100.000000
Greenhouse            8.503254   91.496746

In [34]:
pd.crosstab(df['source'],df['other_market_salary_min'].isna(), normalize='index') * 100

other_market_salary_min     False       True
source
Adzuna                   0.000000  100.000000
Greenhouse               2.169197   97.830803

In [36]:
# Final missing-value treatment
# No imputation is applied because the missing values are mostly
# structural, source-specific, or represent information not provided.

print("No missing values were artificially imputed.")
print("Existing NaN values have been retained.")

No missing values were artificially imputed.
Existing NaN values have been retained.

In [39]:
# Check remaining missing values
missing_final = (df.isna().sum().to_frame('missing_count'))
missing_final['missing_percent'] = (missing_final['missing_count'] / len(df) * 100)
missing_final = missing_final[ missing_final['missing_count'] > 0].sort_values('missing_percent', ascending=False)

missing_final

                                  missing_count  missing_percent
other_market_salary_min                    7219        99.312147
other_market_salary_max                    7219        99.312147
other_market_salary_currency               7139        98.211583
education                                  7109        97.798872
pay_transparency_min                       7073        97.303618
pay_transparency_max                       7073        97.303618
pay_transparency_unit                      7071        97.276104
contract_type                              7013        96.478195
working_model_clean                        6888        94.758564
region                                     6888        94.758564
job_level                                  6888        94.758564
job_type                                   6888        94.758564
ic_or_mg                                   6848        94.208282
ai_opt_out_request_url                     6677        91.855826
salary_currency                            6667        91.718256
include_ai_disclaimer                      6286        86.476819
requisition_id                             5567        76.585500
offices_clean                              4977        68.468840
internal_job_id                            4977        68.468840
updated_at                                 4964        68.289999
language_clean                             4964        68.289999
departments_clean                          4964        68.289999
demographic_data_consent_applies           4964        68.289999
salary_min                                 4653        64.011556
latitude                                   4642        63.860228
longitude                                  4642        63.860228
salary_max                                 4354        59.898198
city                                       3453        47.503095
state                                      3429        47.172926
contract_time                              3369        46.347503
standard_role                              2305        31.710001
category                                   2305        31.710001
location_clean                                8         0.110056

In [42]:
df.loc[
    df['location_clean'].isna(),
    ['title', 'company_name', 'absolute_url', 'city', 'state', 'location_clean']
]

,latitude,longitude,title,company_name,absolute_url,city,state,location_clean
5027,NaN,NaN,"Backend Engineer, Billing/Tax",Stripe,https://stripe.com/jobs/search?gh_jid=7217048,NaN,NaN,NaN
5102,NaN,NaN,"Engineering Manager, Access Management",Stripe,https://stripe.com/jobs/search?gh_jid=8014484,NaN,NaN,NaN
5145,NaN,NaN,"Full Stack Engineer, Billing",Stripe,https://stripe.com/jobs/search?gh_jid=6786324,NaN,NaN,NaN
5147,NaN,NaN,"Full Stack Engineer, Expansion",Stripe,https://stripe.com/jobs/search?gh_jid=7775622,NaN,NaN,NaN
5152,NaN,NaN,"Full Stack Engineer, Money as a Service",Stripe,https://stripe.com/jobs/search?gh_jid=7325118,NaN,NaN,NaN
5156,NaN,NaN,"Full Stack Engineer, Web Presence and Platform",Stripe,https://stripe.com/jobs/search?gh_jid=7436086,NaN,NaN,NaN
5391,NaN,NaN,"Software Engineer, Data Orchestration",Stripe,https://stripe.com/jobs/search?gh_jid=7230670,NaN,NaN,NaN
5419,NaN,NaN,"Staff Data Scientist, Growth",Stripe,https://stripe.com/jobs/search?gh_jid=7568328,NaN,NaN,NaN

## Final Missing-Value Treatment

After investigating the missing-value patterns, no artificial imputation was applied.

Most missing values are caused by:
- Source-specific fields
- Information not provided in the original job posting
- Salary information not reported
- Location information not explicitly available
- Fields that are structurally unavailable for one data source

Therefore, missing values are retained as `NaN`.

The 8 records with missing `location_clean` were also retained as `NaN` because no verified location information was available in the dataset.

In [43]:
# Final dataset verification

print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Total missing values:", df.isna().sum().sum())
print("Columns:", len(df.columns))

Shape: (7269, 42)
Duplicate rows: 0
Total missing values: 179483
Columns: 42

In [45]:
df.columns.tolist()

['absolute_url',
 'ai_opt_out_request_url',
 'category',
 'city',
 'company_name',
 'content_clean',
 'contract_time',
 'contract_type',
 'created',
 'created_date',
 'created_time',
 'demographic_data_consent_applies',
 'departments_clean',
 'education',
 'ic_or_mg',
 'id',
 'include_ai_disclaimer',
 'internal_job_id',
 'job_level',
 'job_type',
 'language_clean',
 'latitude',
 'location_clean',
 'longitude',
 'offices_clean',
 'other_market_salary_currency',
 'other_market_salary_max',
 'other_market_salary_min',
 'pay_transparency_max',
 'pay_transparency_min',
 'pay_transparency_unit',
 'region',
 'requisition_id',
 'salary_currency',
 'salary_max',
 'salary_min',
 'standard_role',
 'state',
 'title',
 'updated_at',
 'working_model_clean',
 'source']

In [46]:
df.to_csv("jobs_cleaned_missing_treated.csv", index=False)
print("Saved successfully.")

Saved successfully.

In [35]:
import re

def extract_figma_job(url):
    
    result = {
        'location_clean': None,
        'salary_currency': None,
        'salary_min': None,
        'salary_max': None,
        'education': None,
        'content_clean': None,
        'page_type': None
    }
    
    try:
        driver.get(url)
        time.sleep(3)
        
        page_text = driver.find_element(By.TAG_NAME, "body").text
        
        # Store full page content
        result['content_clean'] = page_text
        
        # -------------------------
        # PAGE TYPE
        # -------------------------
        if 'Annual Base Salary Range:' in page_text:
            result['page_type'] = 'job_listing'
        else:
            result['page_type'] = 'general_page'
            return result
        
        # -------------------------
        # LOCATION
        # -------------------------
        lines = [line.strip() for line in page_text.split('\n') if line.strip()]
        
        # Usually:
        # line 1 = Back to jobs
        # line 2 = Job title
        # line 3 = Location
        if len(lines) >= 3:
            result['location_clean'] = lines[2]
        
        # -------------------------
        # SALARY
        # -------------------------
        salary_match = re.search(
            r'Annual Base Salary Range:\s*'
            r'\$([\d,]+)\s*-\s*\$([\d,]+)\s*'
            r'(USD|CAD|EUR|GBP)',
            page_text,
            re.IGNORECASE
        )
        
        if salary_match:
            result['salary_min'] = float(
                salary_match.group(1).replace(',', '')
            )
            
            result['salary_max'] = float(
                salary_match.group(2).replace(',', '')
            )
            
            result['salary_currency'] = salary_match.group(3).upper()
        
        # -------------------------
        # EDUCATION
        # -------------------------
        education_patterns = [
            r"(Bachelor['’]?s[^.\n]*)",
            r"(Master['’]?s[^.\n]*)",
            r"(Ph\.?D\.?[^.\n]*)"
        ]
        
        for pattern in education_patterns:
            education_match = re.search(
                pattern,
                page_text,
                re.IGNORECASE
            )
            
            if education_match:
                result['education'] = education_match.group(1).strip()
                break
        
        return result
    
    except Exception as e:
        print(f"Error: {type(e).__name__}: {e}")
        result['page_type'] = 'error'
        return result